# $NetBSD$

DISTNAME=	libxdiff-0.23
CATEGORIES=	devel
MASTER_SITES=	http://www.xmailserver.org/

MAINTAINER=	pkgsrc-users@pkgsrc.org
HOMEPAGE=	http://www.xmailserver.org/xdiff-lib.html
COMMENT=	Library for creating patches for binary and text files
LICENSE=	gnu-lgpl-v2.1

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes

# The test/xregression runs forever so not ran with do-tests.

.include "../../mk/bsd.pkg.mk"
