# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/12 07:29:12 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HUNIT_BUILDLINK3_MK:=	${HUNIT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	HUnit
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NHUnit}
BUILDLINK_PACKAGES+=	HUnit
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}HUnit

.if ${HUNIT_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.HUnit?=	build
BUILDLINK_API_DEPENDS.HUnit+=	HUnit>=1.2.0.3
BUILDLINK_PKGSRCDIR.HUnit?=	../../wip/HUnit
.endif	# HUNIT_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
