# $NetBSD: buildlink3.mk,v 1.2 2009/03/20 19:43:39 jsonn Exp $

BUILDLINK_TREE+=	HUnit

.if !defined(HUNIT_BUILDLINK3_MK)
HUNIT_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.HUnit?=	build
BUILDLINK_API_DEPENDS.HUnit+=	HUnit>=1.2.0.3
BUILDLINK_PKGSRCDIR.HUnit?=	../../wip/HUnit
.endif # HUNIT_BUILDLINK3_MK

BUILDLINK_TREE+=	-HUnit
