# $NetBSD: buildlink3.mk,v 1.3 2006/09/16 06:55:10 thomasklausner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FIREBIRD_BUILDLINK3_MK:=	${FIREBIRD_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	firebird
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfirebird}
BUILDLINK_PACKAGES+=	firebird

.if ${FIREBIRD_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.firebird+=	firebird>=2.0.0.12710rc3
BUILDLINK_PKGSRCDIR.firebird?=		../../wip/firebird
.endif	# FIREBIRD_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
