# $NetBSD: Makefile,v 1.1.1.1 2010/11/25 13:05:01 ryo-on Exp $
#

DISTNAME=	Mako-0.3.6
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	devel
MASTER_SITES=	http://www.makotemplates.org/downloads/

MAINTAINER=	ryo_on@yk.rim.or.jp
HOMEPAGE=	http://www.makotemplates.org/
COMMENT=	Hyperfast and lightweight templating for the Python platform
LICENSE=	mit

PKG_DESTDIR_SUPPORT=	user-destdir

USE_LANGUAGES=	# none

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
