# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/01/18 16:27:13 hoka_adam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LLVM_BUILDLINK3_MK:=	${LLVM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	llvm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nllvm}
BUILDLINK_PACKAGES+=	llvm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}llvm

.if ${LLVM_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.llvm+=	llvm>=2.1
BUILDLINK_PKGSRCDIR.llvm?=	../../wip/llvm
.endif	# LLVM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
