
WITH REPORT, C93006A1, SYSTEM;
USE  REPORT, C93006A1, SYSTEM;
PROCEDURE C93006A IS
BEGIN

     TEST("C93006A", "CHECK ACTIVATION OF TASK DECLARED IN PACKAGE " &
                     "SPECIFICATION");

     SELECT
          T.E;
     OR
          DELAY 60.0;
          FAILED("RENDEZVOUS NOT ACCEPTED WITHIN 60 SECONDS");
     END SELECT;

     RESULT;
END C93006A;
