$NetBSD$

Fix ninja build.

--- libcinnamon-desktop/cdesktop-enums.h.orig	2018-05-18 19:35:15.000000000 +0000
+++ libcinnamon-desktop/cdesktop-enums.h
@@ -219,64 +219,64 @@ typedef enum
 } CDesktopMediaKeyType;
 
 __attribute__((unused)) static const char *media_keys[] = {
-        [C_DESKTOP_MEDIA_KEY_MUTE] = "volume-mute",
-        [C_DESKTOP_MEDIA_KEY_MUTE_QUIET] = "mute-quiet",
-        [C_DESKTOP_MEDIA_KEY_VOLUME_UP] = "volume-up",
-        [C_DESKTOP_MEDIA_KEY_VOLUME_UP_QUIET] = "volume-up-quiet",
-        [C_DESKTOP_MEDIA_KEY_VOLUME_DOWN] = "volume-down",
-        [C_DESKTOP_MEDIA_KEY_VOLUME_DOWN_QUIET] = "volume-down-quiet",
-        [C_DESKTOP_MEDIA_KEY_MIC_MUTE] = "mic-mute",
-        [C_DESKTOP_MEDIA_KEY_EJECT] = "eject",
-        [C_DESKTOP_MEDIA_KEY_MEDIA] = "media",
-        [C_DESKTOP_MEDIA_KEY_SCREENSHOT] = "screenshot",
-        [C_DESKTOP_MEDIA_KEY_WINDOW_SCREENSHOT] = "window-screenshot",
-        [C_DESKTOP_MEDIA_KEY_PLAY] = "play",
-        [C_DESKTOP_MEDIA_KEY_PAUSE] = "pause",
-        [C_DESKTOP_MEDIA_KEY_STOP] = "stop",
-        [C_DESKTOP_MEDIA_KEY_PREVIOUS] = "previous",
-        [C_DESKTOP_MEDIA_KEY_NEXT] = "next",
-        [C_DESKTOP_MEDIA_KEY_REWIND] = "audio-rewind",
-        [C_DESKTOP_MEDIA_KEY_FORWARD] = "audio-forward",
-        [C_DESKTOP_MEDIA_KEY_REPEAT] = "audio-repeat",
-        [C_DESKTOP_MEDIA_KEY_RANDOM] = "audio-random",
-        [C_DESKTOP_MEDIA_KEY_AREA_SCREENSHOT] = "area-screenshot",
-        [C_DESKTOP_MEDIA_KEY_SCREENSHOT_CLIP] = "screenshot-clip",
-        [C_DESKTOP_MEDIA_KEY_WINDOW_SCREENSHOT_CLIP] = "window-screenshot-clip",
-        [C_DESKTOP_MEDIA_KEY_AREA_SCREENSHOT_CLIP] = "area-screenshot-clip",
+        "volume-mute",
+        "mute-quiet",
+        "volume-up",
+        "volume-up-quiet",
+        "volume-down",
+        "volume-down-quiet",
+        "mic-mute",
+        "eject",
+        "media",
+        "screenshot",
+        "window-screenshot",
+        "play",
+        "pause",
+        "stop",
+        "previous",
+        "next",
+        "audio-rewind",
+        "audio-forward",
+        "audio-repeat",
+        "audio-random",
+        "area-screenshot",
+        "screenshot-clip",
+        "window-screenshot-clip",
+        "area-screenshot-clip",
 
-        [C_DESKTOP_MEDIA_KEY_SEPARATOR] = "",
+        "",
 
-        [C_DESKTOP_MEDIA_KEY_TOUCHPAD] = "touchpad-toggle",
-        [C_DESKTOP_MEDIA_KEY_TOUCHPAD_ON] = "touchpad-on",
-        [C_DESKTOP_MEDIA_KEY_TOUCHPAD_OFF] = "touchpad-off",
-        [C_DESKTOP_MEDIA_KEY_LOGOUT] = "logout",
-        [C_DESKTOP_MEDIA_KEY_SHUTDOWN] = "shutdown",
-        [C_DESKTOP_MEDIA_KEY_HOME] = "home",
-        [C_DESKTOP_MEDIA_KEY_CALCULATOR] = "calculator",
-        [C_DESKTOP_MEDIA_KEY_SEARCH] = "search",
-        [C_DESKTOP_MEDIA_KEY_EMAIL] = "email",
-        [C_DESKTOP_MEDIA_KEY_SCREENSAVER] = "screensaver",
-        [C_DESKTOP_MEDIA_KEY_HELP] = "help",
-        [C_DESKTOP_MEDIA_KEY_TERMINAL] = "terminal",
-        [C_DESKTOP_MEDIA_KEY_WWW] = "www",
-        [C_DESKTOP_MEDIA_KEY_VIDEO_OUT] = "video-outputs",
-        [C_DESKTOP_MEDIA_KEY_ROTATE_VIDEO] = "video-rotation",
-        [C_DESKTOP_MEDIA_KEY_ROTATE_VIDEO_LOCK] = "video-rotation-lock",
-        [C_DESKTOP_MEDIA_KEY_SCREENREADER] = "screenreader",
-        [C_DESKTOP_MEDIA_KEY_ON_SCREEN_KEYBOARD] = "on-screen-keyboard",
-        [C_DESKTOP_MEDIA_KEY_INCREASE_TEXT] = "increase-text-size",
-        [C_DESKTOP_MEDIA_KEY_DECREASE_TEXT] = "decrease-text-size",
-        [C_DESKTOP_MEDIA_KEY_TOGGLE_CONTRAST] = "toggle-contrast",
-        [C_DESKTOP_MEDIA_KEY_SUSPEND] = "suspend",
-        [C_DESKTOP_MEDIA_KEY_HIBERNATE] = "hibernate",
-        [C_DESKTOP_MEDIA_KEY_SCREEN_BRIGHTNESS_UP] = "screen-brightness-up",
-        [C_DESKTOP_MEDIA_KEY_SCREEN_BRIGHTNESS_DOWN] = "screen-brightness-down",
-        [C_DESKTOP_MEDIA_KEY_KEYBOARD_BRIGHTNESS_UP] = "kbd-brightness-up",
-        [C_DESKTOP_MEDIA_KEY_KEYBOARD_BRIGHTNESS_DOWN] = "kbd-brightness-down",
-        [C_DESKTOP_MEDIA_KEY_KEYBOARD_BRIGHTNESS_TOGGLE] = "kbd-brightness-toggle",
-        [C_DESKTOP_MEDIA_KEY_BATTERY] = "battery",
+        "touchpad-toggle",
+        "touchpad-on",
+        "touchpad-off",
+        "logout",
+        "shutdown",
+        "home",
+        "calculator",
+        "search",
+         "email",
+        "screensaver",
+        "help",
+        "terminal",
+        "www",
+        "video-outputs",
+        "video-rotation",
+        "video-rotation-lock",
+        "screenreader",
+        "on-screen-keyboard",
+        "increase-text-size",
+        "decrease-text-size",
+        "toggle-contrast",
+        "suspend",
+        "hibernate",
+        "screen-brightness-up",
+        "screen-brightness-down",
+        "kbd-brightness-up",
+        "kbd-brightness-down",
+        "kbd-brightness-toggle",
+        "battery",
 
-        [C_DESKTOP_MEDIA_KEY_LAST] = ""
+        ""
 };
 
 #endif /* __CDesktop_enums_h__ */
