# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/06/07 16:58:48 minskim Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PANORAMIXEXT_BUILDLINK3_MK:=	${PANORAMIXEXT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	panoramixext
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npanoramixext}
BUILDLINK_PACKAGES+=	panoramixext

.if !empty(PANORAMIXEXT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.panoramixext+=	panoramixext>=1.1
BUILDLINK_PKGSRCDIR.panoramixext?=	../../wip/panoramixext
BUILDLINK_DEPMETHOD.panoramixext?=	build
.endif	# PANORAMIXEXT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
