.\"	$NetBSD: pkg_src_summary.1,v 1.7 2008/05/11 21:53:18 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.Dd Jan 29, 2008
.Dt PKG_SRC_SUMMARY 1
.Sh NAME
.Nm pkg_src_summary
.Nd build summary information for source packages
.Sh SYNOPSIS
.Nm
.Op Ar category1/pkg1 category2/pkg2 ...
.Sh DESCRIPTION
.Nm
builds summary information about source packages specified in
arguments or read from stdin (one package per line).  Format of this
summary information is the same as used in pkg_summary(5) built from
binary packages. List of fields (PKGNAME, PKGPATH, DEPENDS etc.) is
very similar but not fully the same.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl h
display help message
.It Fl f Ar fields
A list of fields (separated by space character) to be generated. By
default the following fields are generated: PKGNAME, PKGPATH, DEPENDS,
BUILD_DEPENDS, CONFLICTS, HOMEPAGE, COMMENT, LICENSE, ONLYFOR, NOTFOR,
MAINTAINER, CATEGORIES, DESCRIPTION (multiline), PLIST(multiline).
.It Fl p
use 'bmake plist' for obtaining PLIST
.El
.Sh ENVIRONMENT
.Bd -literal
.Bl -tag -width Cm
.It Cm PKGSRCDIR
pkgsrc root directory, defaults to /usr/pkgsrc
.It Cm BMAKE
path to pkgsrc friendly make utility, defaults to make
.It Cm PSS_SLAVES
Space separated list of remote hosts or +<Number> for distributed
summary generation. If case of +<Number>, <Number> local processes
are run, this is useful for SMP machines.
.It Cm PSS_TRANSPORT
Transport program like ssh or rsh to communicate with remote/slave hosts.
.It Cm PSS_PPERS
A number of packages per slave that are built at once, defaults to 10.
.El
.Ed
.Sh EXAMPLES
.Bd -literal
pkg_src_summary wip/dict-server wip/dict-mueller7 wip/dict-client
printf 'wip/dict-server\\nwip/dict-client\\n' | pkg_src_summary
env BMAKE=/usr/pkg/bin/bmake \\ 
    PSS_SLAVES='host1 host2' \\ 
    PSS_TRANSPORT=/usr/bin/ssh \\ 
    /usr/pkg/bin/pkg_src_summary \\ 
           -f 'PKGNAME PKGPATH DEPENDS BUILD_DEPENDS' \\ 
           < /tmp/packages.txt \\ 
pkg_list_all_pkgs | env PSS_SLAVES='+6' pkg_src_summary
.Ed
.Sh SEE ALSO
.Xr pkg_summary 5 ,
.Xr pkg_info 1 ,
.Xr pkg_micro_src_summary 1 ,
.Sh AUTHOR
.An Aleksey Cheusov
.Aq vle@gmx.net
