.\"	$NetBSD: pkg_update_summary.1,v 1.2 2008/04/12 16:05:00 cheusov Exp $
.\"
.\" Copyright (c) 2007 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.Dd Aug 2, 2007
.Dt PKG_UPDATE_SUMMARY 1
.Sh NAME
.Nm pkg_update_summary
.Nd update, or create a summary file (pkg_summary(5))
.Sh SYNOPSIS
.Nm
.Ar summary_file
.Ar bin_pkg_dir
.Op Ar decompress compress
.Sh DESCRIPTION
.Nm
updates (or creates if it does not exist)
summary information about binary packages 
and stores it in 
.Ar summary_file
file.
That is it checks
whether
.Ar bin_pkg_dir
directory contains packages newer than that from
.Ar summary_file.
If it does,
updates the summary file. NOTE: modification time of
the binary package file is checked, not the content of the package.
Also
.Nm 
removes from 
.Ar summary_file
the information about packages removed from 
.Ar bin_pkg_dir
directory.
.Sh ENVIRONMENT
.Bd -literal
.Bl -tag -width Cm
.It Cm PKG_SUFX
Binary package extension, either .tgz or .tbz, defaults to '.tgz'
.It Cm TEST_CMD
Solaris's test command does not like option -nt, defaults to 'test'
.It Cm PKG_INFO_CMD
Path to pkg_info command, defaults to 'pkg_info'
.El
.Ed
.Sh EXAMPLES
.Bd -literal
pkg_update_summary /srv/packages/All/pkg_summary.txt /srv/packages/All
pkg_update_summary /dir/pkg_summary.gz /dir 'gzip -dc' 'gzip -c'
.Ed
.Sh AUTHOR
.An Aleksey Cheusov
.Aq vle@gmx.net
