.\"	$NetBSD: pkg_grep_summary.1,v 1.5 2008/11/06 22:07:19 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.TH PKG_GREP_SUMMARY 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_grep_summary \- tool for grepping pkgsrc summary file
.SH SYNOPSIS
.B "pkg_grep_summary -h"
.br
.BI pkg_grep_summary " field awk_condition"
.br
.BI "pkg_grep_summary -e" " field"
.br
.SH DESCRIPTION
.B pkg_grep_summary
outputs a summary information about packages that matches
the specified condition.
In other words, pkg_grep_summary is a search tool
somewhat similar to
grep
,
PKGSRCDIR/pkglocate
,
pkg_find
etc. but it is multifield
searcher and is fast because it uses summaries instead
of pkgsrc packages source tree.
.SH OPTIONS
.TP
.BR \-h " or" " --help"
display help message
.TP
.BI \-e " field"
outputs summaries in which
.B "field"
is either empty or absent
.SH EXAMPLES
.BD
  pkg_grep_summary 'PKGNAME' 'fvalue ~ /judy/' \\
        < /usr/pkgsrc/packages/pkg_summary.txt
  pkg_grep_summary 'PKGPATH' 'fvalue ~ /^lang\\//' \\
        < /usr/pkgsrc/packages/pkg_summary.txt
  pkg_grep_summary 'DEPENDS' 'fvalue ~ /libX/' \\
        < /usr/pkgsrc/pkg_src_summary.txt
  pkg_grep_summary 'COMMENT' 'toupper(fvalue) ~ /DNS/' \\
        < /usr/pkgsrc/pkg_src_summary.txt
.ED
.SH SEE ALSO
.BR pkg_summary-utils(7),
.BR pkg_summary(5)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
