.\"	$NetBSD: pkg_grep_summary.1,v 1.9 2010/03/01 20:25:48 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.\" ------------------------------------------------------------------
.de VB \" Verbatim Begin
.ft CW
.nf
.ne \\$1
..
.de VE \" Verbatim End
.ft R
.fi
..
.\" ------------------------------------------------------------------
.TH PKG_GREP_SUMMARY 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_grep_summary \- tool for grepping pkgsrc summary file
.SH SYNOPSIS
.B "pkg_grep_summary -h"
.br
.BI pkg_grep_summary " field awk_condition"
.br
.BI "pkg_grep_summary -e" " field"
.br
.BI "pkg_grep_summary -m" " field regexp"
.br
.BI "pkg_grep_summary -s" " field string"
.br
.SH DESCRIPTION
.B pkg_grep_summary
outputs a summary information about packages that matches
the specified condition.
In other words, pkg_grep_summary is a search tool
somewhat similar to
grep, PKGSRCDIR/pkglocate, pkg_find
etc. but it is a multifield
searcher and is fast because it uses summaries instead
of pkgsrc packages source tree.
In addition to fields really present in input, PKGBASE is also supported,
it is a PKGNAME without package version.
.SH OPTIONS
.TP
.B "-h|--help"
display help message
.TP
.BI "-e" " field"
outputs summaries in which
.I "field"
is either empty or absent
.TP
.BI "-m" " field regexp"
outputs summary if
.I "regexp"
matches the
.I "field"
.TP
.BI "-s" " field string"
outputs summary if
.I "field"
is equal to
.I "string"
.SH EXAMPLES
.VB
pkg_grep_summary -s 'PKGPATH' 'devel/libjudy'
pkg_grep_summary -m 'PKGPATH' '^wip/'
pkg_grep_summary 'PKGNAME' 'fvalue ~ /judy/' \\
      < /usr/pkgsrc/packages/pkg_summary.txt
pkg_grep_summary 'PKGPATH' 'fvalue ~ /^lang\\//' \\
      < /usr/pkgsrc/packages/pkg_summary.txt
pkg_grep_summary 'DEPENDS' 'fvalue ~ /libX/' \\
      < /usr/pkgsrc/pkg_src_summary.txt
pkg_grep_summary 'COMMENT' 'toupper(fvalue) ~ /DNS/' \\
      < /usr/pkgsrc/pkg_src_summary.txt
.VE
.SH SEE ALSO
.BR pkg_summary-utils(7),
.BR pkg_summary(5)
.BR pkg_src_summary(1)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
