.\"	$NetBSD: pkg_list_all_pkgs.1,v 1.5 2008/11/06 23:08:30 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.TH PKG_LIST_ALL_PKGS 1 "Jan 29, 2008" "" ""
.SH NAME
pkg_list_all_pkgs \- list all packages in pkgsrc source tree
.SH SYNOPSIS
.BI pkg_list_all_pkgs " [OPTIONS]"
.SH DESCRIPTION
.B pkg_list_all_pkgs
analyses /usr/pkgsrc/Makefile file (SUBDIR
variable defined there) and outputs all available packages
in category/directory format. One package per line.
.SH OPTIONS
.TP
.B "-h|--help"
display help message
.SH ENVIRONMENT
.TP
.B PKGSRCDIR
pkgsrc root directory, defaults to /usr/pkgsrc
.TP
.B BMAKE
path to pkgsrc friendly make utility, defaults to make
.SH EXAMPLES
.TP
pkg_list_all_pkgs
.SH "SEE ALSO"
.B pkg_summary-utils(7)
.SH AUTHOR
Aleksey Cheusov <vle@gmx.net>
