.\"	$NetBSD: pkg_refresh_summary.1,v 1.2 2008/04/12 16:05:00 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.Dd Jan 29, 2008
.Dt PKG_REFRESH_SUMMARY 1
.Sh NAME
.Nm pkg_refresh_summary
.Nd refreshes the pkg_summary
.Sh SYNOPSIS
.Nm
.Op Ar summary files ...
.Sh DESCRIPTION
.Nm
refreshes pkg_summary, that is
for each PKGPATH:PKGBASE pair present in summary it outputs
the information only about newest version.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl h
display help message
.El
.Sh EXAMPLES
.Bd -literal
pkg_refresh_summary /usr/pkgsrc/packages/pkg_summary.txt
.Ed
.Sh SEE ALSO
.Xr pkg_summary 5 ,
.Xr pkg_info 1 ,
.Xr pkg_src_summary 1 ,
.Xr pkg_update_summary 1 ,
.Xr pkg_micro_src_summary 1 ,
.Xr pkg_cmp_summary 1 ,
.Xr pkg_update_src_summary 1 ,
.Xr pkg_summary4view 1 ,
.Sh AUTHOR
.An Aleksey Cheusov
.Aq vle@gmx.net
