# $NetBSD: Makefile,v 1.3 2012/02/03 17:07:30 realzhtw Exp $
#

DISTNAME=	aoeui-1.6
CATEGORIES=	editors
MASTER_SITES=	http://aoeui.googlecode.com/files/
EXTRACT_SUFX=	.tgz

MAINTAINER=	a@zta.lk
HOMEPAGE=	http://code.google.com/p/aoeui/
COMMENT=	Lightweight text editor optimized for Dvorak
LICENSE=	gnu-gpl-v2

PKG_DESTDIR_SUPPORT=	user-destdir

USE_TOOLS+=	m4

BUILD_TARGET= default

.include "../../mk/bsd.pkg.mk"
