# $NetBSD: Makefile,v 1.3 2012/11/13 23:05:28 othyro Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-sqldatabase-${IO_VERSION}
CATEGORIES=		database

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		SqlDatabase addon for Io

ADDON_NAME=		SqlDatabase

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
