# $NetBSD: Makefile,v 1.1.1.1 2008/09/08 22:45:09 milosn Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-sqldatabase-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		database

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		SqlDatabase addon for Io.

ADDON_NAME=		SqlDatabase

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
