# $NetBSD: Makefile,v 1.6 2005/04/11 21:15:33 tvierling Exp $

DISTNAME=	scponly-3.9
CATEGORIES=	shells
MASTER_SITES=	http://www.sublimation.org/scponly/
EXTRACT_SUFX=	.tgz

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://www.sublimation.org/scponly/
COMMENT=	Tiny shell which only permits scp and sftp

GNU_CONFIGURE=	yes
PKG_SHELL=	${PREFIX}/bin/scponly

.include "../../mk/bsd.pkg.install.mk"
.include "../../mk/bsd.pkg.mk"
