# $NetBSD: buildlink3.mk,v 1.2 2009/01/12 06:24:28 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_HTTP_BUILDLINK3_MK:=	${HS_HTTP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-HTTP
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-HTTP}
BUILDLINK_PACKAGES+=	hs-HTTP
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-HTTP

.if ${HS_HTTP_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-HTTP?=	build
BUILDLINK_API_DEPENDS.hs-HTTP+=	hs-HTTP>=4000.0.1
BUILDLINK_PKGSRCDIR.hs-HTTP?=	../../wip/hs-HTTP
.endif	# HS_HTTP_BUILDLINK3_MK

.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/parsec/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
