# $NetBSD: buildlink3.mk,v 1.1 2008/07/19 08:40:45 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_HTTP_BUILDLINK3_MK:=	${HS_HTTP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-HTTP
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-HTTP}
BUILDLINK_PACKAGES+=	hs-HTTP
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-HTTP

.if ${HS_HTTP_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-HTTP?=	build
BUILDLINK_API_DEPENDS.hs-HTTP+=	hs-HTTP>=3001.0.4
BUILDLINK_PKGSRCDIR.hs-HTTP?=	../../wip/hs-HTTP
.endif	# HS_HTTP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
