-- BXE2010.A
--
--                             Grant of Unlimited Rights
--
--     Under contracts F33600-87-D-0337, F33600-84-D-0280, MDA903-79-C-0687,
--     F08630-91-C-0015, and DCA100-97-D-0025, the U.S. Government obtained 
--     unlimited rights in the software and documentation contained herein.
--     Unlimited rights are defined in DFAR 252.227-7013(a)(19).  By making 
--     this public release, the Government intends to confer upon all 
--     recipients unlimited rights  equal to those held by the Government.  
--     These rights include rights to use, duplicate, release or disclose the 
--     released technical data and computer software in whole or in part, in 
--     any manner and for any purpose whatsoever, and to have or permit others 
--     to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS.  THE GOVERNMENT MAKES NO EXPRESS OR IMPLIED 
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE 
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--*
--
-- OBJECTIVE:
--      Check that a public child library unit of a remote call 
--      interface library unit must itself have a Remote_Call_Interface
--      pragma.
--      Check that a private child library unit of a remote call
--      interface library unit are not subjected to the restrictions
--      of an RCI unit unless the private child unit contains a 
--      Remote_Call_Interface pragma.
--      Check the parameterized form of the pragma to see that a library 
--      unit name can be specified and if it is specified, it must
--      correspond to the library unit in which it is contained.
--      Check that a public child library unit of a normal package
--      cannot be a remote call interface unit.
--      Check that a public child library unit of a pure package
--      can be a remote call interface unit.
--
-- TEST DESCRIPTION:
--      This test declares a remote call interface unit, a normal package,
--      and a pure package and a selection of child units to go with 
--      these different parents.  The units that should compile without
--      error are so noted.
--
-- APPLICABILITY CRITERIA:
--      This test applies only to implementations supporting the
--      Distribution Annex and the Remote_Call_Interface pragma.
--
--
-- CHANGE HISTORY:
--     11 MAR 95   SAIC    Initial version
--     23 OCT 95   SAIC    Incorporate Reviewer comments.
--                         Added pragma Remote_Call_Interface to Bad_Child_1
--     26 FEB 97   PWB.CTA Added pragma Pure to BXE2010_Pure
--
--!

package BXE2010 is
  -- this package should compile without error.
  pragma Remote_Call_Interface;
  procedure Simple_Remote_Call (X, Y : in Integer); 
end BXE2010;
