# $NetBSD: Makefile,v 1.3 2004/02/19 17:53:28 thomasklausner Exp $
#

DISTNAME=	libtlen-20040112
CATEGORIES=	chat
MASTER_SITES=	http://www.libtlen.eu.org/snapshots/archive/

MAINTAINER=	dotz@irc.pl
HOMEPAGE=	http://www.libtlen.eu.org/
COMMENT=	Library to access tlen.pl IM system

USE_BUILDLINK3=		yes
USE_PKGLOCALEDIR=	yes
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
