# $NetBSD: Makefile,v 1.4 2011/11/14 09:39:47 phonohawk Exp $
#

DISTNAME=	text-0.11.1.9
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Efficient packed Unicode text type
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-deepseq/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
