# $NetBSD: Makefile,v 1.1 2006/12/17 22:47:19 cheusov Exp $

.include "../../wip/heirloom-dirs/Makefile.prog2.common"

PKGNAME=	heirloom-tail-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="libcommon build tail"

.include "../../mk/bsd.pkg.mk"
