# $NetBSD$

BUILDLINK_TREE+=	md4c

.if !defined(MD4C_BUILDLINK3_MK)
MD4C_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.md4c+=	md4c>=0.4.7
BUILDLINK_PKGSRCDIR.md4c?=	../../wip/md4c
.endif	# MD4C_BUILDLINK3_MK

BUILDLINK_TREE+=	-md4c
