
WITH MACHINE_CODE; USE MACHINE_CODE;
PROCEDURE BD8004A_7 IS
     FUNCTION F RETURN BOOLEAN IS                        -- ERROR:
     BEGIN
          RETURN TRUE;
     END;
BEGIN
     Asm_Insn'(Asm ("nop"));
END BD8004A_7;
