# $NetBSD$

BUILDLINK_TREE+=	mxml4

.if !defined(MXML4_BUILDLINK3_MK)
MXML4_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.mxml4+=	mxml4>=4.0.3
BUILDLINK_PKGSRCDIR.mxml4?=	../../wip/mxml4
.endif	# MXML4_BUILDLINK3_MK

BUILDLINK_TREE+=	-mxml4
