#include "Rts.h"

/* A quick and dirty hack to resurrect -fvia-C from bitrot.
 *
 * The main function has been removed from rts. It's now generated by
 * compiler/main/DriverPipeline.hs but that doesn't play nice with
 * -fvia-C.
 */

extern StgClosure ZCMain_main_closure;

int main(int argc, char *argv[])
{
    RtsConfig __conf = defaultRtsConfig;
    __conf.rts_opts_enabled = RtsOptsAll;
    return hs_main(argc, argv, &ZCMain_main_closure, __conf);
}
