# $NetBSD: buildlink3.mk,v 1.1 2008/02/21 21:36:58 pmatias Exp $
#

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MINIUPNPC_BUILDLINK3_MK:=	${MINIUPNPC_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	miniupnpc
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nminiupnpc}
BUILDLINK_PACKAGES+=	miniupnpc
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}miniupnpc

.if ${MINIUPNPC_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.miniupnpc+=	miniupnpc>=1.0nb11
BUILDLINK_PKGSRCDIR.miniupnpc?=	../../wip/miniupnpc
.endif	# MINIUPNPC_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
