-- BA16001.A
--
--                             Grant of Unlimited Rights
--
--     The Ada Conformity Assessment Authority (ACAA) holds unlimited
--     rights in the software and documentation contained herein. Unlimited
--     rights are the same as those granted by the U.S. Government for older
--     parts of the Ada Conformity Assessment Test Suite, and are defined
--     in DFAR 252.227-7013(a)(19). By making this public release, the ACAA
--     intends to confer upon all recipients unlimited rights equal to those
--     held by the ACAA. These rights include rights to use, duplicate,
--     release or disclose the released technical data and computer software
--     in whole or in part, in any manner and for any purpose whatsoever, and
--     to have or permit others to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS. THE ACAA MAKES NO EXPRESS OR IMPLIED
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--
--                                     Notice
--
--    The ACAA has created and maintains the Ada Conformity Assessment Test
--    Suite for the purpose of conformity assessments conducted in accordance
--    with the International Standard ISO/IEC 18009 - Ada: Conformity
--    assessment of a language processor. This test suite should not be used
--    to make claims of conformance unless used in accordance with
--    ISO/IEC 18009 and any applicable ACAA procedures.
--
--*
--
-- OBJECTIVE:
--    Check that library subprograms, generic units, and library renames
--    of them cannot be mentioned in a limited_with_clause. (10.1.6(2/2);
--    this is repeated in 10.1.2(17/2)).
--
--    Check that a package nested in a library package cannot be mentioned
--    in a limited_with_clause. (10.1.6(2/2)).
--
--    Check that a child unit cannot be named in a limited_with_clause by its
--    simple name or any abbreviated form of its full name. (10.1.6(2/2)).
--
-- TEST DESCRIPTION:
--    Declare an example of every kind of library unit, and try to use
--    them in a limited with. Use some children and some root units.
--    Also use a few limited private withs to check that the rules are
--    checked for them, too.

-- CHANGE HISTORY:
--    29 Nov 2004   PHL    Initial version.
--    26 Mar 2006   RLB    Created test from submitted test.
--
--!

package BA16001 is
    type Gollywog is null record;
end BA16001;
