# $NetBSD: Makefile,v 1.2 2013/06/16 13:28:20 shattered Exp $

DISTNAME=	atool-0.39.0
CATEGORIES=	archivers
MASTER_SITES=	http://savannah.nongnu.org/download/atool/

MAINTAINER=	mcy@lm7.fr
HOMEPAGE=	http://www.nongnu.org/atool/
COMMENT=	Manage file archives of various types
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LANGUAGES=	# none (perl)
USE_TOOLS+=	gmake perl
REPLACE_PERL=	atool

.include "../../mk/bsd.pkg.mk"
