# $NetBSD: buildlink3.mk,v 1.2 2004/07/02 12:52:14 thomasklausner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JDK12_BUILDLINK3_MK:=	${JDK12_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jdk12
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njdk12}
BUILDLINK_PACKAGES+=	jdk12

.if !empty(JDK12_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.jdk12+=	jdk12>=2.0.11nb1
BUILDLINK_PKGSRCDIR.jdk12?=	../../wip/jdk12
BUILDLINK_JAVA_PREFIX.jdk12=	${PREFIX}/java/jdk-1.2.2

BUILDLINK_PASSTHRU_DIRS+=	${BUILDLINK_JAVA_PREFIX.jdk12}

BUILDLINK_CPPFLAGS.jdk12= \
	-I${BUILDLINK_JAVA_PREFIX.jdk12}/include				\
	-I${BUILDLINK_JAVA_PREFIX.jdk12}/include/netbsd
.endif	# JDK12_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
