$NetBSD$

--- gdbserver/configure.srv.orig	2020-08-26 18:57:35.000000000 +0000
+++ gdbserver/configure.srv
@@ -349,6 +349,12 @@ case "${gdbserver_host}" in
 			srv_tgtobj="${srv_tgtobj} nat/windows-nat.o"
 			srv_tgtobj="${srv_tgtobj} arch/amd64.o arch/i386.o"
 			;;
+  x86_64-*-netbsd*)	srv_regobj=""
+			srv_tgtobj="netbsd-low.o netbsd-x86_64-low.o fork-child.o"
+			srv_tgtobj="${srv_tgtobj} nat/fork-inferior.o"
+			srv_tgtobj="${srv_tgtobj} arch/amd64.o"
+			srv_netbsd=yes
+			;;
 
   xtensa*-*-linux*)	srv_regobj=reg-xtensa.o
 			srv_tgtobj="$srv_linux_obj linux-xtensa-low.o"
