$NetBSD$

--- gdb/gdbserver/configure.srv.orig	2019-07-16 00:00:27.000000000 +0000
+++ gdb/gdbserver/configure.srv
@@ -30,6 +30,10 @@ ipa_ppc_linux_regobj="powerpc-32l-ipa.o 
 # these files over and over again.
 srv_linux_obj="linux-low.o linux-osdata.o linux-procfs.o linux-ptrace.o linux-waitpid.o linux-personality.o linux-namespaces.o fork-child.o fork-inferior.o"
 
+# NetBSD object files.  This is so we don't have to repeat
+# these files over and over again.
+srv_netbsd_obj="netbsd-low.o fork-child.o fork-inferior.o"
+
 # Input is taken from the "${target}" variable.
 
 case "${target}" in
@@ -378,6 +382,11 @@ case "${target}" in
 			ipa_obj="linux-amd64-ipa.o linux-x86-tdesc-ipa.o"
 			ipa_obj="${ipa_obj} arch/amd64-ipa.o"
 			;;
+  x86_64-*-netbsd*)	srv_regobj=""
+			srv_tgtobj="netbsd-low.o netbsd-x86_64-low.o fork-child.o fork-inferior.o"
+			srv_tgtobj="${srv_tgtobj} arch/amd64.o"
+			srv_netbsd=yes
+			;;
   x86_64-*-mingw*)	srv_regobj=""
 			srv_tgtobj="x86-low.o x86-dregs.o i387-fp.o win32-low.o win32-i386-low.o"
 			srv_tgtobj="${srv_tgtobj} arch/amd64.o"
