$NetBSD$

Requires a non-crates.io download not currently supported by cargo.mk.

--- Cargo.toml.orig	2026-05-01 15:56:50.000000000 +0000
+++ Cargo.toml
@@ -53,5 +53,5 @@ kstat-rs = "0.2"
 tempfile = "3.24.0"
 
 [patch.crates-io]
-lua-src = { git = "https://github.com/mlua-rs/lua-src-rs.git", rev = "c641952" }
-systemstat = { git = "https://github.com/jperkin/systemstat", branch = "platform-support" }
+lua-src = { path = "../lua-src-rs-178af5ab1dd388fd378cb9cb24d65747e08f5a5e" }
+systemstat = { path = "../systemstat-2a12cb8de6732366bb7764b84296f53f9be00143" }
