# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:18:37 jeremy-c-reed Exp $

BUILDLINK_DEPMETHOD.xcmiscproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XCMISCPROTO_BUILDLINK3_MK:=	${XCMISCPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	xcmiscproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxcmiscproto}
BUILDLINK_PACKAGES+=	xcmiscproto

.if !empty(XCMISCPROTO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.xcmiscproto+=	xcmiscproto>=1.1
BUILDLINK_PKGSRCDIR.xcmiscproto?=	../../wip/xcmiscproto
.endif	# XCMISCPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
