# $NetBSD: Makefile,v 1.8 2013/09/02 12:07:48 szptvlfn Exp $
#

DISTNAME=	QuickCheck-2.6
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Automatic testing of Haskell programs
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-random/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
