# $NetBSD: Makefile,v 1.10 2014/05/21 21:04:43 szptvlfn Exp $

DISTNAME=	QuickCheck-2.7.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Automatic testing of Haskell programs
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-random/buildlink3.mk"
.include "../../wip/hs-tf-random/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
