# $NetBSD: Makefile,v 1.2 2011/12/01 23:03:39 phonohawk Exp $
#

DISTNAME=	semigroups-0.8
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell 98 semigroups
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
