# $NetBSD$

DISTNAME=	mathdots
PKGNAME=	tex-${DISTNAME}-${TEXLIVE_REV}
TEXLIVE_REV=	34301

TEXLIVE_USE_CTAN=	YES

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Commands to produce dots in math that respect font size

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
