# $NetBSD: buildlink3.mk,v 1.1 2007/02/09 12:16:42 bsadewitz Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JACK_BUILDLINK3_MK:=	${JACK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njack}
BUILDLINK_PACKAGES+=	jack
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}jack

.if !empty(JACK_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.jack=	jack>=0.102.0
BUILDLINK_PKGSRCDIR.jack?=	../../wip/jack-devel
.endif	# JACK_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
