# $NetBSD$

BUILDLINK_TREE+=	sdl12-compat

.if !defined(SDL12_COMPAT_BUILDLINK3_MK)
SDL12_COMPAT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.sdl12-compat+=	sdl12-compat>=1.2.52nb3
BUILDLINK_PKGSRCDIR.sdl12-compat?=	../../wip/sdl12-compat

.endif	# SDL12_COMPAT_BUILDLINK3_MK

BUILDLINK_TREE+=	-sdl12-compat
