# $NetBSD: buildlink3.mk,v 1.2 2004/07/02 12:52:15 thomasklausner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JDK13_BUILDLINK3_MK:=	${JDK13_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jdk13
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njdk13}
BUILDLINK_PACKAGES+=	jdk13

.if !empty(JDK13_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.jdk13+=	jdk13>=1.0.8.20031122nb1
BUILDLINK_PKGSRCDIR.jdk13?=	../../wip/jdk13
BUILDLINK_JAVA_PREFIX.jdk13=	${PREFIX}/java/jdk-1.3.1

BUILDLINK_PASSTHRU_DIRS+=	${BUILDLINK_JAVA_PREFIX.jdk13}

BUILDLINK_CPPFLAGS.jdk13= \
	-I${BUILDLINK_JAVA_PREFIX.jdk13}/include				\
	-I${BUILDLINK_JAVA_PREFIX.jdk13}/include/netbsd
.endif	# JDK13_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
