# $NetBSD: buildlink3.mk,v 1.1 2009/03/11 16:16:56 jihbed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BAKERY_BUILDLINK3_MK:=	${BAKERY_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	bakery
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbakery}
BUILDLINK_PACKAGES+=	bakery
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}bakery

.if ${BAKERY_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.bakery+=	bakery>=2.6.3
BUILDLINK_PKGSRCDIR.bakery?=	../../wip/bakery
.endif	# BAKERY_BUILDLINK3_MK

.include "../../x11/gtkmm/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
