# $NetBSD: Makefile,v 1.1.1.1 2004/03/18 23:55:10 poppnk Exp $

PKGNAME=	kaffe-1.1.4

USE_X11=	YES
CONFIGURE_ARGS+= --with-staticlib

COMMENT=	Virtual machine capable of running Java(tm) code (without X)

# TODO : bl3 of classpath
#.include "../../lang/classpath/buildlink3.mk"
.include "Makefile.common"
