# $NetBSD$

BUILDLINK_TREE+=	abc

.if !defined(ABC_BUILDLINK3_MK)
ABC_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.abc?=	build
BUILDLINK_API_DEPENDS.abc+=	abc>=ef5389d31526003c2ebd7e6d6d6fe3848a20f0a2
BUILDLINK_PKGSRCDIR.abc?=	../../wip/abc
.endif	# ABC_BUILDLINK3_MK

BUILDLINK_TREE+=	-abc
