# $NetBSD$

BUILDLINK_TREE+=	abc

.if !defined(ABC_BUILDLINK3_MK)
ABC_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.abc?=	build
BUILDLINK_API_DEPENDS.abc+=	abc>=0.0.0.5430
BUILDLINK_PKGSRCDIR.abc?=	../../wip/abc
.endif	# ABC_BUILDLINK3_MK

BUILDLINK_TREE+=	-abc
