# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/02/14 14:03:25 obache Exp $
#

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
SJ3_CLIENT_BUILDLINK3_MK:=	${SJ3_CLIENT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	sj3-client
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsj3-client}
BUILDLINK_PACKAGES+=	sj3-client
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}sj3-client

.if ${SJ3_CLIENT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.sj3-client+=	sj3-client>=2.0.1.23
BUILDLINK_PKGSRCDIR.sj3-client?=	../../wip/sj3-client
.endif	# SJ3_CLIENT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
