# $NetBSD$

BUILDLINK_TREE+=	djbsort

.if !defined(DJBSORT_BUILDLINK3_MK)
DJBSORT_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.djbsort+=	djbsort>=20180717
BUILDLINK_PKGSRCDIR.djbsort?=	../../math/djbsort
BUILDLINK_DEPMETHOD.djbsort?=	build
.endif	# DJBSORT_BUILDLINK3_MK

BUILDLINK_TREE+=	-djbsort
