

PACKAGE BODY CA5003B0 IS

     FUNCTION SHOW_ELAB (UNIT : CHARACTER) RETURN INTEGER IS
     BEGIN
          ORDER (INDEX) := UNIT;
          INDEX := INDEX + 1;
          RETURN INDEX - 1;
     END SHOW_ELAB;

END CA5003B0;
