# $NetBSD: buildlink3.mk,v 1.4 2008/03/06 11:25:00 emil_s Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CABAL_BUILDLINK3_MK:=	${CABAL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cabal
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncabal}
BUILDLINK_PACKAGES+=	cabal
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cabal

.if ${CABAL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.cabal?=	build
BUILDLINK_API_DEPENDS.cabal+=	cabal>=1.2.2.0
BUILDLINK_PKGSRCDIR.cabal?=	../../wip/cabal
.endif	# CABAL_BUILDLINK3_MK

.include "../../lang/ghc/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
