# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/11/07 16:51:51 emil_s Exp $

BUILDLINK_DEPMETHOD.cabal?=	build

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CABAL_BUILDLINK3_MK:=	${CABAL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cabal
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncabal}
BUILDLINK_PACKAGES+=	cabal

.if !empty(CABAL_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.cabal+=	cabal>=1.1.3
BUILDLINK_PKGSRCDIR.cabal?=	../../wip/cabal
.endif	# CABAL_BUILDLINK3_MK

.include "../../lang/ghc/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
