# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/12/11 19:15:18 x400 Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
VALE_BUILDLINK3_MK:=	${VALE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	vale
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nvale}
BUILDLINK_PACKAGES+=	vale
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}vale

.if ${VALE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.vale+=	vale>=0.0.2
BUILDLINK_PKGSRCDIR.vale?=	../../wip/vale-current
.endif	# VALE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
