# $NetBSD: Makefile,v 1.5 2007/05/09 13:21:10 obache Exp $
#

.include "../../wip/mecab/Makefile.common"

DISTNAME=	mecab-jumandic-5.1-20070304
PKGNAME=	mecab-jumandic-5.1.20070304

COMMENT=	Japanese Morphological Dictionary for MeCab

GNU_CONFIGURE=	yes

UNLIMIT_RESOURCES=	datasize

.include "../../wip/mecab-base/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
