-- BC53001.A
--
--                             Grant of Unlimited Rights
--
--     Under contracts F33600-87-D-0337, F33600-84-D-0280, MDA903-79-C-0687,
--     F08630-91-C-0015, and DCA100-97-D-0025, the U.S. Government obtained 
--     unlimited rights in the software and documentation contained herein.
--     Unlimited rights are defined in DFAR 252.227-7013(a)(19).  By making 
--     this public release, the Government intends to confer upon all 
--     recipients unlimited rights  equal to those held by the Government.  
--     These rights include rights to use, duplicate, release or disclose the 
--     released technical data and computer software in whole or in part, in 
--     any manner and for any purpose whatsoever, and to have or permit others 
--     to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS.  THE GOVERNMENT MAKES NO EXPRESS OR IMPLIED 
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE 
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--*
--
-- OBJECTIVE:
--      Check that the index subtypes of an unconstrained formal array
--      subtype and its corresponding actual subtype must statically
--      match.
--
--      Check that the index ranges of a constrained formal array
--      subtype and its corresponding actual subtype must statically
--      match.
--
--      Check that the component subtypes of a formal array type and its
--      corresponding actual type must statically match. 
--
-- TEST DESCRIPTION:
--      Two subtypes statically match if their constraints statically match.
--      Two constraints statically match if both are null constraints, both
--      are static and have equal corresponding bounds or discriminant values,
--      or both are nonstatic and result from the same elaboration of a
--      constraint of a subtype indication or the same evaluation of a range
--      of a discrete subtype definition.
--
--      Two ranges statically match if both result from the same evaluation of
--      a range, or both are static and have equal corresponding bounds.
--      
--      Declare formal unconstrained array and constrained array subtypes.
--      Verify that their corresponding actual subtypes must statically
--      match.      
--
--
-- CHANGE HISTORY:
--      01 Feb 95   SAIC    Initial version.
--      20 Apr 95   SAIC    Added a new subtype case.
--


function BC53001_0 return Natural is
begin           -- Artificial; in real code this function might
   return 100;  -- prompt the user for a value.
end BC53001_0;
