# $NetBSD: buildlink3.mk,v 1.2 2006/04/23 11:05:51 cheusov Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBNETTLE_BUILDLINK3_MK:=	${LIBNETTLE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libnettle
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibnettle}
BUILDLINK_PACKAGES+=	libnettle

.if !empty(LIBNETTLE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libnettle+=	libnettle>=1.14
BUILDLINK_PKGSRCDIR.libnettle?=	../../wip/libnettle
.endif	# LIBNETTLE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
