# $NetBSD: Makefile,v 1.2 2014/05/05 00:03:01 szptvlfn Exp $

DISTNAME=	hasktags-0.68.2
PKGNAME=	${DISTNAME}
CATEGORIES=	devel #haskell

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Produces ctags "tags" and etags "TAGS" files for Haskell programs
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
