# $NetBSD$

BUILDLINK_TREE+=	go-sqlite3

.if !defined(GO_SQLITE3_BUILDLINK3_MK)
GO_SQLITE3_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-sqlite3=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-sqlite3?=	build

BUILDLINK_API_DEPENDS.go-sqlite3+=	go-sqlite3>=1.10.0
BUILDLINK_PKGSRCDIR.go-sqlite3?=	../../wip/go-sqlite3
.endif	# GO_SQLITE3_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-sqlite3
