# $NetBSD: Makefile,v 1.2 2004/03/16 21:32:52 mpasternak Exp $
# $Id: Makefile,v 1.2 2004/03/16 21:32:52 mpasternak Exp $
#

DISTNAME=		grep-2.5-i386-2
PKGNAME=		slackware_grep-2.5
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://slackware.com/
COMMENT=		GNU grep for Slackware emulation

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
