# $NetBSD: Makefile,v 1.1.1.1 2011/03/07 13:14:17 jihbed Exp $
#

DISTNAME=	spatt-2.0-pre7
PKGNAME=	${DISTNAME:S/-pre7//}
CATEGORIES=	biology
MASTER_SITES=	http://stat.genopole.cnrs.fr/spatt/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://stat.genopole.cnrs.fr/spatt/
COMMENT=	Statistics for Patterns
LICENSE=	gnu-gpl-v3

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
