# $NetBSD$

BUILDLINK_TREE+=	lzlib

.if !defined(LZLIB_BUILDLINK3_MK)
LZLIB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.lzlib+=	lzlib>=1.11
BUILDLINK_PKGSRCDIR.lzlib?=	../../wip/lzlib
.endif	# LZLIB_BUILDLINK3_MK

BUILDLINK_TREE+=	-lzlib
