# $NetBSD: buildlink3.mk,v 1.4 2008/08/07 18:31:23 htepper Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENCT_BUILDLINK3_MK:=	${OPENCT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	openct
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenct}
BUILDLINK_PACKAGES+=	openct

.if !empty(OPENCT_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.openct+=	openct>=0.6.15
BUILDLINK_PKGSRCDIR.openct?=	../../wip/openct
.endif	# OPENCT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
