# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/07/20 03:46:44 udontknow Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENCT_BUILDLINK3_MK:=	${OPENCT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	openct
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenct}
BUILDLINK_PACKAGES+=	openct

.if !empty(OPENCT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.openct+=	openct>=0.6.5
BUILDLINK_PKGSRCDIR.openct?=	../../wip/openct
.endif	# OPENCT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
