# $NetBSD: buildlink3.mk,v 1.2 2005/06/30 01:26:13 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EDITLINE_BUILDLINK3_MK:=	${EDITLINE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	editline
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Neditline}
BUILDLINK_PACKAGES+=	editline

.if !empty(EDITLINE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.editline+=	editline>=20041207.2.9
BUILDLINK_PKGSRCDIR.editline?=	../../wip/editline
.endif	# EDITLINE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
