# $NetBSD: Makefile,v 1.1 2012/01/25 09:10:22 mwdavies Exp $

DISTNAME=	sweeper-${_KDE_VERSION}
CATEGORIES=	sysutils
COMMENT=	KDE system cleaner

.include "../../wip/kde4/Makefile.kde4"

.include "../../wip/kde4/kde4.mk"

.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../wip/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
