# $NetBSD$

DISTNAME=	teamcity-messages-1.28
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:S/-messages//}
CATEGORIES=     devel python
MASTER_SITES=	https://files.pythonhosted.org/packages/df/c2/4ac5824fa5cc5739a63cfbd38b530c2fb0d19e26faa52779629048f8d0fe/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/JetBrains/teamcity-messages
COMMENT=	Send test results to TeamCity continuous integration server
LICENSE=	apache-2.0


.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
