# $NetBSD: Makefile,v 1.3 2003/06/25 06:52:46 marttikuparinen Exp $

.include "../xfce4/Makefile.common"

VERSION=	0.1
DISTNAME=	xfce4-systray-${VERSION}
COMMENT=	XFce4 systray plugin

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../textproc/libxml2/buildlink2.mk"
.include "../../wip/xfce4-panel/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
