# $NetBSD$

DISTNAME=	lark-parser-0.11.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=l/lark-parser/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/erezsh/lark
COMMENT=	Modern parsing library
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
