
WITH EB4014A1; WITH EB4014A_OUTSIDE;
WITH REPORT; USE REPORT;
PROCEDURE EB4014A IS
     X : INTEGER := EB4014A1;
BEGIN

     TEST("EB4014A", "THIS LINE SHOULD NOT PRINT OUT");

     FAILED("EXCEPTION DID NOT CAUSE MAIN PROGRAM TERMINATION");
     RESULT;
     X := IDENT_INT(X);
END EB4014A;
