
PACKAGE BODY EB4014A_OUTSIDE IS
     PROCEDURE REQUIRE_BODY IS
     BEGIN
          NULL;
     END;
BEGIN
     TEST("EB4014A", "CHECK THAT WHEN EXCEPTIONS ARE RAISED DURING " &
                     "THE ELABORATION OF A LIBRARY UNIT, EXECUTION " &
                     "OF THE MAIN PROGRAM IS ABANDONED");

     SPECIAL_ACTION("CHECK THE OUTPUT/LOG FILE TO SEE IF THIS " &
                    "PROGRAM TERMINATED WITH AN UNHANDLED " &
                    "EXCEPTION");

     RESULT;

     RAISE CONSTRAINT_ERROR;
END EB4014A_OUTSIDE;
