-- BB20001.A
--
--                             Grant of Unlimited Rights
--
--     Under contracts F33600-87-D-0337, F33600-84-D-0280, MDA903-79-C-0687,
--     F08630-91-C-0015, and DCA100-97-D-0025, the U.S. Government obtained 
--     unlimited rights in the software and documentation contained herein.
--     Unlimited rights are defined in DFAR 252.227-7013(a)(19).  By making 
--     this public release, the Government intends to confer upon all 
--     recipients unlimited rights  equal to those held by the Government.  
--     These rights include rights to use, duplicate, release or disclose the 
--     released technical data and computer software in whole or in part, in 
--     any manner and for any purpose whatsoever, and to have or permit others 
--     to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS.  THE GOVERNMENT MAKES NO EXPRESS OR IMPLIED 
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE 
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--*
--
-- OBJECTIVE:
--      Check that an exception_name of a choice cannot denote an exception 
--      declared in a generic formal package.                  
--
-- TEST DESCRIPTION:
--      Declare an exception in a library-level generic package.  Declare 
--      another library-level generic package which declares a formal
--      package with (<>) as its actual part.  Declare various instances
--      of the template for the formal package and use that exception as a
--      choice within an exception handler in the generic body.  Verify that 
--      an exception declared in a generic formal package is illegal when 
--      it is used as an exception choice in generic units.
--
--
-- CHANGE HISTORY:
--      02 May 95   SAIC    Initial prerelease version.
--      07 Sep 96   SAIC    Modified test description. Changed IPck8.Exception
--                          to be ok.                  
--
--!

package BB20001_0 is                                   
   Common_Exception : exception;
end BB20001_0;
