
WITH C23006BPKG, C23006B_PKG;
USE C23006BPKG, C23006B_PKG;
WITH REPORT; USE REPORT;
PROCEDURE C23006B IS
BEGIN
     TEST ("C23006B", "CHECK UNDERSCORES ARE SIGNIFICANT " &
                      "FOR LIBRARY PACKAGE IDENTIFIERS");

     IF A + IDENT_INT(4) /= D THEN
          FAILED ("INCORRECT PACKAGE IDENTIFICATION");
     END IF;

     RESULT;
END C23006B; 
