# $NetBSD: Makefile,v 1.1 2013/04/05 21:36:03 szptvlfn Exp $

DISTNAME=	timezone-olson-0.1.2
CATEGORIES=	time

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://projects.haskell.org/time-ng/
COMMENT=	Pure Haskell parser and renderer for binary Olson timezone files
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-timezone-series/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
