# $NetBSD: buildlink3.mk,v 1.2 2009/03/20 19:43:39 jsonn Exp $

BUILDLINK_TREE+=	TinySVM

.if !defined(TINYSVM_BUILDLINK3_MK)
TINYSVM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.TinySVM+=	TinySVM>=0.09
BUILDLINK_PKGSRCDIR.TinySVM?=	../../wip/TinySVM
.endif # TINYSVM_BUILDLINK3_MK

BUILDLINK_TREE+=	-TinySVM
