# $NetBSD: Makefile,v 1.1.1.1 2008/01/23 07:34:37 obache Exp $
#

DISTNAME=	TinySVM-0.09
CATEGORIES=	devel
MASTER_SITES=	http://www.chasen.org/~taku/software/TinySVM/src/

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	http://www.chasen.org/~taku/software/TinySVM/
COMMENT=	Tiny Support Vector Machines

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

TEST_TARGET=	check

.include "../../mk/bsd.pkg.mk"
