# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/12 03:41:40 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
UNIPLATE_BUILDLINK3_MK:=	${UNIPLATE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	uniplate
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nuniplate}
BUILDLINK_PACKAGES+=	uniplate
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}uniplate

.if ${UNIPLATE_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.uniplate?=	build
BUILDLINK_API_DEPENDS.uniplate+=	uniplate>=1.2.0.3
BUILDLINK_PKGSRCDIR.uniplate?=	../../wip/uniplate
.endif	# UNIPLATE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
