# $NetBSD: Makefile,v 1.2 2012/10/07 12:25:13 asau Exp $
#

DISTNAME=	Khayyam-0.5rc2
PKGNAME=	${PYPKGPREFIX}-khayyam-0.5rc2
CATEGORIES=	time math
MASTER_SITES=	${MASTER_SITE_PYPI:=K/Khayyam/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://pylover.dobisel.com/projects/khayyam
COMMENT=	Khayyam(Jalali Persian Datetime) library

WRKSRC=		${WRKDIR}/Khayyam-0.5rc2

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
