# $NetBSD$

BUILDLINK_TREE+=	SSVUtilsJson

.if !defined(SSVUTILSJSON_BUILDLINK3_MK)
SSVUTILSJSON_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVUtilsJson+=	SSVUtilsJson>=20130714
BUILDLINK_PKGSRCDIR.SSVUtilsJson?=	../../wip/SSVUtilsJson

BUILDLINK_DEPMETHOD.SSVUtilsJson?=	build
BUILDLINK_FILES.SSVUtilsJson+=		lib/cmake/FindSSVUtilsJson.cmake

.endif	# SSVUTILSJSON_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVUtilsJson
