# $NetBSD: Makefile,v 1.1.1.1 2005/12/06 00:07:52 poppnk Exp $
#

DISTNAME=		kawa-1.8
CATEGORIES=		wip lang
MASTER_SITES=		http://ftp.gnu.org/pub/gnu/kawa/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.gnu.org/software/kawa/
COMMENT=		Scheme interpreter written in Java.

USE_PKGLOCALEDIR=	yes
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/java-vm.mk"
.include "../../mk/bsd.pkg.mk"
