# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/09/01 05:27:32 hugor Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CLHEP_BUILDLINK3_MK:=	${CLHEP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	clhep
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nclhep}
BUILDLINK_PACKAGES+=	clhep

.if ${CLHEP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.clhep+=	clhep>=1.9.2.3
BUILDLINK_PKGSRCDIR.clhep?=	../../wip/clhep
.endif

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
