# $NetBSD: buildlink3.mk,v 1.3 2006/09/21 12:51:18 hugor Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CLHEP_BUILDLINK3_MK:=	${CLHEP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	clhep
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nclhep}
BUILDLINK_PACKAGES+=	clhep

.if ${CLHEP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.clhep+=	clhep>=1.9.2.3
BUILDLINK_PKGSRCDIR.clhep?=	../../wip/clhep
BUILDLINK_DEPMETHOD.clhep?=	build
.endif

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
