# $NetBSD: buildlink3.mk,v 1.5 2006/10/31 17:01:33 hugor Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CLHEP_BUILDLINK3_MK:=	${CLHEP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	clhep
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nclhep}
BUILDLINK_PACKAGES+=	clhep
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}clhep

.if ${CLHEP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.clhep+=	clhep>=1.9.3.0
BUILDLINK_PKGSRCDIR.clhep?=	../../wip/clhep
BUILDLINK_DEPMETHOD.clhep?=	build
.endif

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
