# $NetBSD: Makefile,v 1.2 2008/05/24 15:34:13 tnn2 Exp $

PKGVERSION=	0.13
DISTNAME=	Exception-Base-${PKGVERSION}
PKGNAME=	p5-Exception-Base-${PKGVERSION}
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN:=../../authors/id/D/DE/DEXTER/}

MAINTAINER=	ggm@apnic.net
HOMEPAGE=	http://search.cpan.org/src/DEXTER/Exception-Base-0.13
COMMENT=	Exception::Base

PERL5_PACKLIST=	auto/Exception/Base/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
