# $Id: Makefile,v 1.43 2003/04/07 06:09:10 marc Exp $
# $NetBSD: Makefile,v 1.43 2003/04/07 06:09:10 marc Exp $

COMMENT=	WIP pkgsrc packages

SUBDIR+=	PPower4
SUBDIR+=	allegro
SUBDIR+=	aolserver
SUBDIR+=	autoproject
SUBDIR+=	byacc
SUBDIR+=	chksniff
SUBDIR+=	coreutils
SUBDIR+=	cvsd
SUBDIR+=	gkrellm2
SUBDIR+=	gkrellm2-flynn
SUBDIR+=	gkrellm2-server
SUBDIR+=	gkrellm2-share
SUBDIR+=	gkrellm2-volume
SUBDIR+=	gkrellm2-xmms
SUBDIR+=	golem
SUBDIR+=	gtk-sharp
SUBDIR+=	gtkglarea2
SUBDIR+=	httrack
SUBDIR+=	ickle
SUBDIR+=	ike-scan
SUBDIR+=	ion-devel
SUBDIR+=	ion-dock
SUBDIR+=	ircservices
SUBDIR+=	liquidwar
SUBDIR+=	mailfilter
SUBDIR+=	nagios-base
SUBDIR+=	nagios-plugin-ldap
SUBDIR+=	nagios-plugin-mysql
SUBDIR+=	nagios-plugin-pgsql
SUBDIR+=	nagios-plugin-snmp
SUBDIR+=	nagios-plugins
SUBDIR+=	navigatrix
SUBDIR+=	nvtv
SUBDIR+=	p5-Chart
SUBDIR+=	p5-Net-Jabber
SUBDIR+=	p5-Time
SUBDIR+=	p5-Unicode-String
SUBDIR+=	p5-XML-Stream
SUBDIR+=	perltidy
SUBDIR+=	poedit
SUBDIR+=	py-ORBit
SUBDIR+=	py-PgSQL
SUBDIR+=	py-csv
SUBDIR+=	py-gnome2
SUBDIR+=	py-gtk2
SUBDIR+=	startup-notification
SUBDIR+=	tcpflow
SUBDIR+=	tex-foiltex
SUBDIR+=	vim-gtk2
SUBDIR+=	yasm
