# $NetBSD: Makefile,v 1.2 2009/10/02 02:06:45 phonohawk Exp $
#

DISTNAME=	HDBC-sqlite3-2.1.0.2
CATEGORIES=	databases

MAINTAINER=	pho@cielonegro.org
COMMENT=	Sqlite v3 driver for HDBC

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-HDBC/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-utf8-string/buildlink3.mk"
.include "../../databases/sqlite3/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
