# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/01/23 07:39:31 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
YAMCHA_BUILDLINK3_MK:=	${YAMCHA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	yamcha
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nyamcha}
BUILDLINK_PACKAGES+=	yamcha
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}yamcha

.if ${YAMCHA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.yamcha+=	yamcha>=0.33
BUILDLINK_PKGSRCDIR.yamcha?=	../../wip/yamcha
.endif	# YAMCHA_BUILDLINK3_MK

.include "../../wip/TinySVM/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
