
WITH REPORT; USE REPORT;
WITH C83025C_PACK; USE C83025C_PACK;
PROCEDURE C83025C IS

     PROCEDURE NEW_INNER IS NEW INNER;

     PROCEDURE NEW_INNER2 IS NEW INNER2;

     FUNCTION NEW_INNER3 IS NEW INNER3;

     FUNCTION NEW_INNER4 IS NEW INNER4 (Y => EOBJ);

     PROCEDURE NEW_INNER5 IS NEW INNER5;

BEGIN
     TEST ("C83025C", "CHECK THAT A DECLARATION IN A DECLARATIVE " &
                      "REGION OF A GENERIC SUBPROGRAM HIDES AN OUTER " &
                      "DECLARATION OF A HOMOGRAPH");

     A := IDENT_INT(2);
     B := A;

     NEW_INNER (A);

     IF A /= IDENT_INT(3) THEN
          FAILED ("INCORRECT VALUE PASSED OUT - 7");
     END IF;

     A := IDENT_INT(2);

     NEW_INNER2 (A => OBJ);

     IF OBJ /= IDENT_INT(4) THEN
          FAILED ("INCORRECT VALUE PASSED OUT - 16");
     END IF;

     A := IDENT_INT(2);

     B := A;

     IF NEW_INNER3(A) /= IDENT_INT(3) THEN
          FAILED ("INCORRECT VALUE PASSED OUT - 27");
     END IF;

     A := IDENT_INT(2);

     B := A;

     IF NEW_INNER4(A) /= IDENT_INT(3) THEN
          FAILED ("INCORRECT VALUE PASSED OUT - 37");
     END IF;

     OBJ := 1;

     FLO := 6.25;

     NEW_INNER5 (OBJ, FLO);

     IF OBJ /= IDENT_INT(6) THEN
          FAILED ("INCORRECT VALUE RETURNED FROM FUNCTION - 42");
     END IF;

     IF Y /= 5 THEN
          FAILED ("INCORRECT VALUE FOR OUTER HOMOGRAPH - 50");
     END IF;

     IF Z /= 5 THEN
          FAILED ("INCORRECT VALUE FOR OUTER VARIABLE - 51");
     END IF;

     RESULT;
END C83025C;
