
SEPARATE (C83025C_PACK)
PROCEDURE INNER5 (X : IN OUT INTEGER; F : IN FLOAT;
                  Z : CHARACTER := Y) IS
BEGIN
     X := INTEGER(F);

     IF Y /= 'A' THEN
          FAILED ("INCORRECT VALUE FOR INNER HOMOGRAPH - 40");
     END IF;

     IF Z /= 'A' THEN
          FAILED ("INCORRECT VALUE FOR INNER VARIABLE - 41");
     END IF;
END INNER5;
