# $NetBSD: buildlink3.mk,v 1.1 2009/08/24 23:27:40 mbowie Exp $
BUILDLINK_TREE+=	GeoIP

.if !defined(GEOIP_BUILDLINK3_MK)
GEOIP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.GeoIP+=	GeoIP>=1.4.6
BUILDLINK_PKGSRCDIR.GeoIP?=	../../wip/GeoIP
.endif	# GEOIP_BUILDLINK3_MK

BUILDLINK_TREE+=	-GeoIP
