# $NetBSD: buildlink3.mk,v 1.4 2006/06/22 08:28:34 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBUPNP_BUILDLINK3_MK:=	${LIBUPNP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libupnp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibupnp}
BUILDLINK_PACKAGES+=	libupnp

.if ${LIBUPNP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libupnp+=	libupnp>=1.4.0
BUILDLINK_PKGSRCDIR.libupnp?=	../../wip/libupnp
.endif	# LIBUPNP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
