# $NetBSD: Makefile,v 1.6 2005/05/24 10:31:49 rillig Exp $
#

DISTNAME=	wmitime-0.3
CATEGORIES=     x11 sysutils
MASTER_SITES=	http://www.neotokyo.org/illusion/downloads/

MAINTAINER=	poff@sixbit.org
HOMEPAGE=	http://www.neotokyo.org/illusion/dock_apps.html
COMMENT=	Windowmaker dockapp for time/date/itime

WRKSRC=         ${WRKDIR}/wmitime/wmitime

USE_TOOLS+=	gmake
USE_X11=	YES

.include "../../mk/bsd.pkg.mk"
