# $NetBSD: Makefile,v 1.5 2005/04/11 21:16:14 tvierling Exp $
#

DISTNAME=	wmitime-0.3
CATEGORIES=     x11 sysutils
MASTER_SITES=	http://www.neotokyo.org/illusion/downloads/

MAINTAINER=	poff@sixbit.org
HOMEPAGE=	http://www.neotokyo.org/illusion/dock_apps.html
COMMENT=	Windowmaker dockapp for time/date/itime

WRKSRC=         ${WRKDIR}/wmitime/wmitime

USE_GNU_TOOLS+=	make
USE_X11=	YES

.include "../../mk/bsd.pkg.mk"
