# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/06/30 10:57:22 ondratu Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
EVENTLOG_BUILDLINK3_MK:=	${EVENTLOG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	eventlog
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Neventlog}
BUILDLINK_PACKAGES+=	eventlog
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}eventlog

.if ${EVENTLOG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.eventlog+=	eventlog>=0.2.5
BUILDLINK_PKGSRCDIR.eventlog?=	../../wip/eventlog
.endif	# EVENTLOG_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
