# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/11/11 01:31:24 pmatias Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBANIMAL_BUILDLINK3_MK:=	${LIBANIMAL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libanimal
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibanimal}
BUILDLINK_PACKAGES+=	libanimal
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libanimal

.if ${LIBANIMAL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libanimal+=	libanimal>=0.15.0
BUILDLINK_PKGSRCDIR.libanimal?=	../../wip/libanimal
.endif	# LIBANIMAL_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
