# $NetBSD: buildlink3.mk,v 1.2 2004/05/10 01:39:09 blef Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_F2PY2E_BUILDLINK3_MK:=	${PY_F2PY2E_BUILDLINK3_MK}+

.include "../../lang/python/pyversion.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pyf2py2e
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npyf2py2e}
BUILDLINK_PACKAGES+=	pyf2py2e

.if !empty(PY_F2PY2E_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.pyf2py2e+=	${PYPKGPREFIX}-f2py2e-[0-9]*
BUILDLINK_PKGSRCDIR.pyf2py2e?=	../../wip/py-f2py2e
.endif	# PY_F2PY2E_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
