# $NetBSD: buildlink3.mk,v 1.1 2004/05/04 02:47:26 blef Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DUMB_BUILDLINK3_MK:=	${DUMB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dumb
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndumb}
BUILDLINK_PACKAGES+=	dumb

.if !empty(DUMB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.dumb+=	dumb>=0.9.2
BUILDLINK_PKGSRCDIR.dumb?=	../../wip/dumb
.endif	# DUMB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
