# $NetBSD: Makefile,v 1.1.1.1 2009/06/02 06:57:32 phonohawk Exp $
#

DISTNAME=	HUnit-1.2.0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://hunit.sourceforge.net/
COMMENT=	Unit testing framework for Haskell

USE_LANGUAGES=	# none

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
