# $NetBSD: Makefile,v 1.5 2006/05/19 16:51:41 ykomatsu Exp $
#

DISTNAME=		xplore-1.2a
CATEGORIES=		sysutils x11
MASTER_SITES=		http://www.musikwissenschaft.uni-mainz.de/~ag/xplore/
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://www.musikwissenschaft.uni-mainz.de/~ag/xplore/
COMMENT=		X11/Motif File Manager

USE_IMAKE=		YES

.include "../../graphics/xpm/buildlink3.mk"
.include "../../mk/motif.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
