# $NetBSD: Makefile,v 1.8 2005/11/02 18:00:00 thomasklausner Exp $
#

DISTNAME=		bluez-hcidump-1.24
CATEGORIES=		net
MASTER_SITES=		http://bluez.sf.net/download/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.bluez.org/
COMMENT=		Bluetooth packet analyzer

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../wip/bluez-libs/Makefile.common"
.include "../../mk/bsd.pkg.mk"
