# $NetBSD: buildlink3.mk,v 1.1 2008/09/06 23:37:48 milosn Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
IOVM_BUILDLINK3_MK:=		${IOVM_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	io-vm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nio-vm}
BUILDLINK_PACKAGES+=	io-vm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}io-vm

.if !empty(IOVM_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.io-vm+=		io-vm>=20080904
BUILDLINK_ABI_DEPENDS.io-vm+=		io-vm>=20080904
BUILDLINK_PKGSRCDIR.io-vm?=		../../wip/io-vm

BUILDLINK_INCDIRS.io-vm+=		include/io

.endif	# IOVM_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
