
WITH REPORT; USE REPORT;
WITH C38108B_P; USE C38108B_P;
PROCEDURE C38108B IS
     VAL_1, VAL_2 : L;
BEGIN

     TEST ("C38108B", "CHECK THAT INCOMPLETE TYPE CAN BE DECLARED IN " &
                      "PRIVATE PART WITHOUT FULL DECLARATION - " &
                      "LIBRARY PACKAGE");

     ASSIGN (2, VAL_1);
     ASSIGN (2, VAL_2);
     IF NOT "=" (VAL_1, VAL_2) THEN
          FAILED ("INCOMPLETE TYPE NOT FULLY DECLARED");
     END IF;

     RESULT;
END C38108B;
