# $NetBSD: Makefile,v 1.4 2005/07/27 16:31:07 thomasklausner Exp $
#

DISTNAME=		tenmado-0.6
CATEGORIES=		games
MASTER_SITES=		http://www.interq.or.jp/libra/oohara/tenmado/

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://www.interq.or.jp/libra/oohara/tenmado/
COMMENT=		Vertical scrolling shoot'em-up game

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../devel/SDL/buildlink3.mk"
.include "../../graphics/SDL_image/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
