# $NetBSD: Makefile,v 1.1.1.1 2006/03/30 06:41:42 ghen Exp $

MOZILLA=	firefox2-gtk1
COMMENT=	Lightweight gecko-based web browser built with GTK+-1.x

.include "../../wip/firefox2/Makefile-firefox.common"
.include "../../mk/bsd.pkg.mk"
