[Icon Theme]
Name=netbsd
Comment=NetBSD icon theme
Inherits=elementary-mono-dark

Example=directory-x-normal

#Directory list
Directories=places/22,places/24,places/48,places/64,places/128

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Scalable

[places/64]
Size=64
Context=Places
Type=Scalable

[places/128]
Size=128
Context=Places
Type=Scalable
