# $NetBSD: buildlink3.mk,v 1.2 2009/01/12 06:32:32 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HS_UTF8_STRING_BUILDLINK3_MK:=	${HS_UTF8_STRING_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-utf8-string
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-utf8-string}
BUILDLINK_PACKAGES+=	hs-utf8-string
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-utf8-string

.if ${HS_UTF8_STRING_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-utf8-string?=	build
BUILDLINK_API_DEPENDS.hs-utf8-string+=	hs-utf8-string>=0.3.3
BUILDLINK_PKGSRCDIR.hs-utf8-string?=	../../wip/hs-utf8-string
.endif	# HS_UTF8_STRING_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
