# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/01/26 14:49:35 oherrala Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
PBL_BUILDLINK3_MK:=	${PBL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	pbl
.endif

.if !empty(PBL_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		pbl
BUILDLINK_DEPENDS.pbl?=		pbl>=1.02
BUILDLINK_PKGSRCDIR.pbl?=	../../wip/pbl

.endif # PBL_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
