# $NetBSD: Makefile,v 1.6 2013/11/25 10:54:27 szptvlfn Exp $
#

DISTNAME=	case-insensitive-1.1.0.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Case insensitive string comparison
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
