# $NetBSD: buildlink3.mk,v 1.2 2006/10/29 11:23:08 shattered Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FONT_UTIL_BUILDLINK3_MK:=	${FONT_UTIL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	font-util
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfont-util}
BUILDLINK_PACKAGES+=	font-util
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}font-util

.if ${FONT_UTIL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.font-util+=	font-util>=1.0.1
BUILDLINK_PKGSRCDIR.font-util?=	../../wip/font-util
BUILDLINK_DEPMETHOD.font-util?=	build
.endif	# FONT_UTIL_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
