# $NetBSD: buildlink3.mk,v 1.2 2007/07/10 01:00:43 shindenmorr Exp $

BUILDLINK_DEPMETHOD.libdshconfig?=      build
BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBDSHCONFIG_BUILDLINK3_MK:=	${LIBDSHCONFIG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libdshconfig
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibdshconfig}
BUILDLINK_PACKAGES+=	libdshconfig
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libdshconfig

.if ${LIBDSHCONFIG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libdshconfig+=	libdshconfig>=0.20.9
BUILDLINK_PKGSRCDIR.libdshconfig?=	../../wip/libdshconfig
.endif	# LIBDSHCONFIG_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
