# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/27 15:02:53 shindenmorr Exp $

BUILDLINK_DEPMETHOD.pkcs11-helper?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PKCS11_HELPER_BUILDLINK3_MK:=	${PKCS11_HELPER_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	pkcs11-helper
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npkcs11-helper}
BUILDLINK_PACKAGES+=	pkcs11-helper
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}pkcs11-helper

.if ${PKCS11_HELPER_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.pkcs11-helper+=	pkcs11-helper>=1.06
BUILDLINK_PKGSRCDIR.pkcs11-helper?=	../../wip/pkcs11-helper
.endif	# PKCS11_HELPER_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
