# $NetBSD$

PKG_OPTIONS_VAR=		PKG_OPTIONS.prusaslicer
PKG_SUPPORTED_OPTIONS=		glesv2
PKG_SUGGESTED_OPTIONS=

.include "../../mk/bsd.options.mk"

.if !empty(PKG_OPTIONS:Mglesv2)
CMAKE_CONFIGURE_ARGS+=		-DSLIC3R_OPENGL_ES:BOOL=TRUE
CMAKE_CONFIGURE_ARGS+=		-DCMAKE_C_FLAGS:STRING=-DGLAD_GLES2_USE_SYSTEM_EGL=1
.endif
