# $NetBSD$

GO_MODULE_FILES+=	github.com/creack/pty/@v/v1.1.15.mod
GO_MODULE_FILES+=	github.com/creack/pty/@v/v1.1.15.zip
GO_MODULE_FILES+=	github.com/google/go-cmp/@v/v0.5.9.mod
GO_MODULE_FILES+=	github.com/google/go-cmp/@v/v0.5.9.zip
GO_MODULE_FILES+=	github.com/gorilla/websocket/@v/v1.4.1.mod
GO_MODULE_FILES+=	github.com/mattn/go-isatty/@v/v0.0.17.mod
GO_MODULE_FILES+=	github.com/mattn/go-isatty/@v/v0.0.17.zip
GO_MODULE_FILES+=	github.com/sourcegraph/jsonrpc2/@v/v0.2.0.mod
GO_MODULE_FILES+=	github.com/sourcegraph/jsonrpc2/@v/v0.2.0.zip
GO_MODULE_FILES+=	go.etcd.io/bbolt/@v/v1.3.7.mod
GO_MODULE_FILES+=	go.etcd.io/bbolt/@v/v1.3.7.zip
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.1.0.mod
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.1.0.zip
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.0.0-20220811171246-fbc7d0a398ab.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.5.0.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.5.0.zip
GO_MODULE_FILES+=	pkg.nimblebun.works/go-lsp/@v/v1.1.0.mod
GO_MODULE_FILES+=	pkg.nimblebun.works/go-lsp/@v/v1.1.0.zip
