# $NetBSD$

GO_MODULE_FILES+=	github.com/creack/pty/@v/v1.1.18.mod
GO_MODULE_FILES+=	github.com/creack/pty/@v/v1.1.18.zip
GO_MODULE_FILES+=	github.com/google/go-cmp/@v/v0.5.9.mod
GO_MODULE_FILES+=	github.com/google/go-cmp/@v/v0.5.9.zip
GO_MODULE_FILES+=	github.com/gorilla/websocket/@v/v1.4.1.mod
GO_MODULE_FILES+=	github.com/mattn/go-isatty/@v/v0.0.19.mod
GO_MODULE_FILES+=	github.com/mattn/go-isatty/@v/v0.0.19.zip
GO_MODULE_FILES+=	github.com/sourcegraph/jsonrpc2/@v/v0.2.0.mod
GO_MODULE_FILES+=	github.com/sourcegraph/jsonrpc2/@v/v0.2.0.zip
GO_MODULE_FILES+=	go.etcd.io/bbolt/@v/v1.3.7.mod
GO_MODULE_FILES+=	go.etcd.io/bbolt/@v/v1.3.7.zip
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.3.0.mod
GO_MODULE_FILES+=	golang.org/x/sync/@v/v0.3.0.zip
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.10.0.mod
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.10.0.zip
GO_MODULE_FILES+=	golang.org/x/sys/@v/v0.6.0.mod
GO_MODULE_FILES+=	pkg.nimblebun.works/go-lsp/@v/v1.1.0.mod
GO_MODULE_FILES+=	pkg.nimblebun.works/go-lsp/@v/v1.1.0.zip
