# $NetBSD: buildlink3.mk,v 1.5 2006/04/06 07:18:19 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
POSTGRESQL74_POSTGIS_BUILDLINK3_MK:=	${POSTGRESQL74_POSTGIS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	postgresql74-postgis
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npostgresql74-postgis}
BUILDLINK_PACKAGES+=	postgresql74-postgis

.if !empty(POSTGRESQL74_POSTGIS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.postgresql74-postgis+=	postgresql74-postgis>=1.1.1
BUILDLINK_PKGSRCDIR.postgresql74-postgis?=	../../wip/postgresql74-postgis
.endif	# POSTGRESQL74_POSTGIS_BUILDLINK3_MK

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH:S/+$//}
