# $NetBSD: Makefile,v 1.1.1.1 2005/11/08 21:01:19 plunky Exp $

DISTNAME=	hcidump-1.5.1
CATEGORIES=	wip sysutils
MASTER_SITES=	http://www.geocities.com/m_evmenkin/

MAINTAINER=	plunky@rya-online.net
COMMENT=	Bluetooth traffic dumper, similar to tcpdump

ONLY_FOR_PLATFORM=	NetBSD-*-*

WRKSRC=		${WRKDIR}/hcidump

INSTALLATION_DIRS=	man/man1

.include "../../mk/bsd.pkg.mk"
