# $NetBSD: buildlink3.mk,v 1.2 2006/08/09 10:23:14 dauphing Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
UBIT_BUILDLINK3_MK:=		${UBIT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ubit
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nubit}
BUILDLINK_PACKAGES+=	ubit
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ubit

.if !empty(UBIT_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.ubit+=		ubit>=5.0.0
BUILDLINK_PKGSRCDIR.ubit?=		../../wip/ubit
.endif	# UBIT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
