# $NetBSD: Makefile,v 1.4 2005/07/27 16:27:22 thomasklausner Exp $
#

DISTNAME=		Fnorb-1.3
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=fnorb/}

MAINTAINER=		tech-pkg@NetBSD.org
HOMEPAGE=		http://fnorb.sourceforge.net/
COMMENT=		CORBA 2.0 ORB for Python


PY_PATCHPLIST=		yes
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
