# $NetBSD: buildlink3.mk,v 1.3 2006/04/06 07:16:57 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AVIFILE_DEVEL_BUILDLINK3_MK:=	${AVIFILE_DEVEL_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	avifile-devel
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Navifile-devel}
BUILDLINK_PACKAGES+=	avifile-devel

.if !empty(AVIFILE_DEVEL_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.avifile-devel+=	avifile-devel>=0.7.41
BUILDLINK_ABI_DEPENDS.avifile-devel+=	avifile-devel>=0.7.41
BUILDLINK_PKGSRCDIR.avifile-devel?=	../../wip/avifile-devel
.endif	# AVIFILE_DEVEL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
