

WITH REPORT; USE REPORT;
WITH CA5004A1; USE CA5004A1;
PRAGMA ELABORATE (CA5004A1, REPORT);
PACKAGE BODY CA5004A2 IS

     I : INTEGER := 1;

     PROCEDURE REQUIRE_BODY IS
     BEGIN
          NULL;
     END;
BEGIN

     TEST ("CA5004A", "APPLYING PRAGMA ELABORATE TO A PACKAGE " &
                      "DECLARING A TASK OBJECT CAUSES IMPLICIT " &
                      "BODY ELABORATION AND TASK ACTIVATION");

     SELECT
          T.E(I);
          IF I /= 4 THEN
               FAILED ("TASK NOT EXECUTED PROPERLY");
          END IF;
     OR
          DELAY 10.0;
          FAILED ("TASK NOT ACTIVATED AFTER 10 SECONDS");
     END SELECT;

END CA5004A2;
