# $NetBSD$
#

DISTNAME=	tcprelay-1.3.2
CATEGORIES=	net
MASTER_SITES=	http://sebastien.millet1.perso.sfr.fr/tcprelay/packages/

MAINTAINER=	gianni-pkgsrc-wip@daprile.net
HOMEPAGE=	http://sebastien.millet1.perso.sfr.fr/tcprelay/
COMMENT=	Relay TCP connections between a client and a server
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
