# $NetBSD: buildlink3.mk,v 1.3 2005/10/24 02:13:10 minskim Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ZOPE3_BUILDLINK3_MK:=	${ZOPE3_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	zope3
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nzope3}
BUILDLINK_PACKAGES+=	zope3

.if !empty(ZOPE3_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.zope3+=	zope3>=3.1.0
BUILDLINK_PKGSRCDIR.zope3?=	../../wip/zope3
.endif	# ZOPE3_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
