# $NetBSD: Makefile,v 1.1.1.1 2003/09/01 12:52:06 adrian_p Exp $

DISTNAME=	Log-1.7.0
PKGNAME=	pear-${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_PAIR_PACKAGE}

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://www.csh.rit.edu/~jon/projects/pear_log/
COMMENT=	The Log framework provides an abstracted logging system

USE_BUILDLINK2=		YES

.include "../../wip/php4/package.mk"
.include "../../mk/bsd.pkg.mk"
