# $NetBSD: Makefile,v 1.2 2003/04/11 15:07:01 jmmv Exp $
#

DISTNAME=	BillardGL-1.75
PKGNAME=	${DISTNAME:S/BillardGL/billardgl/}
WRKSRC=		${WRKDIR}/src
CATEGORIES=	games
MASTER_SITES=	http://wesley.informatik.uni-freiburg.de/~nopper/BillardGL/download/

MAINTAINER=	wojtek@3miasto.net
HOMEPAGE=	http://www.tobias-nopper.de/BillardGL/
COMMENT=	3D Billard using OpenGL hardware acceleration

USE_GMAKE=	yes

.include "../../mk/bsd.pkg.mk"
