-- CXAC009.A
--
--     The Ada Conformity Assessment Authority (ACAA) holds unlimited
--     rights in the software and documentation contained herein. Unlimited
--     rights are the same as those granted by the U.S. Government for older
--     parts of the Ada Conformity Assessment Test Suite, and are defined
--     in DFAR 252.227-7013(a)(19). By making this public release, the ACAA
--     intends to confer upon all recipients unlimited rights equal to those
--     held by the ACAA. These rights include rights to use, duplicate,
--     release or disclose the released technical data and computer software
--     in whole or in part, in any manner and for any purpose whatsoever, and
--     to have or permit others to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS. THE ACAA MAKES NO EXPRESS OR IMPLIED
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--
--                                     Notice
--
--    The ACAA has created and maintains the Ada Conformity Assessment Test
--    Suite for the purpose of conformity assessments conducted in accordance
--    with the International Standard ISO/IEC 18009 - Ada: Conformity
--    assessment of a language processor. This test suite should not be used
--    to make claims of conformance unless used in accordance with
--    ISO/IEC 18009 and any applicable ACAA procedures.
--
--*
--
-- OBJECTIVE:
--      Check that Stream_IO.File_Type has Preeelaborable_Initialization.
--
-- TEST DESCRIPTION:
--      This test is designed to demonstrate using a logger in a preelaborated
--      package. The logger uses Stream_IO to write to the log as it is the
--      only Ada IO package that can be used in a preelaborated package.
--
--      We use the general design of test CXAC007, but instead of opening and
--      closing the log with each operation, we instead open and close it
--      separately. Once closed, we then read it to verify the expected
--      contents.
--
-- APPLICABILITY CRITERIA:
--      This test is applicable to all implementations capable of supporting
--      external Stream_IO files.
--
--
-- CHANGE HISTORY:
--    23 Mar 2017   RLB   Created version to test Preelaborable_Initialization.
--
--!
with Ada.Streams.Stream_IO;
package CXAC009_Logger
   with Preelaborate is

   procedure Open_Log (Log_Name : in String);
      -- Open the log file Log_Name.
      -- Note: We have to pass the file name here since it is generated by
      -- the Report package, which is not Preelaborated. In a real program,
      -- the name would most likely come from a constant or function declared
      -- in this package rather than being passed.

   procedure Close_Log;
      -- Close the log file.

   procedure Log_Item (Item : in String);
      -- Write an item to the log file.

end CXAC009_Logger;
