# $NetBSD: Makefile,v 1.1.1.1 2004/01/05 21:36:58 xtraeme Exp $

.include "${.CURDIR}/../../wip/cvsup/Makefile.common"

PKGNAME=	cvsup-gui-16.1.h

USE_X11=	YES

CONFLICTS=	cvsup-[0-9]*

.include "../../mk/bsd.pkg.mk"
