# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:17:04 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBASSA_BUILDLINK3_MK:=	${LIBASSA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libassa
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibassa}
BUILDLINK_PACKAGES+=	libassa

.if !empty(LIBASSA_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libassa+=	libassa>=3.4.0
BUILDLINK_PKGSRCDIR.libassa?=	../../wip/libassa
.endif	# LIBASSA_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
