# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/03/16 09:01:33 bartoszkuzma Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBASSA_BUILDLINK3_MK:=	${LIBASSA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libassa
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibassa}
BUILDLINK_PACKAGES+=	libassa

.if !empty(LIBASSA_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libassa+=	libassa>=3.4.0
BUILDLINK_PKGSRCDIR.libassa?=	../../wip/libassa
.endif	# LIBASSA_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
