# $NetBSD: buildlink3.mk,v 1.5 2006/10/09 17:56:00 bartoszkuzma Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBASSA_BUILDLINK3_MK:=	${LIBASSA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libassa
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibassa}
BUILDLINK_PACKAGES+=	libassa

.if !empty(LIBASSA_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libassa+=	libassa>=3.4.2
BUILDLINK_PKGSRCDIR.libassa?=	../../wip/libassa
.endif	# LIBASSA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
