# $NetBSD: buildlink3.mk,v 1.1 2004/05/10 22:04:38 blef Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MINGW_BINUTILS_BUILDLINK3_MK:=	${MINGW_BINUTILS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	mingw-binutils
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmingw-binutils}
BUILDLINK_PACKAGES+=	mingw-binutils

.if !empty(MINGW_BINUTILS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.mingw-binutils+=	mingw-binutils>=2.14.90
BUILDLINK_PKGSRCDIR.mingw-binutils?=	../../wip/mingw-binutils
.endif	# MINGW_BINUTILS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
