# $NetBSD$

DISTNAME=	safety-1.1.1
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_PYPI:=s/safety/}

MAINTAINER=	alberto.m@futurelinkcorporation.com
HOMEPAGE=	https://github.com/pyupio/safety
COMMENT=	Safety checks your installed dependencies
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
