# $NetBSD: buildlink3.mk,v 1.1 2004/11/24 16:06:01 imilh Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBPUSB_BUILDLINK3_MK:=	${LIBPUSB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libpusb
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpusb}
BUILDLINK_PACKAGES+=	libpusb

.if !empty(LIBPUSB_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libpusb+=	libpusb>=0.1
BUILDLINK_PKGSRCDIR.libpusb?=	../../wip/libpusb
.endif	# LIBPUSB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
