# $NetBSD: buildlink3.mk,v 1.3 2006/10/26 19:26:09 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBPUSB_BUILDLINK3_MK:=	${LIBPUSB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libpusb
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpusb}
BUILDLINK_PACKAGES+=	libpusb
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libpusb

.if !empty(LIBPUSB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libpusb+=	libpusb>=0.1
BUILDLINK_PKGSRCDIR.libpusb?=	../../wip/libpusb
.endif	# LIBPUSB_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
