# $NetBSD: Makefile,v 1.1 2015/08/05 20:46:14 jihbed Exp $

DISTNAME=	odeViz-0.2
CATEGORIES=	category
MASTER_SITES=	${MASTER_SITE_PYPI:=o/odeViz/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	https://files.pythonhosted.org/packages/source/o/odeViz/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
