# $NetBSD: Makefile,v 1.10 2010/06/13 22:47:21 thomasklausner Exp $

.include "../../meta-pkgs/xfce4/Makefile.common"

XFCE4_VERSION=	0.3.2

DISTNAME=	xfce4-taskmanager-${XFCE4_VERSION}
#PKGREVISION=	1
PKGREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	http://goodies.xfce.org/releases/xfce4-taskmanager/
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Xfce task manager

.include "../../x11/libxfce4gui/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
