# $NetBSD: Makefile,v 1.1 2015/09/06 18:54:21 jihbed Exp $

DISTNAME=	postmarkup-1.2.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_PYPI:=p/postmarkup/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://code.google.com/p/postmarkup/
COMMENT=	BBCode to (X)HTML rendering engine
LICENSE=	python-software-foundation

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
