# $NetBSD: buildlink3.mk,v 1.1 2008/06/05 23:33:07 schnoebe Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
UDNS_BUILDLINK3_MK:=	${UDNS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	udns
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nudns}
BUILDLINK_PACKAGES+=	udns
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}udns

.if !empty(UDNS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.udns+=	udns>=0.0.9
BUILDLINK_ABI_DEPENDS.udns+=	udns>=0.0.9
BUILDLINK_PKGSRCDIR.udns?=	../../wip/udns
.endif	# UDNS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
