# $NetBSD: buildlink3.mk,v 1.3 2012/05/12 02:04:12 outpaddling Exp $

BUILDLINK_TREE+=	py26-ffc

.if !defined(PY26_FFC_BUILDLINK3_MK)
PY26_FFC_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ffc+=	${PYPKGPREFIX}-ffc>=1.0.0
BUILDLINK_PKGSRCDIR.ffc?=	../../wip/py-ffc
.endif	# PY26_FFC_BUILDLINK3_MK

BUILDLINK_TREE+=	-ffc
