# $NetBSD: Makefile,v 1.3 2007/04/21 10:42:26 thomasklausner Exp $

DISTNAME=	rcsparse-0.0.0_20061004
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	http://distfiles.scode.org/pkgsrc/

MAINTAINER=	peter.schuller@infidyne.com
HOMEPAGE=	http://ww2.fs.ei.tum.de/~corecode/hg/rcsparse/
COMMENT=	RCS parsing library for Python

LICENSE=	corecode-license

PYTHON_VERSIONS_ACCEPTED=24
PYDISTUTILSPKG=	# yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
