# $NetBSD$

TERRAFORM014_VERSION=	0.14.11
#TERRAFORM013_VERSION=	TODO
#TERRAFORM012_VERSION=	TODO

.include "../../mk/bsd.prefs.mk"

TERRAFORM_VERSION_DEFAULT?=	014

.if !empty(TERRAFORM_VERSION_DEFAULT)
TERRAFORMVERSSUFFIX=		${TERRAFORM_VERSION_DEFAULT}
.endif

# Preferred version dependency for Terraform
TERRAFORM_PACKAGE_DEP=		terraform${TERRAFORMVERSSUFFIX}-${TERRAFORM${TERRAFORMVERSSUFFIX}_VERSION}*:../../wip/terraform${TERRAFORMVERSSUFFIX}

PLIST_SUBST+=	TERRAFORMVERSSUFFIX=${TERRAFORMVERSSUFFIX:Q}

PRINT_PLIST_AWK+=	{ sub("${TERRAFORMVERSSUFFIX}", "$${TERRAFORMVERSSUFFIX}") }
