# $NetBSD: Makefile,v 1.8 2014/05/17 21:00:06 szptvlfn Exp $
#

DISTNAME=	crypto-api-0.13
CATEGORIES=	security

MAINTAINER=	pho@cielonegro.org
COMMENT=	Generic interface for cryptographic operations
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-cereal/buildlink3.mk"
.include "../../security/hs-entropy/buildlink3.mk"
.include "../../devel/hs-tagged/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
