# $NetBSD$

DISTNAME=	qttools-everywhere-src-${QTVERSION}
PKGNAME=	qt6-qttools-${QTVERSION}
COMMENT=	Qt6 tools
CATEGORIES=	x11

.include "../../wip/qt6-qtbase/Makefile.common"

.include "../../lang/clang/buildlink3.mk"
.include "../../wip/qt6-qtbase/buildlink3.mk"
.include "../../wip/qt6-qtdeclarative/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
