# $NetBSD$

BSNES_PROFILE=	performance

.include "../../wip/libretro-bsnes-mercury/Makefile.common"

COMMENT=	Libretro core for performant SNES/Super Famicom emulation

.include "../../mk/bsd.pkg.mk"
