# $NetBSD$

BUILDLINK_TREE+=	s6

.if !defined(S6_BUILDLINK3_MK)
S6_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.s6+=	s6>=2.9.2.0
BUILDLINK_PKGSRCDIR.s6?=	../../wip/s6
BUILDLINK_DEPMETHOD.s6?=	build
.endif	# S6_BUILDLINK3_MK

BUILDLINK_TREE+=	-s6
