@comment $NetBSD: PLIST.cairo,v 1.2 2009/10/11 10:44:41 thomasklausner Exp $
lib/gtk2hs/HScairo.o
lib/gtk2hs/cairo.package.conf
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Drawing/Cairo.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Drawing/Paths.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Drawing/Patterns.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Drawing/Text.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Drawing/Transformations.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Fonts/FontOptions.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/Image.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/PDF.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/PNG.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/PS.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/SVG.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Surfaces/Surface.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Internal/Utilities.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Matrix.hi
lib/gtk2hs/imports/cairo/Graphics/Rendering/Cairo/Types.hi
lib/gtk2hs/libHScairo.a
