# $NetBSD: Makefile,v 1.4 2005/11/02 18:00:08 thomasklausner Exp $
#

DISTNAME=		cvsutils-0.2.3
CATEGORIES=		devel
MASTER_SITES=		http://www.red-bean.com/cvsutils/releases/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://www.red-bean.com/cvsutils/releases/
COMMENT=		CVS utilities to facilitate working

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
