# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/14 02:40:48 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_MIME_BUILDLINK3_MK:=	${HS_MIME_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-mime
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-mime}
BUILDLINK_PACKAGES+=	hs-mime
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-mime

.if ${HS_MIME_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-mime?=	build
BUILDLINK_API_DEPENDS.hs-mime+=	hs-mime>=0.3.0
BUILDLINK_PKGSRCDIR.hs-mime?=	../../wip/hs-mime
.endif	# HS_MIME_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
