# $NetBSD$

BUILDLINK_TREE+=	go-bpool

.if !defined(GO_BPOOL_BUILDLINK3_MK)
GO_BPOOL_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-bpool=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-bpool?=		build

BUILDLINK_API_DEPENDS.go-bpool+=	go-bpool>=20190530
BUILDLINK_PKGSRCDIR.go-bpool?=	../../wip/go-bpool
.endif	# GO_BPOOL_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-bpool
