$NetBSD$

Download using the pkgsrc way, see Makefile.

--- Cargo.toml.orig	2025-02-16 11:53:32.750178648 +0000
+++ Cargo.toml
@@ -259,7 +259,7 @@ windows = "0.33.0"
 winreg = "0.10"
 x11 = "2.21"
 xcb = "1.3"
-xcb-imdkit = { version="0.3", git="https://github.com/wez/xcb-imdkit-rs.git", rev="358e226573461fe540efb920e2aad740e3c6fab1"}
+xcb-imdkit = { path = "../xcb-imdkit-rs-358e226573461fe540efb920e2aad740e3c6fab1" }
 xkbcommon = "0.7.0"
 xml-rs = "0.8"
 zbus = "4.2"
