# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/03/28 23:10:54 jihbed Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XESAM_GLIB_BUILDLINK3_MK:=	${XESAM_GLIB_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xesam-glib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxesam-glib}
BUILDLINK_PACKAGES+=	xesam-glib
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xesam-glib

.if ${XESAM_GLIB_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xesam-glib+=	xesam-glib>=0.5.0
BUILDLINK_PKGSRCDIR.xesam-glib?=	../../wip/xesam-glib
.endif	# XESAM_GLIB_BUILDLINK3_MK

.include "../../devel/glib2/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
