# $NetBSD: Makefile,v 1.3 2014/07/19 14:01:16 thomasklausner Exp $

DISTNAME=	Text-EtText-2.3
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	textproc perl5
MASTER_SITES=	http://ettext.taint.org/devel/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ettext.taint.org/devel/
COMMENT=	Simple plain-text format which allows conversion to and from HTML

PERL5_PACKLIST=	auto/Text/EtText/.packlist

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
