# $NetBSD: Makefile,v 1.3 2012/10/03 09:10:41 asau Exp $
#

DISTNAME=	libunistring-0.9.3
CATEGORIES=	devel
MASTER_SITES=	http://ftp.gnu.org/gnu/libunistring/

MAINTAINER=	a@zta.lk
HOMEPAGE=	http://www.gnu.org/software/libunistring/
COMMENT=	Library that provides functions for manipulating Unicode strings
LICENSE=	gnu-lgpl-v3

GNU_CONFIGURE=	yes

.include "../../converters/libiconv/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
