

WITH AD7001C_PACKAGE; USE AD7001C_PACKAGE;
WITH REPORT;  USE REPORT;

PROCEDURE AD7001C0M IS

BEGIN
     TEST ("AD7001C", "CHECK THAT A DECLARATION IN PACKAGE SYSTEM " &
                      "IS ACCESSIBLE IN A LIBRARY PACKAGE BODY IF " &
                      "A WITH CLAUSE NAMING SYSTEM IS PROVIDED FOR " &
                      "THE PACKAGE SPECIFICATION, ALTHOUGH IN A " &
                      "SEPARATE FILE");
     RESULT;
END AD7001C0M;
