# $NetBSD$

DISTNAME=	Cache-1.5.6
CATEGORIES=	devel

MAINTAINER=	noud4@users.sourceforge.net
HOMEPAGE=	https://pear.php.net/package/Cache/
COMMENT=	Framework for caching of arbitrary data

.include "../../lang/php/pear.mk"
.include "../../mk/bsd.pkg.mk"
