# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/07/19 07:54:02 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FILEMANIP_BUILDLINK3_MK:=	${FILEMANIP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	FileManip
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NFileManip}
BUILDLINK_PACKAGES+=	FileManip
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}FileManip

.if ${FILEMANIP_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.FileManip?=	build
BUILDLINK_API_DEPENDS.FileManip+=	FileManip>=0.3.2
BUILDLINK_PKGSRCDIR.FileManip?=	../../wip/FileManip
.endif	# FILEMANIP_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
