# $NetBSD: buildlink3.mk,v 1.2 2009/01/18 03:29:35 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
FILEMANIP_BUILDLINK3_MK:=	${FILEMANIP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	FileManip
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NFileManip}
BUILDLINK_PACKAGES+=	FileManip
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}FileManip

.if ${FILEMANIP_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.FileManip?=	build
BUILDLINK_API_DEPENDS.FileManip+=	FileManip>=0.3.2nb1
BUILDLINK_PKGSRCDIR.FileManip?=	../../wip/FileManip
.endif	# FILEMANIP_BUILDLINK3_MK

.include "../../wip/hs-mtl/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
