# $NetBSD$

DISTNAME=	blad-3.10.4
CATEGORIES=	math
MASTER_SITES=	http://cristal.univ-lille.fr/~boulier/BLAD/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://cristal.univ-lille.fr/~boulier/BLAD/
COMMENT=	Bibliotheques Lilloises Algebre Differentielle
LICENSE=	gnu-lgpl-v3

GNU_CONFIGURE=	yes
USE_TOOLS+=	gmake:run
USE_LANGUAGES=	c c++

INFO_FILES=	yes

.include "options.mk"


.include "../../mk/bsd.pkg.mk"
