# $NetBSD: buildlink3.mk,v 1.2 2005/11/10 03:00:33 jeremy-c-reed Exp $

BUILDLINK_DEPMETHOD.resourceproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
RESOURCEPROTO_BUILDLINK3_MK:=	${RESOURCEPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	resourceproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nresourceproto}
BUILDLINK_PACKAGES+=	resourceproto

.if !empty(RESOURCEPROTO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.resourceproto+=	resourceproto>=1.0.1
BUILDLINK_PKGSRCDIR.resourceproto?=	../../wip/resourceproto
.endif	# RESOURCEPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
