-- B3A2010.A
--
--                             Grant of Unlimited Rights
--
--     Under contracts F33600-87-D-0337, F33600-84-D-0280, MDA903-79-C-0687,
--     F08630-91-C-0015, and DCA100-97-D-0025, the U.S. Government obtained 
--     unlimited rights in the software and documentation contained herein.
--     Unlimited rights are defined in DFAR 252.227-7013(a)(19).  By making 
--     this public release, the Government intends to confer upon all 
--     recipients unlimited rights  equal to those held by the Government.  
--     These rights include rights to use, duplicate, release or disclose the 
--     released technical data and computer software in whole or in part, in 
--     any manner and for any purpose whatsoever, and to have or permit others 
--     to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS.  THE GOVERNMENT MAKES NO EXPRESS OR IMPLIED 
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE 
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--*
--
-- OBJECTIVE:
--      Check that, for P'Access of an access-to-subprogram type S, the
--      accessibility level of the subprogram denoted by P must not be
--      statically deeper than that of S. Check for cases where P'Access
--      occurs in the visible and private part of an instance.
--
-- TEST DESCRIPTION:
--      In order to satisfy accessibility requirements, the designated
--      subprogram P must be at the same or a less deep nesting level than the
--      access-to-subprogram type S -- P must "live" as long as S. Nesting
--      levels are the run-time nestings of masters: block statements;
--      subprogram, task, and entry bodies; and accept statements. Packages
--      are invisible to accessibility rules.
--
--      This test declares two generic packages in which P is declared in
--      the instance itself: one in which P'Access occurs in the visible
--      part, and one in which P'Access occurs in the private part.  In both 
--      cases the type S of P'Access is also passed as an actual parameter,
--      and the accessibility level of P is that of the instance.
--
--      The test declares access-to-subprogram types in various packages and 
--      subprogram bodies. These types are passed as actuals to instantiations, 
--      which are attempted at various nesting levels. The test verifies that 
--      P'Access is illegal when P is declared at a nesting level deeper than 
--      that of the type of P'Access, and legal otherwise.
--
--      The nesting structure is as follows:
--
--          - Library-level package         (Level = 0)
--         |
--          - end package
--
--          - Main subprogram               (Level = 1)
--         |
--         |     *** testing here
--         |
--         |    - Nested procedure          (Level = 2)
--         |   |     *** testing here
--         |   |  begin
--         |    - end procedure
--         |
--         |  begin
--          - end main subprogram
--
--
-- CHANGE HISTORY:
--      06 Dec 94   SAIC    ACVC 2.0
--
--!

package B3A2010_0 is

   type Acc_L0 is access procedure (I : Integer);               -- Level = 0.

end B3A2010_0;
