# $NetBSD: buildlink3.mk,v 1.6 2008/01/28 21:30:19 bsadewitz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JACK_BUILDLINK3_MK:=	${JACK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	jack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njack}
BUILDLINK_PACKAGES+=	jack
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}jack

.if ${JACK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.jack+=	jack>=0.109.0
BUILDLINK_PKGSRCDIR.jack?=	../../local/jack
.endif	# JACK_BUILDLINK3_MK

.include "../../mk/dlopen.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
