# $NetBSD: buildlink3.mk,v 1.5 2007/12/13 22:21:48 rillig Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JACK_BUILDLINK3_MK:=	${JACK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	jack
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njack}
BUILDLINK_PACKAGES+=	jack
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}jack

.if ${JACK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.jack+=	jack>=0.103.0
BUILDLINK_PKGSRCDIR.jack?=	../../wip/jack
.endif	# JACK_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
