# $NetBSD$
    -- posi	2019-09-16 23:08:54.343557721 +0900  \
    build/python_compile_helper.py  \
    docs/doxygen/doxyxml/generated/compound.py  \
    docs/doxygen/doxyxml/generated/compoundsuper.py  \
    docs/doxygen/doxyxml/generated/index.py  \
    docs/doxygen/doxyxml/generated/indexsuper.py  \
    docs/doxygen/other/doxypy.py  \
    docs/exploring-gnuradio/dial_tone.py  \
    docs/exploring-gnuradio/fm_demod.py  \
    gnuradio-runtime/apps/evaluation_random_numbers.py  \
    gnuradio-runtime/examples/mp-sched/affinity_set.py  \
    gnuradio-runtime/examples/mp-sched/plot_flops.py  \
    gnuradio-runtime/examples/mp-sched/run_synthetic.py  \
    gnuradio-runtime/examples/mp-sched/synthetic.py  \
    gnuradio-runtime/examples/mp-sched/wfm_rcv_pll_to_wav.py  \
    gnuradio-runtime/examples/network/audio_sink.py  \
    gnuradio-runtime/examples/network/audio_source.py  \
    gnuradio-runtime/examples/network/dial_tone_sink.py  \
    gnuradio-runtime/examples/network/dial_tone_source.py  \
    gnuradio-runtime/examples/network/vector_sink.py  \
    gnuradio-runtime/examples/network/vector_source.py  \
    gnuradio-runtime/examples/volk_benchmark/volk_math.py  \
    gnuradio-runtime/examples/volk_benchmark/volk_plot.py  \
    gnuradio-runtime/examples/volk_benchmark/volk_test_funcs.py  \
    gnuradio-runtime/examples/volk_benchmark/volk_types.py  \
    gnuradio-runtime/lib/math/gen_sine_table.py  \
    gnuradio-runtime/python/gnuradio/ctrlport/GrDataPlotter.py  \
    gnuradio-runtime/python/gnuradio/ctrlport/RPCConnectionThrift.py  \
    gnuradio-runtime/python/gnuradio/ctrlport/monitor.py  \
    gnuradio-runtime/python/gnuradio/gr/packet_utils.py  \
    gnuradio-runtime/python/gnuradio/gr/pubsub.py  \
    gnuradio-runtime/python/gnuradio/gr/qa_feval.py  \
    gnuradio-runtime/python/gnuradio/gr/qa_flowgraph.py  \
    gnuradio-runtime/python/gnuradio/gr/qa_kludged_imports.py  \
    gnuradio-runtime/python/gnuradio/gr/qa_random.py  \
    gnuradio-runtime/python/gnuradio/gr/qa_tag_utils.py  \
    gnuradio-runtime/python/gnuradio/gr_unittest.py  \
    gnuradio-runtime/python/gnuradio/gru/freqz.py  \
    gnuradio-runtime/python/gnuradio/gru/gnuplot_freqz.py  \
    gnuradio-runtime/python/pmt/qa_pmt.py  \
    gnuradio-runtime/python/pmt/qa_pmt_to_python.py  \
    gr-analog/examples/fmtest.py  \
    gr-analog/examples/tags/uhd_burst_detector.py  \
    gr-analog/python/analog/qa_agc.py  \
    gr-analog/python/analog/qa_cpfsk.py  \
    gr-analog/python/analog/qa_ctcss_squelch.py  \
    gr-analog/python/analog/qa_dpll.py  \
    gr-analog/python/analog/qa_fastnoise.py  \
    gr-analog/python/analog/qa_fm_emph.py  \
    gr-analog/python/analog/qa_fmdet.py  \
    gr-analog/python/analog/qa_frequency_modulator.py  \
    gr-analog/python/analog/qa_noise.py  \
    gr-analog/python/analog/qa_phase_modulator.py  \
    gr-analog/python/analog/qa_pll_carriertracking.py  \
    gr-analog/python/analog/qa_pll_freqdet.py  \
    gr-analog/python/analog/qa_pll_refout.py  \
    gr-analog/python/analog/qa_probe_avg_mag_sqrd.py  \
    gr-analog/python/analog/qa_pwr_squelch.py  \
    gr-analog/python/analog/qa_quadrature_demod.py  \
    gr-analog/python/analog/qa_rail_ff.py  \
    gr-analog/python/analog/qa_random_uniform_source.py  \
    gr-analog/python/analog/qa_sig_source.py  \
    gr-analog/python/analog/qa_simple_squelch.py  \
    gr-audio/examples/python/audio_copy.py  \
    gr-audio/examples/python/audio_play.py  \
    gr-audio/examples/python/audio_to_file.py  \
    gr-audio/examples/python/dial_tone.py  \
    gr-audio/examples/python/dial_tone_daemon.py  \
    gr-audio/examples/python/dial_tone_wav.py  \
    gr-audio/examples/python/mono_tone.py  \
    gr-audio/examples/python/multi_tone.py  \
    gr-audio/examples/python/noise.py  \
    gr-audio/examples/python/spectrum_inversion.py  \
    gr-audio/examples/python/test_resampler.py  \
    gr-blocks/examples/ctrlport/simple_copy_controller.py  \
    gr-blocks/examples/ctrlport/usrp_sink_controller.py  \
    gr-blocks/examples/ctrlport/usrp_source_controller.py  \
    gr-blocks/examples/tags/test_file_tags.py  \
    gr-blocks/python/blocks/parse_file_metadata.py  \
    gr-blocks/python/blocks/qa_add_mult_div_sub.py  \
    gr-blocks/python/blocks/qa_add_mult_v.py  \
    gr-blocks/python/blocks/qa_affinity.py  \
    gr-blocks/python/blocks/qa_argmax.py  \
    gr-blocks/python/blocks/qa_bin_statistics.py  \
    gr-blocks/python/blocks/qa_block_behavior.py  \
    gr-blocks/python/blocks/qa_boolean_operators.py  \
    gr-blocks/python/blocks/qa_burst_tagger.py  \
    gr-blocks/python/blocks/qa_conjugate.py  \
    gr-blocks/python/blocks/qa_copy.py  \
    gr-blocks/python/blocks/qa_cpp_py_binding.py  \
    gr-blocks/python/blocks/qa_cpp_py_binding_set.py  \
    gr-blocks/python/blocks/qa_ctrlport_probes.py  \
    gr-blocks/python/blocks/qa_delay.py  \
    gr-blocks/python/blocks/qa_endian_swap.py  \
    gr-blocks/python/blocks/qa_exponentiate_const_cci.py  \
    gr-blocks/python/blocks/qa_file_descriptor_source_sink.py  \
    gr-blocks/python/blocks/qa_file_metadata.py  \
    gr-blocks/python/blocks/qa_file_sink.py  \
    gr-blocks/python/blocks/qa_file_source.py  \
    gr-blocks/python/blocks/qa_head.py  \
    gr-blocks/python/blocks/qa_hier_block2.py  \
    gr-blocks/python/blocks/qa_hier_block2_message_connections.py  \
    gr-blocks/python/blocks/qa_integrate.py  \
    gr-blocks/python/blocks/qa_interleave.py  \
    gr-blocks/python/blocks/qa_keep_m_in_n.py  \
    gr-blocks/python/blocks/qa_keep_one_in_n.py  \
    gr-blocks/python/blocks/qa_logger.py  \
    gr-blocks/python/blocks/qa_max.py  \
    gr-blocks/python/blocks/qa_message.py  \
    gr-blocks/python/blocks/qa_min.py  \
    gr-blocks/python/blocks/qa_moving_average.py  \
    gr-blocks/python/blocks/qa_multiply_conjugate.py  \
    gr-blocks/python/blocks/qa_multiply_matrix_xx.py  \
    gr-blocks/python/blocks/qa_mute.py  \
    gr-blocks/python/blocks/qa_nlog10.py  \
    gr-blocks/python/blocks/qa_null_sink_source.py  \
    gr-blocks/python/blocks/qa_pack_k_bits.py  \
    gr-blocks/python/blocks/qa_packed_to_unpacked.py  \
    gr-blocks/python/blocks/qa_patterned_interleaver.py  \
    gr-blocks/python/blocks/qa_pdu.py  \
    gr-blocks/python/blocks/qa_peak_detector.py  \
    gr-blocks/python/blocks/qa_peak_detector2.py  \
    gr-blocks/python/blocks/qa_pipe_fittings.py  \
    gr-blocks/python/blocks/qa_plateau_detector_fb.py  \
    gr-blocks/python/blocks/qa_probe_signal.py  \
    gr-blocks/python/blocks/qa_python_message_passing.py  \
    gr-blocks/python/blocks/qa_regenerate.py  \
    gr-blocks/python/blocks/qa_repack_bits_bb.py  \
    gr-blocks/python/blocks/qa_repeat.py  \
    gr-blocks/python/blocks/qa_rms.py  \
    gr-blocks/python/blocks/qa_sample_and_hold.py  \
    gr-blocks/python/blocks/qa_selector.py  \
    gr-blocks/python/blocks/qa_skiphead.py  \
    gr-blocks/python/blocks/qa_socket_pdu.py  \
    gr-blocks/python/blocks/qa_stream_mux.py  \
    gr-blocks/python/blocks/qa_stream_to_tagged_stream.py  \
    gr-blocks/python/blocks/qa_stretch.py  \
    gr-blocks/python/blocks/qa_tag_debug.py  \
    gr-blocks/python/blocks/qa_tag_file_sink.py  \
    gr-blocks/python/blocks/qa_tag_gate.py  \
    gr-blocks/python/blocks/qa_tag_share.py  \
    gr-blocks/python/blocks/qa_tagged_stream_mux.py  \
    gr-blocks/python/blocks/qa_tags_strobe.py  \
    gr-blocks/python/blocks/qa_tcp_server_sink.py  \
    gr-blocks/python/blocks/qa_threshold.py  \
    gr-blocks/python/blocks/qa_throttle.py  \
    gr-blocks/python/blocks/qa_transcendental.py  \
    gr-blocks/python/blocks/qa_tsb_vector_sink_X.py  \
    gr-blocks/python/blocks/qa_type_conversions.py  \
    gr-blocks/python/blocks/qa_udp_source_sink.py  \
    gr-blocks/python/blocks/qa_unpack_k_bits.py  \
    gr-blocks/python/blocks/qa_vco.py  \
    gr-blocks/python/blocks/qa_vector_insert.py  \
    gr-blocks/python/blocks/qa_vector_map.py  \
    gr-blocks/python/blocks/qa_vector_sink_source.py  \
    gr-blocks/python/blocks/qa_wavfile.py  \
    gr-channels/python/channels/amp_bal.py  \
    gr-channels/python/channels/conj_fs_iqcorr.py  \
    gr-channels/python/channels/distortion_2_gen.py  \
    gr-channels/python/channels/distortion_3_gen.py  \
    gr-channels/python/channels/impairments.py  \
    gr-channels/python/channels/iqbal_gen.py  \
    gr-channels/python/channels/phase_bal.py  \
    gr-channels/python/channels/phase_noise_gen.py  \
    gr-channels/python/channels/qa_channel_model.py  \
    gr-channels/python/channels/qa_fading_model.py  \
    gr-channels/python/channels/quantizer.py  \
    gr-digital/examples/berawgn.py  \
    gr-digital/examples/example_costas.py  \
    gr-digital/examples/example_fll.py  \
    gr-digital/examples/example_timing.py  \
    gr-digital/examples/gen_whitener.py  \
    gr-digital/examples/narrowband/benchmark_add_channel.py  \
    gr-digital/examples/narrowband/digital_bert_rx.py  \
    gr-digital/examples/narrowband/digital_bert_tx.py  \
    gr-digital/examples/narrowband/uhd_interface.py  \
    gr-digital/examples/ofdm/benchmark_add_channel.py  \
    gr-digital/examples/ofdm/uhd_interface.py  \
    gr-digital/examples/run_length.py  \
    gr-digital/examples/snr_estimators.py  \
    gr-digital/python/digital/constellation_map_generator.py  \
    gr-digital/python/digital/ofdm.py  \
    gr-digital/python/digital/ofdm_receiver.py  \
    gr-digital/python/digital/ofdm_sync_fixed.py  \
    gr-digital/python/digital/ofdm_sync_ml.py  \
    gr-digital/python/digital/ofdm_sync_pn.py  \
    gr-digital/python/digital/ofdm_sync_pnac.py  \
    gr-digital/python/digital/psk_constellations.py  \
    gr-digital/python/digital/qa_binary_slicer_fb.py  \
    gr-digital/python/digital/qa_burst_shaper.py  \
    gr-digital/python/digital/qa_chunks_to_symbols.py  \
    gr-digital/python/digital/qa_clock_recovery_mm.py  \
    gr-digital/python/digital/qa_cma_equalizer.py  \
    gr-digital/python/digital/qa_constellation.py  \
    gr-digital/python/digital/qa_constellation_decoder_cb.py  \
    gr-digital/python/digital/qa_constellation_receiver.py  \
    gr-digital/python/digital/qa_constellation_soft_decoder_cf.py  \
    gr-digital/python/digital/qa_correlate_access_code.py  \
    gr-digital/python/digital/qa_correlate_access_code_XX_ts.py  \
    gr-digital/python/digital/qa_correlate_access_code_tag.py  \
    gr-digital/python/digital/qa_costas_loop_cc.py  \
    gr-digital/python/digital/qa_cpm.py  \
    gr-digital/python/digital/qa_crc32.py  \
    gr-digital/python/digital/qa_crc32_bb.py  \
    gr-digital/python/digital/qa_diff_encoder.py  \
    gr-digital/python/digital/qa_diff_phasor_cc.py  \
    gr-digital/python/digital/qa_digital.py  \
    gr-digital/python/digital/qa_fll_band_edge.py  \
    gr-digital/python/digital/qa_framer_sink.py  \
    gr-digital/python/digital/qa_glfsr_source.py  \
    gr-digital/python/digital/qa_hdlc_framer.py  \
    gr-digital/python/digital/qa_header_payload_demux.py  \
    gr-digital/python/digital/qa_lfsr.py  \
    gr-digital/python/digital/qa_lms_equalizer.py  \
    gr-digital/python/digital/qa_map.py  \
    gr-digital/python/digital/qa_mpsk_snr_est.py  \
    gr-digital/python/digital/qa_ofdm_carrier_allocator_cvc.py  \
    gr-digital/python/digital/qa_ofdm_chanest_vcvc.py  \
    gr-digital/python/digital/qa_ofdm_cyclic_prefixer.py  \
    gr-digital/python/digital/qa_ofdm_frame_equalizer_vcvc.py  \
    gr-digital/python/digital/qa_ofdm_serializer_vcc.py  \
    gr-digital/python/digital/qa_ofdm_sync_sc_cfb.py  \
    gr-digital/python/digital/qa_ofdm_txrx.py  \
    gr-digital/python/digital/qa_packet_format.py  \
    gr-digital/python/digital/qa_packet_headergenerator_bb.py  \
    gr-digital/python/digital/qa_packet_headerparser_b.py  \
    gr-digital/python/digital/qa_pfb_clock_sync.py  \
    gr-digital/python/digital/qa_pn_correlator_cc.py  \
    gr-digital/python/digital/qa_probe_density.py  \
    gr-digital/python/digital/qa_scrambler.py  \
    gr-digital/python/digital/qa_simple_correlator.py  \
    gr-digital/python/digital/qa_simple_framer.py  \
    gr-digital/python/digital/qam_constellations.py  \
    gr-digital/python/digital/soft_dec_lut_gen.py  \
    gr-digital/python/digital/test_soft_decisions.py  \
    gr-digital/python/digital/utils/__init__.py  \
    gr-digital/python/digital/utils/alignment.py  \
    gr-digital/python/digital/utils/gray_code.py  \
    gr-digital/python/digital/utils/mod_codes.py  \
    gr-digital/python/digital/utils/tagged_streams.py  \
    gr-dtv/examples/atsc_ctrlport_monitor.py  \
    gr-dtv/python/dtv/atsc_rx.py  \
    gr-dtv/python/dtv/atsc_rx_filter.py  \
    gr-dtv/python/dtv/qa_dtv.py  \
    gr-fec/python/fec/LDPC/Generate_LDPC_matrix.py  \
    gr-fec/python/fec/LDPC/Generate_LDPC_matrix_functions.py  \
    gr-fec/python/fec/_qa_helper.py  \
    gr-fec/python/fec/bercurve_generator.py  \
    gr-fec/python/fec/bitflip.py  \
    gr-fec/python/fec/capillary_threaded_decoder.py  \
    gr-fec/python/fec/capillary_threaded_encoder.py  \
    gr-fec/python/fec/extended_async_encoder.py  \
    gr-fec/python/fec/extended_decoder.py  \
    gr-fec/python/fec/extended_encoder.py  \
    gr-fec/python/fec/extended_tagged_decoder.py  \
    gr-fec/python/fec/extended_tagged_encoder.py  \
    gr-fec/python/fec/fec_test.py  \
    gr-fec/python/fec/polar/__init__.py  \
    gr-fec/python/fec/polar/channel_construction.py  \
    gr-fec/python/fec/polar/channel_construction_awgn.py  \
    gr-fec/python/fec/polar/channel_construction_bec.py  \
    gr-fec/python/fec/polar/common.py  \
    gr-fec/python/fec/polar/decoder.py  \
    gr-fec/python/fec/polar/encoder.py  \
    gr-fec/python/fec/polar/helper_functions.py  \
    gr-fec/python/fec/polar/testbed.py  \
    gr-fec/python/fec/qa_ber_bf.py  \
    gr-fec/python/fec/qa_depuncture.py  \
    gr-fec/python/fec/qa_ecc_ccsds_27.py  \
    gr-fec/python/fec/qa_fecapi_cc.py  \
    gr-fec/python/fec/qa_fecapi_dummy.py  \
    gr-fec/python/fec/qa_fecapi_ldpc.py  \
    gr-fec/python/fec/qa_fecapi_repetition.py  \
    gr-fec/python/fec/qa_polar_decoder_sc.py  \
    gr-fec/python/fec/qa_polar_decoder_sc_list.py  \
    gr-fec/python/fec/qa_polar_decoder_sc_systematic.py  \
    gr-fec/python/fec/qa_polar_encoder.py  \
    gr-fec/python/fec/qa_polar_encoder_systematic.py  \
    gr-fec/python/fec/qa_puncture.py  \
    gr-fec/python/fec/threaded_decoder.py  \
    gr-fec/python/fec/threaded_encoder.py  \
    gr-fft/python/fft/qa_fft.py  \
    gr-fft/python/fft/qa_goertzel.py  \
    gr-filter/examples/benchmark_filters.py  \
    gr-filter/examples/channelize.py  \
    gr-filter/examples/chirp_channelize.py  \
    gr-filter/examples/decimate.py  \
    gr-filter/examples/fft_filter_ccc.py  \
    gr-filter/examples/fir_filter_ccc.py  \
    gr-filter/examples/fir_filter_fff.py  \
    gr-filter/examples/gr_filtdes_api.py  \
    gr-filter/examples/gr_filtdes_callback.py  \
    gr-filter/examples/gr_filtdes_live_upd.py  \
    gr-filter/examples/gr_filtdes_restrict.py  \
    gr-filter/examples/interpolate.py  \
    gr-filter/examples/reconstruction.py  \
    gr-filter/examples/resampler.py  \
    gr-filter/examples/synth_filter.py  \
    gr-filter/examples/synth_to_chan.py  \
    gr-filter/python/filter/freq_xlating_fft_filter.py  \
    gr-filter/python/filter/pfb.py  \
    gr-filter/python/filter/qa_dc_blocker.py  \
    gr-filter/python/filter/qa_fft_filter.py  \
    gr-filter/python/filter/qa_filter_delay_fc.py  \
    gr-filter/python/filter/qa_filterbank.py  \
    gr-filter/python/filter/qa_fir_filter.py  \
    gr-filter/python/filter/qa_firdes.py  \
    gr-filter/python/filter/qa_fractional_interpolator.py  \
    gr-filter/python/filter/qa_fractional_resampler.py  \
    gr-filter/python/filter/qa_freq_xlating_fft_filter.py  \
    gr-filter/python/filter/qa_freq_xlating_fir_filter.py  \
    gr-filter/python/filter/qa_hilbert.py  \
    gr-filter/python/filter/qa_iir_filter.py  \
    gr-filter/python/filter/qa_interp_fir_filter.py  \
    gr-filter/python/filter/qa_pfb_arb_resampler.py  \
    gr-filter/python/filter/qa_pfb_channelizer.py  \
    gr-filter/python/filter/qa_pfb_decimator.py  \
    gr-filter/python/filter/qa_pfb_interpolator.py  \
    gr-filter/python/filter/qa_pfb_synthesizer.py  \
    gr-filter/python/filter/qa_pm_remez.py  \
    gr-filter/python/filter/qa_rational_resampler.py  \
    gr-filter/python/filter/qa_single_pole_iir.py  \
    gr-qtgui/apps/uhd_display.py  \
    gr-qtgui/examples/pyqt_const_c.py  \
    gr-qtgui/examples/pyqt_example_c.py  \
    gr-qtgui/examples/pyqt_example_f.py  \
    gr-qtgui/examples/pyqt_freq_c.py  \
    gr-qtgui/examples/pyqt_freq_f.py  \
    gr-qtgui/examples/pyqt_histogram_f.py  \
    gr-qtgui/examples/pyqt_time_c.py  \
    gr-qtgui/examples/pyqt_time_f.py  \
    gr-qtgui/examples/pyqt_time_raster_b.py  \
    gr-qtgui/examples/pyqt_time_raster_f.py  \
    gr-qtgui/examples/pyqt_waterfall_c.py  \
    gr-qtgui/examples/pyqt_waterfall_f.py  \
    gr-qtgui/grc/qtgui_time_sink_x.block.yml.py  \
    gr-qtgui/python/qtgui/qa_qtgui.py  \
    gr-trellis/docs/make_numbered_listing.py  \
    gr-trellis/docs/test_tcm.py  \
    gr-trellis/docs/test_viterbi_equalization1.py  \
    gr-trellis/examples/python/test_tcm.py  \
    gr-trellis/python/trellis/fsm_utils.py  \
    gr-trellis/python/trellis/qa_trellis.py  \
    gr-uhd/apps/uhd_app.py  \
    gr-uhd/apps/uhd_siggen_base.py  \
    gr-uhd/examples/python/freq_hopping.py  \
    gr-uhd/python/uhd/qa_uhd.py  \
    gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/compound.py  \
    gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/compoundsuper.py  \
    gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/index.py  \
    gr-utils/python/modtool/templates/gr-newmod/docs/doxygen/doxyxml/generated/indexsuper.py  \
    gr-utils/python/modtool/tools/__init__.py  \
    gr-utils/python/utils/plot_fft_base.py  \
    gr-utils/python/utils/plot_psd_base.py  \
    gr-video-sdl/python/video_sdl/qa_video_sdl.py  \
    gr-vocoder/examples/alaw_audio_loopback.py  \
    gr-vocoder/examples/codec2_audio_loopback.py  \
    gr-vocoder/examples/cvsd_audio_loopback.py  \
    gr-vocoder/examples/g721_audio_loopback.py  \
    gr-vocoder/examples/g723_24_audio_loopback.py  \
    gr-vocoder/examples/g723_40_audio_loopback.py  \
    gr-vocoder/examples/gsm_audio_loopback.py  \
    gr-vocoder/examples/ulaw_audio_loopback.py  \
    gr-vocoder/python/vocoder/cvsd.py  \
    gr-vocoder/python/vocoder/qa_alaw_vocoder.py  \
    gr-vocoder/python/vocoder/qa_codec2_vocoder.py  \
    gr-vocoder/python/vocoder/qa_cvsd_vocoder.py  \
    gr-vocoder/python/vocoder/qa_g721_vocoder.py  \
    gr-vocoder/python/vocoder/qa_g723_24_vocoder.py  \
    gr-vocoder/python/vocoder/qa_g723_40_vocoder.py  \
    gr-vocoder/python/vocoder/qa_gsm_full_rate.py  \
    gr-vocoder/python/vocoder/qa_ulaw_vocoder.py  \
    gr-wavelet/python/wavelet/qa_classify.py  \
    gr-zeromq/python/zeromq/qa_zeromq_pub.py  \
    gr-zeromq/python/zeromq/qa_zeromq_pubsub.py  \
    gr-zeromq/python/zeromq/qa_zeromq_pushpull.py  \
    gr-zeromq/python/zeromq/qa_zeromq_reqrep.py  \
    gr-zeromq/python/zeromq/qa_zeromq_sub.py  \
    grc/blocks/variable_struct.block.yml.py  \
    grc/core/schema_checker/domain.py  \
    tools/clang_format.py  \
    tools/template_convert.py
