
-----------------------------------------------------------------------

WITH REPORT; USE REPORT;
WITH CA5006A0; USE CA5006A0;
WITH CA5006A2; USE CA5006A2;
PRAGMA ELABORATE(CA5006A0);

PACKAGE BODY CA5006A1 IS
   X : INTEGER;

   FUNCTION F RETURN INTEGER IS
   BEGIN
      RETURN IDENT_INT(0);
   END F;

BEGIN
   X := G;
   IF NOT P_E_RAISED THEN
      FAILED ( "G CALLED" );
   END IF;
EXCEPTION
   WHEN PROGRAM_ERROR =>
      COMMENT ( "PROGRAM_ERROR RAISED IN CA5006A1" );
      SHOW_PE_RAISED;
   WHEN OTHERS =>
      FAILED ( "OTHER ERROR RAISED IN CA5006A1" );
END CA5006A1;
