# $NetBSD: buildlink3.mk,v 1.3 2006/08/25 14:52:07 emil_s Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GIVARO_BUILDLINK3_MK:=	${GIVARO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	givaro
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngivaro}
BUILDLINK_PACKAGES+=	givaro
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}givaro

.if ${GIVARO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.givaro+=	givaro>=3.2.1
BUILDLINK_PKGSRCDIR.givaro?=	../../wip/givaro
.endif	# GIVARO_BUILDLINK3_MK

.include "../../devel/gmp/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
