-- BA11009.A
--
--                             Grant of Unlimited Rights
--
--     Under contracts F33600-87-D-0337, F33600-84-D-0280, MDA903-79-C-0687,
--     F08630-91-C-0015, and DCA100-97-D-0025, the U.S. Government obtained 
--     unlimited rights in the software and documentation contained herein.
--     Unlimited rights are defined in DFAR 252.227-7013(a)(19).  By making 
--     this public release, the Government intends to confer upon all 
--     recipients unlimited rights  equal to those held by the Government.  
--     These rights include rights to use, duplicate, release or disclose the 
--     released technical data and computer software in whole or in part, in 
--     any manner and for any purpose whatsoever, and to have or permit others 
--     to do so.
--
--                                    DISCLAIMER
--
--     ALL MATERIALS OR INFORMATION HEREIN RELEASED, MADE AVAILABLE OR
--     DISCLOSED ARE AS IS.  THE GOVERNMENT MAKES NO EXPRESS OR IMPLIED 
--     WARRANTY AS TO ANY MATTER WHATSOEVER, INCLUDING THE CONDITIONS OF THE
--     SOFTWARE, DOCUMENTATION OR OTHER INFORMATION RELEASED, MADE AVAILABLE 
--     OR DISCLOSED, OR THE OWNERSHIP, MERCHANTABILITY, OR FITNESS FOR A
--     PARTICULAR PURPOSE OF SAID MATERIAL.
--*
--
-- OBJECTIVE:
--      Check that if the generic being renamed is itself a child of a 
--      generic package P, the renaming must occur in a place that is within 
--      the declarative region of P, which includes the body, the children 
--      (and descendant ...), and the subunits of P.
--
-- TEST DESCRIPTION:
--      Declare the first generic grandparent package.  Declare a generic 
--      parent package.  Declare a generic grandchild procedure.  Declare a
--      generic grandchild function.  Declare the second generic grandparent 
--      package.  Declare a subunit in the grandparent package body.  Declare
--      a generic parent package.  Declare a generic grandchild procedure.  
--      Declare a generic grandchild function. 
--
--                           BA11009_0                BA11009_4
--                             /   \                 (BA11009_5)
--                            /     \                  /    \
--                           /       \                /      \
--                      BA11009_1  BA11009_3      BA11009_6  BA11009_8
--                        /                          /
--                       /                          /
--                   BA11009_2                  BA11009_7
--      
--      The following cases should cause compile-time errors:
--         (a) rename generic package BA11009_1 in the subunit, BA11009_5.
--         (b) rename generic procedure BA11009_7 in the subunit, BA11009_5.
--         (c) rename generic procedure BA11009_2 in the subunit, BA11009_5.
--         (d) rename generic function BA11009_3 in the subunit, BA11009_5.
--         (e) rename generic package BA11009_1 in the body of BA11009_6.
--         (f) rename generic procedure BA11009_2 in the body of BA11009_6.
--         (g) rename generic function BA11009_3 in the body of BA11009_6.
--         (h) rename generic package BA11009_1 in the body of BA11009_8.
--         (i) rename generic procedure BA11009_7 in the body of BA11009_8.
--         (j) rename generic procedure BA11009_2 in the body of BA11009_8.
--         (k) rename generic function BA11009_3 in the body of BA11009_8.
--         (l) rename generic package BA11009_1 in BA11009.
--         (m) rename generic procedure BA11009_2 in BA11009.
--         (n) rename generic function BA11009_3 in BA11009.
--
--
-- CHANGE HISTORY:
--      06 Dec 94   SAIC    ACVC 2.0
--      15 Nov 95   SAIC    Update and repair for ACVC 2.0.1
--
--!

-- Generic grandparent package
generic
package BA11009_0 is

   type Grand_Parent_Type is range 1..100;

end BA11009_0;
