# $NetBSD: buildlink3.mk,v 1.1 2007/01/23 17:39:13 bsadewitz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XF86RUSHPROTO_BUILDLINK3_MK:=	${XF86RUSHPROTO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xf86rushproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxf86rushproto}
BUILDLINK_PACKAGES+=	xf86rushproto
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xf86rushproto

.if ${XF86RUSHPROTO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xf86rushproto+=	xf86rushproto>=1.1.2
BUILDLINK_PKGSRCDIR.xf86rushproto?=	../../wip/xf86rushproto
.endif	# XF86RUSHPROTO_BUILDLINK3_MK

.include "../../x11/xproto/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
