# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/12/16 23:03:38 zul_ Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ORTP_BUILDLINK3_MK:=	${ORTP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ortp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nortp}
BUILDLINK_PACKAGES+=	ortp

.if !empty(ORTP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ortp+=	ortp>=0.7.1
BUILDLINK_PKGSRCDIR.ortp?=	../../wip/ortp
.endif	# ORTP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
