# $NetBSD: buildlink3.mk,v 1.1 2007/01/23 17:51:59 bsadewitz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLU_BUILDLINK3_MK:=	${GLU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglu}
BUILDLINK_PACKAGES+=	glu
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}glu

.if !empty(GLU_BUILDLINK3_MK:M+)
BUILDLINK_ABI_DEPENDS.glu+=	glu>=6.5.2
BUILDLINK_PKGSRCDIR.glu?=	../../wip/glu
.endif	# GLU_BUILDLINK3_MK

.include "../../wip/MesaLib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
