# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:18:13 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENSC_BUILDLINK3_MK:=	${OPENSC_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	opensc
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopensc}
BUILDLINK_PACKAGES+=	opensc

.if !empty(OPENSC_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.opensc+=	opensc>=0.9.6
BUILDLINK_PKGSRCDIR.opensc?=	../../wip/opensc
.endif	# OPENSC_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
