# $NetBSD: Makefile,v 1.3 2003/07/04 11:13:53 marttikuparinen Exp $

.include "../xfce4/Makefile.common"

PKGNAME=	xfce4-utils-${XFCE4_VERSION}
DISTNAME=	xfce-utils-${XFCE4_VERSION}
CATEGORIES=	x11
COMMENT=	XFce4 utilities

.include "../../devel/pkgconfig/buildlink2.mk"
.include "../../wip/xfce4-mcs-plugins/buildlink2.mk"
.include "../../mk/bsd.pkg.mk"
