# $NetBSD$

PKGNAME=	suse_fpc-${SUSE_VERSION}
CATEGORIES=	emulators
RPMEDUPKGS+=	fpc-2.6.4-2.1.${SUSE_ARCH}

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Linux compatibility package for Free Pascal Compiler

EMUL_MODULES.linux=	base

.include "../../emulators/suse131_linux/Makefile.common"
.include "../../mk/bsd.pkg.mk"
