
WITH REPORT; USE REPORT;
WITH AA2010A_TYPEDEF; USE AA2010A_TYPEDEF;
WITH AA2010A_PARENT; USE AA2010A_PARENT; 
PROCEDURE AA2010A IS
     E : ENUM;
BEGIN
     TEST ( "AA2010A", "CHECK THAT SUBUNIT NAMES CAN BE IDENTICAL " &
                       "TO IDENTIFIERS DECLARED IN STANDARD, " &
                       "NAMELY, BOOLEAN, INTEGER, FLOAT, " &
                       "CHARACTER, ASCII, NATURAL, POSITIVE, " &
                       "STRING, DURATION, CONSTRAINT_ERROR, " &
                       "NUMERIC_ERROR, PROGRAM_ERROR, " &
                       "STORAGE_ERROR, AND TASKING_ERROR" );
     
     AA2010A_PARENT.BOOLEAN;
     E := AA2010A_PARENT.INTEGER;

     AA2010A_PARENT.CHARACTER;
     E := AA2010A_PARENT.ASCII;
     AA2010A_PARENT.NATURAL.E;

     AA2010A_PARENT.POSITIVE;
     E := AA2010A_PARENT.STRING;

     AA2010A_PARENT.CONSTRAINT_ERROR;
     E := AA2010A_PARENT.NUMERIC_ERROR;
     AA2010A_PARENT.PROGRAM_ERROR.E;

     AA2010A_PARENT.STORAGE_ERROR;
     E := AA2010A_PARENT.TASKING_ERROR;

     RESULT;
END AA2010A;
