
PACKAGE BODY AA2010A_PARENT IS

     PROCEDURE BOOLEAN IS SEPARATE;
     FUNCTION INTEGER RETURN ENUM IS SEPARATE;
     PACKAGE BODY FLOAT IS SEPARATE;

     PROCEDURE CHARACTER IS SEPARATE;
     FUNCTION ASCII RETURN ENUM IS SEPARATE;
     TASK BODY NATURAL IS SEPARATE;

     PROCEDURE POSITIVE IS SEPARATE;
     FUNCTION STRING RETURN ENUM IS SEPARATE;
     PACKAGE BODY DURATION IS SEPARATE;

     PROCEDURE CONSTRAINT_ERROR IS SEPARATE;
     FUNCTION NUMERIC_ERROR RETURN ENUM IS SEPARATE;
     TASK BODY PROGRAM_ERROR IS SEPARATE;

     PROCEDURE STORAGE_ERROR IS SEPARATE;
     FUNCTION TASKING_ERROR RETURN ENUM IS SEPARATE;

END AA2010A_PARENT;
