# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/12/23 01:33:08 netcap Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGNUGETOPT_BUILDLINK3_MK:=	${LIBGNUGETOPT_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libgnugetopt
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgnugetopt}
BUILDLINK_PACKAGES+=	libgnugetopt
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgnugetopt

.if ${LIBGNUGETOPT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libgnugetopt+=	libgnugetopt>=1.2
BUILDLINK_PKGSRCDIR.libgnugetopt?=	../../wip/libgnugetopt
.endif	# LIBGNUGETOPT_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
