# $NetBSD: Makefile,v 1.6 2012/11/14 00:16:14 othyro Exp $
#

DISTNAME=	PyKCS11-1.2.4
PKGREVISION=	1
CATEGORIES=	security
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=pkcs11wrap/}
COMMENT=	PKCS\#11 wrapper for Python
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	c c++

PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
