# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/23 09:42:14 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HSCOLOUR_BUILDLINK3_MK:=	${HSCOLOUR_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hscolour
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhscolour}
BUILDLINK_PACKAGES+=	hscolour
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hscolour

.if ${HSCOLOUR_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.hscolour+=	hscolour>=1.11
BUILDLINK_PKGSRCDIR.hscolour?=	../../wip/hscolour
.endif	# HSCOLOUR_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
