# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:17:31 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBSOUNDTOUCH_BUILDLINK3_MK:=	${LIBSOUNDTOUCH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libSoundTouch
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NlibSoundTouch}
BUILDLINK_PACKAGES+=	libSoundTouch

.if !empty(LIBSOUNDTOUCH_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libSoundTouch+=	libSoundTouch>=1.3.0
BUILDLINK_PKGSRCDIR.libSoundTouch?=	../../wip/libSoundTouch
.endif	# LIBSOUNDTOUCH_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
