# $NetBSD: buildlink3.mk,v 1.3 2007/08/15 23:06:42 othyro Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CCRTP_BUILDLINK3_MK:=	${CCRTP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	ccrtp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nccrtp}
BUILDLINK_PACKAGES+=	ccrtp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}ccrtp

.if ${CCRTP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.ccrtp+=	ccrtp>=1.5.0
BUILDLINK_PKGSRCDIR.ccrtp?=	../../wip/ccrtp
.endif	# CCRTP_BUILDLINK3_MK

.include "../../wip/commoncpp2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
