# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/04/21 04:24:13 jeremy-c-reed Exp $

BUILDLINK_DEPMETHOD.glproto?=	build

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GLPROTO_BUILDLINK3_MK:=	${GLPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	glproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nglproto}
BUILDLINK_PACKAGES+=	glproto

.if !empty(GLPROTO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.glproto+=	glproto>=1.4.6
BUILDLINK_PKGSRCDIR.glproto?=	../../wip/glproto
.endif	# GLPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
