# $NetBSD: buildlink3.mk,v 1.1 2007/04/30 00:18:49 bsadewitz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SESSREG_BUILDLINK3_MK:=	${SESSREG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	sessreg
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsessreg}
BUILDLINK_PACKAGES+=	sessreg
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}sessreg

.if ${SESSREG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.sessreg+=	sessreg>=1.0.2
BUILDLINK_PKGSRCDIR.sessreg?=	../../wip/sessreg
.endif	# SESSREG_BUILDLINK3_MK

.include "../../x11/libX11/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
