#!/bin/sh
#
# $NetBSD: rox,v 1.1.1.1 2003/12/04 22:25:31 anielski Exp $
#

# The user's Choices directory  
ROX_CHOICES_DIR="$HOME/.RoxChoices"

#
# If CHOICESPATH is not set, then check to see whether the user has
# a $ROX_CHOICES_DIR directory. If they haven't, set one up.
#
if [ -z "$CHOICESPATH" ]; then
        [ ! -d "$ROX_CHOICES_DIR" ] &&                                  \
                        cp -R @PREFIX@/share/rox/Choices "$ROX_CHOICES_DIR";
        export CHOICESPATH="$ROX_CHOICES_DIR";
fi

export XDG_DATA_DIRS="$XDG_DATA_DIRS:@PREFIX@/share"

# Run the ROX-Filer application
exec @PREFIX@/share/rox/ROX-Filer/AppRun "$@"
