# $NetBSD: Makefile,v 1.1.1.1 2009/02/07 20:12:53 milosn Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-thread-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Thread addon for Io.

ADDON_NAME=		Thread

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
