# $NetBSD: Makefile,v 1.2 2012/09/24 18:26:54 asau Exp $
#

DISTNAME=	clustershell-1.2.83
CATEGORIES=	shells
MASTER_SITES=	http://downloads.sourceforge.net/project/clustershell/clustershell/1.3%20beta3/
EXTRACT_SUFX=	.tgz

MAINTAINER=	wenheping@gmail.com
HOMEPAGE=	http://clustershell.sourceforge.net/
COMMENT=	Python library to execute commands on local or distant cluster nodes

PYDISTUTILSPKG= yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
