
PACKAGE BODY CC3019A_QUEUES IS

     PROCEDURE ADD (TO_Q : IN OUT QUEUE_TYPE;
                    VALUE : ELEMENT_TYPE) IS
     BEGIN
          TO_Q.SIZE := TO_Q.SIZE + 1;
          TO_Q.CONTENTS(TO_Q.SIZE) := VALUE;
     END ADD;

--   GENERIC
--        WITH PROCEDURE APPLY (VAL : ELEMENT_TYPE);
     PROCEDURE ITERATOR (TO_Q : QUEUE_TYPE) IS
     BEGIN
          FOR I IN TO_Q.CONTENTS'FIRST .. TO_Q.SIZE LOOP
               APPLY (TO_Q.CONTENTS(I));
          END LOOP;
     END ITERATOR;

END CC3019A_QUEUES;
