# $NetBSD: buildlink3.mk,v 1.1 2004/02/27 11:01:20 johnrshannon Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FLORIST_BUILDLINK3_MK:=	${FLORIST_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	florist
.endif

.if !empty(FLORIST_BUILDLINK3_MK:M+)
BUILDLINK_PACKAGES+=		florist
BUILDLINK_DEPENDS.florist+=	florist>=3.6.1
BUILDLINK_PKGSRCDIR.florist?=	../../wip/florist

.endif	# FLORIST_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
