# $NetBSD$

BUILDLINK_TREE+=	aml

.if !defined(AML_BUILDLINK3_MK)
AML_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.aml+=	aml>=1.0.0
BUILDLINK_PKGSRCDIR.aml?=	../../wip/aml
.endif	# AML_BUILDLINK3_MK

BUILDLINK_TREE+=	-aml
