# $NetBSD$

BUILDLINK_TREE+=	OpenSTA

.if !defined(OPENSTA_BUILDLINK3_MK)
OPENSTA_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.OpenSTA+=	OpenSTA>=20925bb
BUILDLINK_PKGSRCDIR.OpenSTA?=	../../wip/OpenSTA

.endif	# OPENSTA_BUILDLINK3_MK

BUILDLINK_TREE+=	-OpenSTA
