# $NetBSD: Makefile.common,v 1.5 2005/08/04 18:25:00 scott8586 Exp $
#

PLUGINSVERSION=	1.4.1
DISTNAME=	nagios-plugins-${PLUGINSVERSION}

.include "../../wip/nagios-base/Makefile.common"

CONFIGURE_ARGS+=	--with-nagios-user=${NAGIOS_USER}
CONFIGURE_ARGS+=	--with-nagios-group=${NAGIOS_GROUP}
