# $NetBSD$

BUILDLINK_TREE+=	HTSeq

.if !defined(HTSEQ_BUILDLINK3_MK)
HTSEQ_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.HTSeq+=	HTSeq>=0.6.1p1
BUILDLINK_PKGSRCDIR.HTSeq?=	../../wip/py-htseq
.endif	# HTSEQ_BUILDLINK3_MK

BUILDLINK_TREE+=	-HTSeq
