# $NetBSD$

DISTNAME=	palettable-3.3.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	comms python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/palettable/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://jiffyclub.github.io/palettable/
COMMENT=	Python library of color palettes for Python
LICENSE=	mit

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
