$NetBSD$

--- syncserver-common/Cargo.toml.orig	2024-11-05 10:46:45.621411238 +0000
+++ syncserver-common/Cargo.toml
@@ -12,8 +12,8 @@ cadence.workspace = true
 futures.workspace = true
 futures-util.workspace = true
 sha2.workspace = true
-sentry.workspace = true
-sentry-backtrace.workspace = true
+sentry = { path = "../../sentry-rust-1b65b5c99af975496880e7325218479e0037d097/sentry" }
+sentry-backtrace = { path = "../../sentry-rust-1b65b5c99af975496880e7325218479e0037d097/sentry-backtrace" }
 serde.workspace = true
 serde_json.workspace = true
 slog.workspace = true
