$NetBSD: patch-syncstorage-spanner_Cargo.toml,v 1.1 2024/06/13 12:11:59 wiz Exp $

Let pkgsrc provide the file instead of running git to fetch.

--- syncstorage-spanner/Cargo.toml.orig	2024-05-11 20:44:58.000000000 +0000
+++ syncstorage-spanner/Cargo.toml
@@ -16,7 +16,7 @@ thiserror.workspace = true
 
 async-trait = "0.1.40"
 google-cloud-rust-raw = { version = "0.16.1", features = ["spanner"] }
-deadpool = { git = "https://github.com/mozilla-services/deadpool", tag = "deadpool-v0.7.0" }
+deadpool = { path = "../../deadpool" }
 form_urlencoded = "1.2"
 # Some versions of OpenSSL 1.1.1 conflict with grpcio's built-in boringssl which can cause
 # syncserver to either fail to either compile, or start. In those cases, try
