$NetBSD: patch-syncserver-db-common_Cargo.toml,v 1.2 2024/07/14 13:59:54 wiz Exp $

Let pkgsrc provide the file instead of running git to fetch.

--- syncserver-db-common/Cargo.toml.orig	2024-07-11 23:26:43.000000000 +0000
+++ syncserver-db-common/Cargo.toml
@@ -12,6 +12,6 @@ http.workspace = true
 thiserror.workspace = true
 
 diesel = { workspace = true, features = ["mysql", "r2d2"] }
-deadpool = { git = "https://github.com/mozilla-services/deadpool", tag = "deadpool-v0.7.0" }
+deadpool = { path = "../../deadpool" }
 diesel_migrations = { workspace = true, features = ["mysql"] }
 syncserver-common = { path = "../syncserver-common" }
