$NetBSD$

--- Cargo.toml.orig	2024-11-05 10:45:29.552602599 +0000
+++ Cargo.toml
@@ -66,13 +66,13 @@ reqwest = { version = "0.12", default-fe
 ] }
 # rev 1b65b5c includes https://github.com/getsentry/sentry-rust/pull/701
 # TODO: bump to 0.35 as soon as it's available
-sentry = { version = "0.34", git = "https://github.com/getsentry/sentry-rust", rev = "1b65b5c", default-features = false, features = [
+sentry = { path = "../sentry-rust-1b65b5c99af975496880e7325218479e0037d097/sentry", default-features = false, features = [
   "curl",
   "backtrace",
   "contexts",
   "debug-images",
 ] }
-sentry-backtrace = { version = "0.34", git = "https://github.com/getsentry/sentry-rust", rev = "1b65b5c" }
+sentry-backtrace = { path = "../sentry-rust-1b65b5c99af975496880e7325218479e0037d097/sentry-backtrace" }
 serde = "1.0"
 serde_derive = "1.0"
 serde_json = { version = "1.0", features = ["arbitrary_precision"] }
