# $NetBSD$

BUILDLINK_TREE+=	chafa

.if !defined(CHAFA_BUILDLINK3_MK)
CHAFA_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.chafa+=	chafa>=1.14.4
BUILDLINK_PKGSRCDIR.chafa?=	../../wip/chafa

.endif	# SUITESPARSE_BUILDLINK3_MK

BUILDLINK_TREE+=	-chafa
