# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/12/04 23:07:12 shattered Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
DYNAMITE_BUILDLINK3_MK:=	${DYNAMITE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	dynamite
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndynamite}
BUILDLINK_PACKAGES+=	dynamite
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}dynamite

.if !empty(DYNAMITE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.dynamite+=	dynamite>=0.1
BUILDLINK_PKGSRCDIR.dynamite?=		../../wip/synce-dynamite
.endif	# DYNAMITE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
