# $NetBSD$

BUILDLINK_TREE+=	SSVJsonCpp

.if !defined(SSVJSONCPP_BUILDLINK3_MK)
SSVJSONCPP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVJsonCpp+=	SSVJsonCpp>=20130708
BUILDLINK_PKGSRCDIR.SSVJsonCpp?=	../../wip/SSVJsonCpp

BUILDLINK_FILES.SSVJsonCpp+=		lib/cmake/FindSSVJsonCpp.cmake

.endif	# SSVJSONCPP_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVJsonCpp
