# $NetBSD$

BUILDLINK_TREE+=	SSVJsonCpp

.if !defined(SSVJSONCPP_BUILDLINK3_MK)
SSVJSONCPP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVJsonCpp+=	SSVJsonCpp>=20130708
BUILDLINK_PKGSRCDIR.SSVJsonCpp?=	../../wip/SSVJsonCpp

SSVJSONCPP_MODULE=	${PREFIX}/lib/cmake/SSVJsonCpp

.endif	# SSVJSONCPP_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVJsonCpp
