

-- CASE B:
GENERIC
PACKAGE B83004B_PACK2 IS
     TYPE INT2 IS PRIVATE;
PRIVATE
     VAR2 : INTEGER := 2;
     CON2 : CONSTANT STRING := "HELLO";
     EXC2 : EXCEPTION;

     TYPE INT2 IS NEW INTEGER;
     SUBTYPE INT_SUBTYPE2 IS INTEGER RANGE 2..20;

     PACKAGE P2 IS
          X : INTEGER := 0;
     END P2;

     TASK T2;

     GENERIC
     FUNCTION FUN2 RETURN INTEGER;

     PROCEDURE PROC2 (X : IN INTEGER; Y : OUT BOOLEAN);
END B83004B_PACK2;
