$NetBSD: patch-alire.toml,v 1.0 2024/05/02 14:00:00 dkazankov Exp $

Add NetBSD support

--- alire.toml.orig	2024-03-12 23:27:05.000000000 +0200
+++ alire.toml	2024-03-20 13:02:32.616680360 +0200
@@ -40,6 +40,7 @@
 # Building alr requires the explicit setting of this variable
 [gpr-set-externals."case(os)"]
 freebsd = { ALIRE_OS = "freebsd" }
+netbsd  = { ALIRE_OS = "netbsd" }
 linux   = { ALIRE_OS = "linux" }
 macos   = { ALIRE_OS = "macos" }
 windows = { ALIRE_OS = "windows" }
