# $NetBSD: buildlink3.mk,v 1.2 2004/11/03 10:13:55 adrian_p Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TRE_BUILDLINK3_MK:=	${TRE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	tre
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntre}
BUILDLINK_PACKAGES+=	tre

.if !empty(TRE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.tre+=	tre>=0.7.0
BUILDLINK_PKGSRCDIR.tre?=	../../wip/tre
BUILDLINK_DEPMETHOD.tre?=	build
.endif	# TRE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
