

WITH REPORT, CA1003A_P, CA1003A_PKG, CA1003A_F;
USE REPORT;

PROCEDURE CA1003A IS

     I : INTEGER := IDENT_INT (0);

BEGIN
     TEST ("CA1003A", "INDEPENDENT UNITS IN A SINGLE FILE");

     CA1003A_P (I);
     IF I /= 1 THEN
          FAILED ("INDEPENDENT PROCEDURE NOT INVOKED");
     END IF;

     CA1003A_PKG.I := CA1003A_PKG.I + IDENT_INT(10);
     IF CA1003A_PKG.I /= 10 THEN
          FAILED ("INDEPENDENT PACKAGE VARIABLE ACCESSED INCORRECTLY");
     END IF;

     IF CA1003A_F(IDENT_INT(5)) /= -5 THEN
          FAILED ("INDEPENDENT FUNCTION NOT INVOKED");
     END IF;

     RESULT;
END CA1003A;
