# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/09/06 22:03:58 thomasklausner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBOSIP2_BUILDLINK3_MK:=	${LIBOSIP2_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libosip2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibosip2}
BUILDLINK_PACKAGES+=	libosip2
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libosip2

.if ${LIBOSIP2_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libosip2+=	libosip2>=2.2.2<3.0
BUILDLINK_PKGSRCDIR.libosip2?=		../../wip/libosip222
.endif	# LIBOSIP2_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
