# $NetBSD: buildlink3.mk,v 1.1 2007/12/26 17:27:06 bsadewitz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MPG123_BASE_BUILDLINK3_MK:=	${MPG123_BASE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mpg123-base
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmpg123-base}
BUILDLINK_PACKAGES+=	mpg123-base
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mpg123-base

.if ${MPG123_BASE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mpg123-base+=	mpg123-base>=1.0.0
BUILDLINK_PKGSRCDIR.mpg123-base?=	../../wip/mpg123
.endif	# MPG123_BASE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
