# $NetBSD$

BUILDLINK_TREE+=	muffin

.if !defined(MUFFIN_BUILDLINK3_MK)
MUFFIN_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.muffin+=	muffin>=3.8.1
BUILDLINK_PKGSRCDIR.muffin?=	../../wip/muffin

.endif	# MUFFIN_BUILDLINK3_MK

BUILDLINK_TREE+=	-muffin
