# $NetBSD: buildlink3.mk,v 1.1 2009/03/20 23:02:58 jihbed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CSOAP_BUILDLINK3_MK:=	${CSOAP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	csoap
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncsoap}
BUILDLINK_PACKAGES+=	csoap
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}csoap

.if ${CSOAP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.csoap+=	csoap>=1.1.0
BUILDLINK_PKGSRCDIR.csoap?=	../../wip/csoap
.endif	# CSOAP_BUILDLINK3_MK

.include "../../textproc/libxml2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
