# $NetBSD: buildlink3.mk,v 1.3 2006/09/25 12:37:52 dhowland Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_MMPYTHON_BUILDLINK3_MK:=	${PY_MMPYTHON_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py-mmpython
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy-mmpython}
BUILDLINK_PACKAGES+=	py-mmpython
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py-mmpython

.if ${PY_MMPYTHON_BUILDLINK3_MK} == "+"
.include "../../lang/python/pyversion.mk"
BUILDLINK_API_DEPENDS.py-mmpython+=	${PYPKGPREFIX}-mmpython>=0.4.9
BUILDLINK_PKGSRCDIR.py-mmpython?=	../../wip/py-mmpython
.endif	# PY_MMPYTHON_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
