# $NetBSD: buildlink3.mk,v 1.1 2009/02/10 09:55:36 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CPPHS_BUILDLINK3_MK:=	${CPPHS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	cpphs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncpphs}
BUILDLINK_PACKAGES+=	cpphs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cpphs

.if ${CPPHS_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.cpphs?=	build
BUILDLINK_API_DEPENDS.cpphs+=	cpphs>=1.6
BUILDLINK_PKGSRCDIR.cpphs?=	../../wip/cpphs
.endif	# CPPHS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
