# $NetBSD: Makefile,v 1.2 2012/11/13 22:25:32 othyro Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-contracts-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Contracts addon for Io

ADDON_NAME=		Contracts

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
