# $NetBSD$

BUILDLINK_TREE+=	ThirdParty-ASL

.if !defined(THIRDPARTY_ASL_BUILDLINK3_MK)
THIRDPARTY_ASL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ThirdParty-ASL+=	ThirdParty-ASL>=2.0.1
BUILDLINK_PKGSRCDIR.ThirdParty-ASL?=	../../wip/ThirdParty-ASL
.endif	# THIRDPARTY_ASL_BUILDLINK3_MK

BUILDLINK_TREE+=	-ThirdParty-ASL
