# $NetBSD$
#BUILDLINK_DEPMETHOD.lua-compat53?=	build

BUILDLINK_TREE+=	lua-compat53

.if !defined(LUA_COMPAT53_BUILDLINK3_MK)
LUA_COMPAT53_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.lua-compat53+=		${LUA_PKGPREFIX}-compat53>=0.7
BUILDLINK_PKGSRCDIR.lua-compat53?=		../../wip/lua-compat53
BUILDLINK_CONTENTS_FILTER.lua-compat53?=	${EGREP} '(\.c$$|\.h$$)'
.endif	# LUA_COMPAT53_BUILDLINK3_MK

BUILDLINK_TREE+=	-lua-compat53
