
WITH SPPRT13;
WITH REPORT; USE REPORT;
PRAGMA ELABORATE (SPPRT13);
PRAGMA ELABORATE (REPORT);
SEPARATE (CD5003H_PACK3)
PACKAGE BODY PACK4 IS
     TEST_VAR : INTEGER := 0;
     FOR TEST_VAR USE AT SPPRT13.VARIABLE_ADDRESS;
     USE SYSTEM;
BEGIN
     TEST ("CD5003H", "A 'WITH' CLAUSE NAMING 'SYSTEM' NEED NOT BE " &
                      "GIVEN FOR A GENERIC PACKAGE BODY SUBUNIT " &
                      "CONTAINING AN ADDRESS CLAUSE AS LONG AS " &
                      "A 'WITH' CLAUSE IS GIVEN FOR THE UNIT " &
                      "CONTAINING THE GENERIC PACKAGE SPECIFICATION.");

     TEST_VAR := IDENT_INT (3);

     IF TEST_VAR /= 3 THEN
          FAILED ("INCORRECT VALUE FOR TEST_VAR");
     END IF;

     IF TEST_VAR'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR TEST_VAR");
     END IF;
END PACK4;
