# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/20 05:37:11 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
BINARY_BUILDLINK3_MK:=	${BINARY_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	binary
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbinary}
BUILDLINK_PACKAGES+=	binary
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}binary

.if ${BINARY_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.binary?=	build
BUILDLINK_API_DEPENDS.binary+=	binary>=0.4.4
BUILDLINK_PKGSRCDIR.binary?=	../../wip/hs-binary
.endif	# BINARY_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
