# $NetBSD: buildlink3.mk,v 1.2 2009/02/10 07:39:00 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HS_BINARY_BUILDLINK3_MK:=	${HS_BINARY_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-binary
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-binary}
BUILDLINK_PACKAGES+=	hs-binary
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-binary

.if ${HS_BINARY_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-binary?=	build
BUILDLINK_API_DEPENDS.hs-binary+=	hs-binary>=0.4.4nb1
BUILDLINK_PKGSRCDIR.hs-binary?=	../../wip/hs-binary
.endif	# HS_BINARY_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
