# $NetBSD: Makefile,v 1.1 2004/05/14 05:52:27 yeled Exp $
#

DISTNAME=	ifstat-1.1
CATEGORIES=	net sysutils
MASTER_SITES=	${HOMEPAGE}

MAINTAINER=	charlie@rubberduck.com
HOMEPAGE=	http://gael.roualland.free.fr/ifstat/
COMMENT=	iftat is a tool to report network interfaces bandwith.

USE_BUILDLINK3=	YES
GNU_CONFIGURE=	YES

.include "../../mk/bsd.pkg.mk"

# TODO
# --with-snmp
