# $NetBSD: buildlink3.mk,v 1.1 2007/01/23 13:52:28 bsadewitz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XBITMAPS_BUILDLINK3_MK:=	${XBITMAPS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xbitmaps
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxbitmaps}
BUILDLINK_PACKAGES+=	xbitmaps
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xbitmaps

.if ${XBITMAPS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.xbitmaps+=	xbitmaps>=1.0.1
BUILDLINK_PKGSRCDIR.xbitmaps?=	../../wip/xbitmaps
.endif	# XBITMAPS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
