# $NetBSD: buildlink3.mk,v 1.5 2007/04/30 15:30:12 bsadewitz Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
LIBPTHREAD_STUBS_BUILDLINK3_MK:=	${LIBPTHREAD_STUBS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libpthread-stubs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibpthread-stubs}
BUILDLINK_PACKAGES+=	libpthread-stubs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libpthread-stubs

.if ${LIBPTHREAD_STUBS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libpthread-stubs+=	libpthread-stubs>=1.0nb4
BUILDLINK_PKGSRCDIR.libpthread-stubs?=	../../wip/libpthread-stubs
.endif	# LIBPTHREAD_STUBS_BUILDLINK3_MK

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH:S/+$//}
