# $NetBSD$

BUILDLINK_TREE+=	ndevd

.if !defined(NDEVD_BUILDLINK3_MK)
NDEVD_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ndevd+=	ndevd>=24.06.25
BUILDLINK_ABI_DEPENDS.ndevd+=	ndevd>=24.06.25
BUILDLINK_PKGSRCDIR.ndevd?=	../../wip/ndevd

.endif # NDEVD_BUILDLINK3_MK

BUILDLINK_TREE+=	-ndevd
