# $NetBSD: Makefile,v 1.1.1.1 2003/09/01 12:51:03 adrian_p Exp $

DISTNAME=	Date-1.3
PKGNAME=	pear-${DISTNAME}
CATEGORIES=	www
MASTER_SITES=	${MASTER_SITE_PAIR_PACKAGE}

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://pear.php.net/package/Date
COMMENT=	Date and Time Zone Classes

USE_BUILDLINK2=		YES

.include "../../wip/php4/package.mk"
.include "../../mk/bsd.pkg.mk"
