# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/02/21 21:14:19 pmatias Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AGG_BUILDLINK3_MK:=	${AGG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	agg
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nagg}
BUILDLINK_PACKAGES+=	agg
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}agg

.if ${AGG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.agg+=	agg>=2.5
BUILDLINK_PKGSRCDIR.agg?=	../../wip/agg
.endif	# AGG_BUILDLINK3_MK

.include "../../graphics/freetype2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
