# $NetBSD: Makefile,v 1.3 2006/11/29 19:04:21 cheusov Exp $

PKGNAME=	pike-MIME-${PIKE_VERSION}
CATEGORIES=	lang
COMMENT=	MIME module for Pike programming language
LICENSE=	gnu-gpl-v2 AND gnu-lgpl-v2.1 AND mpl-1.1

MODULE_NAMES=	MIME
MODULE_DIRS=	modules/MIME
MODULE_SO=	___MIME.so

.include "../../wip/pike-core/Makefile.common"
.include "../../wip/pike-core/Makefile.modules_common"

.include "../../mk/bsd.pkg.mk"
