===========================================================================
$NetBSD: MESSAGE.module,v 1.1 2004/07/16 17:21:09 ppostma Exp $

To enable this module, add the following to ${PKG_SYSCONFDIR}/php.ini:

    extension=${MODNAME}.so

and make sure extension_dir points to the dir where ${MODNAME}.so is.

Then restart your PHP5-enabled HTTP server to load this module.
===========================================================================
