
PACKAGE B83024F_P2 IS
     A : INTEGER := 2;

     PROCEDURE P;

     GENERIC
          X : IN INTEGER := A;
          A : IN OUT FLOAT;
     PACKAGE B83024F_PACK2 IS
          TYPE P IS NEW INTEGER;
     END B83024F_PACK2;

     PROCEDURE REQUIRE_BODY;
END B83024F_P2;
