# $NetBSD: Makefile,v 1.2 2005/11/02 18:00:25 thomasklausner Exp $
#

DISTNAME=		RealTimeBattle-1.0.7-Std
PKGNAME=		realtimebattle-1.0.7
CATEGORIES=		games
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=realtimebattle/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://realtimebattle.sourceforge.net/
COMMENT=		Programming robots game

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../x11/gtk2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
