# $NetBSD$

DISTNAME=	pfsc-util-0.22.8
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel python
MASTER_SITES=	${MASTER_SITE_PYPI:=p/pfsc-util/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/proofscape/pfsc-util
COMMENT=	Proofscape Utilities
LICENSE=	apache-2.0

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
