# $NetBSD$

DISTNAME=	wip-tools-0.1.0.25
CATEGORIES=	pkgtools
MASTER_SITES=	${MASTER_SITE_GITHUB:=outpaddling/}
GITHUB_TAG=	bf32126e6d1979c27762c11045e3046e03a19993
GITHUB_PROJECT=	pkgsrc-wip-tools

OWNER=		bacon@NetBSD.org
HOMEPAGE=	https://github.com/outpaddling/
COMMENT=	Tools for developing wip packages
LICENSE=	modified-bsd

USE_LANGUAGES=	# empty

DEPENDS+=	pkg-dev>=0:../../wip/pkg-dev

.include "../../mk/bsd.pkg.mk"
