# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/10/14 12:47:25 hoka_adam Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBCONFIG_BUILDLINK3_MK:=	${LIBCONFIG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libconfig
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibconfig}
BUILDLINK_PACKAGES+=	libconfig
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libconfig

.if ${LIBCONFIG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libconfig+=	libconfig>=1.1.3
BUILDLINK_PKGSRCDIR.libconfig?=	../../wip/libconfig
.endif	# LIBCONFIG_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
