# $NetBSD: Makefile,v 1.1 2014/09/29 15:22:03 khorben Exp $

DISTNAME=	suse_libbz2-${SUSE_VERSION}
CATEGORIES=	emulators
RPMPKGS+=	libbz2-1-1.0.6-14.1.4.${SUSE_ARCH}

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Linux compatibility package for libgcrypt

.include "../../emulators/suse121_linux/Makefile.common"
.include "../../mk/bsd.pkg.mk"
