# $NetBSD: Makefile,v 1.2 2012/10/07 16:23:19 asau Exp $
#

DISTNAME=	SymbolicC++3-3.35-ac
PKGNAME=	symbolic++-3.35
CATEGORIES=	math
MASTER_SITES=	http://issc.uj.ac.za/symbolic/sources/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://issc.uj.ac.za/symbolic/symbolic.html
COMMENT=	C++ and POO programming to develop a computer algebra system
LICENSE=	gnu-gpl-v2

WRKSRC=		${WRKDIR}/SymbolicC++3-3.35

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
