# $NetBSD: buildlink3.mk,v 1.1 2009/03/27 00:04:30 smoppy Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
STFL_BUILDLINK3_MK:=	${STFL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	stfl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nstfl}
BUILDLINK_PACKAGES+=	stfl
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}stfl

.if ${STFL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.stfl+=	stfl>=0.19
BUILDLINK_PKGSRCDIR.stfl?=	../../wip/stfl
BUILDLINK_DEPMETHOD.stfl?=	build
.endif	# STFL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
