# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/01/19 11:54:23 tnn2 Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JDK15_BUILDLINK3_MK:=	${JDK15_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jdk16
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njdk16}
BUILDLINK_PACKAGES+=	jdk16
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}jdk16

.if !empty(JDK15_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.jdk15+=	jdk16>=1.6.0.0
BUILDLINK_PKGSRCDIR.jdk15?=	../../wip/jdk16
BUILDLINK_JAVA_PREFIX.jdk15=	${PREFIX}/java/jdk-1.6.0

BUILDLINK_PASSTHRU_DIRS+=	${BUILDLINK_JAVA_PREFIX.jdk16}

BUILDLINK_CPPFLAGS.jdk16= \
	-I${BUILDLINK_JAVA_PREFIX.jdk16}/include	\
	-I${BUILDLINK_JAVA_PREFIX.jdk16}/include/netbsd
.endif	# JDK16_BUILDLINK3_MK

.include "../../x11/libXi/buildlink3.mk"
.include "../../x11/libXtst/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
