# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/07/16 14:13:42 krub1 Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
USBIDS_BUILDLINK3_MK:=	${USBIDS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	usbids
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nusbids}
BUILDLINK_PACKAGES+=	usbids
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}usbids

.if ${USBIDS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.usbids+=	usbids>=10032007
BUILDLINK_PKGSRCDIR.usbids?=	../../misc/usbids
.endif	# USBIDS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
