# $NetBSD$

DISTNAME=	textfsm-0.3.0
PKGNAME=	${PYPKGPREFIX}-j${DISTNAME}
CATEGORIES=	textproc
MASTER_SITES=	${MASTER_SITE_GITHUB:=jonathanslenders/}
GITHUB_PROJECT=	textfsm

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jonathanslenders/textfsm
COMMENT=	Template based state machine for semi-formatted text
LICENSE=	apache-2.0

.include "../../wip/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
