     
WITH AA2012A1;
WITH REPORT; USE REPORT;
PROCEDURE AA2012A IS

BEGIN
     TEST ( "AA2012A", "CHECK THAT A BODY STUB CAN SERVE AS AN " &
                       "IMPLICIT DECLARATION OF A SUBPROGRAM, " &
                       "I.E., A PRECEDING SUBPROGRAM DECLARATION " &
                       "IS NOT REQUIRED" );

     AA2012A1;

     RESULT;
END AA2012A;
