# $NetBSD: Makefile,v 1.3 2005/12/01 23:49:15 hisazumi Exp $
#

DISTNAME=		Kahua-0.3.4
CATEGORIES=		wip
MASTER_SITES=		http://www.kahua.org/download/kahua/
EXTRACT_SUFX=		.tgz

MAINTAINER=		nel@soraneko.com
HOMEPAGE=		http://www.kahua.org/download/kahua/
COMMENT=		Kahua is a web application framework for Gauche

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../lang/gauche/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
