# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/08/25 22:19:19 bsadewitz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
VALA_BUILDLINK3_MK:=	${VALA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	vala
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nvala}
BUILDLINK_PACKAGES+=	vala
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}vala

.if ${VALA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.vala+=	vala>=0.3.5
BUILDLINK_PKGSRCDIR.vala?=	../../wip/vala
.endif	# VALA_BUILDLINK3_MK

.include "../../devel/glib2/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
