# $NetBSD: Makefile,v 1.2 2014/06/24 20:59:49 szptvlfn Exp $

DISTNAME=	stringsearch-0.3.6.5
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast searching, splitting and replacing of ByteStrings
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
