# $NetBSD: buildlink3.mk,v 1.3 2005/06/12 23:51:20 kristerw Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JDK14_BUILDLINK3_MK:=	${JDK14_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jdk14
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njdk14}
BUILDLINK_PACKAGES+=	jdk14

.if !empty(JDK14_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.jdk14+=	jdk14>=1.4.2.6
BUILDLINK_PKGSRCDIR.jdk14?=	../../wip/jdk14
BUILDLINK_JAVA_PREFIX.jdk14=	${PREFIX}/java/jdk-1.4.2

BUILDLINK_PASSTHRU_DIRS+=	${BUILDLINK_JAVA_PREFIX.jdk14}

BUILDLINK_CPPFLAGS.jdk14= \
	-I${BUILDLINK_JAVA_PREFIX.jdk14}/include				\
	-I${BUILDLINK_JAVA_PREFIX.jdk14}/include/netbsd
.endif	# JDK14_BUILDLINK3_MK

.include "../../mk/x11.buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
