# $NetBSD$

DISTNAME=	sqlite3-1.4.2
CATEGORIES=	databases

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/sparklemotion/sqlite3-ruby/
COMMENT=	Ruby bindings for the SQLite3 embedded database
LICENSE=	modified-bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
