# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/17 08:50:22 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HSH_BUILDLINK3_MK:=	${HSH_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	HSH
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NHSH}
BUILDLINK_PACKAGES+=	HSH
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}HSH

.if ${HSH_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.HSH?=	build
BUILDLINK_API_DEPENDS.HSH+=	HSH>=1.2.6
BUILDLINK_PKGSRCDIR.HSH?=	../../wip/HSH
.endif	# HSH_BUILDLINK3_MK

.include "../../wip/MissingH/buildlink3.mk"
.include "../../wip/hslogger/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
