# $NetBSD$

BUILDLINK_TREE+=	olm

.if !defined(OLM_BUILDLINK3_MK)
OLM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.olm+=	olm>=3.2.2
BUILDLINK_PKGSRCDIR.olm?=	../../wip/olm
.endif	# OLM_BUILDLINK3_MK

BUILDLINK_TREE+=	-olm
