# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/03/01 03:14:51 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MCS_BUILDLINK3_MK:=	${MCS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mcs
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmcs}
BUILDLINK_PACKAGES+=	mcs
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mcs

.if ${MCS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mcs+=	mcs>=0.4.1
BUILDLINK_PKGSRCDIR.mcs?=	../../wip/libmcs
.endif	# MCS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
