# $NetBSD$

BUILDLINK_TREE+=	parafly

.if !defined(PARAFLY_BUILDLINK3_MK)
PARAFLY_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.parafly+=	parafly>=2013.01.21
BUILDLINK_PKGSRCDIR.parafly?=	../../wip/parafly
.endif	# PARAFLY_BUILDLINK3_MK

BUILDLINK_TREE+=	-parafly
