# $NetBSD$

BUILDLINK_TREE+=	OpenBLAS

.if !defined(OPENBLAS_BUILDLINK3_MK)
OPENBLAS_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.OpenBLAS+=	OpenBLAS>=0.2.19
BUILDLINK_PKGSRCDIR.OpenBLAS?=		../../wip/OpenBLAS
.endif	# OPENBLAS_BUILDLINK3_MK

BUILDLINK_TREE+=	-OpenBLAS
