

WITH REPORT, CA1005A_F, CA1005A_P;
USE REPORT;

PROCEDURE CA1005A IS

     I : INTEGER := IDENT_INT (7);

BEGIN
     TEST ("CA1005A", "SUBPROGRAM DECLARATIONS AND BODIES " &
           "SUBMITTED TOGETHER");

     IF CA1005A_F (IDENT_INT(2)) /= 3 THEN
          FAILED ("FUNCTION NOT EXECUTED");
     END IF;

     CA1005A_P (I);
     IF I /= -7 THEN
          FAILED ("PROCEDURE NOT EXECUTED");
     END IF;

     RESULT;
END CA1005A;
