# $NetBSD$

DISTNAME=	pkgsrc-wip-tools-0.1.0.1
CATEGORIES=	pkgtools
MASTER_SITES=	${MASTER_SITE_GITHUB:=outpaddling/}
GITHUB_TAG=	27ab7f517bcafbb6cdf94a0b38f985f5e610d6ec

MAINTAINER=	bacon@NetBSD.org
HOMEPAGE=	https://github.com/outpaddling/
COMMENT=	Tools for developing wip packages
LICENSE=	modified-bsd

USE_LANGUAGES=	# empty

.include "../../mk/bsd.pkg.mk"
