# $NetBSD: Makefile,v 1.10 2005/08/05 21:04:58 poppnk Exp $
#

DISTNAME=		rolo-011
CATEGORIES=		wip mail
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=rolo/}

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://rolo.sourceforge.net/
COMMENT=		Text-based contact manager

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../wip/libvc/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
