# $NetBSD: buildlink2.mk,v 1.1.1.1 2004/02/11 17:37:42 bjan2 Exp $
#
# This Makefile fragment is included by packages that use QUANTA.
#
# This file was created automatically using createbuildlink-3.1.
#

.if !defined(QUANTA_BUILDLINK2_MK)
QUANTA_BUILDLINK2_MK=	# defined

BUILDLINK_PACKAGES+=			QUANTA
BUILDLINK_DEPENDS.QUANTA?=		QUANTA>=0.3
BUILDLINK_PKGSRCDIR.QUANTA?=		../../wip/QUANTA

EVAL_PREFIX+=	BUILDLINK_PREFIX.QUANTA=QUANTA
BUILDLINK_PREFIX.QUANTA_DEFAULT=	${LOCALBASE}
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTA.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTA_APPLICATION_INCLUDES
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAconfig.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAconfig_win32.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAdb_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAdb_sharedState_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAglobals.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAinit.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_debug.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_exception_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_fileList_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_hash.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_hashDict.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_list_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_observer_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_queue_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_stack_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAmisc_vector_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_barrierBase_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_barrierTcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_barrierUdp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_datapack_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_extendedParallelTcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_extendedTcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_fecClient_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_fecEngine_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_fecServer_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_http_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_iovec_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_mcast_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_objectStreamBase_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_objectStreamTcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_objectStreamUdp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_parallelTcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_perfClient_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_perfDaemon_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_perfMonitor_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_rbudpBase_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_rbudpReceiver_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_rbudpSender_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_remoteFileIO32_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_remoteFileIO64_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_remoteParallelFileIO32_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_remoteParallelFileIO64_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_rpc_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_serializable_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_socketbase_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_tcpReflector_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_tcp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_udpReflector_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAnet_udp_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAts_barrier_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAts_condition_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAts_mutex_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/QUANTAts_thread_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/gettimeofday.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/keytool.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/md5.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/md5Key_c.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/perfmon.hxx
BUILDLINK_FILES.QUANTA+=	include/QUANTA/pthread_win.hxx
BUILDLINK_FILES.QUANTA+=	lib/libquanta_32.*

BUILDLINK_TARGETS+=	QUANTA-buildlink

QUANTA-buildlink: _BUILDLINK_USE

.endif	# QUANTA_BUILDLINK2_MK
