# $NetBSD: Makefile,v 1.3 2005/01/13 11:38:44 ianzag Exp $

DISTNAME=		koffice-i18n-et-1.3.5
CATEGORIES=		x11 kde
MASTER_SITES=	ftp://ftp.kde.org/pub/kde/stable/koffice-1.3.5/src/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=		ianzag@mail.ru
HOMEPAGE=		http://www.koffice.org/
COMMENT=		KOffice et language pack

USE_BUILDLINK3=	YES
GNU_CONFIGURE=	YES
USE_GNU_TOOLS+=	make

.include "../../misc/koffice/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
