# $NetBSD: Makefile,v 1.9 2011/01/17 10:48:03 emil_s Exp $
#

DISTNAME=	happy-1.18.6
PKGNAME=	${DISTNAME}
CATEGORIES=	devel
MAINTAINER=	esg@sdf.lonestar.org
HOMEPAGE=	http://www.haskell.org/happy/
COMMENT=	LALR(1) parser generator for the functional language Haskell
LICENSE=	modified-bsd

USE_TOOLS+=	perl

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
