# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/03/12 05:27:58 bsadewitz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
AUDIO_MML_BUILDLINK3_MK:=	${AUDIO_MML_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	audio-mml
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Naudio-mml}
BUILDLINK_PACKAGES+=	audio-mml
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}audio-mml

.if ${AUDIO_MML_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.audio-mml+=	audio-mml>=4.4.01
BUILDLINK_PKGSRCDIR.audio-mml?=	../../wip/audio-mml
.endif	# AUDIO_MML_BUILDLINK3_MK

.include "../../wip/common-mml/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
