# $NetBSD: buildlink3.mk,v 1.1 2007/08/12 01:40:02 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
IKSEMEL_BUILDLINK3_MK:=	${IKSEMEL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	iksemel
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Niksemel}
BUILDLINK_PACKAGES+=	iksemel
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}iksemel

.if ${IKSEMEL_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.iksemel+=	iksemel>=1.3
BUILDLINK_PKGSRCDIR.iksemel?=	../../wip/iksemel
.endif	# IKSEMEL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
