# $NetBSD: Makefile,v 1.3 2006/04/29 17:43:15 shattered Exp $
#

DISTNAME=	ccrypt-1.4
CATEGORIES=	security
MASTER_SITES=   http://www.mathstat.dal.ca/~selinger/ccrypt/download/

MAINTAINER=	poff@sixbit.org
HOMEPAGE=	http://www.mathstat.dal.ca/~selinger/ccrypt/
COMMENT=	Encrypts/decrypts files using Rijndael block cipher

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
