# $NetBSD: Makefile,v 1.1 2015/08/29 17:03:23 f8l Exp $
.include "../../wip/dwb-git-gtk2/Makefile.common"

PKGNAME=        dwb-git-gtk3
COMMENT=	Dynamic WebKit browser, gtk3 version

MAKE_ENV+=	GTK=3

.include "../../www/webkit24-gtk3/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
