$NetBSD$

* Part of patchset to build chromium on NetBSD
* Based on OpenBSD's chromium patches, and
  pkgsrc's qt5-qtwebengine patches

--- third_party/openscreen/src/util/BUILD.gn.orig	2026-09-17 03:47:47.000000000 +0000
+++ third_party/openscreen/src/util/BUILD.gn
@@ -107,7 +107,7 @@ openscreen_source_set("util") {
     sources += [ "scoped_wake_lock_mac.cc" ]
   }
 
-  if (is_linux) {
+  if (is_linux && !is_bsd) {
     sources += [ "scoped_wake_lock_linux.cc" ]
   }
 
