# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/08/28 06:14:09 makoto Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
CYGWIN_BINUTILS_BUILDLINK3_MK:=	${CYGWIN_BINUTILS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	cygwin-binutils
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncygwin-binutils}
BUILDLINK_PACKAGES+=	cygwin-binutils
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}cygwin-binutils

.if ${CYGWIN_BINUTILS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.cygwin-binutils+=	cygwin-binutils>=2.18
BUILDLINK_PKGSRCDIR.cygwin-binutils?=	../../wip/cygwin-binutils
.endif	# CYGWIN_BINUTILS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
