
WITH C86007A_PACK; WITH REPORT; USE REPORT;
PROCEDURE C86007A IS
BEGIN
     TEST("C86007A", "CHECK THAT AN EXPANDED NAME FOR AN ENTITY " &
                     "DECLARED IN THE VISIBLE PART OF A LIBRARY " &
                     "PACKAGE CAN START WITH THE NAME ""STANDARD""");

     STANDARD.C86007A_PACK.PROC;

     RESULT;
END C86007A;
