
PACKAGE BODY C86007A_PACK IS
     PROCEDURE SWAP(X,Y: IN OUT STANDARD.C86007A_PACK.ITEM) IS
          T : STANDARD.C86007A_PACK.ITEM;
     BEGIN
          T := X;
          X := Y;
          Y := T;
     END SWAP;

     PROCEDURE PROC IS
          X : STANDARD.C86007A_PACK.ITEM := IDENT_INT(10);
          W : STANDARD.C86007A_PACK.ACC;
     BEGIN

          W := NEW STANDARD.C86007A_PACK.ITEM;
          W.ALL := X;
          STANDARD.C86007A_PACK.SWAP(X, STANDARD.C86007A_PACK.Y);
          IF STANDARD.C86007A_PACK.Y /= IDENT_INT(10) THEN
               FAILED("FAILED STANDARD.NAME CALL PROCEDURE - B-10");
          END IF;
          IF X /= IDENT_INT(5) THEN
               FAILED("FAILED STANDARD.NAME CALL PROCEDURE - B-5");
          END IF;
     END PROC;
END C86007A_PACK;
