# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/08/08 19:00:22 larnor Exp $

BUILDLINK_DEPMETHOD.xextproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XEXTPROTO_BUILDLINK3_MK:=	${XEXTPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	xextproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxextproto}
BUILDLINK_PACKAGES+=	xextproto

.if !empty(XEXTPROTO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.xextproto+=	xextproto>=7.0
BUILDLINK_PKGSRCDIR.xextproto?=	../../wip/xextproto
.endif	# XEXTPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
