# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/08/09 23:05:04 ondratu Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LINUX_ATTR_BUILDLINK3_MK:=	${LINUX_ATTR_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	linux-attr
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlinux-attr}
BUILDLINK_PACKAGES+=	linux-attr
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}linux-attr

.if ${LINUX_ATTR_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.linux-attr+=	linux-attr>=2.4.32.1
BUILDLINK_PKGSRCDIR.linux-attr?=	../../wip/linux-attr
.endif	# LINUX_ATTR_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
