$NetBSD$

Let pkgsrc provide the file instead of running git to fetch.

--- syncserver-db-common/Cargo.toml.orig	2023-06-10 19:04:16.000000000 +0000
+++ syncserver-db-common/Cargo.toml
@@ -8,7 +8,7 @@ backtrace = "0.3.61"
 # Pin to 0.5 for now, to keep it under tokio 0.2 (issue977).
 # Fix for #803 (deadpool#92) points to our fork for now
 #deadpool = "0.5"  # pin to 0.5
-deadpool = { git = "https://github.com/mozilla-services/deadpool", branch = "deadpool-v0.5.2-issue92" }
+deadpool = { path = "../../deadpool" }
 diesel = { version = "1.4", features = ["mysql", "r2d2"] }
 diesel_migrations = { version = "1.4.0", features = ["mysql"] }
 futures = { version = "0.3", features = ["compat"] }
