
WITH CD7202A_SYS;
WITH REPORT; USE REPORT;
PROCEDURE CD7202A IS

     INT : INTEGER := 2;

     BOOL : BOOLEAN := (INT'ADDRESS IN CD7202A_SYS.MY_ADDRESS);

BEGIN
     TEST ("CD7202A", "THE 'ADDRESS ATTRIBUTE CAN BE USED IN A" &
                      " COMPILATION UNIT EVEN IF A WITH CLAUSE FOR " &
                      "PACKAGE SYSTEM DOES NOT APPLY TO THE UNIT");

     IF NOT IDENT_BOOL(BOOL) THEN
          FAILED("ADDRESS ATTRIBUTE INCORRECT");
     END IF;

     RESULT;
END CD7202A;
