# $NetBSD$

BUILDLINK_TREE+=	GtkD

.if !defined(GTKD_BUILDLINK3_MK)
GTKD_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.GtkD+=	GtkD>=3.9.0
BUILDLINK_PKGSRCDIR.GtkD?=	../../wip/gtk-d
.endif	# GTKD_BUILDLINK3_MK

BUILDLINK_TREE+=	-GtkD
