# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/05/31 02:30:17 hoka_adam Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LUA_BUILDLINK3_MK:=	${LUA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	lua
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlua}
BUILDLINK_PACKAGES+=	lua
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}lua

.if ${LUA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.lua+=	lua>=5.0.3
BUILDLINK_PKGSRCDIR.lua?=	../../wip/lua50
.endif	# LUA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
