# $NetBSD: Makefile,v 1.9 2013/12/04 10:12:19 phonohawk Exp $
#

DISTNAME=	hashed-storage-0.5.10
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Hashed file storage support code
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-dataenc/buildlink3.mk"
.include "../../wip/hs-extensible-exceptions/buildlink3.mk"
.include "../../wip/hs-mmap/buildlink3.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-zlib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
