# $NetBSD: buildlink3.mk,v 1.2 2007/09/16 06:50:48 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBMTP_BUILDLINK3_MK:=	${LIBMTP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libmtp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmtp}
BUILDLINK_PACKAGES+=	libmtp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libmtp

.if ${LIBMTP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libmtp+=	libmtp>=0.2.1
BUILDLINK_PKGSRCDIR.libmtp?=	../../wip/libmtp
.endif	# LIBMTP_BUILDLINK3_MK

.include "../../devel/libusb/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
