# $NetBSD$

BUILDLINK_TREE+=	libcap

.if !defined(LIBCAP_BUILDLINK3_MK)
LIBCAP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.libcap+=	libcap>=2.25
BUILDLINK_PKGSRCDIR.libcap?=	../../local/libcap
.endif	# LIBCAP_BUILDLINK3_MK

BUILDLINK_TREE+=	-libcap
