# $NetBSD: Makefile,v 1.8 2013/08/15 04:38:03 szptvlfn Exp $
#

DISTNAME=	uniplate-1.6.11
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Help writing simple, concise and fast generic operations
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-hashable/buildlink3.mk"
.include "../../wip/hs-syb/buildlink3.mk"
.include "../../wip/hs-unordered-containers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
