# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/03/16 15:54:03 jihbed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JSON_C_BUILDLINK3_MK:=	${JSON_C_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	json-c
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njson-c}
BUILDLINK_PACKAGES+=	json-c
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}json-c

.if ${JSON_C_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.json-c+=	json-c>=0.7
BUILDLINK_PKGSRCDIR.json-c?=	../../category/json
.endif	# JSON_C_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
