# $NetBSD: buildlink3.mk,v 1.5 2007/12/04 04:17:22 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EET_BUILDLINK3_MK:=	${EET_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	eet
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Neet}
BUILDLINK_PACKAGES+=	eet
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}eet

.if ${EET_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.eet+=	eet>=0.9.10.041
BUILDLINK_PKGSRCDIR.eet?=	../../wip/eet
.endif	# EET_BUILDLINK3_MK

.include "../../graphics/jpeg/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
