# $NetBSD: buildlink3.mk,v 1.1 2004/09/16 13:40:56 airhead Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EET_BUILDLINK3_MK:=	${JPEG_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	eet
.endif

BUILDLINK_PACKAGES+=	eet

.if !empty(EET_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.eet+=		eet>=0.9.9
BUILDLINK_PKGSRCDIR.eet?=	../../wip/eet
.endif	# EET_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
