# $NetBSD: Makefile,v 1.10 2008/06/29 21:34:31 shindenmorr Exp $
#

DISTNAME=	eet-1.0.1
CATEGORIES=	misc
MASTER_SITES=	http://download.enlightenment.org/snapshots/2008-05-19/ \
		http://www.yazzy.org/pkgsrc/e17/ \
		http://jfranz.users.bsdprojects.net/pkgsrc/e17/

MAINTAINER=	yazzy@yazzy.org
HOMEPAGE=	http://enlightenment.org/
COMMENT=	Distribution Container Library and Tools

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_TOOLS=	gmake pkg-config

.include "../../graphics/jpeg/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
