# $NetBSD$

DISTNAME=	gpkit-0.3.4.7
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_PYPI:=g/gpkit/}

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	https://github.com/hoburg/gpkit
COMMENT=	Defining and manipulating geometric programming models
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/python/distutils.mk"
.include "../../math/py-numpy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
