
SEPARATE (C83022G0M)
PROCEDURE TEMPLATE (X : IN INTEGER := A;
                    Y : IN OUT INTEGER) IS
BEGIN  -- TEMPLATE
     IF X /= IDENT_INT(2) THEN
          FAILED ("INCORRECT RESULTS FOR VARIABLE - 30");
     END IF;

     IF Y /= IDENT_INT(5) THEN
          FAILED ("INCORRECT RESULTS FOR VARIABLE - 31");
     END IF;

     Y := IDENT_INT(2 * X);

     IF C83022G0M.A /= IDENT_INT(2) THEN
          FAILED ("INCORRECT RESULTS FOR OUTER HOMOGRAPH - " &
                  "32");
     END IF;
END TEMPLATE;
