# $NetBSD: buildlink3.mk,v 1.2 2009/03/20 19:43:51 jsonn Exp $

BUILDLINK_TREE+=	omniORB

.if !defined(OMNIORB_BUILDLINK3_MK)
OMNIORB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.omniORB+=	omniORB>=4.1.2
BUILDLINK_PKGSRCDIR.omniORB?=	../../wip/omniORB
.endif # OMNIORB_BUILDLINK3_MK

BUILDLINK_TREE+=	-omniORB
