# $NetBSD: buildlink3.mk,v 1.1 2008/08/20 08:12:57 tonnerre Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OMNIORB_BUILDLINK3_MK:=	${OMNIORB_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	omniORB
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NomniORB}
BUILDLINK_PACKAGES+=	omniORB
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}omniORB

.if ${OMNIORB_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.omniORB+=	omniORB>=4.1.2
BUILDLINK_PKGSRCDIR.omniORB?=	../../wip/omniORB
.endif	# OMNIORB_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
