# $NetBSD: buildlink3.mk,v 1.5 2012/03/04 07:19:03 phonohawk Exp $

BUILDLINK_TREE+=	hs-SHA

.if !defined(HS_SHA_BUILDLINK3_MK)
HS_SHA_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.hs-SHA+=	hs-SHA>=1.5.0
BUILDLINK_PKGSRCDIR.hs-SHA?=	../../wip/hs-SHA

.endif	# HS_SHA_BUILDLINK3_MK

BUILDLINK_TREE+=	-hs-SHA
