# $NetBSD: Makefile,v 1.5 2012/03/04 07:19:03 phonohawk Exp $
#

DISTNAME=	SHA-1.5.0.0
CATEGORIES=	security

MAINTAINER=	pho@cielonegro.org
COMMENT=	Haskell implementation of SHA digest functions
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
