# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/03/17 02:53:59 phonohawk Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
P5_SUB_RECURSIVE_BUILDLINK3_MK:=	${P5_SUB_RECURSIVE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	p5-Sub-Recursive
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Sub-Recursive}
BUILDLINK_PACKAGES+=	p5-Sub-Recursive
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}p5-Sub-Recursive

.if ${P5_SUB_RECURSIVE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.p5-Sub-Recursive+=	p5-Sub-Recursive>=0.03
BUILDLINK_PKGSRCDIR.p5-Sub-Recursive?=	../../wip/p5-Sub-Recursive
.endif	# P5_SUB_RECURSIVE_BUILDLINK3_MK

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH:S/+$//}
