# $NetBSD$

DISTNAME=	prawn-templates-0.1.2
CATEGORIES=	print

MAINTAINER=	cfkoch@edgebsd.org
HOMEPAGE=	http://prawnpdf.org/
COMMENT=	Experimental extraction of template features from Prawn
LICENSE=	ruby-license

DEPENDS+=	${RUBY_PKGPREFIX}-prawn>=1.3.0:../../print/ruby-prawn
DEPENDS+=	${RUBY_PKGPREFIX}-pdf-reader>=2.0.0:../../print/ruby-pdf-reader

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
