# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/08/08 19:01:52 larnor Exp $

BUILDLINK_DEPMETHOD.xf86bigfontproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XF86BIGFONTPROTO_BUILDLINK3_MK:=	${XF86BIGFONTPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	xf86bigfontproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxf86bigfontproto}
BUILDLINK_PACKAGES+=	xf86bigfontproto

.if !empty(XF86BIGFONTPROTO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.xf86bigfontproto+=	xf86bigfontproto>=1.1
BUILDLINK_PKGSRCDIR.xf86bigfontproto?=	../../wip/xf86bigfontproto
.endif	# XF86BIGFONTPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
