# $NetBSD: Makefile,v 1.1 2005/12/29 10:27:11 martijnb Exp $
#

DISTNAME=		par2cmdline-0.4
CATEGORIES=		misc
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=parchive/}

MAINTAINER=		martijn.van.buul@gmail.com
HOMEPAGE=		http://parchive.sourceforge.net/
COMMENT=		Commandline PAR2 'party volume set' tool

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
