# $NetBSD: Makefile.common,v 1.3 2005/04/11 21:15:52 tvierling Exp $

DISTNAME=	smtprc-0.9.7
PKGNAME=	smtprc-0.9.7b
WRKSRC=		${WRKDIR}/smtprc
CATEGORIES=	net mail
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=smtprc/}
EXTRACT_SUFX=	.tgz

MAINTAINER=	adrianp@stindustries.net
HOMEPAGE= 	http://irc.warg.co.uk/smtprc-website/index.html

USE_PKGINSTALL=		YES
PKG_SYSCONFSUBDIR=	smtprc
