# $NetBSD: buildlink3.mk,v 1.1 2006/09/12 09:40:29 neimal Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBNJB_BUILDLINK3_MK:=	${LIBNJB_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libnjb
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibnjb}
BUILDLINK_PACKAGES+=	libnjb
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libnjb

.if ${LIBNJB_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libnjb+=	libnjb>=2.2.5
BUILDLINK_PKGSRCDIR.libnjb?=	../../wip/libnjb
.endif	# LIBNJB_BUILDLINK3_MK

.include "../../devel/libusb/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
