# $NetBSD$

BUILDLINK_TREE+=	SSVMenuSystem

.if !defined(SSVMENUSYSTEM_BUILDLINK3_MK)
SSVMENUSYSTEM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVMenuSystem+=	SSVMenuSystem>=20130713
BUILDLINK_PKGSRCDIR.SSVMenuSystem?=	../../wip/SSVMenuSystem

SSVMENUSYSTEM_MODULE=	${PREFIX}/lib/cmake/SSVMenuSystem

.endif	# SSVMENUSYSTEM_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVMenuSystem
