# $NetBSD$
# _anaconda_depends 2024.02 is missing
# _libgcc_mutex 0.1 is missing
# _openmp_mutex 5.1 is missing
# abseil-cpp 20211102.0 is missing
DEPENDS+=	${PYPKGPREFIX}-aiohttp-[0-9]*:../../www/py-aiohttp  # aiohttp 3.9.3
# aioitertools 0.7.1 is missing
DEPENDS+=	${PYPKGPREFIX}-aiosignal-[0-9]*:../../devel/py-aiosignal  # aiosignal 1.2.0
DEPENDS+=	${PYPKGPREFIX}-alabaster-[0-9]*:../../textproc/py-alabaster  # alabaster 0.7.12
DEPENDS+=	${PYPKGPREFIX}-altair-[0-9]*:../../wip/py-altair  # altair 5.0.1
# anaconda-anon-usage 0.4.3 is missing
# anaconda-catalogs 0.2.0 is missing
# anaconda-client 1.12.3 is missing
# anaconda-cloud-auth 0.1.4 is missing
# anaconda-navigator 2.5.2 is missing
# anaconda-project 0.11.1 is missing
DEPENDS+=	${PYPKGPREFIX}-anyio-[0-9]*:../../devel/py-anyio  # anyio 4.2.0
# aom 3.6.0 is missing
DEPENDS+=	${PYPKGPREFIX}-appdirs-[0-9]*:../../devel/py-appdirs  # appdirs 1.4.4
# archspec 0.2.1 is missing
DEPENDS+=	${PYPKGPREFIX}-argon2-cffi-[0-9]*:../../security/py-argon2-cffi  # argon2-cffi 21.3.0
DEPENDS+=	${PYPKGPREFIX}-argon2-cffi-bindings-[0-9]*:../../security/py-argon2-cffi-bindings  # argon2-cffi-bindings 21.2.0
DEPENDS+=	${PYPKGPREFIX}-arrow-[0-9]*:../../time/py-arrow  # arrow 1.2.3
# arrow-cpp 14.0.2 is missing
DEPENDS+=	${PYPKGPREFIX}-astroid-[0-9]*:../../devel/py-astroid  # astroid 2.14.2
DEPENDS+=	${PYPKGPREFIX}-astropy-[0-9]*:../../math/py-astropy  # astropy 5.3.4
DEPENDS+=	${PYPKGPREFIX}-asttokens-[0-9]*:../../lang/py-asttokens  # asttokens 2.0.5
DEPENDS+=	${PYPKGPREFIX}-async-lru-[0-9]*:../../devel/py-async-lru  # async-lru 2.0.4
DEPENDS+=	${PYPKGPREFIX}-atomicwrites-[0-9]*:../../devel/py-atomicwrites  # atomicwrites 1.4.0
DEPENDS+=	${PYPKGPREFIX}-attrs-[0-9]*:../../devel/py-attrs  # attrs 23.1.0
DEPENDS+=	${PYPKGPREFIX}-automat-[0-9]*:../../devel/py-automat  # automat 20.2.0
DEPENDS+=	${PYPKGPREFIX}-autopep8-[0-9]*:../../devel/py-autopep8  # autopep8 1.6.0
# aws-c-auth 0.6.19 is missing
# aws-c-cal 0.5.20 is missing
# aws-c-common 0.8.5 is missing
# aws-c-compression 0.2.16 is missing
# aws-c-event-stream 0.2.15 is missing
# aws-c-http 0.6.25 is missing
# aws-c-io 0.13.10 is missing
# aws-c-mqtt 0.7.13 is missing
# aws-c-s3 0.1.51 is missing
# aws-c-sdkutils 0.1.6 is missing
# aws-checksums 0.1.13 is missing
# aws-crt-cpp 0.18.16 is missing
# aws-sdk-cpp 1.10.55 is missing
DEPENDS+=	${PYPKGPREFIX}-babel-[0-9]*:../../devel/py-babel  # babel 2.11.0
DEPENDS+=	${PYPKGPREFIX}-backports-[0-9]*:../../devel/py-backports  # backports 1.1
# backports.functools_lru_cache 1.6.4 is missing
# backports.tempfile 1.0 is missing
# backports.weakref 1.0.post1 is missing
DEPENDS+=	bcrypt-[0-9]*:../../security/bcrypt  # bcrypt 3.2.0
DEPENDS+=	${PYPKGPREFIX}-beautifulsoup4-[0-9]*:../../www/py-beautifulsoup4  # beautifulsoup4 4.12.2
DEPENDS+=	${PYPKGPREFIX}-binaryornot-[0-9]*:../../devel/py-binaryornot  # binaryornot 0.4.4
DEPENDS+=	${PYPKGPREFIX}-black-[0-9]*:../../textproc/py-black  # black 23.11.0
DEPENDS+=	blas-[0-9]*:../../math/blas  # blas 1.0
DEPENDS+=	${PYPKGPREFIX}-bleach-[0-9]*:../../www/py-bleach  # bleach 4.1.0
DEPENDS+=	${PYPKGPREFIX}-blinker-[0-9]*:../../devel/py-blinker  # blinker 1.6.2
DEPENDS+=	blosc-[0-9]*:../../devel/blosc  # blosc 1.21.3
DEPENDS+=	${PYPKGPREFIX}-bokeh-[0-9]*:../../wip/py-bokeh  # bokeh 3.3.4
DEPENDS+=	${PYPKGPREFIX}-boltons-[0-9]*:../../devel/py-boltons  # boltons 23.0.0
# boost-cpp 1.82.0 is missing
DEPENDS+=	${PYPKGPREFIX}-botocore-[0-9]*:../../net/py-botocore  # botocore 1.31.64
DEPENDS+=	${PYPKGPREFIX}-bottleneck-[0-9]*:../../math/py-bottleneck  # bottleneck 1.3.7
DEPENDS+=	brotli-[0-9]*:../../archivers/brotli  # brotli 1.0.9
# brotli-bin 1.0.9 is missing
# brotli-python 1.0.9 is missing
# brunsli 0.1 is missing
DEPENDS+=	bzip2-[0-9]*:../../archivers/bzip2  # bzip2 1.0.8
# c-ares 1.19.1 is missing
# c-blosc2 2.12.0 is missing
DEPENDS+=	ca-certificates-[0-9]*:../../security/ca-certificates  # ca-certificates 2023.12.12
DEPENDS+=	${PYPKGPREFIX}-cachetools-[0-9]*:../../devel/py-cachetools  # cachetools 4.2.2
DEPENDS+=	${PYPKGPREFIX}-certifi-[0-9]*:../../security/py-certifi  # certifi 2024.2.2
DEPENDS+=	${PYPKGPREFIX}-cffi-[0-9]*:../../devel/py-cffi  # cffi 1.16.0
DEPENDS+=	cfitsio-[0-9]*:../../devel/cfitsio  # cfitsio 3.470
DEPENDS+=	${PYPKGPREFIX}-chardet-[0-9]*:../../converters/py-chardet  # chardet 4.0.0
DEPENDS+=	charls-[0-9]*:../../graphics/charls  # charls 2.2.0
DEPENDS+=	${PYPKGPREFIX}-charset-normalizer-[0-9]*:../../converters/py-charset-normalizer  # charset-normalizer 2.0.4
DEPENDS+=	${PYPKGPREFIX}-click-[0-9]*:../../devel/py-click  # click 8.1.7
DEPENDS+=	${PYPKGPREFIX}-cloudpickle-[0-9]*:../../wip/py-cloudpickle  # cloudpickle 2.2.1
# clyent 1.2.2 is missing
DEPENDS+=	${PYPKGPREFIX}-colorama-[0-9]*:../../comms/py-colorama  # colorama 0.4.6
DEPENDS+=	${PYPKGPREFIX}-colorcet-[0-9]*:../../wip/py-colorcet  # colorcet 3.0.1
DEPENDS+=	${PYPKGPREFIX}-comm-[0-9]*:../../net/py-comm  # comm 0.1.2
# conda-build 24.1.2 is missing
# conda-content-trust 0.2.0 is missing
# conda-index 0.4.0 is missing
# conda-libmamba-solver 24.1.0 is missing
# conda-pack 0.6.0 is missing
# conda-package-handling 2.2.0 is missing
# conda-package-streaming 0.9.0 is missing
# conda-repo-cli 1.0.75 is missing
# conda-token 0.4.0 is missing
# conda-verify 3.4.2 is missing
DEPENDS+=	${PYPKGPREFIX}-constantly-[0-9]*:../../devel/py-constantly  # constantly 23.10.4
DEPENDS+=	${PYPKGPREFIX}-contourpy-[0-9]*:../../graphics/py-contourpy  # contourpy 1.2.0
DEPENDS+=	${PYPKGPREFIX}-cookiecutter-[0-9]*:../../devel/py-cookiecutter  # cookiecutter 2.5.0
DEPENDS+=	${PYPKGPREFIX}-cryptography-[0-9]*:../../security/py-cryptography  # cryptography 42.0.2
DEPENDS+=	${PYPKGPREFIX}-cssselect-[0-9]*:../../textproc/py-cssselect  # cssselect 1.2.0
DEPENDS+=	curl-[0-9]*:../../www/curl  # curl 8.5.0
DEPENDS+=	${PYPKGPREFIX}-cycler-[0-9]*:../../graphics/py-cycler  # cycler 0.11.0
DEPENDS+=	cyrus-sasl-[0-9]*:../../security/cyrus-sasl  # cyrus-sasl 2.1.28
DEPENDS+=	${PYPKGPREFIX}-cytoolz-[0-9]*:../../devel/py-cytoolz  # cytoolz 0.12.2
DEPENDS+=	${PYPKGPREFIX}-dask-[0-9]*:../../wip/py-dask  # dask 2023.11.0
# dask-core 2023.11.0 is missing
DEPENDS+=	dav1d-[0-9]*:../../multimedia/dav1d  # dav1d 1.2.1
DEPENDS+=	dbus-[0-9]*:../../sysutils/dbus  # dbus 1.13.18
DEPENDS+=	${PYPKGPREFIX}-debugpy-[0-9]*:../../devel/py-debugpy  # debugpy 1.6.7
DEPENDS+=	${PYPKGPREFIX}-decorator-[0-9]*:../../devel/py-decorator  # decorator 5.1.1
DEPENDS+=	${PYPKGPREFIX}-defusedxml-[0-9]*:../../textproc/py-defusedxml  # defusedxml 0.7.1
DEPENDS+=	${PYPKGPREFIX}-diff-match-patch-[0-9]*:../../textproc/py-diff-match-patch  # diff-match-patch 20200713
DEPENDS+=	${PYPKGPREFIX}-dill-[0-9]*:../../textproc/py-dill  # dill 0.3.7
DEPENDS+=	${PYPKGPREFIX}-distributed-[0-9]*:../../wip/py-distributed  # distributed 2023.11.0
DEPENDS+=	${PYPKGPREFIX}-distro-[0-9]*:../../devel/py-distro  # distro 1.8.0
DEPENDS+=	${PYPKGPREFIX}-docstring-to-markdown-[0-9]*:../../textproc/py-docstring-to-markdown  # docstring-to-markdown 0.11
DEPENDS+=	${PYPKGPREFIX}-docutils-[0-9]*:../../textproc/py-docutils  # docutils 0.18.1
DEPENDS+=	${PYPKGPREFIX}-entrypoints-[0-9]*:../../devel/py-entrypoints  # entrypoints 0.4
# et_xmlfile 1.1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-executing-[0-9]*:../../lang/py-executing  # executing 0.8.3
DEPENDS+=	expat-[0-9]*:../../textproc/expat  # expat 2.5.0
DEPENDS+=	${PYPKGPREFIX}-filelock-[0-9]*:../../devel/py-filelock  # filelock 3.13.1
DEPENDS+=	${PYPKGPREFIX}-flake8-[0-9]*:../../devel/py-flake8  # flake8 6.0.0
DEPENDS+=	${PYPKGPREFIX}-flask-[0-9]*:../../www/py-flask  # flask 2.2.5
# fmt 9.1.0 is missing
DEPENDS+=	fontconfig-[0-9]*:../../fonts/fontconfig  # fontconfig 2.14.1
DEPENDS+=	${PYPKGPREFIX}-fonttools-[0-9]*:../../fonts/py-fonttools  # fonttools 4.25.0
DEPENDS+=	freetype-[0-9]*:../../graphics/freetype  # freetype 2.12.1
DEPENDS+=	${PYPKGPREFIX}-frozenlist-[0-9]*:../../devel/py-frozenlist  # frozenlist 1.4.0
DEPENDS+=	${PYPKGPREFIX}-fsspec-[0-9]*:../../sysutils/py-fsspec  # fsspec 2023.10.0
DEPENDS+=	${PYPKGPREFIX}-future-[0-9]*:../../devel/py-future  # future 0.18.3
DEPENDS+=	gflags-[0-9]*:../../devel/gflags  # gflags 2.2.2
DEPENDS+=	giflib-[0-9]*:../../graphics/giflib  # giflib 5.2.1
DEPENDS+=	${PYPKGPREFIX}-gitdb-[0-9]*:../../devel/py-gitdb  # gitdb 4.0.7
DEPENDS+=	${PYPKGPREFIX}-gitpython-[0-9]*:../../devel/py-gitpython  # gitpython 3.1.37
DEPENDS+=	glib-[0-9]*:../../devel/glib  # glib 2.78.4
# glib-tools 2.78.4 is missing
# glog 0.5.0 is missing
DEPENDS+=	gmp-[0-9]*:../../devel/gmp  # gmp 6.2.1
DEPENDS+=	${PYPKGPREFIX}-gmpy2-[0-9]*:../../math/py-gmpy2  # gmpy2 2.1.2
DEPENDS+=	${PYPKGPREFIX}-greenlet-[0-9]*:../../devel/py-greenlet  # greenlet 3.0.1
# grpc-cpp 1.48.2 is missing
# gst-plugins-base 1.14.1 is missing
# gstreamer 1.14.1 is missing
DEPENDS+=	${PYPKGPREFIX}-h5py-[0-9]*:../../devel/py-h5py  # h5py 3.9.0
DEPENDS+=	hdf5-[0-9]*:../../devel/hdf5  # hdf5 1.12.1
DEPENDS+=	${PYPKGPREFIX}-HeapDict-[0-9]*:../../wip/py-HeapDict  # heapdict 1.0.1
# hvplot 0.9.2 is missing
DEPENDS+=	${PYPKGPREFIX}-hyperlink-[0-9]*:../../www/py-hyperlink  # hyperlink 21.0.0
DEPENDS+=	icu-[0-9]*:../../textproc/icu  # icu 73.1
DEPENDS+=	${PYPKGPREFIX}-idna-[0-9]*:../../www/py-idna  # idna 3.4
# imagecodecs 2023.1.23 is missing
DEPENDS+=	${PYPKGPREFIX}-imageio-[0-9]*:../../graphics/py-imageio  # imageio 2.33.1
DEPENDS+=	${PYPKGPREFIX}-imagesize-[0-9]*:../../graphics/py-imagesize  # imagesize 1.4.1
# imbalanced-learn 0.11.0 is missing
DEPENDS+=	${PYPKGPREFIX}-importlib-metadata-[0-9]*:../../devel/py-importlib-metadata  # importlib-metadata 7.0.1
# importlib_metadata 7.0.1 is missing
DEPENDS+=	${PYPKGPREFIX}-incremental-[0-9]*:../../devel/py-incremental  # incremental 22.10.0
DEPENDS+=	${PYPKGPREFIX}-inflection-[0-9]*:../../textproc/py-inflection  # inflection 0.5.1
DEPENDS+=	${PYPKGPREFIX}-iniconfig-[0-9]*:../../devel/py-iniconfig  # iniconfig 1.1.1
# intake 0.6.8 is missing
# intel-openmp 2023.1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-intervaltree-[0-9]*:../../devel/py-intervaltree  # intervaltree 3.1.0
DEPENDS+=	${PYPKGPREFIX}-ipykernel-[0-9]*:../../devel/py-ipykernel  # ipykernel 6.28.0
DEPENDS+=	${PYPKGPREFIX}-ipython-[0-9]*:../../devel/py-ipython  # ipython 8.20.0
DEPENDS+=	${PYPKGPREFIX}-ipython_genutils-[0-9]*:../../devel/py-ipython_genutils  # ipython_genutils 0.2.0
DEPENDS+=	${PYPKGPREFIX}-ipywidgets-[0-9]*:../../www/py-ipywidgets  # ipywidgets 7.6.5
DEPENDS+=	${PYPKGPREFIX}-isort-[0-9]*:../../devel/py-isort  # isort 5.9.3
DEPENDS+=	${PYPKGPREFIX}-itemadapter-[0-9]*:../../textproc/py-itemadapter  # itemadapter 0.3.0
DEPENDS+=	${PYPKGPREFIX}-itemloaders-[0-9]*:../../textproc/py-itemloaders  # itemloaders 1.1.0
DEPENDS+=	${PYPKGPREFIX}-itsdangerous-[0-9]*:../../security/py-itsdangerous  # itsdangerous 2.0.1
DEPENDS+=	${PYPKGPREFIX}-jaraco.classes-[0-9]*:../../devel/py-jaraco.classes  # jaraco.classes 3.2.1
DEPENDS+=	${PYPKGPREFIX}-jedi-[0-9]*:../../editors/py-jedi  # jedi 0.18.1
DEPENDS+=	${PYPKGPREFIX}-jeepney-[0-9]*:../../sysutils/py-jeepney  # jeepney 0.7.1
DEPENDS+=	${PYPKGPREFIX}-jellyfish-[0-9]*:../../textproc/py-jellyfish  # jellyfish 1.0.1
DEPENDS+=	${PYPKGPREFIX}-jinja2-[0-9]*:../../textproc/py-jinja2  # jinja2 3.1.3
DEPENDS+=	${PYPKGPREFIX}-jmespath-[0-9]*:../../textproc/py-jmespath  # jmespath 1.0.1
DEPENDS+=	${PYPKGPREFIX}-joblib-[0-9]*:../../devel/py-joblib  # joblib 1.2.0
DEPENDS+=	jpeg-[0-9]*:../../graphics/jpeg  # jpeg 9e
DEPENDS+=	jq-[0-9]*:../../devel/jq  # jq 1.6
DEPENDS+=	${PYPKGPREFIX}-json5-[0-9]*:../../textproc/py-json5  # json5 0.9.6
DEPENDS+=	${PYPKGPREFIX}-jsonpatch-[0-9]*:../../wip/py-jsonpatch  # jsonpatch 1.32
DEPENDS+=	${PYPKGPREFIX}-jsonpointer-[0-9]*:../../wip/py-jsonpointer  # jsonpointer 2.1
DEPENDS+=	${PYPKGPREFIX}-jsonschema-[0-9]*:../../textproc/py-jsonschema  # jsonschema 4.19.2
DEPENDS+=	${PYPKGPREFIX}-jsonschema-specifications-[0-9]*:../../textproc/py-jsonschema-specifications  # jsonschema-specifications 2023.7.1
# jupyter 1.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-jupyter-lsp-[0-9]*:../../www/py-jupyter-lsp  # jupyter-lsp 2.2.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_client-[0-9]*:../../devel/py-jupyter_client  # jupyter_client 8.6.0
# jupyter_console 6.6.3 is missing
DEPENDS+=	${PYPKGPREFIX}-jupyter_core-[0-9]*:../../devel/py-jupyter_core  # jupyter_core 5.5.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_events-[0-9]*:../../devel/py-jupyter_events  # jupyter_events 0.8.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_server-[0-9]*:../../www/py-jupyter_server  # jupyter_server 2.10.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_server_terminals-[0-9]*:../../comms/py-jupyter_server_terminals  # jupyter_server_terminals 0.4.4
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-[0-9]*:../../www/py-jupyterlab  # jupyterlab 4.0.11
# jupyterlab-variableinspector 3.1.0 is missing
# jupyterlab_pygments 0.1.2 is missing
# jupyterlab_server 2.25.1 is missing
# jupyterlab_widgets 3.0.9 is missing
DEPENDS+=	jxrlib-[0-9]*:../../graphics/jxrlib  # jxrlib 1.1
DEPENDS+=	${PYPKGPREFIX}-keyring-[0-9]*:../../security/py-keyring  # keyring 23.13.1
DEPENDS+=	${PYPKGPREFIX}-kiwisolver-[0-9]*:../../math/py-kiwisolver  # kiwisolver 1.4.4
DEPENDS+=	${PYPKGPREFIX}-krb5-[0-9]*:../../security/py-krb5  # krb5 1.20.1
DEPENDS+=	${PYPKGPREFIX}-lazy-object-proxy-[0-9]*:../../devel/py-lazy-object-proxy  # lazy-object-proxy 1.6.0
DEPENDS+=	${PYPKGPREFIX}-lazy_loader-[0-9]*:../../misc/py-lazy_loader  # lazy_loader 0.3
DEPENDS+=	lcms2-[0-9]*:../../graphics/lcms2  # lcms2 2.12
# ld_impl_linux-64 2.38 is missing
# lerc 3.0 is missing
DEPENDS+=	libaec-[0-9]*:../../archivers/libaec  # libaec 1.0.4
DEPENDS+=	libarchive-[0-9]*:../../archivers/libarchive  # libarchive 3.6.2
DEPENDS+=	libavif-[0-9]*:../../graphics/libavif  # libavif 0.11.1
# libboost 1.82.0 is missing
# libbrotlicommon 1.0.9 is missing
# libbrotlidec 1.0.9 is missing
# libbrotlienc 1.0.9 is missing
# libclang 14.0.6 is missing
# libclang13 14.0.6 is missing
DEPENDS+=	libcups-[0-9]*:../../print/libcups  # libcups 2.4.2
# libcurl 8.5.0 is missing
DEPENDS+=	libdeflate-[0-9]*:../../devel/libdeflate  # libdeflate 1.17
# libedit 3.1.20230828 is missing
DEPENDS+=	libev-[0-9]*:../../devel/libev  # libev 4.33
DEPENDS+=	libevent-[0-9]*:../../devel/libevent  # libevent 2.1.12
DEPENDS+=	libffi-[0-9]*:../../devel/libffi  # libffi 3.4.4
# libgcc-ng 11.2.0 is missing
# libgfortran-ng 11.2.0 is missing
# libgfortran5 11.2.0 is missing
# libglib 2.78.4 is missing
# libgomp 11.2.0 is missing
DEPENDS+=	libiconv-[0-9]*:../../converters/libiconv  # libiconv 1.16
# liblief 0.12.3 is missing
# libllvm14 14.0.6 is missing
# libmamba 1.5.6 is missing
# libmambapy 1.5.6 is missing
# libnghttp2 1.57.0 is missing
# libpng 1.6.39 is missing
# libpq 12.17 is missing
# libprotobuf 3.20.3 is missing
DEPENDS+=	libsodium-[0-9]*:../../security/libsodium  # libsodium 1.0.18
# libsolv 0.7.24 is missing
# libspatialindex 1.9.3 is missing
DEPENDS+=	libssh2-[0-9]*:../../security/libssh2  # libssh2 1.10.0
# libstdcxx-ng 11.2.0 is missing
DEPENDS+=	libthrift-[0-9]*:../../devel/libthrift  # libthrift 0.15.0
# libtiff 4.5.1 is missing
DEPENDS+=	libuuid-[0-9]*:../../devel/libuuid  # libuuid 1.41.5
# libwebp-base 1.3.2 is missing
DEPENDS+=	libxml2-[0-9]*:../../textproc/libxml2  # libxml2 2.10.4
DEPENDS+=	libxslt-[0-9]*:../../textproc/libxslt  # libxslt 1.1.37
# libzopfli 1.0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-linkify-it-py-[0-9]*:../../textproc/py-linkify-it-py  # linkify-it-py 2.0.0
DEPENDS+=	${PYPKGPREFIX}-llvmlite-[0-9]*:../../devel/py-llvmlite  # llvmlite 0.42.0
DEPENDS+=	${PYPKGPREFIX}-locket-[0-9]*:../../wip/py-locket  # locket 1.0.0
DEPENDS+=	${PYPKGPREFIX}-lxml-[0-9]*:../../textproc/py-lxml  # lxml 4.9.3
DEPENDS+=	lz4-[0-9]*:../../archivers/lz4  # lz4 4.3.2
# lz4-c 1.9.4 is missing
DEPENDS+=	lzo-[0-9]*:../../archivers/lzo  # lzo 2.10
DEPENDS+=	${PYPKGPREFIX}-markdown-[0-9]*:../../textproc/py-markdown  # markdown 3.4.1
DEPENDS+=	${PYPKGPREFIX}-markdown-it-py-[0-9]*:../../textproc/py-markdown-it-py  # markdown-it-py 2.2.0
DEPENDS+=	${PYPKGPREFIX}-markupsafe-[0-9]*:../../textproc/py-markupsafe  # markupsafe 2.1.3
DEPENDS+=	${PYPKGPREFIX}-matplotlib-[0-9]*:../../graphics/py-matplotlib  # matplotlib 3.8.0
# matplotlib-base 3.8.0 is missing
DEPENDS+=	${PYPKGPREFIX}-matplotlib-inline-[0-9]*:../../graphics/py-matplotlib-inline  # matplotlib-inline 0.1.6
DEPENDS+=	${PYPKGPREFIX}-mccabe-[0-9]*:../../devel/py-mccabe  # mccabe 0.7.0
DEPENDS+=	${PYPKGPREFIX}-mdit-py-plugins-[0-9]*:../../textproc/py-mdit-py-plugins  # mdit-py-plugins 0.3.0
DEPENDS+=	${PYPKGPREFIX}-mdurl-[0-9]*:../../www/py-mdurl  # mdurl 0.1.0
# menuinst 2.0.2 is missing
DEPENDS+=	${PYPKGPREFIX}-mistune-[0-9]*:../../textproc/py-mistune  # mistune 2.0.4
# mkl 2023.1.0 is missing
# mkl-service 2.4.0 is missing
# mkl_fft 1.3.8 is missing
# mkl_random 1.2.4 is missing
DEPENDS+=	${PYPKGPREFIX}-more-itertools-[0-9]*:../../devel/py-more-itertools  # more-itertools 10.1.0
DEPENDS+=	mpc-[0-9]*:../../audio/mpc  # mpc 1.1.0
DEPENDS+=	mpfr-[0-9]*:../../math/mpfr  # mpfr 4.0.2
DEPENDS+=	${PYPKGPREFIX}-mpmath-[0-9]*:../../math/py-mpmath  # mpmath 1.3.0
# msgpack-python 1.0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-multidict-[0-9]*:../../databases/py-multidict  # multidict 6.0.4
DEPENDS+=	${PYPKGPREFIX}-multipledispatch-[0-9]*:../../devel/py-multipledispatch  # multipledispatch 0.6.0
DEPENDS+=	${PYPKGPREFIX}-munkres-[0-9]*:../../math/py-munkres  # munkres 1.1.4
DEPENDS+=	${PYPKGPREFIX}-mypy-[0-9]*:../../lang/py-mypy  # mypy 1.8.0
DEPENDS+=	${PYPKGPREFIX}-mypy_extensions-[0-9]*:../../lang/py-mypy_extensions  # mypy_extensions 1.0.0
# mysql 5.7.24 is missing
# navigator-updater 0.4.0 is missing
DEPENDS+=	${PYPKGPREFIX}-nbclient-[0-9]*:../../www/py-nbclient  # nbclient 0.8.0
DEPENDS+=	${PYPKGPREFIX}-nbconvert-[0-9]*:../../www/py-nbconvert  # nbconvert 7.10.0
DEPENDS+=	${PYPKGPREFIX}-nbformat-[0-9]*:../../www/py-nbformat  # nbformat 5.9.2
DEPENDS+=	ncurses-[0-9]*:../../devel/ncurses  # ncurses 6.4
DEPENDS+=	${PYPKGPREFIX}-nest-asyncio-[0-9]*:../../devel/py-nest-asyncio  # nest-asyncio 1.6.0
DEPENDS+=	${PYPKGPREFIX}-networkx-[0-9]*:../../math/py-networkx  # networkx 3.1
DEPENDS+=	${PYPKGPREFIX}-nltk-[0-9]*:../../textproc/py-nltk  # nltk 3.8.1
DEPENDS+=	${PYPKGPREFIX}-notebook-[0-9]*:../../www/py-notebook  # notebook 7.0.8
# notebook-shim 0.2.3 is missing
DEPENDS+=	nspr-[0-9]*:../../devel/nspr  # nspr 4.35
DEPENDS+=	nss-[0-9]*:../../devel/nss  # nss 3.89.1
DEPENDS+=	${PYPKGPREFIX}-numexpr-[0-9]*:../../math/py-numexpr  # numexpr 2.8.7
DEPENDS+=	${PYPKGPREFIX}-numpy-[0-9]*:../../math/py-numpy  # numpy 1.26.4
# numpy-base 1.26.4 is missing
DEPENDS+=	${PYPKGPREFIX}-numpydoc-[0-9]*:../../textproc/py-numpydoc  # numpydoc 1.5.0
DEPENDS+=	oniguruma-[0-9]*:../../textproc/oniguruma  # oniguruma 6.9.7.1
DEPENDS+=	openjpeg-[0-9]*:../../graphics/openjpeg  # openjpeg 2.4.0
DEPENDS+=	${PYPKGPREFIX}-openpyxl-[0-9]*:../../textproc/py-openpyxl  # openpyxl 3.0.10
DEPENDS+=	orc-[0-9]*:../../devel/orc  # orc 1.7.4
DEPENDS+=	${PYPKGPREFIX}-overrides-[0-9]*:../../devel/py-overrides  # overrides 7.4.0
DEPENDS+=	${PYPKGPREFIX}-packaging-[0-9]*:../../devel/py-packaging  # packaging 23.1
DEPENDS+=	${PYPKGPREFIX}-pandas-[0-9]*:../../math/py-pandas  # pandas 2.1.4
DEPENDS+=	${PYPKGPREFIX}-pandocfilters-[0-9]*:../../textproc/py-pandocfilters  # pandocfilters 1.5.0
DEPENDS+=	${PYPKGPREFIX}-param-[0-9]*:../../wip/py-param  # param 2.0.2
DEPENDS+=	${PYPKGPREFIX}-parsel-[0-9]*:../../www/py-parsel  # parsel 1.8.1
DEPENDS+=	${PYPKGPREFIX}-parso-[0-9]*:../../lang/py-parso  # parso 0.8.3
DEPENDS+=	${PYPKGPREFIX}-partd-[0-9]*:../../wip/py-partd  # partd 1.4.1
DEPENDS+=	patch-[0-9]*:../../devel/patch  # patch 2.7.6
DEPENDS+=	patchelf-[0-9]*:../../devel/patchelf  # patchelf 0.17.2
DEPENDS+=	${PYPKGPREFIX}-pathspec-[0-9]*:../../devel/py-pathspec  # pathspec 0.10.3
DEPENDS+=	${PYPKGPREFIX}-patsy-[0-9]*:../../math/py-patsy  # patsy 0.5.3
DEPENDS+=	pcre2-[0-9]*:../../devel/pcre2  # pcre2 10.42
DEPENDS+=	${PYPKGPREFIX}-pexpect-[0-9]*:../../devel/py-pexpect  # pexpect 4.8.0
DEPENDS+=	${PYPKGPREFIX}-pickleshare-[0-9]*:../../databases/py-pickleshare  # pickleshare 0.7.5
DEPENDS+=	${PYPKGPREFIX}-Pillow-[0-9]*:../../graphics/py-Pillow  # pillow 10.2.0
DEPENDS+=	${PYPKGPREFIX}-pip-[0-9]*:../../devel/py-pip  # pip 23.3.1
# pkce 1.0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-pkginfo-[0-9]*:../../devel/py-pkginfo  # pkginfo 1.9.6
DEPENDS+=	${PYPKGPREFIX}-platformdirs-[0-9]*:../../misc/py-platformdirs  # platformdirs 3.10.0
DEPENDS+=	${PYPKGPREFIX}-pluggy-[0-9]*:../../devel/py-pluggy  # pluggy 1.0.0
DEPENDS+=	${PYPKGPREFIX}-ply-[0-9]*:../../devel/py-ply  # ply 3.11
DEPENDS+=	${PYPKGPREFIX}-prometheus_client-[0-9]*:../../net/py-prometheus_client  # prometheus_client 0.14.1
# prompt-toolkit 3.0.43 is missing
DEPENDS+=	${PYPKGPREFIX}-prompt_toolkit-[0-9]*:../../devel/py-prompt_toolkit  # prompt_toolkit 3.0.43
DEPENDS+=	${PYPKGPREFIX}-protego-[0-9]*:../../www/py-protego  # protego 0.1.16
DEPENDS+=	protobuf-[0-9]*:../../devel/protobuf  # protobuf 3.20.3
DEPENDS+=	${PYPKGPREFIX}-psutil-[0-9]*:../../sysutils/py-psutil  # psutil 5.9.0
DEPENDS+=	${PYPKGPREFIX}-ptyprocess-[0-9]*:../../sysutils/py-ptyprocess  # ptyprocess 0.7.0
# pure_eval 0.2.2 is missing
DEPENDS+=	${PYPKGPREFIX}-cpuinfo-[0-9]*:../../sysutils/py-cpuinfo  # py-cpuinfo 9.0.0
# py-lief 0.12.3 is missing
DEPENDS+=	${PYPKGPREFIX}-arrow-[0-9]*:../../time/py-arrow  # pyarrow 14.0.2
DEPENDS+=	${PYPKGPREFIX}-asn1-[0-9]*:../../security/py-asn1  # pyasn1 0.4.8
DEPENDS+=	${PYPKGPREFIX}-asn1-modules-[0-9]*:../../security/py-asn1-modules  # pyasn1-modules 0.2.8
# py-bind11-abi 4 is missing
DEPENDS+=	${PYPKGPREFIX}-codestyle-[0-9]*:../../devel/py-codestyle  # pycodestyle 2.10.0
DEPENDS+=	${PYPKGPREFIX}-cosat-[0-9]*:../../wip/py-cosat  # pycosat 0.6.6
DEPENDS+=	${PYPKGPREFIX}-cparser-[0-9]*:../../devel/py-cparser  # pycparser 2.21
DEPENDS+=	${PYPKGPREFIX}-ct-[0-9]*:../../wip/py-ct  # pyct 0.5.0
DEPENDS+=	${PYPKGPREFIX}-curl-[0-9]*:../../www/py-curl  # pycurl 7.45.2
DEPENDS+=	${PYPKGPREFIX}-pydantic-[0-9]*:../../devel/py-pydantic  # pydantic 1.10.12
# py-deck 0.8.0 is missing
DEPENDS+=	${PYPKGPREFIX}-pydispatcher-[0-9]*:../../devel/py-pydispatcher  # pydispatcher 2.0.5
DEPENDS+=	${PYPKGPREFIX}-docstyle-[0-9]*:../../devel/py-docstyle  # pydocstyle 6.3.0
DEPENDS+=	${PYPKGPREFIX}-pyerfa-[0-9]*:../../math/py-pyerfa  # pyerfa 2.0.0
DEPENDS+=	${PYPKGPREFIX}-flakes-[0-9]*:../../devel/py-flakes  # pyflakes 3.0.1
DEPENDS+=	${PYPKGPREFIX}-pygments-[0-9]*:../../textproc/py-pygments  # pygments 2.15.1
DEPENDS+=	${PYPKGPREFIX}-JWT-[0-9]*:../../textproc/py-JWT  # pyjwt 2.4.0
DEPENDS+=	${PYPKGPREFIX}-pylint-[0-9]*:../../devel/py-pylint  # pylint 2.16.2
DEPENDS+=	${PYPKGPREFIX}-pylint-venv-[0-9]*:../../wip/py-pylint-venv  # pylint-venv 2.3.0
DEPENDS+=	${PYPKGPREFIX}-pyls-spyder-[0-9]*:../../wip/py-pyls-spyder  # pyls-spyder 0.4.0
# py-odbc 5.0.1 is missing
DEPENDS+=	${PYPKGPREFIX}-OpenSSL-[0-9]*:../../security/py-OpenSSL  # pyopenssl 24.0.0
DEPENDS+=	${PYPKGPREFIX}-pyparsing-[0-9]*:../../devel/py-pyparsing  # pyparsing 3.0.9
# py-qt 5.15.10 is missing
# py-qt5-sip 12.13.0 is missing
# py-qtwebengine 5.15.10 is missing
DEPENDS+=	${PYPKGPREFIX}-Socks-[0-9]*:../../net/py-Socks  # pysocks 1.7.1
DEPENDS+=	${PYPKGPREFIX}-tables-[0-9]*:../../math/py-tables  # pytables 3.9.2
DEPENDS+=	${PYPKGPREFIX}-test-[0-9]*:../../devel/py-test  # pytest 7.4.0
# py-thon 3.11.7 is missing
DEPENDS+=	${PYPKGPREFIX}-dateutil-[0-9]*:../../time/py-dateutil  # python-dateutil 2.8.2
DEPENDS+=	${PYPKGPREFIX}-dotenv-[0-9]*:../../devel/py-dotenv  # python-dotenv 0.21.0
DEPENDS+=	${PYPKGPREFIX}-fastjsonschema-[0-9]*:../../textproc/py-fastjsonschema  # python-fastjsonschema 2.16.2
DEPENDS+=	${PYPKGPREFIX}-json-logger-[0-9]*:../../textproc/py-json-logger  # python-json-logger 2.0.7
DEPENDS+=	${PYPKGPREFIX}-libarchive-c-[0-9]*:../../archivers/py-libarchive-c  # python-libarchive-c 2.9
DEPENDS+=	${PYPKGPREFIX}-lmdb-[0-9]*:../../databases/py-lmdb  # python-lmdb 1.4.1
DEPENDS+=	${PYPKGPREFIX}-lsp-black-[0-9]*:../../wip/py-lsp-black  # python-lsp-black 1.2.1
DEPENDS+=	${PYPKGPREFIX}-lsp-jsonrpc-[0-9]*:../../textproc/py-lsp-jsonrpc  # python-lsp-jsonrpc 1.0.0
DEPENDS+=	${PYPKGPREFIX}-lsp-server-[0-9]*:../../lang/py-lsp-server  # python-lsp-server 1.7.2
DEPENDS+=	${PYPKGPREFIX}-slugify-[0-9]*:../../devel/py-slugify  # python-slugify 5.0.2
DEPENDS+=	${PYPKGPREFIX}-snappy-[0-9]*:../../devel/py-snappy  # python-snappy 0.6.1
DEPENDS+=	${PYPKGPREFIX}-tzdata-[0-9]*:../../time/py-tzdata  # python-tzdata 2023.3
DEPENDS+=	${PYPKGPREFIX}-toolconfig-[0-9]*:../../devel/py-toolconfig  # pytoolconfig 1.2.6
DEPENDS+=	${PYPKGPREFIX}-pytz-[0-9]*:../../time/py-pytz  # pytz 2023.3.post1
# py-viz_comms 3.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-pywavelets-[0-9]*:../../math/py-pywavelets  # pywavelets 1.5.0
DEPENDS+=	${PYPKGPREFIX}-xdg-[0-9]*:../../devel/py-xdg  # pyxdg 0.27
DEPENDS+=	${PYPKGPREFIX}-yaml-[0-9]*:../../textproc/py-yaml  # pyyaml 6.0.1
DEPENDS+=	${PYPKGPREFIX}-zmq-[0-9]*:../../net/py-zmq  # pyzmq 25.1.2
DEPENDS+=	${PYPKGPREFIX}-qdarkstyle-[0-9]*:../../wip/py-qdarkstyle  # qdarkstyle 3.0.2
# qt-main 5.15.2 is missing
# qt-webengine 5.15.9 is missing
DEPENDS+=	${PYPKGPREFIX}-qtawesome-[0-9]*:../../wip/py-qtawesome  # qtawesome 1.2.2
DEPENDS+=	${PYPKGPREFIX}-qtconsole-[0-9]*:../../wip/py-qtconsole  # qtconsole 5.4.2
DEPENDS+=	${PYPKGPREFIX}-QtPy-[0-9]*:../../wip/py-qtpy  # qtpy 2.4.1
DEPENDS+=	${PYPKGPREFIX}-queuelib-[0-9]*:../../devel/py-queuelib  # queuelib 1.6.2
DEPENDS+=	re2-[0-9]*:../../devel/re2  # re2 2022.04.01
DEPENDS+=	readline-[0-9]*:../../devel/readline  # readline 8.2
DEPENDS+=	${PYPKGPREFIX}-referencing-[0-9]*:../../textproc/py-referencing  # referencing 0.30.2
DEPENDS+=	${PYPKGPREFIX}-regex-[0-9]*:../../textproc/py-regex  # regex 2023.10.3
DEPENDS+=	reproc-[0-9]*:../../wip/reproc  # reproc 14.2.4
# reproc-cpp 14.2.4 is missing
DEPENDS+=	${PYPKGPREFIX}-requests-[0-9]*:../../devel/py-requests  # requests 2.31.0
DEPENDS+=	${PYPKGPREFIX}-requests-file-[0-9]*:../../devel/py-requests-file  # requests-file 1.5.1
DEPENDS+=	${PYPKGPREFIX}-requests-toolbelt-[0-9]*:../../devel/py-requests-toolbelt  # requests-toolbelt 1.0.0
DEPENDS+=	${PYPKGPREFIX}-rfc3339-validator-[0-9]*:../../time/py-rfc3339-validator  # rfc3339-validator 0.1.4
DEPENDS+=	${PYPKGPREFIX}-rfc3986-validator-[0-9]*:../../www/py-rfc3986-validator  # rfc3986-validator 0.1.1
DEPENDS+=	${PYPKGPREFIX}-rich-[0-9]*:../../comms/py-rich  # rich 13.3.5
DEPENDS+=	${PYPKGPREFIX}-rope-[0-9]*:../../devel/py-rope  # rope 1.7.0
DEPENDS+=	${PYPKGPREFIX}-rpds-py-[0-9]*:../../devel/py-rpds-py  # rpds-py 0.10.6
DEPENDS+=	${PYPKGPREFIX}-rtree-[0-9]*:../../wip/py-rtree  # rtree 1.0.1
# ruamel.yaml 0.17.21 is missing
# ruamel_yaml 0.17.21 is missing
# s2n 1.3.27 is missing
DEPENDS+=	${PYPKGPREFIX}-scikit-image-[0-9]*:../../math/py-scikit-image  # scikit-image 0.22.0
DEPENDS+=	${PYPKGPREFIX}-scikit-learn-[0-9]*:../../math/py-scikit-learn  # scikit-learn 1.2.2
DEPENDS+=	${PYPKGPREFIX}-scipy-[0-9]*:../../math/py-scipy  # scipy 1.11.4
DEPENDS+=	${PYPKGPREFIX}-scrapy-[0-9]*:../../www/py-scrapy  # scrapy 2.8.0
DEPENDS+=	${PYPKGPREFIX}-seaborn-[0-9]*:../../graphics/py-seaborn  # seaborn 0.12.2
DEPENDS+=	${PYPKGPREFIX}-secretstorage-[0-9]*:../../security/py-secretstorage  # secretstorage 3.3.1
DEPENDS+=	${PYPKGPREFIX}-semver-[0-9]*:../../devel/py-semver  # semver 2.13.0
DEPENDS+=	${PYPKGPREFIX}-Send2Trash-[0-9]*:../../sysutils/py-Send2Trash  # send2trash 1.8.2
DEPENDS+=	${PYPKGPREFIX}-service_identity-[0-9]*:../../security/py-service_identity  # service_identity 18.1.0
DEPENDS+=	${PYPKGPREFIX}-setuptools-[0-9]*:../../devel/py-setuptools  # setuptools 68.2.2
# sip 6.7.12 is missing
DEPENDS+=	${PYPKGPREFIX}-six-[0-9]*:../../lang/py-six  # six 1.16.0
# smart_open 5.2.1 is missing
DEPENDS+=	${PYPKGPREFIX}-smmap-[0-9]*:../../devel/py-smmap  # smmap 4.0.0
DEPENDS+=	${PYPKGPREFIX}-snappy-[0-9]*:../../devel/py-snappy  # snappy 1.1.10
DEPENDS+=	${PYPKGPREFIX}-sniffio-[0-9]*:../../misc/py-sniffio  # sniffio 1.3.0
DEPENDS+=	${PYPKGPREFIX}-snowballstemmer-[0-9]*:../../textproc/py-snowballstemmer  # snowballstemmer 2.2.0
DEPENDS+=	${PYPKGPREFIX}-sortedcontainers-[0-9]*:../../devel/py-sortedcontainers  # sortedcontainers 2.4.0
DEPENDS+=	${PYPKGPREFIX}-soupsieve-[0-9]*:../../www/py-soupsieve  # soupsieve 2.5
DEPENDS+=	${PYPKGPREFIX}-sphinx-[0-9]*:../../textproc/py-sphinx  # sphinx 5.0.2
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-applehelp-[0-9]*:../../textproc/py-sphinxcontrib-applehelp  # sphinxcontrib-applehelp 1.0.2
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-devhelp-[0-9]*:../../textproc/py-sphinxcontrib-devhelp  # sphinxcontrib-devhelp 1.0.2
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-htmlhelp-[0-9]*:../../textproc/py-sphinxcontrib-htmlhelp  # sphinxcontrib-htmlhelp 2.0.0
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-jsmath-[0-9]*:../../textproc/py-sphinxcontrib-jsmath  # sphinxcontrib-jsmath 1.0.1
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-qthelp-[0-9]*:../../textproc/py-sphinxcontrib-qthelp  # sphinxcontrib-qthelp 1.0.3
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-serializinghtml-[0-9]*:../../textproc/py-sphinxcontrib-serializinghtml  # sphinxcontrib-serializinghtml 1.1.5
DEPENDS+=	${PYPKGPREFIX}-spyder-kernels-[0-9]*:../../wip/py-spyder-kernels  # spyder-kernels 2.4.4
DEPENDS+=	${PYPKGPREFIX}-sqlalchemy-[0-9]*:../../databases/py-sqlalchemy  # sqlalchemy 2.0.25
DEPENDS+=	sqlite-[0-9]*:../../databases/sqlite  # sqlite 3.41.2
# stack_data 0.2.0 is missing
DEPENDS+=	${PYPKGPREFIX}-statsmodels-[0-9]*:../../math/py-statsmodels  # statsmodels 0.14.0
# streamlit 1.30.0 is missing
DEPENDS+=	${PYPKGPREFIX}-sympy-[0-9]*:../../math/py-sympy  # sympy 1.12
DEPENDS+=	${PYPKGPREFIX}-tabulate-[0-9]*:../../textproc/py-tabulate  # tabulate 0.9.0
# tbb 2021.8.0 is missing
DEPENDS+=	${PYPKGPREFIX}-tblib-[0-9]*:../../wip/py-tblib  # tblib 1.7.0
DEPENDS+=	${PYPKGPREFIX}-tenacity-[0-9]*:../../devel/py-tenacity  # tenacity 8.2.2
DEPENDS+=	${PYPKGPREFIX}-terminado-[0-9]*:../../www/py-terminado  # terminado 0.17.1
DEPENDS+=	${PYPKGPREFIX}-text-unidecode-[0-9]*:../../textproc/py-text-unidecode  # text-unidecode 1.3
DEPENDS+=	${PYPKGPREFIX}-textdistance-[0-9]*:../../wip/py-textdistance  # textdistance 4.2.1
DEPENDS+=	${PYPKGPREFIX}-threadpoolctl-[0-9]*:../../parallel/py-threadpoolctl  # threadpoolctl 2.2.0
DEPENDS+=	${PYPKGPREFIX}-three-merge-[0-9]*:../../wip/py-three-merge  # three-merge 0.1.1
DEPENDS+=	${PYPKGPREFIX}-tifffile-[0-9]*:../../graphics/py-tifffile  # tifffile 2023.4.12
DEPENDS+=	${PYPKGPREFIX}-tinycss2-[0-9]*:../../textproc/py-tinycss2  # tinycss2 1.2.1
DEPENDS+=	${PYPKGPREFIX}-tldextract-[0-9]*:../../net/py-tldextract  # tldextract 3.2.0
DEPENDS+=	${PYPKGPREFIX}-toml-[0-9]*:../../textproc/py-toml  # toml 0.10.2
DEPENDS+=	${PYPKGPREFIX}-tomlkit-[0-9]*:../../textproc/py-tomlkit  # tomlkit 0.11.1
DEPENDS+=	${PYPKGPREFIX}-toolz-[0-9]*:../../devel/py-toolz  # toolz 0.12.0
DEPENDS+=	${PYPKGPREFIX}-tornado-[0-9]*:../../www/py-tornado  # tornado 6.3.3
DEPENDS+=	${PYPKGPREFIX}-tqdm-[0-9]*:../../misc/py-tqdm  # tqdm 4.65.0
DEPENDS+=	${PYPKGPREFIX}-traitlets-[0-9]*:../../devel/py-traitlets  # traitlets 5.7.1
DEPENDS+=	${PYPKGPREFIX}-truststore-[0-9]*:../../security/py-truststore  # truststore 0.8.0
DEPENDS+=	${PYPKGPREFIX}-twisted-[0-9]*:../../net/py-twisted  # twisted 23.10.0
DEPENDS+=	${PYPKGPREFIX}-typing-extensions-[0-9]*:../../devel/py-typing-extensions  # typing-extensions 4.9.0
# typing_extensions 4.9.0 is missing
DEPENDS+=	${PYPKGPREFIX}-tzdata-[0-9]*:../../time/py-tzdata  # tzdata 2023d
DEPENDS+=	${PYPKGPREFIX}-tzlocal-[0-9]*:../../time/py-tzlocal  # tzlocal 2.1
DEPENDS+=	${PYPKGPREFIX}-uc-micro-py-[0-9]*:../../textproc/py-uc-micro-py  # uc-micro-py 1.0.1
DEPENDS+=	${PYPKGPREFIX}-ujson-[0-9]*:../../textproc/py-ujson  # ujson 5.4.0
DEPENDS+=	${PYPKGPREFIX}-Unidecode-[0-9]*:../../textproc/py-Unidecode  # unidecode 1.2.0
DEPENDS+=	unixodbc-[0-9]*:../../databases/unixodbc  # unixodbc 2.3.11
DEPENDS+=	${PYPKGPREFIX}-urllib3-[0-9]*:../../www/py-urllib3  # urllib3 2.0.7
DEPENDS+=	utf8proc-[0-9]*:../../converters/utf8proc  # utf8proc 2.6.1
DEPENDS+=	${PYPKGPREFIX}-validators-[0-9]*:../../textproc/py-validators  # validators 0.18.2
DEPENDS+=	${PYPKGPREFIX}-w3lib-[0-9]*:../../www/py-w3lib  # w3lib 2.1.2
DEPENDS+=	${PYPKGPREFIX}-watchdog-[0-9]*:../../sysutils/py-watchdog  # watchdog 2.1.6
DEPENDS+=	${PYPKGPREFIX}-wcwidth-[0-9]*:../../devel/py-wcwidth  # wcwidth 0.2.5
DEPENDS+=	${PYPKGPREFIX}-webencodings-[0-9]*:../../textproc/py-webencodings  # webencodings 0.5.1
DEPENDS+=	${PYPKGPREFIX}-websocket-client-[0-9]*:../../www/py-websocket-client  # websocket-client 0.58.0
DEPENDS+=	${PYPKGPREFIX}-werkzeug-[0-9]*:../../www/py-werkzeug  # werkzeug 2.2.3
DEPENDS+=	${PYPKGPREFIX}-whatthepatch-[0-9]*:../../devel/py-whatthepatch  # whatthepatch 1.0.2
DEPENDS+=	${PYPKGPREFIX}-wheel-[0-9]*:../../devel/py-wheel  # wheel 0.41.2
DEPENDS+=	${PYPKGPREFIX}-widgetsnbextension-[0-9]*:../../www/py-widgetsnbextension  # widgetsnbextension 3.5.2
DEPENDS+=	${PYPKGPREFIX}-wrapt-[0-9]*:../../devel/py-wrapt  # wrapt 1.14.1
DEPENDS+=	${PYPKGPREFIX}-wurlitzer-[0-9]*:../../wip/py-wurlitzer  # wurlitzer 3.0.2
DEPENDS+=	${PYPKGPREFIX}-xarray-[0-9]*:../../math/py-xarray  # xarray 2023.6.0
DEPENDS+=	${PYPKGPREFIX}-xyzservices-[0-9]*:../../wip/py-xyzservices  # xyzservices 2022.9.0
DEPENDS+=	xz-[0-9]*:../../archivers/xz  # xz 5.4.5
DEPENDS+=	${PYPKGPREFIX}-yaml-[0-9]*:../../textproc/py-yaml  # yaml 0.2.5
DEPENDS+=	yaml-cpp-[0-9]*:../../textproc/yaml-cpp  # yaml-cpp 0.8.0
DEPENDS+=	${PYPKGPREFIX}-yapf-[0-9]*:../../devel/py-yapf  # yapf 0.31.0
DEPENDS+=	${PYPKGPREFIX}-yarl-[0-9]*:../../www/py-yarl  # yarl 1.9.3
DEPENDS+=	zeromq-[0-9]*:../../net/zeromq  # zeromq 4.3.5
# zfp 1.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-zict-[0-9]*:../../wip/py-zict  # zict 3.0.0
DEPENDS+=	${PYPKGPREFIX}-zipp-[0-9]*:../../archivers/py-zipp  # zipp 3.17.0
DEPENDS+=	zlib-[0-9]*:../../devel/zlib  # zlib 1.2.13
DEPENDS+=	zlib-ng-[0-9]*:../../archivers/zlib-ng  # zlib-ng 2.0.7
# zope 1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-zope.interface-[0-9]*:../../devel/py-zope.interface  # zope.interface 5.4.0
DEPENDS+=	${PYPKGPREFIX}-zstandard-[0-9]*:../../archivers/py-zstandard  # zstandard 0.19.0
DEPENDS+=	zstd-[0-9]*:../../archivers/zstd  # zstd 1.5.5
