# _anaconda_depends 2025.12 is missing
# _libgcc_mutex 0.1 is missing
# _openmp_mutex 5.1 is missing
# aiobotocore 2.25.0 is skipped
DEPENDS+=	${PYPKGPREFIX}-aiodns-[0-9]*:../../net/py-aiodns  # aiodns 3.5.0
DEPENDS+=	${PYPKGPREFIX}-aiohappyeyeballs-[0-9]*:../../net/py-aiohappyeyeballs  # aiohappyeyeballs 2.6.1
DEPENDS+=	${PYPKGPREFIX}-aiohttp-[0-9]*:../../www/py-aiohttp  # aiohttp 3.13.2
# aioitertools 0.12.0 is missing
DEPENDS+=	${PYPKGPREFIX}-aiosignal-[0-9]*:../../devel/py-aiosignal  # aiosignal 1.4.0
DEPENDS+=	${PYPKGPREFIX}-alabaster-[0-9]*:../../textproc/py-alabaster  # alabaster 0.7.16
DEPENDS+=	alsa-lib-[0-9]*:../../audio/alsa-lib  # alsa-lib 1.2.14
DEPENDS+=	${PYPKGPREFIX}-altair-[0-9]*:../../wip/py-altair  # altair 5.5.0
# anaconda-anon-usage 0.7.5 is missing
# anaconda-auth 0.12.3 is missing
# anaconda-catalogs 0.2.0 is missing
# anaconda-cli-base 0.7.0 is missing
# anaconda-client 1.14.0 is missing
# anaconda-navigator 2.7.0 is missing
# anaconda-project 0.11.1 is missing
# anaconda_powershell_prompt nan is missing
# anaconda_prompt nan is missing
DEPENDS+=	${PYPKGPREFIX}-annotated-types-[0-9]*:../../lang/py-annotated-types  # annotated-types 0.6.0
DEPENDS+=	${PYPKGPREFIX}-anyio-[0-9]*:../../devel/py-anyio  # anyio 4.10.0
# aom 3.12.1 is missing
DEPENDS+=	${PYPKGPREFIX}-appdirs-[0-9]*:../../devel/py-appdirs  # appdirs 1.4.4
# applaunchservices nan is missing
# appnope nan is missing
# appscript nan is missing
# archspec 0.2.5 is missing
DEPENDS+=	${PYPKGPREFIX}-argon2-cffi-[0-9]*:../../security/py-argon2-cffi  # argon2-cffi 21.3.0
DEPENDS+=	${PYPKGPREFIX}-argon2-cffi-bindings-[0-9]*:../../security/py-argon2-cffi-bindings  # argon2-cffi-bindings 25.1.0
DEPENDS+=	${PYPKGPREFIX}-arrow-[0-9]*:../../time/py-arrow  # arrow 1.4.0
# arrow-cpp 21.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-astroid-[0-9]*:../../devel/py-astroid  # astroid 3.3.11
DEPENDS+=	${PYPKGPREFIX}-astropy-[0-9]*:../../math/py-astropy  # astropy 7.1.1
DEPENDS+=	${PYPKGPREFIX}-astropy-iers-data-[0-9]*:../../math/py-astropy-iers-data  # astropy-iers-data 0.2025.11.10.0.38.31
DEPENDS+=	${PYPKGPREFIX}-asttokens-[0-9]*:../../lang/py-asttokens  # asttokens 3.0.0
DEPENDS+=	${PYPKGPREFIX}-async-lru-[0-9]*:../../devel/py-async-lru  # async-lru 2.0.5
DEPENDS+=	${PYPKGPREFIX}-asyncssh-[0-9]*:../../security/py-asyncssh  # asyncssh 2.21.1
DEPENDS+=	${PYPKGPREFIX}-atomicwrites-[0-9]*:../../devel/py-atomicwrites  # atomicwrites 1.4.0
DEPENDS+=	${PYPKGPREFIX}-attrs-[0-9]*:../../devel/py-attrs  # attrs 25.4.0
DEPENDS+=	${PYPKGPREFIX}-automat-[0-9]*:../../devel/py-automat  # automat 24.8.1
DEPENDS+=	${PYPKGPREFIX}-autopep8-[0-9]*:../../devel/py-autopep8  # autopep8 2.0.4
# aws-c-auth 0.9.0 is missing
# aws-c-cal 0.9.2 is missing
# aws-c-common 0.12.4 is missing
# aws-c-compression 0.3.1 is missing
# aws-c-event-stream 0.5.6 is missing
# aws-c-http 0.10.4 is missing
# aws-c-io 0.21.4 is missing
# aws-c-mqtt 0.13.3 is missing
# aws-c-s3 0.8.7 is missing
# aws-c-sdkutils 0.2.4 is missing
# aws-checksums 0.2.7 is missing
# aws-crt-cpp 0.34.0 is missing
# aws-sdk-cpp 1.11.638 is missing
DEPENDS+=	${PYPKGPREFIX}-babel-[0-9]*:../../devel/py-babel  # babel 2.17.0
DEPENDS+=	bcrypt-[0-9]*:../../security/bcrypt  # bcrypt 5.0.0
DEPENDS+=	${PYPKGPREFIX}-beautifulsoup4-[0-9]*:../../www/py-beautifulsoup4  # beautifulsoup4 4.13.5
DEPENDS+=	${PYPKGPREFIX}-binaryornot-[0-9]*:../../devel/py-binaryornot  # binaryornot 0.4.4
DEPENDS+=	${PYPKGPREFIX}-black-[0-9]*:../../textproc/py-black  # black 25.9.0
DEPENDS+=	blas-[0-9]*:../../math/blas  # blas 1.0
DEPENDS+=	${PYPKGPREFIX}-bleach-[0-9]*:../../www/py-bleach  # bleach 6.3.0
DEPENDS+=	${PYPKGPREFIX}-blinker-[0-9]*:../../devel/py-blinker  # blinker 1.9.0
DEPENDS+=	blosc-[0-9]*:../../devel/blosc  # blosc 1.21.6
DEPENDS+=	${PYPKGPREFIX}-bokeh-[0-9]*:../../wip/py-bokeh  # bokeh 3.8.0
DEPENDS+=	${PYPKGPREFIX}-boltons-[0-9]*:../../devel/py-boltons  # boltons 25.0.0
DEPENDS+=	${PYPKGPREFIX}-botocore-[0-9]*:../../net/py-botocore  # botocore 1.40.46
DEPENDS+=	${PYPKGPREFIX}-bottleneck-[0-9]*:../../math/py-bottleneck  # bottleneck 1.4.2
DEPENDS+=	${PYPKGPREFIX}-brotlicffi-[0-9]*:../../archivers/py-brotlicffi  # brotlicffi 1.1.0.0
DEPENDS+=	bzip2-[0-9]*:../../archivers/bzip2  # bzip2 1.0.8
# c-ares 1.34.5 is missing
# c-blosc2 2.17.1 is missing
DEPENDS+=	ca-certificates-[0-9]*:../../security/ca-certificates  # ca-certificates 2025.11.4
DEPENDS+=	${PYPKGPREFIX}-cachetools-[0-9]*:../../devel/py-cachetools  # cachetools 5.5.1
DEPENDS+=	cairo-[0-9]*:../../graphics/cairo  # cairo 1.18.4
DEPENDS+=	${PYPKGPREFIX}-cattrs-[0-9]*:../../devel/py-cattrs  # cattrs 25.3.0
# cctools nan is missing
DEPENDS+=	${PYPKGPREFIX}-certifi-[0-9]*:../../security/py-certifi  # certifi 2025.11.12
DEPENDS+=	${PYPKGPREFIX}-cffi-[0-9]*:../../devel/py-cffi  # cffi 2.0.0
DEPENDS+=	${PYPKGPREFIX}-chardet-[0-9]*:../../converters/py-chardet  # chardet 5.2.0
DEPENDS+=	${PYPKGPREFIX}-charset-normalizer-[0-9]*:../../converters/py-charset-normalizer  # charset-normalizer 3.4.4
DEPENDS+=	${PYPKGPREFIX}-click-[0-9]*:../../devel/py-click  # click 8.2.1
DEPENDS+=	${PYPKGPREFIX}-cloudpickle-[0-9]*:../../converters/py-cloudpickle  # cloudpickle 3.1.1
# colorama nan is missing
DEPENDS+=	${PYPKGPREFIX}-colorcet-[0-9]*:../../wip/py-colorcet  # colorcet 3.1.0
DEPENDS+=	${PYPKGPREFIX}-comm-[0-9]*:../../net/py-comm  # comm 0.2.3
# conda 25.11.1 is skipped
# conda-anaconda-telemetry 0.3.0 is missing
# conda-anaconda-tos 0.2.2 is missing
# conda-build 25.11.1 is missing
# conda-content-trust 0.2.0 is missing
# conda-index 0.7.0 is missing
# conda-libmamba-solver 25.11.0 is missing
# conda-pack 0.8.1 is missing
# conda-package-handling 2.4.0 is missing
# conda-package-streaming 0.12.0 is missing
# conda-repo-cli 1.0.173 is missing
DEPENDS+=	${PYPKGPREFIX}-constantly-[0-9]*:../../devel/py-constantly  # constantly 23.10.4
DEPENDS+=	${PYPKGPREFIX}-contourpy-[0-9]*:../../graphics/py-contourpy  # contourpy 1.3.3
DEPENDS+=	${PYPKGPREFIX}-cookiecutter-[0-9]*:../../devel/py-cookiecutter  # cookiecutter 2.6.0
# cpp-expected 1.1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-cryptography-[0-9]*:../../security/py-cryptography  # cryptography 46.0.3
DEPENDS+=	${PYPKGPREFIX}-cssselect-[0-9]*:../../textproc/py-cssselect  # cssselect 1.2.0
DEPENDS+=	curl-[0-9]*:../../www/curl  # libcurl 8.16.0
DEPENDS+=	${PYPKGPREFIX}-cycler-[0-9]*:../../graphics/py-cycler  # cycler 0.11.0
DEPENDS+=	cyrus-sasl-[0-9]*:../../security/cyrus-sasl  # cyrus-sasl 2.1.28
DEPENDS+=	${PYPKGPREFIX}-dask-[0-9]*:../../wip/py-dask  # dask 2025.11.0
# dask-core 2025.11.0 is missing
# datashader 0.18.2 is skipped
DEPENDS+=	dav1d-[0-9]*:../../multimedia/dav1d  # dav1d 1.2.1
DEPENDS+=	dbus-[0-9]*:../../sysutils/dbus  # dbus 1.16.2
DEPENDS+=	${PYPKGPREFIX}-debugpy-[0-9]*:../../devel/py-debugpy  # debugpy 1.8.16
DEPENDS+=	${PYPKGPREFIX}-decorator-[0-9]*:../../devel/py-decorator  # decorator 5.2.1
DEPENDS+=	${PYPKGPREFIX}-defusedxml-[0-9]*:../../textproc/py-defusedxml  # defusedxml 0.7.1
DEPENDS+=	${PYPKGPREFIX}-diff-match-patch-[0-9]*:../../textproc/py-diff-match-patch  # diff-match-patch 20200713
DEPENDS+=	${PYPKGPREFIX}-dill-[0-9]*:../../textproc/py-dill  # dill 0.4.0
DEPENDS+=	${PYPKGPREFIX}-distributed-[0-9]*:../../wip/py-distributed  # distributed 2025.11.0
DEPENDS+=	${PYPKGPREFIX}-distro-[0-9]*:../../devel/py-distro  # distro 1.9.0
# dmglib nan is missing
DEPENDS+=	${PYPKGPREFIX}-docstring-to-markdown-[0-9]*:../../textproc/py-docstring-to-markdown  # docstring-to-markdown 0.17
DEPENDS+=	${PYPKGPREFIX}-docutils-[0-9]*:../../textproc/py-docutils  # docutils 0.21.2
DEPENDS+=	${PYPKGPREFIX}-et_xmlfile-[0-9]*:../../textproc/py-et_xmlfile  # et_xmlfile 2.0.0
# evalidate 2.0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-executing-[0-9]*:../../lang/py-executing  # executing 2.2.1
DEPENDS+=	expat-[0-9]*:../../textproc/expat  # expat 2.7.3
DEPENDS+=	${PYPKGPREFIX}-filelock-[0-9]*:../../devel/py-filelock  # filelock 3.20.0
DEPENDS+=	${PYPKGPREFIX}-flake8-[0-9]*:../../devel/py-flake8  # flake8 7.1.1
DEPENDS+=	${PYPKGPREFIX}-flask-[0-9]*:../../www/py-flask  # flask 3.1.2
# fmt 11.2.0 is missing
DEPENDS+=	fontconfig-[0-9]*:../../fonts/fontconfig  # fontconfig 2.15.0
DEPENDS+=	${PYPKGPREFIX}-fonttools-[0-9]*:../../fonts/py-fonttools  # fonttools 4.60.1
# freeglut nan is missing
DEPENDS+=	freetype2-[0-9]*:../../graphics/freetype2  # freetype 2.13.3
DEPENDS+=	fribidi-[0-9]*:../../converters/fribidi  # fribidi 1.0.10
DEPENDS+=	${PYPKGPREFIX}-frozendict-[0-9]*:../../devel/py-frozendict  # frozendict 2.4.6
DEPENDS+=	${PYPKGPREFIX}-frozenlist-[0-9]*:../../devel/py-frozenlist  # frozenlist 1.8.0
DEPENDS+=	${PYPKGPREFIX}-fsspec-[0-9]*:../../sysutils/py-fsspec  # fsspec 2025.10.0
DEPENDS+=	gettext-[0-9]*:../../devel/gettext  # gettext 0.21.0
DEPENDS+=	gflags-[0-9]*:../../devel/gflags  # gflags 2.2.2
DEPENDS+=	${PYPKGPREFIX}-gitdb-[0-9]*:../../devel/py-gitdb  # gitdb 4.0.12
DEPENDS+=	${PYPKGPREFIX}-gitpython-[0-9]*:../../devel/py-gitpython  # gitpython 3.1.45
DEPENDS+=	glib2-[0-9]*:../../devel/glib2  # glib 2.84.4
# glib-tools 2.84.4 is missing
DEPENDS+=	google-glog-[0-9]*:../../devel/google-glog  # glog 0.5.0
DEPENDS+=	gmp-[0-9]*:../../devel/gmp  # gmp 6.3.0
DEPENDS+=	${PYPKGPREFIX}-gmpy2-[0-9]*:../../math/py-gmpy2  # gmpy2 2.2.1
DEPENDS+=	graphite2-[0-9]*:../../graphics/graphite2  # graphite2 1.3.14
DEPENDS+=	${PYPKGPREFIX}-greenlet-[0-9]*:../../devel/py-greenlet  # greenlet 3.2.4
DEPENDS+=	gst-plugins1-base-[0-9]*:../../multimedia/gst-plugins1-base  # gst-plugins-base 1.24.12
DEPENDS+=	gstreamer1-[0-9]*:../../multimedia/gstreamer1  # gstreamer 1.24.12
# gstreamer-orc 0.4.41 is missing
DEPENDS+=	${PYPKGPREFIX}-h11-[0-9]*:../../www/py-h11  # h11 0.16.0
DEPENDS+=	${PYPKGPREFIX}-h5py-[0-9]*:../../devel/py-h5py  # h5py 3.15.1
DEPENDS+=	harfbuzz-[0-9]*:../../fonts/harfbuzz  # harfbuzz 10.2.0
DEPENDS+=	hdf5-[0-9]*:../../devel/hdf5  # hdf5 1.14.5
DEPENDS+=	${PYPKGPREFIX}-HeapDict-[0-9]*:../../wip/py-HeapDict  # heapdict 1.0.1
# holoviews 1.22.0 is skipped
DEPENDS+=	${PYPKGPREFIX}-html5lib-[0-9]*:../../textproc/py-html5lib  # html5lib 1.1
DEPENDS+=	${PYPKGPREFIX}-httpcore-[0-9]*:../../www/py-httpcore  # httpcore 1.0.9
DEPENDS+=	httpx-[0-9]*:../../security/httpx  # httpx 0.28.1
# hvplot 0.12.1 is missing
DEPENDS+=	${PYPKGPREFIX}-hyperlink-[0-9]*:../../www/py-hyperlink  # hyperlink 21.0.0
# icc_rt nan is missing
DEPENDS+=	icu-[0-9]*:../../textproc/icu  # icu 73.1
DEPENDS+=	${PYPKGPREFIX}-idna-[0-9]*:../../www/py-idna  # idna 3.11
DEPENDS+=	${PYPKGPREFIX}-imageio-[0-9]*:../../graphics/py-imageio  # imageio 2.37.2
DEPENDS+=	${PYPKGPREFIX}-imagesize-[0-9]*:../../graphics/py-imagesize  # imagesize 1.4.1
# imbalanced-learn 0.14.0 is missing
DEPENDS+=	${PYPKGPREFIX}-importlib-metadata-[0-9]*:../../devel/py-importlib-metadata  # importlib-metadata 8.7.0
DEPENDS+=	${PYPKGPREFIX}-incremental-[0-9]*:../../devel/py-incremental  # incremental 24.7.2
DEPENDS+=	${PYPKGPREFIX}-inflection-[0-9]*:../../textproc/py-inflection  # inflection 0.5.1
DEPENDS+=	${PYPKGPREFIX}-iniconfig-[0-9]*:../../devel/py-iniconfig  # iniconfig 2.1.0
# intake 2.0.8 is missing
# intel-openmp 2025.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-intervaltree-[0-9]*:../../devel/py-intervaltree  # intervaltree 3.1.0
DEPENDS+=	${PYPKGPREFIX}-ipykernel-[0-9]*:../../devel/py-ipykernel  # ipykernel 6.31.0
# ipympl 0.9.7 is missing
DEPENDS+=	${PYPKGPREFIX}-ipython-[0-9]*:../../devel/py-ipython  # ipython 9.7.0
# ipython_pygments_lexers 1.1.1 is missing
DEPENDS+=	${PYPKGPREFIX}-ipywidgets-[0-9]*:../../www/py-ipywidgets  # ipywidgets 8.1.7
DEPENDS+=	${PYPKGPREFIX}-isort-[0-9]*:../../devel/py-isort  # isort 6.1.0
DEPENDS+=	${PYPKGPREFIX}-itemadapter-[0-9]*:../../textproc/py-itemadapter  # itemadapter 0.12.1
DEPENDS+=	${PYPKGPREFIX}-itemloaders-[0-9]*:../../textproc/py-itemloaders  # itemloaders 1.3.2
DEPENDS+=	${PYPKGPREFIX}-itsdangerous-[0-9]*:../../security/py-itsdangerous  # itsdangerous 2.2.0
DEPENDS+=	jansson-[0-9]*:../../textproc/jansson  # jansson 2.14
DEPENDS+=	${PYPKGPREFIX}-jaraco.classes-[0-9]*:../../devel/py-jaraco.classes  # jaraco.classes 3.4.0
DEPENDS+=	${PYPKGPREFIX}-jaraco.context-[0-9]*:../../devel/py-jaraco.context  # jaraco.context 6.0.0
DEPENDS+=	${PYPKGPREFIX}-jaraco.functools-[0-9]*:../../devel/py-jaraco.functools  # jaraco.functools 4.1.0
DEPENDS+=	${PYPKGPREFIX}-jedi-[0-9]*:../../editors/py-jedi  # jedi 0.19.2
DEPENDS+=	${PYPKGPREFIX}-jeepney-[0-9]*:../../sysutils/py-jeepney  # jeepney 0.7.1
DEPENDS+=	${PYPKGPREFIX}-jellyfish-[0-9]*:../../textproc/py-jellyfish  # jellyfish 1.2.1
DEPENDS+=	${PYPKGPREFIX}-jinja2-[0-9]*:../../textproc/py-jinja2  # jinja2 3.1.6
DEPENDS+=	${PYPKGPREFIX}-jmespath-[0-9]*:../../textproc/py-jmespath  # jmespath 1.0.1
DEPENDS+=	${PYPKGPREFIX}-joblib-[0-9]*:../../devel/py-joblib  # joblib 1.5.2
# jpeg 9f is skipped
DEPENDS+=	jq-[0-9]*:../../devel/jq  # jq 1.8.1
DEPENDS+=	${PYPKGPREFIX}-json5-[0-9]*:../../textproc/py-json5  # json5 0.12.1
DEPENDS+=	${PYPKGPREFIX}-jsonpatch-[0-9]*:../../wip/py-jsonpatch  # jsonpatch 1.33
DEPENDS+=	${PYPKGPREFIX}-jsonpointer-[0-9]*:../../wip/py-jsonpointer  # jsonpointer 3.0.0
DEPENDS+=	${PYPKGPREFIX}-jsonschema-[0-9]*:../../textproc/py-jsonschema  # jsonschema 4.25.0
DEPENDS+=	${PYPKGPREFIX}-jsonschema-specifications-[0-9]*:../../textproc/py-jsonschema-specifications  # jsonschema-specifications 2025.9.1
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-[0-9]*:../../www/py-jupyterlab  # jupyter 1.1.1
DEPENDS+=	${PYPKGPREFIX}-jupyter-lsp-[0-9]*:../../www/py-jupyter-lsp  # jupyter-lsp 2.2.5
DEPENDS+=	${PYPKGPREFIX}-jupyter_client-[0-9]*:../../devel/py-jupyter_client  # jupyter_client 8.6.3
DEPENDS+=	${PYPKGPREFIX}-jupyter-console-[0-9]*:../../devel/py-jupyter-console  # jupyter_console 6.6.3
DEPENDS+=	${PYPKGPREFIX}-jupyter_core-[0-9]*:../../devel/py-jupyter_core  # jupyter_core 5.8.1
DEPENDS+=	${PYPKGPREFIX}-jupyter_events-[0-9]*:../../devel/py-jupyter_events  # jupyter_events 0.12.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_server-[0-9]*:../../www/py-jupyter_server  # jupyter_server 2.16.0
DEPENDS+=	${PYPKGPREFIX}-jupyter_server_terminals-[0-9]*:../../comms/py-jupyter_server_terminals  # jupyter_server_terminals 0.5.3
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-[0-9]*:../../www/py-jupyterlab  # jupyterlab 4.4.7
# jupyterlab-variableinspector 3.2.4 is missing
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-pygments-[0-9]*:../../textproc/py-jupyterlab-pygments  # jupyterlab_pygments 0.3.0
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-server-[0-9]*:../../www/py-jupyterlab-server  # jupyterlab_server 2.28.0
DEPENDS+=	${PYPKGPREFIX}-jupyterlab-widgets-[0-9]*:../../www/py-jupyterlab-widgets  # jupyterlab_widgets 3.0.15
DEPENDS+=	${PYPKGPREFIX}-keyring-[0-9]*:../../security/py-keyring  # keyring 25.7.0
DEPENDS+=	${PYPKGPREFIX}-kiwisolver-[0-9]*:../../math/py-kiwisolver  # kiwisolver 1.4.9
DEPENDS+=	${PYPKGPREFIX}-lazy_loader-[0-9]*:../../misc/py-lazy_loader  # lazy_loader 0.4
DEPENDS+=	lcms2-[0-9]*:../../graphics/lcms2  # lcms2 2.17
# ld64 nan is missing
# ld_impl_linux-64 2.44 is missing
# ld_impl_linux-aarch64 nan is missing
DEPENDS+=	lerc-[0-9]*:../../graphics/lerc  # lerc 4.0.0
# libabseil 20250127.0 is missing
DEPENDS+=	libarchive-[0-9]*:../../archivers/libarchive  # libarchive 3.8.2
DEPENDS+=	libavif-[0-9]*:../../graphics/libavif  # libavif 1.3.0
DEPENDS+=	brotli-[0-9]*:../../archivers/brotli  # libbrotlicommon 1.0.9
# libbrotlidec 1.0.9 is missing
# libbrotlienc 1.0.9 is missing
# libclang13 20.1.8 is missing
DEPENDS+=	libcups-[0-9]*:../../print/libcups  # libcups 2.4.2
# libcxx nan is missing
DEPENDS+=	libdeflate-[0-9]*:../../devel/libdeflate  # libdeflate 1.22
DEPENDS+=	libdrm-[0-9]*:../../wip/libdrm  # libdrm 2.4.124
DEPENDS+=	editline-[0-9]*:../../devel/editline  # libedit 3.1.20230828
# libegl 1.7.0 is missing
DEPENDS+=	libev-[0-9]*:../../devel/libev  # libev 4.33
DEPENDS+=	libevent-[0-9]*:../../devel/libevent  # libevent 2.1.12
DEPENDS+=	libffi-[0-9]*:../../devel/libffi  # libffi 3.4.4
# libgcc 15.2.0 is missing
# libgcc-ng 15.2.0 is missing
# libgfortran 15.2.0 is missing
# libgfortran-ng 15.2.0 is missing
# libgfortran5 15.2.0 is missing
# libgl 1.7.0 is missing
# libglib 2.84.4 is missing
DEPENDS+=	libglvnd-[0-9]*:../../wip/libglvnd  # libglvnd 1.7.0
# libglx 1.7.0 is missing
DEPENDS+=	openmp-[0-9]*:../../parallel/openmp  # libgomp 15.2.0
# libgrpc 1.71.0 is missing
DEPENDS+=	libiconv-[0-9]*:../../converters/libiconv  # libiconv 1.16
DEPENDS+=	libidn2-[0-9]*:../../devel/libidn2  # libidn2 2.3.8
# libkrb5 1.21.3 is missing
# liblief 0.16.4 is missing
# libllvm15 15.0.7 is missing
# libllvm20 20.1.8 is missing
# libmamba 2.3.2 is missing
# libmambapy 2.3.2 is missing
# libmpdec 4.0.0 is missing
# libnghttp2 1.67.1 is missing
DEPENDS+=	libogg-[0-9]*:../../multimedia/libogg  # libogg 1.3.5
# libopenblas nan is missing
# libopengl 1.7.0 is missing
# libopenjpeg 2.5.4 is missing
DEPENDS+=	libopus-[0-9]*:../../audio/libopus  # libopus 1.3.1
DEPENDS+=	libpciaccess-[0-9]*:../../sysutils/libpciaccess  # libpciaccess 0.18
DEPENDS+=	png-[0-9]*:../../graphics/png  # libpng 1.6.50
# libpq 17.6 is missing
# libprotobuf 5.29.3 is missing
# libre2-11 2024.07.02 is missing
DEPENDS+=	libsodium-[0-9]*:../../security/libsodium  # libsodium 1.0.20
# libsolv 0.7.30 is missing
# libspatialindex 1.9.3 is missing
DEPENDS+=	libssh2-[0-9]*:../../security/libssh2  # libssh2 1.11.1
# libstdcxx 15.2.0 is missing
# libstdcxx-ng 15.2.0 is missing
DEPENDS+=	libthrift-[0-9]*:../../devel/libthrift  # libthrift 0.22.0
DEPENDS+=	tiff-[0-9]*:../../graphics/tiff  # libtiff 4.7.1
DEPENDS+=	libunistring-[0-9]*:../../textproc/libunistring  # libunistring 1.3
DEPENDS+=	libuuid-[0-9]*:../../devel/libuuid  # libuuid 1.41.5
DEPENDS+=	libuv-[0-9]*:../../devel/libuv  # libuv 1.48.0
DEPENDS+=	libvorbis-[0-9]*:../../audio/libvorbis  # libvorbis 1.3.7
DEPENDS+=	libvpx-[0-9]*:../../multimedia/libvpx  # libvpx 1.13.1
# libwebp-base 1.6.0 is missing
# libxcb 1.17.0 is skipped
# libxkbcommon 1.9.1 is skipped
DEPENDS+=	libxkbfile-[0-9]*:../../x11/libxkbfile  # libxkbfile 1.1.0
DEPENDS+=	libxml2-[0-9]*:../../textproc/libxml2  # libxml2 2.13.9
DEPENDS+=	libxslt-[0-9]*:../../textproc/libxslt  # libxslt 1.1.43
# libzlib 1.3.1 is missing
DEPENDS+=	${PYPKGPREFIX}-linkify-it-py-[0-9]*:../../textproc/py-linkify-it-py  # linkify-it-py 2.0.3
# llvm-openmp nan is missing
DEPENDS+=	${PYPKGPREFIX}-llvmlite-[0-9]*:../../devel/py-llvmlite  # llvmlite 0.45.1
DEPENDS+=	lmdb-[0-9]*:../../databases/lmdb  # lmdb 0.9.31
DEPENDS+=	${PYPKGPREFIX}-locket-[0-9]*:../../wip/py-locket  # locket 1.0.0
DEPENDS+=	${PYPKGPREFIX}-lsprotocol-[0-9]*:../../lang/py-lsprotocol  # lsprotocol 2025.0.0
DEPENDS+=	${PYPKGPREFIX}-lxml-[0-9]*:../../textproc/py-lxml  # lxml 5.3.0
DEPENDS+=	lz4-[0-9]*:../../archivers/lz4  # lz4 4.4.5
# lz4-c 1.9.4 is missing
DEPENDS+=	lzo-[0-9]*:../../archivers/lzo  # lzo 2.10
# m2-msys2-runtime nan is missing
# m2-patch nan is missing
# m2w64-gcc-libgfortran nan is missing
# m2w64-gcc-libs nan is missing
# m2w64-gcc-libs-core nan is missing
# m2w64-gmp nan is missing
# m2w64-libwinpthread-git nan is missing
DEPENDS+=	${PYPKGPREFIX}-markdown-[0-9]*:../../textproc/py-markdown  # markdown 3.8
DEPENDS+=	${PYPKGPREFIX}-markdown-it-py-[0-9]*:../../textproc/py-markdown-it-py  # markdown-it-py 2.2.0
DEPENDS+=	${PYPKGPREFIX}-markupsafe-[0-9]*:../../textproc/py-markupsafe  # markupsafe 3.0.2
DEPENDS+=	${PYPKGPREFIX}-matplotlib-[0-9]*:../../graphics/py-matplotlib  # matplotlib 3.10.6
# matplotlib-base 3.10.6 is missing
DEPENDS+=	${PYPKGPREFIX}-matplotlib-inline-[0-9]*:../../graphics/py-matplotlib-inline  # matplotlib-inline 0.2.1
DEPENDS+=	mbedtls3-[0-9]*:../../security/mbedtls3  # mbedtls 3.5.1
DEPENDS+=	${PYPKGPREFIX}-mccabe-[0-9]*:../../devel/py-mccabe  # mccabe 0.7.0
DEPENDS+=	${PYPKGPREFIX}-mdit-py-plugins-[0-9]*:../../textproc/py-mdit-py-plugins  # mdit-py-plugins 0.5.0
DEPENDS+=	${PYPKGPREFIX}-mdurl-[0-9]*:../../www/py-mdurl  # mdurl 0.1.2
# menuinst 2.4.2 is missing
# mesalib 25.1.5 is skipped
DEPENDS+=	${PYPKGPREFIX}-mistune-[0-9]*:../../textproc/py-mistune  # mistune 3.1.2
# mkl 2025.0.0 is missing
# mkl-service 2.5.2 is missing
# mkl_fft 2.1.1 is missing
# mkl_random 1.3.0 is missing
DEPENDS+=	${PYPKGPREFIX}-more-itertools-[0-9]*:../../devel/py-more-itertools  # more-itertools 10.8.0
DEPENDS+=	mpc-[0-9]*:../../audio/mpc  # mpc 1.3.1
DEPENDS+=	mpfr-[0-9]*:../../math/mpfr  # mpfr 4.2.1
# mpi 1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-mpi4py-[0-9]*:../../wip/py-mpi4py  # mpi4py 4.0.3
# mpich 4.3.2 is missing
DEPENDS+=	${PYPKGPREFIX}-mpmath-[0-9]*:../../math/py-mpmath  # mpmath 1.3.0
DEPENDS+=	${PYPKGPREFIX}-msgpack-[0-9]*:../../devel/py-msgpack  # msgpack-python 1.1.1
# msmpi nan is missing
# msys2-conda-epoch nan is missing
DEPENDS+=	${PYPKGPREFIX}-multidict-[0-9]*:../../databases/py-multidict  # multidict 6.7.0
DEPENDS+=	${PYPKGPREFIX}-multipledispatch-[0-9]*:../../devel/py-multipledispatch  # multipledispatch 1.0.0
DEPENDS+=	${PYPKGPREFIX}-mypy-[0-9]*:../../lang/py-mypy  # mypy 1.17.1
DEPENDS+=	${PYPKGPREFIX}-mypy_extensions-[0-9]*:../../lang/py-mypy_extensions  # mypy_extensions 1.0.0
# mysql-common 9.3.0 is missing
# mysql-libs 9.3.0 is missing
# narwhals 2.7.0 is missing
# navigator-updater 0.6.0 is missing
DEPENDS+=	${PYPKGPREFIX}-nbclient-[0-9]*:../../www/py-nbclient  # nbclient 0.10.2
DEPENDS+=	${PYPKGPREFIX}-nbconvert-[0-9]*:../../www/py-nbconvert  # nbconvert 7.16.6
# nbconvert-core 7.16.6 is missing
# nbconvert-pandoc 7.16.6 is missing
DEPENDS+=	${PYPKGPREFIX}-nbformat-[0-9]*:../../www/py-nbformat  # nbformat 5.10.4
DEPENDS+=	ncurses-[0-9]*:../../devel/ncurses  # ncurses 6.5
DEPENDS+=	${PYPKGPREFIX}-nest-asyncio-[0-9]*:../../devel/py-nest-asyncio  # nest-asyncio 1.6.0
DEPENDS+=	${PYPKGPREFIX}-networkx-[0-9]*:../../math/py-networkx  # networkx 3.5
# nlohmann_json 3.11.2 is missing
DEPENDS+=	${PYPKGPREFIX}-nltk-[0-9]*:../../textproc/py-nltk  # nltk 3.9.2
DEPENDS+=	${PYPKGPREFIX}-notebook-[0-9]*:../../www/py-notebook  # notebook 7.4.5
DEPENDS+=	${PYPKGPREFIX}-notebook_shim-[0-9]*:../../www/py-notebook_shim  # notebook-shim 0.2.4
DEPENDS+=	nspr-[0-9]*:../../devel/nspr  # nspr 4.37
DEPENDS+=	nss-[0-9]*:../../devel/nss  # nss 3.117
# numba 0.62.1 is skipped
DEPENDS+=	${PYPKGPREFIX}-numexpr-[0-9]*:../../math/py-numexpr  # numexpr 2.14.1
DEPENDS+=	${PYPKGPREFIX}-numpy-[0-9]*:../../math/py-numpy  # numpy 2.3.5
# numpy-base 2.3.5 is missing
DEPENDS+=	${PYPKGPREFIX}-numpydoc-[0-9]*:../../textproc/py-numpydoc  # numpydoc 1.9.0
DEPENDS+=	oniguruma-[0-9]*:../../textproc/oniguruma  # oniguruma 6.9.10
DEPENDS+=	openjpeg-[0-9]*:../../graphics/openjpeg  # openjpeg 2.5.4
DEPENDS+=	openldap-[0-9]*:../../databases/openldap  # openldap 2.6.10
DEPENDS+=	${PYPKGPREFIX}-openpyxl-[0-9]*:../../textproc/py-openpyxl  # openpyxl 3.1.5
# openssl 3.0.18 is skipped
DEPENDS+=	orc-[0-9]*:../../devel/orc  # orc 2.2.0
DEPENDS+=	${PYPKGPREFIX}-overrides-[0-9]*:../../devel/py-overrides  # overrides 7.7.0
DEPENDS+=	${PYPKGPREFIX}-packaging-[0-9]*:../../devel/py-packaging  # packaging 25.0
DEPENDS+=	${PYPKGPREFIX}-pandas-[0-9]*:../../math/py-pandas  # pandas 2.3.3
# pandoc 3.8 is skipped
# pandocfilters 1.5.1 is skipped
# panel 1.8.3 is skipped
DEPENDS+=	${PYPKGPREFIX}-param-[0-9]*:../../wip/py-param  # param 2.3.0
DEPENDS+=	${PYPKGPREFIX}-parsel-[0-9]*:../../www/py-parsel  # parsel 1.10.0
DEPENDS+=	${PYPKGPREFIX}-parso-[0-9]*:../../lang/py-parso  # parso 0.8.5
DEPENDS+=	${PYPKGPREFIX}-partd-[0-9]*:../../wip/py-partd  # partd 1.4.2
DEPENDS+=	patch-[0-9]*:../../devel/patch  # patch 2.8
DEPENDS+=	patchelf-[0-9]*:../../devel/patchelf  # patchelf 0.17.2
DEPENDS+=	${PYPKGPREFIX}-pathspec-[0-9]*:../../devel/py-pathspec  # pathspec 0.12.1
DEPENDS+=	${PYPKGPREFIX}-patsy-[0-9]*:../../math/py-patsy  # patsy 1.0.1
DEPENDS+=	pcre2-[0-9]*:../../devel/pcre2  # pcre2 10.46
DEPENDS+=	${PYPKGPREFIX}-pexpect-[0-9]*:../../devel/py-pexpect  # pexpect 4.9.0
DEPENDS+=	${PYPKGPREFIX}-pickleshare-[0-9]*:../../databases/py-pickleshare  # pickleshare 0.7.5
DEPENDS+=	${PYPKGPREFIX}-Pillow-[0-9]*:../../graphics/py-Pillow  # pillow 12.0.0
DEPENDS+=	${PYPKGPREFIX}-pip-[0-9]*:../../devel/py-pip  # pip 25.3
DEPENDS+=	pixman-[0-9]*:../../x11/pixman  # pixman 0.46.4
# pkce 1.0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-pkginfo-[0-9]*:../../devel/py-pkginfo  # pkginfo 1.12.1.2
DEPENDS+=	${PYPKGPREFIX}-platformdirs-[0-9]*:../../misc/py-platformdirs  # platformdirs 4.5.0
# plotly 6.3.0 is skipped
DEPENDS+=	${PYPKGPREFIX}-pluggy-[0-9]*:../../devel/py-pluggy  # pluggy 1.5.0
DEPENDS+=	${PYPKGPREFIX}-prometheus_client-[0-9]*:../../net/py-prometheus_client  # prometheus_client 0.21.1
DEPENDS+=	${PYPKGPREFIX}-prompt_toolkit-[0-9]*:../../devel/py-prompt_toolkit  # prompt-toolkit 3.0.52
DEPENDS+=	${PYPKGPREFIX}-prompt_toolkit-[0-9]*:../../devel/py-prompt_toolkit  # prompt_toolkit 3.0.52
DEPENDS+=	${PYPKGPREFIX}-propcache-[0-9]*:../../devel/py-propcache  # propcache 0.3.1
DEPENDS+=	${PYPKGPREFIX}-protego-[0-9]*:../../www/py-protego  # protego 0.4.0
DEPENDS+=	protobuf-[0-9]*:../../devel/protobuf  # protobuf 5.29.3
DEPENDS+=	${PYPKGPREFIX}-psutil-[0-9]*:../../sysutils/py-psutil  # psutil 7.0.0
# pthread-stubs 0.3 is missing
DEPENDS+=	${PYPKGPREFIX}-ptyprocess-[0-9]*:../../sysutils/py-ptyprocess  # ptyprocess 0.7.0
# pure_eval 0.2.3 is missing
DEPENDS+=	${PYPKGPREFIX}-cpuinfo-[0-9]*:../../sysutils/py-cpuinfo  # py-cpuinfo 9.0.0
# py-lief 0.16.4 is missing
DEPENDS+=	${PYPKGPREFIX}-arrow-[0-9]*:../../time/py-arrow  # pyarrow 21.0.0
DEPENDS+=	${PYPKGPREFIX}-asn1-[0-9]*:../../security/py-asn1  # pyasn1 0.6.1
DEPENDS+=	${PYPKGPREFIX}-asn1-modules-[0-9]*:../../security/py-asn1-modules  # pyasn1-modules 0.4.2
# py-bind11-abi 5 is missing
DEPENDS+=	${PYPKGPREFIX}-cares-[0-9]*:../../net/py-cares  # pycares 4.10.0
DEPENDS+=	${PYPKGPREFIX}-codestyle-[0-9]*:../../devel/py-codestyle  # pycodestyle 2.12.1
DEPENDS+=	${PYPKGPREFIX}-cosat-[0-9]*:../../wip/py-cosat  # pycosat 0.6.6
DEPENDS+=	${PYPKGPREFIX}-cparser-[0-9]*:../../devel/py-cparser  # pycparser 2.23
DEPENDS+=	${PYPKGPREFIX}-ct-[0-9]*:../../wip/py-ct  # pyct 0.6.0
DEPENDS+=	${PYPKGPREFIX}-curl-[0-9]*:../../www/py-curl  # pycurl 7.45.7
DEPENDS+=	${PYPKGPREFIX}-pydantic-[0-9]*:../../devel/py-pydantic  # pydantic 2.12.4
DEPENDS+=	${PYPKGPREFIX}-pydantic-core-[0-9]*:../../devel/py-pydantic-core  # pydantic-core 2.41.5
DEPENDS+=	${PYPKGPREFIX}-pydantic-settings-[0-9]*:../../devel/py-pydantic-settings  # pydantic-settings 2.12.0
DEPENDS+=	${PYPKGPREFIX}-pydispatcher-[0-9]*:../../devel/py-pydispatcher  # pydispatcher 2.0.7
DEPENDS+=	${PYPKGPREFIX}-docstyle-[0-9]*:../../devel/py-docstyle  # pydocstyle 6.3.0
DEPENDS+=	${PYPKGPREFIX}-pyerfa-[0-9]*:../../math/py-pyerfa  # pyerfa 2.0.1.5
DEPENDS+=	${PYPKGPREFIX}-flakes-[0-9]*:../../devel/py-flakes  # pyflakes 3.2.0
# py-github 2.8.1 is missing
DEPENDS+=	${PYPKGPREFIX}-pygments-[0-9]*:../../textproc/py-pygments  # pygments 2.19.2
DEPENDS+=	${PYPKGPREFIX}-JWT-[0-9]*:../../textproc/py-JWT  # pyjwt 2.10.1
DEPENDS+=	${PYPKGPREFIX}-pylint-[0-9]*:../../devel/py-pylint  # pylint 3.3.8
DEPENDS+=	${PYPKGPREFIX}-pylint-venv-[0-9]*:../../wip/py-pylint-venv  # pylint-venv 3.0.3
DEPENDS+=	${PYPKGPREFIX}-pyls-spyder-[0-9]*:../../wip/py-pyls-spyder  # pyls-spyder 0.4.0
DEPENDS+=	${PYPKGPREFIX}-nacl-[0-9]*:../../security/py-nacl  # pynacl 1.6.0
# pyobjc-core nan is missing
# pyobjc-framework-cocoa nan is missing
# pyobjc-framework-coreservices nan is missing
# pyobjc-framework-fsevents nan is missing
# py-odbc 5.3.0 is missing
DEPENDS+=	${PYPKGPREFIX}-OpenSSL-[0-9]*:../../security/py-OpenSSL  # pyopenssl 25.3.0
DEPENDS+=	${PYPKGPREFIX}-pyparsing-[0-9]*:../../devel/py-pyparsing  # pyparsing 3.2.5
# py-qt 5.15.11 is missing
# py-qt5-sip 12.17.0 is missing
# py-qtwebengine 5.15.11 is missing
# pyside6 6.9.2 is skipped
DEPENDS+=	${PYPKGPREFIX}-Socks-[0-9]*:../../net/py-Socks  # pysocks 1.7.1
DEPENDS+=	${PYPKGPREFIX}-tables-[0-9]*:../../math/py-tables  # pytables 3.10.2
DEPENDS+=	${PYPKGPREFIX}-test-[0-9]*:../../devel/py-test  # pytest 8.4.2
# py-thon 3.13.9 is missing
DEPENDS+=	${PYPKGPREFIX}-dateutil-[0-9]*:../../time/py-dateutil  # python-dateutil 2.9.0post0
DEPENDS+=	${PYPKGPREFIX}-dotenv-[0-9]*:../../devel/py-dotenv  # python-dotenv 1.1.0
DEPENDS+=	${PYPKGPREFIX}-fastjsonschema-[0-9]*:../../textproc/py-fastjsonschema  # python-fastjsonschema 2.21.2
DEPENDS+=	${PYPKGPREFIX}-json-logger-[0-9]*:../../textproc/py-json-logger  # python-json-logger 3.2.1
DEPENDS+=	${PYPKGPREFIX}-libarchive-c-[0-9]*:../../archivers/py-libarchive-c  # python-libarchive-c 5.1
DEPENDS+=	${PYPKGPREFIX}-lmdb-[0-9]*:../../databases/py-lmdb  # python-lmdb 1.7.5
DEPENDS+=	${PYPKGPREFIX}-lsp-black-[0-9]*:../../wip/py-lsp-black  # python-lsp-black 2.0.0
DEPENDS+=	${PYPKGPREFIX}-lsp-jsonrpc-[0-9]*:../../textproc/py-lsp-jsonrpc  # python-lsp-jsonrpc 1.1.2
# py-lsp-ruff 2.3.0 is missing
DEPENDS+=	${PYPKGPREFIX}-lsp-server-[0-9]*:../../lang/py-lsp-server  # python-lsp-server 1.13.1
DEPENDS+=	${PYPKGPREFIX}-slugify-[0-9]*:../../devel/py-slugify  # python-slugify 8.0.4
DEPENDS+=	${PYPKGPREFIX}-tzdata-[0-9]*:../../time/py-tzdata  # python-tzdata 2025.2
# python.app nan is missing
# py-thon_abi 3.13 is missing
DEPENDS+=	${PYPKGPREFIX}-pytokens-[0-9]*:../../devel/py-pytokens  # pytokens 0.3.0
DEPENDS+=	${PYPKGPREFIX}-toolconfig-[0-9]*:../../devel/py-toolconfig  # pytoolconfig 1.2.6
DEPENDS+=	${PYPKGPREFIX}-pytz-[0-9]*:../../time/py-pytz  # pytz 2025.2
# py-uca 1.2 is missing
# py-viz_comms 3.0.6 is missing
DEPENDS+=	${PYPKGPREFIX}-pywavelets-[0-9]*:../../math/py-pywavelets  # pywavelets 1.9.0
# pywin32 nan is missing
# pywin32-ctypes nan is missing
# pywinpty nan is missing
DEPENDS+=	${PYPKGPREFIX}-xdg-[0-9]*:../../devel/py-xdg  # pyxdg 0.28
DEPENDS+=	${PYPKGPREFIX}-yaml-[0-9]*:../../textproc/py-yaml  # pyyaml 6.0.3
DEPENDS+=	${PYPKGPREFIX}-zmq-[0-9]*:../../net/py-zmq  # pyzmq 27.1.0
DEPENDS+=	${PYPKGPREFIX}-qdarkstyle-[0-9]*:../../wip/py-qdarkstyle  # qdarkstyle 3.2.3
# qstylizer 0.2.2 is skipped
# qt-main 5.15.2 is missing
# qt-webengine 5.15.9 is missing
DEPENDS+=	${PYPKGPREFIX}-qtawesome-[0-9]*:../../wip/py-qtawesome  # qtawesome 1.4.0
# qtbase 6.9.2 is missing
DEPENDS+=	${PYPKGPREFIX}-qtconsole-[0-9]*:../../wip/py-qtconsole  # qtconsole 5.7.0
# qtdeclarative 6.9.2 is missing
DEPENDS+=	${PYPKGPREFIX}-qtpy-[0-9]*:../../wip/py-qtpy  # qtpy 2.4.3
# qtshadertools 6.9.2 is missing
# qtsvg 6.9.2 is missing
# qttools 6.9.2 is missing
# qtwebchannel 6.9.2 is missing
# qtwebengine 6.9.2 is missing
# qtwebsockets 6.9.2 is missing
DEPENDS+=	${PYPKGPREFIX}-queuelib-[0-9]*:../../devel/py-queuelib  # queuelib 1.8.0
DEPENDS+=	re2-[0-9]*:../../devel/re2  # re2 2024.07.02
# readchar 4.2.1 is missing
DEPENDS+=	readline-[0-9]*:../../devel/readline  # readline 8.3
DEPENDS+=	${PYPKGPREFIX}-referencing-[0-9]*:../../textproc/py-referencing  # referencing 0.37.0
DEPENDS+=	${PYPKGPREFIX}-regex-[0-9]*:../../textproc/py-regex  # regex 2025.9.1
DEPENDS+=	reproc-[0-9]*:../../wip/reproc  # reproc 14.2.4
# reproc-cpp 14.2.4 is missing
DEPENDS+=	${PYPKGPREFIX}-requests-[0-9]*:../../devel/py-requests  # requests 2.32.5
DEPENDS+=	${PYPKGPREFIX}-requests-file-[0-9]*:../../devel/py-requests-file  # requests-file 2.1.0
DEPENDS+=	${PYPKGPREFIX}-requests-toolbelt-[0-9]*:../../devel/py-requests-toolbelt  # requests-toolbelt 1.0.0
DEPENDS+=	${PYPKGPREFIX}-rfc3339-validator-[0-9]*:../../time/py-rfc3339-validator  # rfc3339-validator 0.1.4
DEPENDS+=	${PYPKGPREFIX}-rfc3986-validator-[0-9]*:../../www/py-rfc3986-validator  # rfc3986-validator 0.1.1
DEPENDS+=	${PYPKGPREFIX}-rich-[0-9]*:../../comms/py-rich  # rich 14.2.0
# roman-numerals-py 3.1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-rope-[0-9]*:../../devel/py-rope  # rope 1.14.0
DEPENDS+=	${PYPKGPREFIX}-rpds-py-[0-9]*:../../devel/py-rpds-py  # rpds-py 0.28.0
DEPENDS+=	${PYPKGPREFIX}-rtree-[0-9]*:../../wip/py-rtree  # rtree 1.4.1
# ruamel.yaml 0.18.16 is missing
# ruamel.yaml.clib 0.2.14 is missing
# ruamel_yaml 0.17.21 is missing
DEPENDS+=	${PYPKGPREFIX}-ruff-[0-9]*:../../devel/py-ruff  # ruff 0.12.0
# s2n 1.5.14 is missing
# s3fs 2025.10.0 is skipped
DEPENDS+=	${PYPKGPREFIX}-scikit-image-[0-9]*:../../math/py-scikit-image  # scikit-image 0.25.2
DEPENDS+=	${PYPKGPREFIX}-scikit-learn-[0-9]*:../../math/py-scikit-learn  # scikit-learn 1.7.2
DEPENDS+=	${PYPKGPREFIX}-scipy-[0-9]*:../../math/py-scipy  # scipy 1.16.3
DEPENDS+=	${PYPKGPREFIX}-scrapy-[0-9]*:../../www/py-scrapy  # scrapy 2.13.3
DEPENDS+=	${PYPKGPREFIX}-seaborn-[0-9]*:../../graphics/py-seaborn  # seaborn 0.13.2
DEPENDS+=	${PYPKGPREFIX}-secretstorage-[0-9]*:../../security/py-secretstorage  # secretstorage 3.4.0
DEPENDS+=	${PYPKGPREFIX}-semver-[0-9]*:../../devel/py-semver  # semver 3.0.4
DEPENDS+=	${PYPKGPREFIX}-Send2Trash-[0-9]*:../../sysutils/py-Send2Trash  # send2trash 1.8.2
DEPENDS+=	${PYPKGPREFIX}-service_identity-[0-9]*:../../security/py-service_identity  # service_identity 24.2.0
DEPENDS+=	${PYPKGPREFIX}-setuptools-[0-9]*:../../devel/py-setuptools  # setuptools 80.9.0
DEPENDS+=	${PYPKGPREFIX}-shellingham-[0-9]*:../../misc/py-shellingham  # shellingham 1.5.4
# simdjson 3.10.1 is missing
DEPENDS+=	${PYPKGPREFIX}-sip6-[0-9]*:../../x11/py-sip6  # sip 6.12.0
DEPENDS+=	${PYPKGPREFIX}-six-[0-9]*:../../lang/py-six  # six 1.17.0
DEPENDS+=	${PYPKGPREFIX}-smmap-[0-9]*:../../devel/py-smmap  # smmap 4.0.0
DEPENDS+=	${PYPKGPREFIX}-snappy-[0-9]*:../../devel/py-snappy  # snappy 1.2.1
DEPENDS+=	${PYPKGPREFIX}-sniffio-[0-9]*:../../misc/py-sniffio  # sniffio 1.3.0
DEPENDS+=	${PYPKGPREFIX}-snowballstemmer-[0-9]*:../../textproc/py-snowballstemmer  # snowballstemmer 3.0.1
DEPENDS+=	${PYPKGPREFIX}-sortedcontainers-[0-9]*:../../devel/py-sortedcontainers  # sortedcontainers 2.4.0
DEPENDS+=	${PYPKGPREFIX}-soupsieve-[0-9]*:../../www/py-soupsieve  # soupsieve 2.5
DEPENDS+=	${PYPKGPREFIX}-sphinx-[0-9]*:../../textproc/py-sphinx  # sphinx 8.2.3
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-applehelp-[0-9]*:../../textproc/py-sphinxcontrib-applehelp  # sphinxcontrib-applehelp 2.0.0
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-devhelp-[0-9]*:../../textproc/py-sphinxcontrib-devhelp  # sphinxcontrib-devhelp 2.0.0
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-htmlhelp-[0-9]*:../../textproc/py-sphinxcontrib-htmlhelp  # sphinxcontrib-htmlhelp 2.1.0
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-jsmath-[0-9]*:../../textproc/py-sphinxcontrib-jsmath  # sphinxcontrib-jsmath 1.0.1
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-qthelp-[0-9]*:../../textproc/py-sphinxcontrib-qthelp  # sphinxcontrib-qthelp 2.0.0
DEPENDS+=	${PYPKGPREFIX}-sphinxcontrib-serializinghtml-[0-9]*:../../textproc/py-sphinxcontrib-serializinghtml  # sphinxcontrib-serializinghtml 2.0.0
DEPENDS+=	spirv-tools-[0-9]*:../../parallel/spirv-tools  # spirv-tools 2025.1
# spyder 6.1.0 is skipped
DEPENDS+=	${PYPKGPREFIX}-spyder-kernels-[0-9]*:../../wip/py-spyder-kernels  # spyder-kernels 3.1.1
DEPENDS+=	${PYPKGPREFIX}-sqlalchemy-[0-9]*:../../databases/py-sqlalchemy  # sqlalchemy 2.0.43
DEPENDS+=	sqlite3-[0-9]*:../../databases/sqlite3  # sqlite 3.51.0
# stack_data 0.6.3 is missing
DEPENDS+=	${PYPKGPREFIX}-statsmodels-[0-9]*:../../math/py-statsmodels  # statsmodels 0.14.5
# streamlit 1.51.0 is missing
# superqt 0.7.6 is missing
DEPENDS+=	${PYPKGPREFIX}-sympy-[0-9]*:../../math/py-sympy  # sympy 1.14.0
DEPENDS+=	${PYPKGPREFIX}-tabulate-[0-9]*:../../textproc/py-tabulate  # tabulate 0.9.0
# tapi nan is missing
# tbb 2022.0.0 is missing
# tbb-devel 2022.0.0 is missing
DEPENDS+=	${PYPKGPREFIX}-tblib-[0-9]*:../../wip/py-tblib  # tblib 3.1.0
DEPENDS+=	${PYPKGPREFIX}-tenacity-[0-9]*:../../devel/py-tenacity  # tenacity 9.1.2
DEPENDS+=	${PYPKGPREFIX}-terminado-[0-9]*:../../www/py-terminado  # terminado 0.18.1
DEPENDS+=	${PYPKGPREFIX}-text-unidecode-[0-9]*:../../textproc/py-text-unidecode  # text-unidecode 1.3
DEPENDS+=	${PYPKGPREFIX}-textdistance-[0-9]*:../../wip/py-textdistance  # textdistance 4.6.3
DEPENDS+=	${PYPKGPREFIX}-threadpoolctl-[0-9]*:../../parallel/py-threadpoolctl  # threadpoolctl 3.5.0
DEPENDS+=	${PYPKGPREFIX}-three-merge-[0-9]*:../../wip/py-three-merge  # three-merge 0.1.1
DEPENDS+=	${PYPKGPREFIX}-tifffile-[0-9]*:../../graphics/py-tifffile  # tifffile 2025.10.4
DEPENDS+=	${PYPKGPREFIX}-tinycss2-[0-9]*:../../textproc/py-tinycss2  # tinycss2 1.4.0
# tk 8.6.15 is skipped
DEPENDS+=	${PYPKGPREFIX}-tldextract-[0-9]*:../../net/py-tldextract  # tldextract 5.1.2
DEPENDS+=	${PYPKGPREFIX}-toml-[0-9]*:../../textproc/py-toml  # toml 0.10.2
DEPENDS+=	${PYPKGPREFIX}-tomli-[0-9]*:../../textproc/py-tomli  # tomli 2.2.1
DEPENDS+=	${PYPKGPREFIX}-tomlkit-[0-9]*:../../textproc/py-tomlkit  # tomlkit 0.13.3
DEPENDS+=	${PYPKGPREFIX}-toolz-[0-9]*:../../devel/py-toolz  # toolz 1.0.0
DEPENDS+=	${PYPKGPREFIX}-tornado-[0-9]*:../../www/py-tornado  # tornado 6.5.1
DEPENDS+=	${PYPKGPREFIX}-tqdm-[0-9]*:../../misc/py-tqdm  # tqdm 4.67.1
DEPENDS+=	${PYPKGPREFIX}-traitlets-[0-9]*:../../devel/py-traitlets  # traitlets 5.14.3
DEPENDS+=	${PYPKGPREFIX}-truststore-[0-9]*:../../security/py-truststore  # truststore 0.10.1
DEPENDS+=	${PYPKGPREFIX}-twisted-[0-9]*:../../net/py-twisted  # twisted 25.5.0
# twisted-iocpsupport nan is missing
DEPENDS+=	${PYPKGPREFIX}-typer-[0-9]*:../../wip/py-typer  # typer 0.20.0
# typer-slim 0.20.0 is missing
# typer-slim-standard 0.20.0 is missing
DEPENDS+=	${PYPKGPREFIX}-typing-extensions-[0-9]*:../../devel/py-typing-extensions  # typing-extensions 4.15.0
DEPENDS+=	${PYPKGPREFIX}-typing-inspection-[0-9]*:../../devel/py-typing-inspection  # typing-inspection 0.4.2
# typing_extensions 4.15.0 is missing
DEPENDS+=	${PYPKGPREFIX}-tzdata-[0-9]*:../../time/py-tzdata  # tzdata 2025b
DEPENDS+=	${PYPKGPREFIX}-uc-micro-py-[0-9]*:../../textproc/py-uc-micro-py  # uc-micro-py 1.0.3
# ucrt nan is missing
DEPENDS+=	${PYPKGPREFIX}-ujson-[0-9]*:../../textproc/py-ujson  # ujson 5.11.0
DEPENDS+=	unixodbc-[0-9]*:../../databases/unixodbc  # unixodbc 2.3.14
DEPENDS+=	${PYPKGPREFIX}-urllib3-[0-9]*:../../www/py-urllib3  # urllib3 2.5.0
DEPENDS+=	utf8proc-[0-9]*:../../converters/utf8proc  # utf8proc 2.6.1
DEPENDS+=	${PYPKGPREFIX}-uvloop-[0-9]*:../../devel/py-uvloop  # uvloop 0.22.1
# vc nan is missing
# vc14_runtime nan is missing
# vs2015_runtime nan is missing
DEPENDS+=	${PYPKGPREFIX}-w3lib-[0-9]*:../../www/py-w3lib  # w3lib 2.3.1
DEPENDS+=	${PYPKGPREFIX}-watchdog-[0-9]*:../../sysutils/py-watchdog  # watchdog 6.0.0
DEPENDS+=	${PYPKGPREFIX}-wcwidth-[0-9]*:../../devel/py-wcwidth  # wcwidth 0.2.13
DEPENDS+=	${PYPKGPREFIX}-webencodings-[0-9]*:../../textproc/py-webencodings  # webencodings 0.5.1
DEPENDS+=	${PYPKGPREFIX}-websocket-client-[0-9]*:../../www/py-websocket-client  # websocket-client 1.8.0
DEPENDS+=	${PYPKGPREFIX}-werkzeug-[0-9]*:../../www/py-werkzeug  # werkzeug 3.1.3
DEPENDS+=	${PYPKGPREFIX}-whatthepatch-[0-9]*:../../devel/py-whatthepatch  # whatthepatch 1.0.7
DEPENDS+=	${PYPKGPREFIX}-wheel-[0-9]*:../../devel/py-wheel  # wheel 0.45.1
DEPENDS+=	${PYPKGPREFIX}-widgetsnbextension-[0-9]*:../../www/py-widgetsnbextension  # widgetsnbextension 4.0.14
# win_inet_pton nan is missing
# winloop nan is missing
# winpty nan is missing
DEPENDS+=	${PYPKGPREFIX}-wrapt-[0-9]*:../../devel/py-wrapt  # wrapt 1.17.0
DEPENDS+=	${PYPKGPREFIX}-wurlitzer-[0-9]*:../../wip/py-wurlitzer  # wurlitzer 3.1.1
DEPENDS+=	${PYPKGPREFIX}-xarray-[0-9]*:../../math/py-xarray  # xarray 2025.10.1
DEPENDS+=	xcb-util-[0-9]*:../../x11/xcb-util  # xcb-util 0.4.1
DEPENDS+=	xcb-util-cursor-[0-9]*:../../x11/xcb-util-cursor  # xcb-util-cursor 0.1.5
DEPENDS+=	xcb-util-image-[0-9]*:../../x11/xcb-util-image  # xcb-util-image 0.4.0
DEPENDS+=	xcb-util-keysyms-[0-9]*:../../x11/xcb-util-keysyms  # xcb-util-keysyms 0.4.1
DEPENDS+=	xcb-util-renderutil-[0-9]*:../../x11/xcb-util-renderutil  # xcb-util-renderutil 0.3.10
DEPENDS+=	xcb-util-wm-[0-9]*:../../x11/xcb-util-wm  # xcb-util-wm 0.4.2
DEPENDS+=	xkeyboard-config-[0-9]*:../../x11/xkeyboard-config  # xkeyboard-config 2.44
# xlwings nan is missing
# xorg-libice 1.1.2 is missing
# xorg-libsm 1.2.6 is missing
# xorg-libx11 1.8.12 is missing
# xorg-libxau 1.0.12 is missing
# xorg-libxcomposite 0.4.6 is missing
# xorg-libxdamage 1.1.6 is missing
# xorg-libxdmcp 1.1.5 is missing
# xorg-libxext 1.3.6 is missing
# xorg-libxfixes 6.0.1 is missing
# xorg-libxi 1.8.2 is missing
# xorg-libxrandr 1.5.4 is missing
# xorg-libxrender 0.9.12 is missing
# xorg-libxshmfence 1.3.3 is missing
# xorg-libxtst 1.2.5 is missing
# xorg-libxxf86vm 1.1.6 is missing
# xorg-xorgproto 2024.1 is missing
DEPENDS+=	${PYPKGPREFIX}-xyzservices-[0-9]*:../../wip/py-xyzservices  # xyzservices 2025.4.0
DEPENDS+=	xz-[0-9]*:../../archivers/xz  # xz 5.6.4
DEPENDS+=	${PYPKGPREFIX}-yaml-[0-9]*:../../textproc/py-yaml  # yaml 0.2.5
DEPENDS+=	yaml-cpp-[0-9]*:../../textproc/yaml-cpp  # yaml-cpp 0.8.0
DEPENDS+=	${PYPKGPREFIX}-yapf-[0-9]*:../../devel/py-yapf  # yapf 0.43.0
DEPENDS+=	${PYPKGPREFIX}-yarl-[0-9]*:../../www/py-yarl  # yarl 1.22.0
DEPENDS+=	zeromq-[0-9]*:../../net/zeromq  # zeromq 4.3.5
DEPENDS+=	${PYPKGPREFIX}-zict-[0-9]*:../../wip/py-zict  # zict 3.0.0
DEPENDS+=	${PYPKGPREFIX}-zipp-[0-9]*:../../archivers/py-zipp  # zipp 3.23.0
DEPENDS+=	zlib-[0-9]*:../../devel/zlib  # zlib 1.3.1
DEPENDS+=	${PYPKGPREFIX}-zlib-ng-[0-9]*:../../archivers/py-zlib-ng  # zlib-ng 2.0.7
# zope 1.0 is missing
DEPENDS+=	${PYPKGPREFIX}-zope.interface-[0-9]*:../../devel/py-zope.interface  # zope.interface 8.0.1
DEPENDS+=	${PYPKGPREFIX}-zstandard-[0-9]*:../../archivers/py-zstandard  # zstandard 0.24.0
DEPENDS+=	zstd-[0-9]*:../../archivers/zstd  # zstd 1.5.7
