# $NetBSD$

DISTNAME=	pathtree-20140121
GITHUB_PROJECT=	pathtree
GITHUB_TAG=	41257a1839e945fce74afd070e02bab2ea2c776a
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=robfig/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/robfig/pathtree/
COMMENT=	Go pathtree
LICENSE=	mit

GO_DIST_BASE=   ${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=     github.com/robfig/${GITHUB_PROJECT}

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
