# $NetBSD: Makefile,v 1.3 2004/04/25 07:11:57 blef Exp $
#

DISTNAME=	cgic202
PKGNAME=	cgic-2.02
CATEGORIES=	www
MASTER_SITES=	http://www.boutell.com/cgic/

MAINTAINER=	cinnion@ka8zrt.com
HOMEPAGE=	http://www.boutell.com/cgic/
COMMENT=	Thomas Boutell's ANSI C library for CGI Programming

USE_BUILDLINK3=		yes
USE_LIBTOOL=		yes

.include "../../mk/bsd.pkg.mk"
