# $NetBSD: Makefile,v 1.4 2014/01/15 02:33:47 outpaddling Exp $
#

DISTNAME=	twintk-0.9.4.31
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=outpaddling/}
GITHUB_TAG=	da7813f93c7ba9c750490860d077f1ccad0e19dd

OWNER=		bacon@NetBSD.org
HOMEPAGE=	https://github.com/outpaddling/twintk
COMMENT=	Terminal Windows Toolkit
LICENSE=	2-clause-bsd

USE_TOOLS=	gmake

.include "../../wip/libxtend/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
