# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/18 11:00:32 thomasklausner Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBLINEBREAK_BUILDLINK3_MK:=	${LIBLINEBREAK_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	liblinebreak
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nliblinebreak}
BUILDLINK_PACKAGES+=	liblinebreak
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}liblinebreak

.if ${LIBLINEBREAK_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.liblinebreak+=	liblinebreak>=0.0.20080420
BUILDLINK_PKGSRCDIR.liblinebreak?=	../../wip/liblinebreak
.endif	# LIBLINEBREAK_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
