# $NetBSD$
# XXX	BUILDLINK_DEPMETHOD.fsom?=	build

BUILDLINK_TREE+=	fsom

.if !defined(FSOM_BUILDLINK3_MK)
FSOM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.fsom+=	fsom>=0.0.0.20151117
BUILDLINK_PKGSRCDIR.fsom?=	../../wip/fsom
.endif	# FSOM_BUILDLINK3_MK

BUILDLINK_TREE+=	-fsom
