# $NetBSD: Makefile,v 1.2 2004/08/02 17:19:05 minskim Exp $
#

DISTNAME=		wipe-2.2.0
CATEGORIES=		wip sysutils
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=wipe/}
EXTRACT_SUFX=		.tar.bz2

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://wipe.sourceforge.net/
COMMENT=		Secure data destruction

USE_BUILDLINK3=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
