# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/07/20 06:27:40 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
TAGSOUP_BUILDLINK3_MK:=	${TAGSOUP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	tagsoup
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ntagsoup}
BUILDLINK_PACKAGES+=	tagsoup
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}tagsoup

.if ${TAGSOUP_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.tagsoup?=	build
BUILDLINK_API_DEPENDS.tagsoup+=	tagsoup>=0.6
BUILDLINK_PKGSRCDIR.tagsoup?=	../../wip/tagsoup
.endif	# TAGSOUP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
