# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/05/03 16:53:43 poppnk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGTK_JAVA_BUILDLINK3_MK:=	${LIBGTK_JAVA_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libgtk-java
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgtk-java}
BUILDLINK_PACKAGES+=	libgtk-java

.if !empty(LIBGTK_JAVA_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libgtk-java+=	libgtk-java>=2.6.2
BUILDLINK_PKGSRCDIR.libgtk-java?=	../../wip/libgtk-java
.endif	# LIBGTK_JAVA_BUILDLINK3_MK

#CLASSPATH=${PREFIX}/share/java/gtk2.6.jar

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
