# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/04/29 16:04:20 dhowland Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_BEAUTIFULSOUP_BUILDLINK3_MK:=	${PY_BEAUTIFULSOUP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	py-BeautifulSoup
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Npy-BeautifulSoup}
BUILDLINK_PACKAGES+=	py-BeautifulSoup
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}py-BeautifulSoup

.if ${PY_BEAUTIFULSOUP_BUILDLINK3_MK} == "+"
.include "../../lang/python/pyversion.mk"
BUILDLINK_API_DEPENDS.py-BeautifulSoup+=	${PYPKGPREFIX}-BeautifulSoup>=3.0.4
BUILDLINK_PKGSRCDIR.py-BeautifulSoup?=	../../wip/py-BeautifulSoup
.endif	# PY_BEAUTIFULSOUP_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
