# $NetBSD: buildlink3.mk,v 1.1 2013/02/21 20:04:31 szptvlfn Exp $

BUILDLINK_TREE+=	hs-QIO

.if !defined(HS_QIO_BUILDLINK3_MK)
HS_QIO_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.hs-QIO+=	hs-QIO>=1.2
BUILDLINK_PKGSRCDIR.hs-QIO?=	../../wip/hs-QIO

.endif	# HS_QIO_BUILDLINK3_MK

BUILDLINK_TREE+=	-hs-QIO
