# $NetBSD: buildlink3.mk,v 1.2 2009/03/20 19:43:38 jsonn Exp $

BUILDLINK_TREE+=	HCL

.if !defined(HCL_BUILDLINK3_MK)
HCL_BUILDLINK3_MK:=

BUILDLINK_DEPMETHOD.HCL?=	build
BUILDLINK_API_DEPENDS.HCL+=	HCL>=1.3
BUILDLINK_PKGSRCDIR.HCL?=	../../wip/HCL
.endif # HCL_BUILDLINK3_MK

BUILDLINK_TREE+=	-HCL
