# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/11/17 09:26:01 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HCL_BUILDLINK3_MK:=	${HCL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	HCL
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NHCL}
BUILDLINK_PACKAGES+=	HCL
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}HCL

.if ${HCL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.HCL?=	build
BUILDLINK_API_DEPENDS.HCL+=	HCL>=1.3
BUILDLINK_PKGSRCDIR.HCL?=	../../wip/HCL
.endif	# HCL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
