# $NetBSD: buildlink3.mk,v 1.2 2008/04/16 12:05:16 asau Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MPICH_BUILDLINK3_MK:=	${MPICH_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	mpich
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmpich}
BUILDLINK_PACKAGES+=	mpich
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mpich

.if !empty(MPICH_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.mpich+=	mpich>=1.2.6
BUILDLINK_ABI_DEPENDS.mpich?=	mpich>=1.2.6nb3
BUILDLINK_PKGSRCDIR.mpich?=	../../wip/mpi-ch
BUILDLINK_DEPMETHOD.mpich?=	build
.endif	# MPICH_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
