# $NetBSD: Makefile,v 1.2 2012/10/07 11:54:39 asau Exp $
#

DISTNAME=	ghalatawi-0.2
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	textproc python arabic
MASTER_SITES=	http://pypi.python.org/packages/source/g/ghalatawi/
EXTRACT_SUFX=	.zip#md5=7afa6950e1786db9729f2582c451a2a9

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://ghalatawi.sourceforge.net/
COMMENT=	Ghalatawi: Arabic AUtocorrec
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
