
WITH P1, F1, C230063PROC, C23006EGFUNC;
WITH REPORT; USE REPORT;
PROCEDURE C23006E IS

     X1, X2 : INTEGER;
     PROCEDURE P2 IS NEW C230063PROC;
     FUNCTION F2 IS NEW C23006EGFUNC;

BEGIN
     TEST ("C23006E", "CHECK UNDERSCORES ARE SIGNIFICANT " &
                      "FOR GENERIC LIBRARY SUBPROGRAM IDENTIFIERS");

     P1 (X1);
     P2 (X2);
     IF X1 + IDENT_INT(1) /= X2 THEN
          FAILED ("INCORRECT PROCEDURE IDENTIFICATION");
     END IF;

     IF F1 + IDENT_INT(1) /= F2 THEN
          FAILED ("INCORRECT FUNCTION IDENTIFICATION");
     END IF;

     RESULT;
END C23006E; 
