# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:17:52 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBP11_BUILDLINK3_MK:=	${LIBP11_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libp11
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibp11}
BUILDLINK_PACKAGES+=	libp11

.if !empty(LIBP11_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libp11+=	libp11>=0.2.1
BUILDLINK_PKGSRCDIR.libp11?=	../../wip/libp11
.endif	# LIBP11_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
