# $NetBSD: buildlink3.mk,v 1.1 2003/11/25 03:48:25 minskim Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBGPG_ERROR_BUILDLINK3_MK:=	${LIBGPG_ERROR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M\+)
BUILDLINK_DEPENDS+=	libgpg-error
.endif

.if !empty(LIBGPG_ERROR_BUILDLINK3_MK:M\+)
BUILDLINK_DEPENDS.libgpg-error?=	libgpg-error>=0.5
BUILDLINK_PKGSRCDIR.libgpg-error?=	../../wip/libgpg-error
BUILDLINK_PACKAGES+=	libgpg-error
.endif # LIBGPG_ERROR_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:C/\+$//}
