.\"	$NetBSD$
.\"
.\" Copyright (c) 2023 The NetBSD Foundation, Inc.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to The NetBSD Foundation
.\" by Thomas Klausner.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
.\" ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
.\" TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
.\" PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd June 24, 2023
.Dt CVS2HG 1
.Os
.Sh NAME
.Nm cvs2hg
.Nd convert CVS repository to Mercurial
.Sh SYNOPSIS
.Nm
.Ar source
.Ar destination
.Sh DESCRIPTION
.Nm
is a script to convert a
.Xr cvs 1
repository to
.Xr hg 1
using
.Xr cvs2fossil 1 ,
.Xr git 1 ,
and
.Xr hg 1 .
.Pp
.Ar source
must be a CVS repository (the server side, i.e. the RCS files, not a
checkout).
.Nm
will create
.Ar destination Ns Pa .fossil
(the fossil conversion created by
.Xr cvs2fossil 1 ) ,
.Ar destination Ns Pa .git
(the git conversion created via the
.Xr git 1
fast-import file exported by
.Xr fossil 1 ) ,
and finally
.Ar destination Ns Pa .hg ,
the Mercurial repository created from the git one by
.Xr hg 1 .
.Sh EXAMPLES
To convert the NetBSD src repository, if you have developer access, do:
.Bd -literal -offset indent
export REPO=src
export LOGIN=username
rsync -aS --delete -e ssh "$USERNAME"@cvs.NetBSD.org::cvsroot/"$REPO" "$REPO"-rsync
cvs2hg "$REPO"-rsync/"$REPO" "$REPO"
.Ed
.Pp
The conversion is in
.Pa src.hg .
The intermediate fossil and git directories are
.Pa src.fossil
and
.Pa src.git ,
respectively.
You can delete them after the conversion.
.Sh BUGS
There is no way to provide an
.Pa authormap
file to convert Unix user names to email addresses.
