# $NetBSD: Makefile,v 1.3 2012/10/07 13:57:26 asau Exp $
#

DISTNAME=	plink
EGG_NAME=	${DISTNAME}-${VERSION}
PKGNAME=	${PYPKGPREFIX}-${EGG_NAME}
CATEGORIES=	graphics python
MASTER_SITES=	http://math.uic.edu/~t3m/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://math.uic.edu/~t3m/plink/
COMMENT=	Link Projection Editor
LICENSE=	gnu-gpl-v2

VERSION=	1.1

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
