# $NetBSD$

BSNES_PROFILE=	accuracy

.include "../../wip/libretro-bsnes-mercury/Makefile.common"

COMMENT=	Libretro core for (more) accurate SNES/Super Famicom emulation

.include "../../mk/bsd.pkg.mk"
