# $NetBSD: buildlink3.mk,v 1.3 2012/05/12 02:04:12 outpaddling Exp $

BUILDLINK_TREE+=	py26-ufl

.if !defined(PY26_UFL_BUILDLINK3_MK)
PY26_UFL_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ufl+=	${PYPKGPREFIX}-ufl>=1.0.0
BUILDLINK_PKGSRCDIR.ufl?=	../../wip/py-ufl
.endif	# PY26_UFL_BUILDLINK3_MK

BUILDLINK_TREE+=	-ufl
