# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/12 02:40:42 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MTL_BUILDLINK3_MK:=	${MTL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mtl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmtl}
BUILDLINK_PACKAGES+=	mtl
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mtl

.if ${MTL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.mtl?=	build
BUILDLINK_API_DEPENDS.mtl+=	mtl>=1.1.0.2
BUILDLINK_PKGSRCDIR.mtl?=	../../wip/hs-mtl
.endif	# MTL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
