# $NetBSD: buildlink3.mk,v 1.2 2009/01/12 06:10:46 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_MTL_BUILDLINK3_MK:=	${HS_MTL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-mtl
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-mtl}
BUILDLINK_PACKAGES+=	hs-mtl
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-mtl

.if ${HS_MTL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-mtl?=	build
BUILDLINK_API_DEPENDS.hs-mtl+=	hs-mtl>=1.1.0.2
BUILDLINK_PKGSRCDIR.hs-mtl?=	../../wip/hs-mtl
.endif	# HS_MTL_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
