# $NetBSD: Makefile,v 1.8 2014/05/08 00:29:55 szptvlfn Exp $

DISTNAME=	mtl-2.2.0.1
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Monad classes using functional dependencies
LICENSE=	modified-bsd

.include "../../mk/haskell.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
