# $NetBSD: buildlink3.mk,v 1.2 2008/02/17 22:16:30 bsadewitz Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBLO_BUILDLINK3_MK:=	${LIBLO_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	liblo
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nliblo}
BUILDLINK_PACKAGES+=	liblo
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}liblo

.if ${LIBLO_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.liblo+=	liblo>=0.23
BUILDLINK_PKGSRCDIR.liblo?=	../../wip/liblo
.endif	# LIBLO_BUILDLINK3_MK

.include "../../mk/pthread.buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
