# $NetBSD: Makefile,v 1.1 2013/11/25 11:31:34 szptvlfn Exp $

DISTNAME=	http-types-0.8.2
CATEGORIES=	www

MAINTAINER=	szptvlfn@a-net.email.ne.jp
COMMENT=	Generic HTTP types for Haskell (for both client and server code)
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-blaze-builder/buildlink3.mk"
.include "../../wip/hs-case-insensitive/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
