# $NetBSD: Makefile,v 1.2 2012/10/07 12:25:25 asau Exp $
#

DISTNAME=	Naftawayh-0.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	textproc python
MASTER_SITES=	${MASTER_SITE_PYPI:=N/Naftawayh/}
EXTRACT_SUFX=	.zip

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://naftawayh.sourceforge.net/
COMMENT=	Naftawayh: Arabic word tagger
LICENSE=	gnu-gpl-v3

USE_LANGUAGES=	# none
PYDISTUTILSPKG=	yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
