# $NetBSD$

BUILDLINK_TREE+=	go-ewma

.if !defined(GO_EWMA_BUILDLINK3_MK)
GO_EWMA_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-ewma=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-ewma?=		build

BUILDLINK_API_DEPENDS.go-ewma+=	go-ewma>=20201215
BUILDLINK_PKGSRCDIR.go-ewma?=	../../wip/go-ewma
.endif	# GO_EWMA_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-ewma
