# $NetBSD$

BUILDLINK_TREE+=	ewma

.if !defined(EWMA_BUILDLINK3_MK)
EWMA_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.ewma=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.ewma?=	build

BUILDLINK_API_DEPENDS.ewma+=	ewma>=20201216
BUILDLINK_PKGSRCDIR.ewma?=	../../wip/go-ewma
.endif	# EWMA_BUILDLINK3_MK

BUILDLINK_TREE+=	-ewma
