# $NetBSD: Makefile,v 1.2 2014/05/05 00:03:06 szptvlfn Exp $

DISTNAME=	wai-1.4.1
CATEGORIES=	www

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Web Application Interface
LICENSE=	mit

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-blaze-builder/buildlink3.mk"
.include "../../wip/hs-conduit/buildlink3.mk"
.include "../../wip/hs-http-types/buildlink3.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../wip/hs-text/buildlink3.mk"
.include "../../wip/hs-transformers/buildlink3.mk"
.include "../../wip/hs-vault/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
