# $NetBSD: Makefile,v 1.2 2006/12/18 18:59:56 cheusov Exp $

.include "../../wip/heirloom-common/Makefile.prog2.common"

PKGNAME=	heirloom-listusers-${HEIRLOOM_VER}
CATEGORIES=	textproc

MAKE_FLAGS+=	SUBDIRS="libcommon build listusers"

.include "../../mk/bsd.pkg.mk"
