# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/12 07:07:18 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
STM_BUILDLINK3_MK:=	${STM_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	stm
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nstm}
BUILDLINK_PACKAGES+=	stm
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}stm

.if ${STM_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.stm?=	build
BUILDLINK_API_DEPENDS.stm+=	stm>=2.1.1.2
BUILDLINK_PKGSRCDIR.stm?=	../../wip/stm
.endif	# STM_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
