# $NetBSD$

BUILDLINK_TREE+=	openjfx23

.if !defined(OPENJFX23_BUILDLINK3_MK)
OPENJFX23_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.openjfx23+=	openjfx23>=23
BUILDLINK_PKGSRCDIR.openjfx23?=		../../x11/openjfx23

.endif	# OPENJFX23_BUILDLINK3_MK

BUILDLINK_TREE+=	-openjfx23
