# $NetBSD: Makefile,v 1.3 2005/05/24 10:31:46 rillig Exp $
#

DISTNAME=	tv-0.3
PKGNAME=        treeviewx-0.3
CATEGORIES=	biology
MASTER_SITES=	http://darwin.zoology.gla.ac.uk/~rpage/treeviewx/

MAINTAINER=	hdp@cs.nmsu.edu
HOMEPAGE=       http://darwin.zoology.gla.ac.uk/~rpage/treeviewx/index.html
COMMENT=	Phylogenetic tree viewer for Linux and Unix

USE_TOOLS+= gmake
GNU_CONFIGURE=	YES

.include "../../x11/wxGTK/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
