# $NetBSD: Makefile,v 1.1.1.1 2009/01/12 03:27:58 phonohawk Exp $
#

DISTNAME=	haskell-src-exts-0.4.8
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://www.cs.chalmers.se/~d00nibro/haskell-src-exts/
COMMENT=	Manipulating Haskell source

.include "../../wip/mk/haskell.mk"
.include "../../wip/cpphs/buildlink3.mk"
.include "../../wip/happy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
