# $NetBSD$

BUILDLINK_TREE+=	SSVEntitySystem

.if !defined(SSVENTITYSYSTEM_BUILDLINK3_MK)
SSVENTITYSYSTEM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVEntitySystem+=	SSVEntitySystem>=20130704
BUILDLINK_PKGSRCDIR.SSVEntitySystem?=	../../wip/SSVEntitySystem

BUILDLINK_FILES.SSVEntitySystem+=	lib/cmake/FindSSVEntitySystem.cmake

.endif	# SSVENTITYSYSTEM_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVEntitySystem
