# $NetBSD$

BUILDLINK_TREE+=	SSVEntitySystem

.if !defined(SSVENTITYSYSTEM_BUILDLINK3_MK)
SSVENTITYSYSTEM_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SSVEntitySystem+=	SSVEntitySystem>=20130704
BUILDLINK_PKGSRCDIR.SSVEntitySystem?=	../../wip/SSVEntitySystem

SSVENTITYSYSTEM_MODULE=	${PREFIX}/lib/cmake/SSVEntitySystem

.endif	# SSVENTITYSYSTEM_BUILDLINK3_MK

BUILDLINK_TREE+=	-SSVEntitySystem
