# $NetBSD: Makefile,v 1.1.1.1 2004/06/09 23:21:59 xtraeme Exp $

.include "Makefile.common"

USE_X11=	yes
COMMENT=	Graphics library for the dynamic creation of images (X11)

.include "../../graphics/xpm/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
