$NetBSD$

Let pkgsrc fetch it.

--- Cargo.toml.orig	2025-02-18 10:10:08.307339456 +0000
+++ Cargo.toml
@@ -15,7 +15,7 @@ pkg-url = "{ repo }/releases/download/v{
 
 
 [dependencies]
-ansi-to-tui = { git = "https://github.com/Cretezy/ansi-to-tui.git", rev = "74bd97e" }
+ansi-to-tui = { path = "../ansi-to-tui-74bd97e76066186cace33ea04cf497055db67e62/" }
 anyhow = "1.0.95"
 chrono = "0.4.39"
 clap = { version = "4.5.27", features = ["derive"] }
