# $NetBSD: Makefile,v 1.2 2011/01/12 02:34:04 phonohawk Exp $
#

DISTNAME=	deepseq-1.1.0.2
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fully evaluate data structures
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
