# $NetBSD: buildlink3.mk,v 1.1 2008/06/08 23:42:41 zul_ Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
XMONAD_BUILDLINK3_MK:=	${XMONAD_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	xmonad
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxmonad}
BUILDLINK_PACKAGES+=	xmonad
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}xmonad

.if ${XMONAD_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.xmonad?=	build
BUILDLINK_API_DEPENDS.xmonad+=	xmonad>=0.7
BUILDLINK_PKGSRCDIR.xmonad?=	../../wip/xmonad
.endif	# XMONAD_BUILDLINK3_MK

.include "../../lang/ghc/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
