$NetBSD: patch-four-bar-ui_Cargo.toml,v 1.3 2024/09/15 17:31:39 pin Exp $

Don't pull git version of ron.

--- four-bar-ui/Cargo.toml.orig	2024-09-15 16:52:44.001589626 +0000
+++ four-bar-ui/Cargo.toml
@@ -40,7 +40,7 @@ image = { version = "0.25", default-feat
     "gif",
 ] }
 rfd = "0.14"
-ron = { git = "https://github.com/ron-rs/ron" }
+ron = "0.8.1"
 serde = { version = "1", features = ["derive"] }
 smartcore = { version = "0.3", features = ["ndarray-bindings"] }
 
