$NetBSD$

Don't pull git version of ron.

--- four-bar-ui/Cargo.toml.orig	2024-09-11 06:05:13.864770477 +0000
+++ four-bar-ui/Cargo.toml
@@ -40,7 +40,7 @@ image = { version = "0.25", default-feat
     "gif",
 ] }
 rfd = "0.14"
-ron = { git = "https://github.com/ron-rs/ron" }
+ron = "0.8.1"
 serde = { version = "1", features = ["derive"] }
 smartcore = { version = "0.3", features = ["ndarray-bindings"] }
 
