# $NetBSD: Makefile,v 1.9 2013/08/21 13:08:12 szptvlfn Exp $
#

DISTNAME=	haskell-src-exts-1.14.0
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/happy/buildlink3.mk"
.include "../../wip/hs-cpphs/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
