# $NetBSD: Makefile,v 1.8 2013/03/01 21:08:04 szptvlfn Exp $
#

DISTNAME=	haskell-src-exts-1.13.5
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Manipulating Haskell source
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/happy/buildlink3.mk"
.include "../../wip/hs-cpphs/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
