# $NetBSD$

BUILDLINK_TREE+=	XSB

.if !defined(XSB_BUILDLINK3_MK)
XSB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.XSB+=	XSB>=5.0
BUILDLINK_PKGSRCDIR.XSB?=	../../wip/xsb

XSBDIR=			${BUILDLINK_PREFIX.XSB}/xsb-5.0.0
XSBARCHDIR=		${XSBDIR}/config/local
XSBLIBDIR=		${XSBARCHDIR}/bin

BUILDLINK_INCDIRS.XSB+=		${XSBARCHDIR} ${XSBDIR}/emu
BUILDLINK_LDFLAGS.XSB+=		${COMPILER_RPATH_FLAG}${XSBLIBDIR}
BUILDLINK_LIBDIRS.XSB+=		${XSBLIBDIR}

.endif	# XSB_BUILDLINK3_MK

BUILDLINK_TREE+=	-XSB
