# $NetBSD$

BUILDLINK_TREE+=	xsb

.if !defined(XSB_BUILDLINK3_MK)
XSB_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.xsb+=	xsb>=5.0
BUILDLINK_PKGSRCDIR.xsb?=	../../wip/xsb

XSBDIR=			${BUILDLINK_PREFIX.xsb}/xsb-5.0.0
XSBARCHDIR=		${XSBDIR}/config/${MACHINE_GNU_PLATFORM}
XSBLIBDIR=		${XSBARCHDIR}/bin

BUILDLINK_INCDIRS.xsb+=		${XSBARCHDIR} ${XSBDIR}/emu
BUILDLINK_LDFLAGS.xsb+=		${COMPILER_RPATH_FLAG}${XSBLIBDIR}
BUILDLINK_LIBDIRS.xsb+=		${XSBLIBDIR}

.endif	# XSB_BUILDLINK3_MK

BUILDLINK_TREE+=	-xsb
