$NetBSD$

Point workspace to patched location.

--- crates/uv-client/Cargo.toml.orig	2025-03-06 10:25:42.144348326 +0000
+++ crates/uv-client/Cargo.toml
@@ -49,7 +49,7 @@ serde = { workspace = true }
 serde_json = { workspace = true }
 sys-info = { workspace = true }
 thiserror = { workspace = true }
-tl = { workspace = true }
+tl = { path = "../../../tl-6e25b2ee2513d75385101a8ff9f591ef51f314ec" }
 tokio = { workspace = true }
 tokio-util = { workspace = true }
 tracing = { workspace = true }
