# $NetBSD: buildlink3.mk,v 1.3 2007/08/15 22:16:03 shindenmorr Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBGADU_BUILDLINK3_MK:=	${LIBGADU_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libgadu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibgadu}
BUILDLINK_PACKAGES+=	libgadu
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libgadu

.if !empty(LIBGADU_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libgadu+=	libgadu>=1.7.1
BUILDLINK_ABI_DEPENDS.libgadu+=	libgadu>=1.7.1
BUILDLINK_PKGSRCDIR.libgadu?=	../../wip/libgadu
.endif	# LIBGADU_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
