# $NetBSD: buildlink3.mk,v 1.1 2004/05/12 12:39:44 thomasklausner Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
COM_ERR_BUILDLINK3_MK:=	${COM_ERR_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	com_err
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncom_err}
BUILDLINK_PACKAGES+=	com_err

.if !empty(COM_ERR_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.com_err+=	com_err>=1.35
BUILDLINK_PKGSRCDIR.com_err?=	../../wip/com_err

BUILDLINK_FILES.com_err+=	share/et/*
BUILDLINK_PASSTHRU_DIRS=	${LOCALBASE}/share/et
.endif	# COM_ERR_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
