# $NetBSD: buildlink3.mk,v 1.2 2006/12/16 18:41:46 cheusov Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBUXRE_BUILDLINK3_MK:=	${LIBUXRE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libuxre
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibuxre}
BUILDLINK_PACKAGES+=	libuxre

.if ${LIBUXRE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libuxre+=	libuxre>=060122
BUILDLINK_PKGSRCDIR.libuxre?=	../../wip/libuxre
BUILDLINK_INCDIRS.libuxre+=	include/uxre
.endif	# LIBUXRE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
