# $NetBSD: buildlink3.mk,v 1.3 2007/01/13 10:55:55 cheusov Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBUXRE_BUILDLINK3_MK:=	${LIBUXRE_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libuxre
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibuxre}
BUILDLINK_PACKAGES+=	libuxre
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libuxre

.if ${LIBUXRE_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libuxre+=	libuxre>=060122
BUILDLINK_PKGSRCDIR.libuxre?=	../../wip/libuxre
BUILDLINK_INCDIRS.libuxre+=	include/uxre
.endif	# LIBUXRE_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
