# $NetBSD$

BUILDLINK_TREE+=	iir1

.if !defined(IIR1_BUILDLINK3_MK)
IIR1_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.iir1+=	iir1>=1.9.4
BUILDLINK_PKGSRCDIR.iir1?=	../../wip/iir1
.endif	# IIR1_BUILDLINK3_MK

BUILDLINK_TREE+=	-iir1
