# $NetBSD: buildlink3.mk,v 1.2 2007/08/02 15:13:19 makoto Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
GOOCANVAS_BUILDLINK3_MK:=	${GOOCANVAS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	goocanvas
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngoocanvas}
BUILDLINK_PACKAGES+=	goocanvas
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}goocanvas

.if ${GOOCANVAS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.goocanvas+=	goocanvas>=0.4
BUILDLINK_PKGSRCDIR.goocanvas?=	../../wip/goocanvas
.endif	# GOOCANVAS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}

.include "../../x11/gtk2/buildlink3.mk"
