
WITH C23006DPKG, C23006D_INST;
USE C23006D_INST;
WITH REPORT; USE REPORT;
PROCEDURE C23006D IS

     PACKAGE P2 IS NEW C23006DPKG;
     USE P2;

BEGIN
     TEST ("C23006D", "CHECK UNDERSCORES ARE SIGNIFICANT " &
                      "FOR GENERIC LIBRARY PACKAGE IDENTIFIERS");

     IF A + IDENT_INT(4) /= D THEN
          FAILED ("INCORRECT PACKAGE IDENTIFICATION - 1");
     END IF;

     RESULT;
END C23006D;
