@comment $NetBSD: PLIST.sh,v 1.2 2004/01/30 13:10:52 marttikuparinen Exp $
include/asm/addrspace.h
include/asm/bigsur.h
include/asm/cachectl.h
include/asm/dc_sysasic.h
include/asm/ec3104.h
include/asm/hd64461.h
include/asm/hd64465.h
include/asm/hd64465_gpio.h
include/asm/hitachi_7751se.h
include/asm/hitachi_hs7729pci.h
include/asm/hitachi_se.h
include/asm/hitachi_shmse.h
include/asm/hw_irq.h
include/asm/init.h
include/asm/io_7751se.h
include/asm/io_adx.h
include/asm/io_bigsur.h
include/asm/io_cat68701.h
include/asm/io_dc.h
include/asm/io_ec3104.h
include/asm/io_generic.h
include/asm/io_hd64461.h
include/asm/io_hd64465.h
include/asm/io_hs7729pci.h
include/asm/io_keywest.h
include/asm/io_microdev.h
include/asm/io_se.h
include/asm/io_sh2000.h
include/asm/io_shmse.h
include/asm/io_snapgear.h
include/asm/io_unknown.h
include/asm/ipc.h
include/asm/irq-sh7300.h
include/asm/irq_microdev.h
include/asm/keyboard-ec3104.h
include/asm/keyboard-hs7729pci.h
include/asm/keyboard.h
include/asm/kgdb.h
include/asm/linux_logo.h
include/asm/machvec.h
include/asm/machvec_init.h
include/asm/mc146818rtc.h
include/asm/mmzone.h
include/asm/parport.h
include/asm/pci-sh7751.h
include/asm/pgtable-2level.h
include/asm/rtc.h
include/asm/semaphore-helper.h
include/asm/serial-bigsur.h
include/asm/serial-ec3104.h
include/asm/serial.h
include/asm/sh_bios.h
include/asm/smc37c93x.h
include/asm/smp.h
include/asm/spinlock.h
include/asm/ubc.h
include/asm/ucontext.h
