# $NetBSD: Makefile,v 1.4 2006/05/19 16:51:37 ykomatsu Exp $
# $Id: Makefile,v 1.4 2006/05/19 16:51:37 ykomatsu Exp $
#

DISTNAME=		binutils-2.14.90.0.8-i486-1
PKGNAME=		slackware_binutils-2.14.90.0.8
CATEGORIES=		emulators
MASTER_SITES=		${SLACKWARE_MASTER_SITES}

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://slackware.com/
COMMENT=		binutils for Slackware development

SLACK_GROUP=	        d

.include "../../wip/slackware_compat/Makefile.common"
.include "../../mk/bsd.pkg.mk"
