# $NetBSD: buildlink3.mk,v 1.1.1.1 2004/09/01 16:01:22 adrian_p Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBSPF2_BUILDLINK3_MK:=	${LIBSPF2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libspf2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibspf2}
BUILDLINK_PACKAGES+=	libspf2

.if !empty(LIBSPF2_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libspf2+=	libspf2>=1.0.4
BUILDLINK_PKGSRCDIR.libspf2?=	../../wip/libspf2
BUILDLINK_FILES.libspf2+=	include/spf2/*
BUILDLINK_FILES.libspf2+=	lib/libspf2.*
.endif	# LIBSPF2_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
