# $NetBSD: buildlink3.mk,v 1.1 2004/03/29 23:39:27 mpasternak Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
PY_TWISTED_BUILDLINK3_MK:=	${PY_TWISTED_BUILDLINK3_MK}+

.include "../../lang/python/pyversion.mk"

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	${PYPKGPREFIX}-twisted
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:N${PYPKGPREFIX}-twisted}
BUILDLINK_PACKAGES+=	${PYPKGPREFIX}-twisted

.if !empty(PY_TWISTED_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.${PYPKGPREFIX}-twisted+=	${PYPKGPREFIX}-twisted>=1.2.0
BUILDLINK_PKGSRCDIR.${PYPKGPREFIX}-twisted?=	../../wip/py-twisted
.endif	# PY_TWISTED_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
