# $NetBSD: Makefile,v 1.1.1.1 2009/05/23 07:36:36 phonohawk Exp $
#

DISTNAME=	network-bytestring-0.1.2.1
CATEGORIES=	net

MAINTAINER=	pho@cielonegro.org
COMMENT=	Fast, memory-efficient, low-level networking

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-network/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
