# $NetBSD$

BUILDLINK_TREE+=	libADLMIDI

.if !defined(LIBADLMIDI_BUILDLINK3_MK)
LIBADLMIDI_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.libADLMIDI+=	libADLMIDI>=1.6.1
BUILDLINK_PKGSRCDIR.libADLMIDI?=	../../wip/libADLMIDI

.endif # LIBADLMIDI_BUILDLINK3_MK

BUILDLINK_TREE+=	-libADLMIDI
