.\"	$NetBSD: pkg_src_micro_summary.1,v 1.1 2008/02/11 19:14:48 cheusov Exp $
.\"
.\" Copyright (c) 2008 by Aleksey Cheusov (vle@gmx.net)
.\" Absolutely no warranty.
.\"
.Dd Jan 29, 2008
.Dt PKG_SRC_MICRO_SUMMARY 1
.Sh NAME
.Nm pkg_src_micro_summary
.Nd build summary information for source packages
.Sh SYNOPSIS
.Nm
.Op Ar category1/pkg1 category2/pkg2 ...
.Sh DESCRIPTION
.Nm
builds micro summary information about source packages specified in
arguments or read from stdin (one package per line).  The word micro
means that only PKGNAME and PKGPATH fields are generated. Format of
this summary is the same as used in pkg_summary.gz built from binary
packages. Fields (PKGNAME, PKGPATH, DEPENDS etc.) are very similar but
not fully the same. The main advantage of this utility is that is
works DRAMMATICALLY faster than pkg_src_summary in most cases.  This
is possible because special hack is used (only when it is possible!)
to fetch PKGNAME instead of running make. And for ~90% of all packages
(pkgsrc + wip) it is possible to use this hack. So
pkg_src_micro_summary works approximately 10 times faster than
pkg_src_summary.
.Sh ENVIRONMENT
.Bd -literal
.Bl -tag -width Cm
.It Cm PKGSRCDIR
pkgsrc root directory, defaults to /usr/pkgsrc
.It Cm BMAKE
path to pkgsrc friendly make utility, defaults to make
.El
.Ed
.Sh EXAMPLES
.Bd -literal
pkg_src_micro_summary wip/dict-server wip/dict-mueller7 x11/xxkb
printf 'wip/dict-server\\ntextproc/dictem\\n' | pkg_src_micro_summary
.Ed
.Sh SEE ALSO
.Xr pkg_src_summary 1 ,
.Xr pkg_info 1 ,
.Sh AUTHOR
.An Aleksey Cheusov
.Aq vle@gmx.net
