# $NetBSD$

DISTNAME=	mewn-20200701
PKGNAME=	go-${DISTNAME}
GITHUB_PROJECT=	mewn
GITHUB_TAG=	bf7fd609ac1bdb1bdbffd9332021aa9fe9604d6d
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=leaanthony/}

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	https://github.com/leaanthony/mewn/
COMMENT=	Zero dependency asset embedder for Go
LICENSE=	mit

GO_DIST_BASE=	${GITHUB_PROJECT}-${GITHUB_TAG}
GO_SRCPATH=	github.com/leaanthony/mewn

.include "../../lang/go/go-package.mk"
.include "../../mk/bsd.pkg.mk"
