# $NetBSD$

DISTNAME=	biolibc-0.1.0.40
CATEGORIES=	biology
MASTER_SITES=	${MASTER_SITE_GITHUB:=auerlab/}
GITHUB_PROJECT=	biolibc
GITHUB_TAG=	632eb8b13d8bfa5e2a1ab76b112c33a9d4e360e1

MAINTAINER=	bacon@NetBSD.org
HOMEPAGE=	https://github.com/auerlab/vcfio
COMMENT=	Low-level high-performance bioinformatics library
LICENSE=	2-clause-bsd

.include "../../mk/bsd.pkg.mk"
