# $NetBSD$

BUILDLINK_TREE+=	ggml

.if !defined(GGML_BUILDLINK3_MK)
GGML_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ggml+=	ggml>=0.15.3
BUILDLINK_PKGSRCDIR.ggml?=	../../wip/ggml

.endif	# GGML_BUILDLINK3_MK

BUILDLINK_TREE+=	-ggml
