#
# $NetBSD: Makefile.common,v 1.5 2005/02/16 22:24:25 airhead Exp $
#
# Common Makefile for packages that are installed using scsh-install-lib
#

#
# XXX: This should actually be moved to shells/scsh/Makefile.common or
#       something
#
BUILD_DEPENDS+=		scsh>=0.6:../../shells/scsh
BUILD_DEPENDS+=		scsh-install-lib>=1:../../wip/scsh-install-lib

NO_BUILD=		yes

do-install:
	cd ${WRKSRC}; \
	scsh-install-pkg --prefix=${PREFIX} \
			 --layout fhs \
			 --verbose
