# $NetBSD: buildlink3.mk,v 1.1 2008/06/01 02:28:14 tnn2 Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
FIREFOX_BUILDLINK3_MK:=	${FIREFOX_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=		firefox
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nfirefox}
BUILDLINK_PACKAGES+=	firefox
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}firefox

.if !empty(FIREFOX_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.firefox+=	firefox>=3.0rc1
BUILDLINK_PKGSRCDIR.firefox?=	../../wip/firefox
.endif	# FIREFOX_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
