# $NetBSD$

BUILDLINK_TREE+=	csv2

.if !defined(CSV2_BUILDLINK3_MK)
CSV2_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.csv2+=	csv2>=0.1
BUILDLINK_PKGSRCDIR.csv2?=	../../wip/csv2
BUILDLINK_DEPMETHOD.csv2?=	build
.endif	# CSV2_BUILDLINK3_MK

BUILDLINK_TREE+=	-csv2
