$NetBSD$

download this separately

--- Cargo.toml.orig	2026-04-09 12:29:53.791895196 +0000
+++ Cargo.toml
@@ -44,4 +44,4 @@ vstorage = { version = "0.7.0", default-features = fal
 vstorage = { version = "0.7.0", default-features = false }
 
 [patch.crates-io]
-hashify = { git = "https://github.com/WhyNotHugo/hashify/", branch = "reproducible-builds" }
+hashify = { path = "../hashify-242c78f03ce1eea42c273912395e880c72d69b23" }
