# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/05/25 10:21:57 larnor Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MEANWHILE_BUILDLINK3_MK:=	${MEANWHILE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	meanwhile
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmeanwhile}
BUILDLINK_PACKAGES+=	meanwhile

.if !empty(MEANWHILE_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.meanwhile+=	meanwhile>=1.0.2
BUILDLINK_PKGSRCDIR.meanwhile?=	../../wip/meanwhile
.endif	# MEANWHILE_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
