# $NetBSD: buildlink3.mk,v 1.1 2005/01/05 22:50:05 mreriksson Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
LIBWBXML2_BUILDLINK3_MK:=	${LIBWBXML2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libwbxml2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibwbxml2}
BUILDLINK_PACKAGES+=	libwbxml2

.if !empty(LIBWBXML2_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libwbxml2+=	libwbxml2>=0.9.0
BUILDLINK_RECOMMENDED.libwbxml2+=	libwbxml2>=0.9.0
BUILDLINK_PKGSRCDIR.libwbxml2?=		../../wip/libwbxml2-patched
.endif	# LIBWBXML2_BUILDLINK_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
