@comment $NetBSD: PLIST.java,v 1.1 2013/09/25 22:22:20 ryo-on Exp $
${PKGNAME}/program/classes/ScriptFramework.jar
${PKGNAME}/program/classes/ScriptProviderForBeanShell.jar
${PKGNAME}/program/classes/ScriptProviderForJava.jar
${PKGNAME}/program/classes/ScriptProviderForJavaScript.jar
${PKGNAME}/program/classes/XMergeBridge.jar
${PKGNAME}/program/classes/bsh.jar
${PKGNAME}/program/classes/commons-logging-1.1.1.jar
${PKGNAME}/program/classes/commonwizards.jar
${PKGNAME}/program/classes/flow-engine-0.9.4.jar
${PKGNAME}/program/classes/flute-1.1.6.jar
${PKGNAME}/program/classes/form.jar
${PKGNAME}/program/classes/js.jar
${PKGNAME}/program/classes/libbase-1.1.6.jar
${PKGNAME}/program/classes/libfonts-1.1.6.jar
${PKGNAME}/program/classes/libformula-1.1.7.jar
${PKGNAME}/program/classes/liblayout-0.2.10.jar
${PKGNAME}/program/classes/libloader-1.1.6.jar
${PKGNAME}/program/classes/librepository-1.1.6.jar
${PKGNAME}/program/classes/libserializer-1.1.6.jar
${PKGNAME}/program/classes/libxml-1.1.7.jar
${PKGNAME}/program/classes/officebean.jar
${PKGNAME}/program/classes/query.jar
${PKGNAME}/program/classes/report.jar
${PKGNAME}/program/classes/reportbuilder.jar
${PKGNAME}/program/classes/reportbuilderwizard.jar
${PKGNAME}/program/classes/sac.jar
${PKGNAME}/program/classes/sdbc_hsqldb.jar
${PKGNAME}/program/classes/smoketest.jar
${PKGNAME}/program/classes/table.jar
${PKGNAME}/program/classes/unoil.jar
${PKGNAME}/program/classes/xmerge.jar
${PKGNAME}/program/libhsqldb.so
${PKGNAME}/program/libjdbclo.so
${PKGNAME}/program/libofficebean.so
${PKGNAME}/program/services/scriptproviderforbeanshell.rdb
${PKGNAME}/program/services/scriptproviderforjavascript.rdb
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/InstallationFinder$StreamGobbler.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/InstallationFinder.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/Loader$CustomURLClassLoader.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/Loader$Drain.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/Loader.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/WinRegKey.class
${PKGNAME}/sdk/classes/com/sun/star/lib/loader/WinRegKeyException.class
${PKGNAME}/sdk/classes/win/unowinreg.dll
${PKGNAME}/sdk/docs/java/ref/allclasses-frame.html
${PKGNAME}/sdk/docs/java/ref/allclasses-noframe.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/Bootstrap.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/BootstrapException.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/ComponentContext.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/ComponentContextEntry.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/SharedLibraryLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/UnoInfo.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/Bootstrap.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/BootstrapException.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/ComponentContext.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/ComponentContextEntry.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/SharedLibraryLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/class-use/UnoInfo.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/package-frame.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/package-summary.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/package-tree.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/comp/helper/package-use.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/ComponentBase.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/Factory.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/InterfaceContainer.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/MultiTypeInterfaceContainer.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/PropertySet.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/PropertySetMixin.BoundListeners.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/PropertySetMixin.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/UnoUrl.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/WeakAdapter.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/WeakBase.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/ComponentBase.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/Factory.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/InterfaceContainer.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/MultiTypeInterfaceContainer.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/PropertySet.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/PropertySetMixin.BoundListeners.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/PropertySetMixin.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/UnoUrl.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/WeakAdapter.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/class-use/WeakBase.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/package-frame.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/package-summary.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/package-tree.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/uno/helper/package-use.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/UnoClassLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/UnoLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/class-use/UnoClassLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/class-use/UnoLoader.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/package-frame.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/package-summary.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/package-tree.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/unoloader/package-use.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/UrlToFileMapper.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/class-use/UrlToFileMapper.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/package-frame.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/package-summary.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/package-tree.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/lib/util/package-use.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/Any.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/AnyConverter.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/Ascii.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/AsciiString.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/Enum.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IBridge.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IEnvironment.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IFieldDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IMapping.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IMemberDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IMethodDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/IQueryInterface.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/ITypeDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/MappingException.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/Type.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/Union.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/UnoRuntime.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/WeakReference.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/Any.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/AnyConverter.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/Ascii.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/AsciiString.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/Enum.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IBridge.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IEnvironment.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IFieldDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IMapping.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IMemberDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IMethodDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/IQueryInterface.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/ITypeDescription.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/MappingException.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/Type.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/Union.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/UnoRuntime.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/class-use/WeakReference.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/package-frame.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/package-summary.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/package-tree.html
${PKGNAME}/sdk/docs/java/ref/com/sun/star/uno/package-use.html
${PKGNAME}/sdk/docs/java/ref/constant-values.html
${PKGNAME}/sdk/docs/java/ref/deprecated-list.html
${PKGNAME}/sdk/docs/java/ref/help-doc.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-1.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-10.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-11.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-12.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-13.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-14.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-15.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-16.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-17.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-18.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-19.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-2.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-20.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-21.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-3.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-4.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-5.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-6.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-7.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-8.html
${PKGNAME}/sdk/docs/java/ref/index-files/index-9.html
${PKGNAME}/sdk/docs/java/ref/index.html
${PKGNAME}/sdk/docs/java/ref/overview-frame.html
${PKGNAME}/sdk/docs/java/ref/overview-summary.html
${PKGNAME}/sdk/docs/java/ref/overview-tree.html
${PKGNAME}/sdk/docs/java/ref/package-list
${PKGNAME}/sdk/docs/java/ref/resources/background.gif
${PKGNAME}/sdk/docs/java/ref/resources/tab.gif
${PKGNAME}/sdk/docs/java/ref/resources/titlebar.gif
${PKGNAME}/sdk/docs/java/ref/resources/titlebar_end.gif
${PKGNAME}/sdk/docs/java/ref/serialized-form.html
${PKGNAME}/sdk/docs/java/ref/stylesheet.css
${PKGNAME}/share/Scripts/beanshell/Capitalise/capitalise.bsh
${PKGNAME}/share/Scripts/beanshell/Capitalise/parcel-descriptor.xml
${PKGNAME}/share/Scripts/beanshell/HelloWorld/helloworld.bsh
${PKGNAME}/share/Scripts/beanshell/HelloWorld/parcel-descriptor.xml
${PKGNAME}/share/Scripts/beanshell/Highlight/ButtonPressHandler.bsh
${PKGNAME}/share/Scripts/beanshell/Highlight/ShowDialog.bsh
${PKGNAME}/share/Scripts/beanshell/Highlight/highlighter.bsh
${PKGNAME}/share/Scripts/beanshell/Highlight/parcel-descriptor.xml
${PKGNAME}/share/Scripts/beanshell/MemoryUsage/memusage.bsh
${PKGNAME}/share/Scripts/beanshell/MemoryUsage/parcel-descriptor.xml
${PKGNAME}/share/Scripts/beanshell/WordCount/parcel-descriptor.xml
${PKGNAME}/share/Scripts/beanshell/WordCount/wordcount.bsh
${PKGNAME}/share/Scripts/java/HelloWorld/HelloWorld.jar
${PKGNAME}/share/Scripts/java/HelloWorld/HelloWorld.java
${PKGNAME}/share/Scripts/java/HelloWorld/parcel-descriptor.xml
${PKGNAME}/share/Scripts/java/Highlight/Highlight.jar
${PKGNAME}/share/Scripts/java/Highlight/HighlightText.java
${PKGNAME}/share/Scripts/java/Highlight/parcel-descriptor.xml
${PKGNAME}/share/Scripts/java/MemoryUsage/MemoryUsage.jar
${PKGNAME}/share/Scripts/java/MemoryUsage/MemoryUsage.java
${PKGNAME}/share/Scripts/java/MemoryUsage/parcel-descriptor.xml
${PKGNAME}/share/Scripts/javascript/ExportSheetsToHTML/exportsheetstohtml.js
${PKGNAME}/share/Scripts/javascript/ExportSheetsToHTML/parcel-descriptor.xml
${PKGNAME}/share/Scripts/javascript/HelloWorld/helloworld.js
${PKGNAME}/share/Scripts/javascript/HelloWorld/parcel-descriptor.xml
${PKGNAME}/share/Scripts/javascript/Highlight/ButtonPressHandler.js
${PKGNAME}/share/Scripts/javascript/Highlight/ShowDialog.js
${PKGNAME}/share/Scripts/javascript/Highlight/parcel-descriptor.xml
${PKGNAME}/share/extensions/nlpsolver/EvolutionarySolver.jar
${PKGNAME}/share/extensions/nlpsolver/META-INF/manifest.xml
${PKGNAME}/share/extensions/nlpsolver/components.rdb
${PKGNAME}/share/extensions/nlpsolver/description-en-US.txt
${PKGNAME}/share/extensions/nlpsolver/description.xml
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.db_
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.ht_
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.idxl/_0.cfs
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.idxl/segments.gen
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.idxl/segments_3
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.jar
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.key_
${PKGNAME}/share/extensions/nlpsolver/help/en-US/help.tree
${PKGNAME}/share/extensions/nlpsolver/locale/NLPSolverCommon_en_US.default
${PKGNAME}/share/extensions/nlpsolver/locale/NLPSolverCommon_en_US.properties
${PKGNAME}/share/extensions/nlpsolver/locale/NLPSolverStatusDialog_en_US.default
${PKGNAME}/share/extensions/nlpsolver/locale/NLPSolverStatusDialog_en_US.properties
${PKGNAME}/share/extensions/nlpsolver/nlpsolver.jar
${PKGNAME}/share/extensions/nlpsolver/registration/LICENSE
${PKGNAME}/share/extensions/wiki-publisher/Addons.xcu
${PKGNAME}/share/extensions/wiki-publisher/Filter.xcu
${PKGNAME}/share/extensions/wiki-publisher/META-INF/manifest.xml
${PKGNAME}/share/extensions/wiki-publisher/OptionsDialog.xcu
${PKGNAME}/share/extensions/wiki-publisher/Paths.xcu
${PKGNAME}/share/extensions/wiki-publisher/ProtocolHandler.xcu
${PKGNAME}/share/extensions/wiki-publisher/Types.xcu
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/EditSetting.xdl
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/Module1.xba
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/SendToMediaWiki.xdl
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/Settings.xdl
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/dialog.xlb
${PKGNAME}/share/extensions/wiki-publisher/WikiEditor/script.xlb
${PKGNAME}/share/extensions/wiki-publisher/WikiExtension.xcs
${PKGNAME}/share/extensions/wiki-publisher/WikiExtension.xcu
${PKGNAME}/share/extensions/wiki-publisher/commons-codec-1.6.jar
${PKGNAME}/share/extensions/wiki-publisher/commons-httpclient-3.1.jar
${PKGNAME}/share/extensions/wiki-publisher/commons-lang-2.4.jar
${PKGNAME}/share/extensions/wiki-publisher/commons-logging-1.1.1.jar
${PKGNAME}/share/extensions/wiki-publisher/components.rdb
${PKGNAME}/share/extensions/wiki-publisher/description-en-US.txt
${PKGNAME}/share/extensions/wiki-publisher/description.xml
${PKGNAME}/share/extensions/wiki-publisher/filter/math/cmarkup.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/entities.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/glayout.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/mmltex.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/scripts.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/tables.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/math/tokens.xsl
${PKGNAME}/share/extensions/wiki-publisher/filter/odt2mediawiki.xsl
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.db_
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.ht_
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.idxl/_0.cfs
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.idxl/segments.gen
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.idxl/segments_3
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.jar
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.key_
${PKGNAME}/share/extensions/wiki-publisher/help/en-US/help.tree
${PKGNAME}/share/extensions/wiki-publisher/license/THIRDPARTYLICENSEREADME.html
${PKGNAME}/share/extensions/wiki-publisher/mediawiki.jar
${PKGNAME}/share/extensions/wiki-publisher/registration/LICENSE
${PKGNAME}/share/extensions/wiki-publisher/templates/MediaWiki/mediawiki.ott
${PKGNAME}/share/registry/reportbuilder.xcd
${PKGNAME}/share/template/common/wizard/report/default.otr
${PKGNAME}/ure/bin/javaldx
${PKGNAME}/ure/lib/JREProperties.class
${PKGNAME}/ure/lib/javaloader.uno.so
${PKGNAME}/ure/lib/javavm.uno.so
${PKGNAME}/ure/lib/libjava_uno.so
${PKGNAME}/ure/lib/libjpipe.so
${PKGNAME}/ure/lib/libjuh.so
${PKGNAME}/ure/lib/libjuhx.so
${PKGNAME}/ure/lib/libjvmaccess.so
${PKGNAME}/ure/lib/libjvmfwk.so
${PKGNAME}/ure/lib/libsunjavaplugin.so
${PKGNAME}/ure/share/java/java_uno.jar
${PKGNAME}/ure/share/java/juh.jar
${PKGNAME}/ure/share/java/jurt.jar
${PKGNAME}/ure/share/java/ridl.jar
${PKGNAME}/ure/share/java/unoloader.jar
${PKGNAME}/ure/share/misc/javavendors.xml
