# $NetBSD: Makefile,v 1.2 2008/03/16 19:41:30 hoka_adam Exp $

VERSION=	20050307
DISTNAME=	fo_FO
MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Faroese dictionary for hunspell

.include "../../wip/hunspell-af_ZA/Makefile.common"

.include "../../mk/bsd.pkg.mk"
