# $NetBSD: buildlink3.mk,v 1.1 2007/11/05 06:53:56 bsadewitz Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBATOMIC_OPS_BUILDLINK3_MK:=	${LIBATOMIC_OPS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	libatomic_ops
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibatomic_ops}
BUILDLINK_PACKAGES+=	libatomic_ops
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libatomic_ops

.if ${LIBATOMIC_OPS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.libatomic_ops+=	libatomic_ops>=1.2
BUILDLINK_PKGSRCDIR.libatomic_ops?=	../../wip/libatomic_ops
.endif	# LIBATOMIC_OPS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
