# $NetBSD: Makefile,v 1.14 2008/08/06 13:53:39 yazzy Exp $
#

DISTNAME=	embryo-0.9.9.043
CATEGORIES=	lang
MASTER_SITES=	http://download.enlightenment.org/snapshots/2008-05-19/ \
		http://www.ezunix.org/pkgsrc/e17/snapshots/2008-05-19/ \
		http://jfranz.users.bsdprojects.net/pkgsrc/e17/

MAINTAINER=	grzela@seculture.com
HOMEPAGE=	http://enlightenment.org/
COMMENT=	Embeddable Scripting Language

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes
USE_TOOLS+=	gmake pkg-config

.include "../../mk/bsd.pkg.mk"
