# $NetBSD$

BUILDLINK_TREE+=	lvm2

.if !defined(LVM2_BUILDLINK3_MK)
LVM2_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.lvm2+=	lvm2>=2.02.98
BUILDLINK_PKGSRCDIR.lvm2?=	../../wip/lvm2
.endif	# LVM2_BUILDLINK3_MK

BUILDLINK_TREE+=	-lvm2
