# $NetBSD: Makefile,v 1.2 2013/03/18 13:06:10 midar Exp $
#

DISTNAME=	objfw-0.7.1
MASTER_SITES=	https://webkeks.org/objfw/downloads/
EXTRACT_SUFX=	.tar.xz

CATEGORIES=	devel
COMMENT=	Portable, lightweight framework for the Objective-C language
LICENSE=	qpl-v1.0 OR gnu-gpl-v2 OR gnu-gpl-v3
HOMEPAGE=	https://webkeks.org/objfw/
MAINTAINER=	js@webkeks.org

FETCH_USING=	wget	# required for https

GNU_CONFIGURE=	yes
USE_LANGUAGES=	objc

.include "../../mk/bsd.pkg.mk"
