# $NetBSD: buildlink3.mk,v 1.2 2005/11/11 22:46:44 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBXDMCP_BUILDLINK3_MK:=	${LIBXDMCP_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libXdmcp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NlibXdmcp}
BUILDLINK_PACKAGES+=	libXdmcp

.if !empty(LIBXDMCP_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libXdmcp+=	libXdmcp>=0.99.0
BUILDLINK_PKGSRCDIR.libXdmcp?=	../../wip/libXdmcp
.endif	# LIBXDMCP_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
