# $NetBSD: Makefile,v 1.3 2006/08/09 17:13:59 marttikuparinen Exp $

.include "../../wip/xfce4/Makefile.common"

DISTNAME=	xfce4-appfinder-${XFCE4_VERSION}
CATEGORIES=	sysutils
COMMENT=	Xfce application finder

USE_TOOLS+=	intltool

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../wip/libxfce4gui/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
