# $NetBSD: Makefile,v 1.1 2015/03/07 17:46:25 ishit Exp $

DISTNAME=	kakasi-1.0.2
CATEGORIES=	textproc

MAINTAINER=	ishit@users.sourceforge.net
HOMEPAGE=	https://github.com/eitoball/kakasi-ruby/
COMMENT=	Ruby binding for KAKASI implemented with Fiddle/DL/FFI
LICENSE=	2-clause-bsd OR ruby-license

RUBY_VERSION_SUPPORTED=	200 21

.include "../../textproc/kakasi/buildlink3.mk"
.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
