# $NetBSD: hacks.mk,v 1.1.1.1 2010/11/27 01:24:40 rxg Exp $

# Reduce the dirty work for modifying the OS defines.
# Be sure to confirm the file before adding it in the list.

PKG_HACKS+=		ossrc

SUBST_CLASSES+=		osgyp
SUBST_MESSAGE.osgyp=	Fixing OS condition in gyp files
SUBST_STAGE.osgyp=	post-patch
SUBST_FILES.osgyp=	${OS_GYP}
SUBST_SED.osgyp+=	-e 's:OS *== *"linux" :(OS=="linux" or OS=="dragonfly" or OS=="freebsd" or OS=="netbsd" or OS=="openbsd") :'
SUBST_SED.osgyp+=	-e 's:OS *!= *"linux" :OS!="linux" and OS!="dragonfly" and OS!="freebsd" and OS!="netbsd" and OS!="openbsd" :'

SUBST_CLASSES+=		oschk
SUBST_MESSAGE.oschk=	Fixing OS check in source files
SUBST_STAGE.oschk=	post-patch
SUBST_FILES.oschk=	${OS_CHK}
SUBST_SED.oschk+=	-e 's:(LINUX):(UNIX):'

SUBST_CLASSES+=		osdef
SUBST_MESSAGE.osdef=	Fixing OS defines in source files
SUBST_STAGE.osdef=	post-patch
SUBST_FILES.osdef=	${OS_DEF}
SUBST_SED.osdef+=	-e 's:(OS_LINUX):(OS_POSIX) \&\& !defined(OS_MACOSX):'
SUBST_SED.osdef+=	-e 's:OS_LINUX:OS_POSIX \&\& !OS_MACOSX:'

OS_GYP=	app/app.gyp \
	app/app_base.gypi \
	base/allocator/allocator.gyp \
	base/base.gyp \
	base/base.gypi \
	build/all.gyp \
	build/common.gypi \
	build/features_override.gypi \
	chrome/chrome.gyp \
	chrome/chrome_browser.gypi \
	chrome/chrome_common.gypi \
	chrome/chrome_exe.gypi \
	chrome/chrome_tests.gypi \
	chrome/common_constants.gypi \
	chrome/default_plugin/default_plugin.gyp \
	chrome/test/interactive_ui/interactive_ui_tests.gypi \
	gfx/gfx.gyp \
	gpu/demos/demos.gyp \
	gpu/gpu.gyp \
	ipc/ipc.gyp \
	jingle/jingle.gyp \
	media/media.gyp \
	native_client/build/common.gypi \
	native_client/src/shared/platform/platform.gyp \
	native_client/src/trusted/service_runtime/service_runtime.gyp \
	net/net.gyp \
	net/third_party/nss/ssl.gyp \
	printing/printing.gyp \
	remoting/remoting.gyp \
	skia/skia.gyp \
	testing/gtest.gyp \
	third_party/WebKit/JavaScriptCore/JavaScriptCore.gyp/JavaScriptCore.gyp \
	third_party/WebKit/WebCore/WebCore.gyp/WebCore.gyp \
	third_party/WebKit/WebKit/chromium/WebKit.gyp \
	third_party/expat/expat.gyp \
	third_party/ffmpeg/ffmpeg.gyp \
	third_party/hunspell/hunspell.gyp \
	third_party/icu/icu.gyp \
	third_party/libjingle/libjingle.gyp \
	third_party/libxml/libxml.gyp \
	third_party/libxslt/libxslt.gyp \
	third_party/mesa/mesa.gyp \
	third_party/npapi/npapi.gyp \
	third_party/ppapi/ppapi.gyp \
	third_party/sqlite/sqlite.gyp \
	tools/gyp/test/additional-targets/src/dir1/actions.gyp \
	tools/gyp/test/library/src/library.gyp \
	v8/tools/gyp/v8.gyp \
	views/views.gyp \
	webkit/glue/webkit_glue.gypi \
	webkit/tools/npapi_layout_test_plugin/npapi_layout_test_plugin.gypi \
	webkit/tools/pepper_test_plugin/pepper_test_plugin.gyp \
	webkit/tools/test_shell/test_shell.gypi

OS_CHK=	third_party/WebKit/JavaScriptCore/assembler/MacroAssemblerARM.cpp \
	third_party/WebKit/JavaScriptCore/jit/ExecutableAllocator.cpp \
	third_party/WebKit/JavaScriptCore/jit/ExecutableAllocator.h \
	third_party/WebKit/JavaScriptCore/jit/JITStubs.cpp \
	third_party/WebKit/JavaScriptCore/wtf/StringExtras.h \
	third_party/WebKit/WebCore/dom/SelectElement.cpp \
	third_party/WebKit/WebCore/loader/CachedFont.cpp \
	third_party/WebKit/WebCore/page/EventHandler.cpp \
	third_party/WebKit/WebCore/page/NavigatorBase.cpp \
	third_party/WebKit/WebCore/page/chromium/EventHandlerChromium.cpp \
	third_party/WebKit/WebCore/platform/Scrollbar.cpp \
	third_party/WebKit/WebCore/platform/UUID.cpp \
	third_party/WebKit/WebCore/platform/chromium/ChromiumBridge.h \
	third_party/WebKit/WebCore/platform/graphics/chromium/FontCustomPlatformData.cpp \
	third_party/WebKit/WebCore/platform/graphics/chromium/FontCustomPlatformData.h \
	third_party/WebKit/WebCore/platform/graphics/chromium/FontPlatformData.h \
	third_party/WebKit/WebCore/platform/graphics/skia/ImageBufferSkia.cpp \
	third_party/WebKit/WebCore/platform/graphics/skia/PlatformContextSkia.cpp \
	third_party/WebKit/WebCore/platform/graphics/skia/PlatformContextSkia.h \
	third_party/WebKit/WebKit/chromium/src/ChromiumBridge.cpp \
	third_party/WebKit/WebKit/chromium/src/WebFrameImpl.cpp \
	third_party/WebKit/WebKit/chromium/src/WebViewImpl.cpp

OS_DEF=	app/gfx/gl/gl_bindings.h \
	app/gfx/gl/gl_context_egl.cc \
	base/file_util.h \
	base/leak_annotations.h \
	base/process_util.h \
	base/profiler.cc \
	base/sys_string_conversions_unittest.cc \
	chrome/app/chrome_dll_main.cc \
	chrome/app/chrome_exe_main_gtk.cc \
	chrome/app/chrome_main_uitest.cc \
	chrome/browser/app_modal_dialog.cc \
	chrome/browser/app_modal_dialog.h \
	chrome/browser/browser.cc \
	chrome/browser/browser_about_handler.cc \
	chrome/browser/browser_focus_uitest.cc \
	chrome/browser/browser_keyevents_browsertest.cc \
	chrome/browser/browser_main.cc \
	chrome/browser/browser_process.h \
	chrome/browser/browser_process_impl.cc \
	chrome/browser/browser_process_impl.h \
	chrome/browser/browser_shutdown.cc \
	chrome/browser/child_process_launcher.cc \
	chrome/browser/cookie_modal_dialog.h \
	chrome/browser/dom_ui/bug_report_ui.cc \
	chrome/browser/extensions/extension_storage_apitest.cc \
	chrome/browser/extensions/extension_tabs_apitest.cc \
	chrome/browser/extensions/notifications_apitest.cc \
	chrome/browser/find_bar_host_browsertest.cc \
	chrome/browser/first_run/first_run.cc \
	chrome/browser/first_run/first_run.h \
	chrome/browser/first_run/first_run_gtk.cc \
	chrome/browser/gpu_process_host.cc \
	chrome/browser/gpu_process_host.h \
	chrome/browser/labs.cc \
	chrome/browser/locale_tests_uitest.cc \
	chrome/browser/memory_details.cc \
	chrome/browser/memory_purger.cc \
	chrome/browser/net/connection_tester.cc \
	chrome/browser/notifications/balloon_collection_impl.h \
	chrome/browser/options_util.cc \
	chrome/browser/process_singleton_linux_uitest.cc \
	chrome/browser/renderer_host/render_widget_host_unittest.cc \
	chrome/browser/sessions/session_restore_browsertest.cc \
	chrome/browser/sessions/session_restore_uitest.cc \
	chrome/browser/shell_integration_unittest.cc \
	chrome/browser/sync/engine/syncer_thread.cc \
	chrome/browser/sync/engine/syncer_thread.h \
	chrome/browser/tab_contents/tab_contents.cc \
	chrome/browser/task_manager_resource_providers.cc \
	chrome/browser/unload_uitest.cc \
	chrome/browser/views/accessibility_event_router_views_unittest.cc \
	chrome/browser/views/accessible_view_helper.cc \
	chrome/browser/views/accessible_view_helper.h \
	chrome/browser/views/autocomplete/autocomplete_popup_contents_view.cc \
	chrome/browser/views/bookmark_bar_view_test.cc \
	chrome/browser/views/content_setting_bubble_contents.cc \
	chrome/browser/views/create_application_shortcut_view.cc \
	chrome/browser/views/download_item_view.cc \
	chrome/browser/views/dropdown_bar_host.cc \
	chrome/browser/views/extensions/extension_popup.cc \
	chrome/browser/views/extensions/extension_view.cc \
	chrome/browser/views/find_bar_host_interactive_uitest.cc \
	chrome/browser/views/find_bar_view.cc \
	chrome/browser/views/find_bar_view.h \
	chrome/browser/views/frame/app_panel_browser_frame_view.cc \
	chrome/browser/views/frame/browser_view.cc \
	chrome/browser/views/frame/browser_view_layout.cc \
	chrome/browser/views/frame/opaque_browser_frame_view.cc \
	chrome/browser/views/frame/popup_non_client_frame_view.cc \
	chrome/browser/views/fullscreen_exit_bubble.cc \
	chrome/browser/views/fullscreen_exit_bubble.h \
	chrome/browser/views/html_dialog_view.cc \
	chrome/browser/views/html_dialog_view_browsertest.cc \
	chrome/browser/views/info_bubble.cc \
	chrome/browser/views/info_bubble.h \
	chrome/browser/views/location_bar/location_bar_view.cc \
	chrome/browser/views/location_bar/location_bar_view.h \
	chrome/browser/views/notifications/balloon_view.cc \
	chrome/browser/views/notifications/balloon_view_host.cc \
	chrome/browser/views/tabs/dragged_tab_controller.cc \
	chrome/browser/views/tabs/dragged_tab_view.cc \
	chrome/browser/views/tabs/dragged_tab_view.h \
	chrome/browser/views/tabs/tab_dragging_test.cc \
	chrome/browser/views/tabs/tab_strip.cc \
	chrome/browser/views/tabs/tab_strip.h \
	chrome/browser/web_applications/web_app.cc \
	chrome/browser/wrench_menu_model.cc \
	chrome/common/child_process_host.cc \
	chrome/common/child_process_logging.h \
	chrome/common/chrome_constants.cc \
	chrome/common/chrome_switches.cc \
	chrome/common/chrome_switches.h \
	chrome/common/extensions/extension_action.cc \
	chrome/common/gpu_messages_internal.h \
	chrome/common/logging_chrome_uitest.cc \
	chrome/gpu/gpu_channel.cc \
	chrome/gpu/gpu_config.h \
	chrome/gpu/gpu_thread.cc \
	chrome/gpu/x_util.h \
	chrome/plugin/plugin_thread.cc \
	chrome/renderer/mock_render_thread.cc \
	chrome/renderer/mock_render_thread.h \
	chrome/renderer/pepper_scrollbar_widget.h \
	chrome/renderer/render_process_impl.cc \
	chrome/renderer/render_thread.cc \
	chrome/renderer/render_view.h \
	chrome/renderer/render_view_browsertest.cc \
	chrome/renderer/renderer_glue.cc \
	chrome/renderer/renderer_main.cc \
	chrome/renderer/renderer_webkitclient_impl.cc \
	chrome/renderer/webplugin_delegate_pepper.cc \
	chrome/renderer/webplugin_delegate_pepper.h \
	chrome/service/service_process.cc \
	chrome/test/automation/automation_proxy_uitest.cc \
	chrome/test/chrome_process_util.cc \
	chrome/test/in_process_browser_test.cc \
	chrome/test/memory_test/memory_test.cc \
	chrome/test/page_cycler/page_cycler_test.cc \
	chrome/test/reliability/page_load_test.cc \
	chrome/test/render_view_test.cc \
	chrome/test/startup/feature_startup_test.cc \
	chrome/test/startup/startup_test.cc \
	chrome/test/testing_browser_process.h \
	chrome/test/testing_profile.cc \
	chrome/test/ui/dom_checker_uitest.cc \
	chrome/test/ui/dromaeo_benchmark_uitest.cc \
	chrome/test/ui/history_uitest.cc \
	chrome/test/ui/sunspider_uitest.cc \
	chrome/test/ui/ui_layout_test.cc \
	chrome/test/ui/ui_perf_test.cc \
	chrome/test/ui/ui_test.cc \
	chrome/test/ui/v8_benchmark_uitest.cc \
	chrome/test/ui_test_utils.cc \
	chrome/test/url_fetch_test/url_fetch_test.cc \
	chrome/worker/worker_uitest.cc \
	googleurl/src/gurl_test_main.cc \
	gpu/demos/framework/main_exe.cc \
	gpu/demos/framework/main_pepper.cc \
	ipc/sync_socket_unittest.cc \
	media/base/media_switches.cc \
	media/base/media_switches.h \
	net/base/dnsrr_resolver_unittest.cc \
	net/base/host_resolver_impl.cc \
	third_party/tcmalloc/chromium/src/config.h \
	views/accelerator.cc \
	views/controls/button/native_button.cc \
	views/controls/link.cc \
	views/controls/menu/menu_controller.cc \
	views/controls/menu/submenu_view.cc \
	views/controls/native/native_view_host.cc \
	views/controls/resize_area.cc \
	views/controls/scrollbar/bitmap_scroll_bar.cc \
	views/controls/separator.cc \
	views/controls/single_split_view.cc \
	views/controls/slider/slider.h \
	views/controls/textfield/textfield.cc \
	views/event.h \
	views/examples/examples_main.cc \
	views/examples/widget_example.h \
	views/focus/accelerator_handler.h \
	views/focus/focus_manager.cc \
	views/focus/focus_manager_unittest.cc \
	views/view.cc \
	views/view_unittest.cc \
	views/widget/root_view.cc \
	views/widget/root_view.h \
	views/window/client_view.cc \
	views/window/custom_frame_view.cc \
	webkit/glue/plugins/pepper_plugin_instance.cc \
	webkit/glue/plugins/pepper_plugin_instance.h \
	webkit/glue/plugins/pepper_private.cc \
	webkit/glue/plugins/plugin_lib_unittest.cc \
	webkit/glue/webkit_glue.h \
	webkit/support/webkit_support_glue.cc \
	webkit/tools/test_shell/test_shell.cc
