# $NetBSD: Makefile,v 1.1 2013/03/09 03:44:31 szptvlfn Exp $
#

DISTNAME=	hothasktags-0.3.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@a-net.email.ne.jp
HOMEPAGE=	http://github.com/luqui/hothasktags
COMMENT=	Generates ctags for Haskell
LICENSE=	modified-bsd


.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-cpphs/buildlink3.mk"
.include "../../wip/hs-haskell-src-exts/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
