# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/12/04 03:50:24 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
EDBUS_BUILDLINK3_MK:=	${EDBUS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	edbus
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nedbus}
BUILDLINK_PACKAGES+=	edbus
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}edbus

.if ${EDBUS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.edbus+=	edbus>=0.1.0.003
BUILDLINK_PKGSRCDIR.edbus?=	../../wip/edbus
.endif	# EDBUS_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
