# $NetBSD$
#
# used by wip/llama.cpp/Makefile
# used by wip/py-llama-cpp-scripts/Makefile

DISTNAME=	llama.cpp-${GITHUB_TAG}
MASTER_SITES=	${MASTER_SITE_GITHUB:=ggml-org/}
GITHUB_PROJECT=	llama.cpp
GITHUB_TAG=	b${LLAMA_BUILD_NUMBER}

# embedded in version string in binary
LLAMA_BUILD_NUMBER=	9969
LLAMA_BUILD_COMMIT=	76f2798059575a96a12e4d34342165a4b6a6a312
