# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/14 13:41:27 obache Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBCHEWING_BUILDLINK3_MK:=	${LIBCHEWING_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libchewing
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibchewing}
BUILDLINK_PACKAGES+=	libchewing
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}libchewing

.if !empty(LIBCHEWING_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.libchewing+=		libchewing>=0.3.2
BUILDLINK_ABI_DEPENDS.libchewing+=	libchewing>=0.3.2
BUILDLINK_PKGSRCDIR.libchewing?=	../../wip/libchewing
.endif	# LIBCHEWING_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
