# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/09/19 03:20:57 hugor Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
AIDA_BUILDLINK3_MK:=	${AIDA_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	aida
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Naida}
BUILDLINK_PACKAGES+=	aida
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}aida

.if ${AIDA_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.aida+=	aida>=3.2.1
BUILDLINK_PKGSRCDIR.aida?=	../../wip/aida
BUILDLINK_DEPMETHOD.aida?=	build
.endif	# AIDA_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
