# $NetBSD: buildlink3.mk,v 1.1 2008/07/20 06:00:49 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HSSVN_BUILDLINK3_MK:=	${HSSVN_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	HsSVN
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NHsSVN}
BUILDLINK_PACKAGES+=	HsSVN
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}HsSVN

.if ${HSSVN_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.HsSVN?=	build
BUILDLINK_API_DEPENDS.HsSVN+=	HsSVN>=0.3.3
BUILDLINK_PKGSRCDIR.HsSVN?=	../../wip/HsSVN
.endif	# HSSVN_BUILDLINK3_MK

.include "../../devel/subversion-base/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
