$NetBSD$

Update the broken dependency.

--- Cargo.toml.orig	2025-07-27 21:22:42.263433360 +0000
+++ Cargo.toml
@@ -5,7 +5,7 @@ edition = "2021"
 authors = ["Mufeed VH <mufeed@lyminal.space>", "Pommaq"]
 
 [dependencies]
-indicatif = "0.16.2"
+indicatif = "0.18.0"
 log = "0.4.19"
 anyhow = "1.0.72"
 crossbeam = "0.8.2"
