$NetBSD$

--- src/pal/src/configure.cmake.orig	2016-02-15 22:52:17.000000000 +0000
+++ src/pal/src/configure.cmake
@@ -933,6 +933,8 @@ if(CMAKE_SYSTEM_NAME STREQUAL Darwin)
   set(PAL_PT_READ_D PT_READ_D)
   set(PAL_PT_WRITE_D PT_WRITE_D)
   set(HAS_FTRUNCATE_LENGTH_ISSUE 1)
+  set(HAVE_SCHED_OTHER_ASSIGNABLE 1)
+
 elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
   if(NOT HAVE_LIBUNWIND_H)
     unset(HAVE_LIBUNWIND_H CACHE)
@@ -950,6 +952,7 @@ elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBS
   set(PAL_PT_WRITE_D PT_WRITE_D)
   set(HAS_FTRUNCATE_LENGTH_ISSUE 0)
   set(BSD_REGS_STYLE "((reg).r_##rr)")
+  set(HAVE_SCHED_OTHER_ASSIGNABLE 1)
 
   if(EXISTS "/lib/libc.so.7")
     set(FREEBSD_LIBC "/lib/libc.so.7")
@@ -974,6 +977,7 @@ elseif(CMAKE_SYSTEM_NAME STREQUAL NetBSD
   set(PAL_PT_WRITE_D PT_WRITE_D)
   set(HAS_FTRUNCATE_LENGTH_ISSUE 0)
   set(BSD_REGS_STYLE "((reg).regs[_REG_##RR])")
+  set(HAVE_SCHED_OTHER_ASSIGNABLE 0)
 
 elseif(CMAKE_SYSTEM_NAME STREQUAL SunOS)
   if(NOT HAVE_LIBUNWIND_H)
@@ -1011,6 +1015,7 @@ else() # Anything else is Linux
   set(PAL_PT_READ_D PTRACE_PEEKDATA)
   set(PAL_PT_WRITE_D PTRACE_POKEDATA)
   set(HAS_FTRUNCATE_LENGTH_ISSUE 0)
+  set(HAVE_SCHED_OTHER_ASSIGNABLE 1)
 endif(CMAKE_SYSTEM_NAME STREQUAL Darwin)
 
 configure_file(${CMAKE_CURRENT_SOURCE_DIR}/config.h.in ${CMAKE_CURRENT_BINARY_DIR}/config.h)
