# $NetBSD$

DISTNAME=	brython-3.9.0
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python
MASTER_SITES=	https://files.pythonhosted.org/packages/18/f8/be149513799b76b68659daaa0a1cfe09afd7df2c853bbc03be634ba6c6b2/

MAINTAINER=	kamelderouiche@yahoo.com
HOMEPAGE=	http://brython.info/
COMMENT=	Implementation of Python3 running in the browser
LICENSE=	modified-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
