

PACKAGE CA2002A2 IS

     PROCEDURE PROC (Y : OUT INTEGER);
     FUNCTION FUN (Z : INTEGER := 3) RETURN BOOLEAN;

     PACKAGE PKG IS
          I : INTEGER;
          PROCEDURE PKG_PROC (YY : IN OUT INTEGER);
     END PKG;

END CA2002A2;
