# $NetBSD$

DISTNAME=	gatspy-0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	math
MASTER_SITES=	https://pypi.python.org/packages/b0/fa/a075f6cd3f40255a883e8a966df17322825f6b86cb4907edce06098aa566/

MAINTAINER=	jihbed.research@gmail.com
HOMEPAGE=	http://github.com/astroml/gatspy
COMMENT=	General tools for Astronomical Time Series in Python
LICENSE=	2-clause-bsd

USE_LANGUAGES=	# none

.include "../../lang/python/distutils.mk"
.include "../../math/py-numpy/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
