# $NetBSD: Makefile,v 1.4 2012/11/14 00:16:12 othyro Exp $
#

DISTNAME=	Business-ISSN-0.91
PKGNAME=	p5-${DISTNAME}
CATEGORIES=	misc
MASTER_SITES=	http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://search.cpan.org/CPAN/authors/id/B/BD/BDFOY/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

PERL5_PACKLIST=	auto/Business/ISSN/.packlist
USE_LANGUAGES=	# none

.include "../../lang/perl5/module.mk"
.include "../../mk/bsd.pkg.mk"
