# $NetBSD$

BUILDLINK_TREE+=	HiGHS

.if !defined(HIGHS_BUILDLINK3_MK)
HIGHS_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.HiGHS+=	HiGHS>=1.7.2
BUILDLINK_PKGSRCDIR.HiGHS?=	../../wip/HiGHS
.endif	# HIGHS_BUILDLINK3_MK

BUILDLINK_TREE+=	-HiGHS
