# $NetBSD: buildlink3.mk,v 1.2 2006/04/06 07:18:34 jeremy-c-reed Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
SVGALIB_BUILDLINK3_MK:=	${SVGALIB_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	svgalib
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nsvgalib}
BUILDLINK_PACKAGES+=	svgalib

.if !empty(SVGALIB_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.svgalib+=	svgalib>=1.4.2
BUILDLINK_PKGSRCDIR.svgalib?=	../../wip/svgalib
.endif	# SVGALIB_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
