# $NetBSD: Makefile,v 1.4 2005/04/11 21:14:00 tvierling Exp $
#

DISTNAME=	matchbox-themes-extra-0.3
CATEGORIES=	x11
MASTER_SITES=	http://projects.o-hand.com/matchbox/sources/matchbox-themes-extra/0.3/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	tech-pkg@NetBSD.org
HOMEPAGE=	http://projects.o-hand.com/matchbox/
COMMENT=	Collection of themes for Matchbox

USE_DIRS+=		gnome2-1.5
USE_LIBTOOL=		yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
