# $NetBSD: Makefile,v 1.5 2015/04/09 20:38:31 krytarowski Exp $

.include "../../wip/mate/Makefile.common"

DISTNAME=	mate-backgrounds-${MATE_VERSION}
CATEGORIES=	graphics

COMMENT=	Set of backgrounds packaged with the MATE desktop

BUILDLINK_DEPMETHOD.gettext=	build
.include "../../devel/gettext-lib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
