# $NetBSD: Makefile,v 1.9 2014/05/17 21:00:06 szptvlfn Exp $

DISTNAME=	comonad-4.2
CATEGORIES=	math

MAINTAINER=	pho@cielonegro.org
COMMENT=	Comonads
LICENSE=	2-clause-bsd

.include "../../mk/haskell.mk"
.include "../../wip/hs-contravariant/buildlink3.mk"
.include "../../wip/hs-distributive/buildlink3.mk"
.include "../../devel/hs-mtl/buildlink3.mk"
.include "../../wip/hs-semigroups/buildlink3.mk"
.include "../../devel/hs-tagged/buildlink3.mk"
.include "../../devel/hs-transformers/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
