
WITH REPORT, FIRST_PKG;
USE REPORT;
PRAGMA ELABORATE (FIRST_PKG);
PACKAGE CA1108B_PKG IS

     I, J : INTEGER;
     PROCEDURE PROC;
     PROCEDURE CALL_SUBS (X, Y : IN OUT INTEGER);

END CA1108B_PKG;
