
WITH REPORT, CA1108B_PKG;
USE REPORT, CA1108B_PKG;
PROCEDURE CA1108B IS

     VAR1, VAR2 : INTEGER;

BEGIN

     TEST ("CA1108B", "IF DIFFERENT WITH_CLAUSES GIVEN FOR PACKAGE " &
                      "SPEC AND BODY, ALL NAMED UNITS ARE VISIBLE " &
                      "IN THE BODY AND ITS SUBUNITS");

     PROC;

     VAR1 := 0;
     VAR2 := 1;
     CALL_SUBS (VAR1, VAR2);
     IF VAR1 /= 1 THEN
          FAILED ("FIRST_PKG FUNCTION NOT VISIBLE IN SUBUNIT");
     END IF;

     IF VAR2 /= 3 THEN
          FAILED ("LATER_PKG FUNCTION NOT VISIBLE IN SUBUNIT");
     END IF;

     RESULT;

END CA1108B;
