
WITH LATER_PKG;
PRAGMA ELABORATE (LATER_PKG);
PACKAGE BODY CA1108B_PKG IS

     PROCEDURE SUB (X, Y : IN OUT INTEGER) IS SEPARATE;

     PROCEDURE PROC IS
          I, J : INTEGER;
     BEGIN
          I := FIRST_PKG.F;
          IF I /= 1 THEN
               FAILED ("FIRST_PKG FUNCTION NOT VISIBLE IN " &
                       "PACKAGE BODY PROCEDURE");
          END IF;
          J := LATER_PKG.F;
          IF J /= 3 THEN
               FAILED ("LATER_PKG FUNCITON NOT VISIBLE IN " &
                       "PACKAGE BODY PROCEDURE");
          END IF;
     END PROC;

     PROCEDURE CALL_SUBS (X, Y : IN OUT INTEGER) IS
     BEGIN
          SUB (X, Y);
     END CALL_SUBS;

BEGIN

     I := FIRST_PKG.F;
     IF I /= 1 THEN
          FAILED ("FIRST_PKG FUNCTION NOT VISIBLE IN PACKAGE BODY");
     END IF;
     J := LATER_PKG.F;
     IF J /= 3 THEN
          FAILED ("LATER_PKG FUNCTION NOT VISIBLE IN PACKAGE BODY");
     END IF;

END CA1108B_PKG;
