
WITH C23006F_INST, C23006FINST;
WITH REPORT; USE REPORT;
PROCEDURE C23006F IS
BEGIN
     TEST ("C23006F", "CHECK THAT UNDERSCORES ARE SIGNIFICANT IN " &
                      "NAMES USED FOR A LIBRARY PACKAGE INSTANTIATION");

     IF C23006F_INST.A + IDENT_INT(1) /= C23006FINST.A THEN
          FAILED ("INCORRECT PACKAGE IDENTIFICATION - 1");
     END IF;

     RESULT;
END C23006F; 
