# $NetBSD$

BUILDLINK_TREE+=	go-lzw

.if !defined(GO_LZW_BUILDLINK3_MK)
GO_LZW_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-lzw=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-lzw?=		build

BUILDLINK_API_DEPENDS.go-lzw+=	go-lzw>=20190829
BUILDLINK_PKGSRCDIR.go-lzw?=	../../wip/go-lzw
.endif	# GO_LZW_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-lzw
