# $NetBSD: buildlink3.mk,v 1.5 2004/10/15 22:18:18 johnrshannon Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GNUPG2_BUILDLINK3_MK:=	${GNUPG2_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gnupg2
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngnupg2}
BUILDLINK_PACKAGES+=	gnupg2

.if !empty(GNUPG2_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.gnupg2+=	gnupg2>=1.9.11
BUILDLINK_PKGSRCDIR.gnupg2?=	../../wip/gnupg-1.9
.endif	# GNUPG2_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
