# $NetBSD: Makefile,v 1.1.1.1 2011/02/16 11:15:41 ryo-on Exp $
#

HELPLANGUAGE=		zh_CN

DISTNAME=		gimp-help-2.6.1-html-${HELPLANGUAGE}
PKGNAME=		gimp-docs-${HELPLANGUAGE}-${DISTNAME:S/gimp-help-//:S/-html-${HELPLANGUAGE}//}

PKG_DESTDIR_SUPPORT=	user-destdir

.include "../../wip/gimp-docs-en/Makefile.common"

COMMENT=		Documentation package for The Gimp image manipulation software
