# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/02/14 18:40:19 netcap Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
ADPLUG_BUILDLINK3_MK:=	${ADPLUG_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	adplug
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nadplug}
BUILDLINK_PACKAGES+=	adplug
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}adplug

.if ${ADPLUG_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.adplug+=	adplug>=2.0.1
BUILDLINK_PKGSRCDIR.adplug?=	../../wip/libadplug
BUILDLINK_DEPMETHOD.adplug?=	build
.endif	# ADPLUG_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
