# $NetBSD: Makefile,v 1.1.1.1 2008/09/07 16:48:55 milosn Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-fnmatch-${IO_VERSION}
PKGREVISION=		0
CATEGORIES=		devel

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		Fnmatch addon for Io.

ADDON_NAME=		Fnmatch

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
