
PACKAGE BODY BA1001D_PKG IS

     FUNCTION "AND"
         (LEFT, RIGHT: BOOLEAN) RETURN BOOLEAN IS SEPARATE; -- ERROR: {1:6;1}

     FUNCTION "="
         (LEFT, RIGHT: LIM) RETURN BOOLEAN IS SEPARATE; -- ERROR: {1:6;1}

     FUNCTION "+"
         (LEFT, RIGHT: INTEGER) RETURN INTEGER IS SEPARATE; -- ERROR: {1:6;1}

     FUNCTION "+"
         (RIGHT: INTEGER) RETURN INTEGER IS SEPARATE; -- ERROR: {1:6;1}

END BA1001D_PKG;
