# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/11/05 06:49:51 marttikuparinen Exp $

BUILDLINK_DEPTH:=			${BUILDLINK_DEPTH}+
P5_CURSES_UI_POE_BUILDLINK3_MK:=	${P5_CURSES_UI_POE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-Curses-UI-POE
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Curses-UI-POE}
BUILDLINK_PACKAGES+=	p5-Curses-UI-POE

.if !empty(P5_CURSES_UI_POE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-Curses-UI-POE+=	p5-Curses-UI-POE>=0.02801
BUILDLINK_PKGSRCDIR.p5-Curses-UI-POE?=	../../wip/p5-Curses-UI-POE
.endif	# P5_CURSES_UI_POE_BUILDLINK3_MK

.include "../../wip/p5-Curses-UI/buildlink3.mk"

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
