# $NetBSD$

PKGNAME=	serious-engine-tse-0.0
PATCHDIR=	../../wip/serious-engine-tfe-git/patches

CMAKE_ARGS+=	-DTFE:BOOL=FALSE
LDFLAGS+=	${COMPILER_RPATH_FLAG}${PREFIX}/lib/ssam-tse

.include "../../wip/serious-engine-tfe-git/Makefile.common"
