# $NetBSD: buildlink3.mk,v 1.1 2004/05/02 21:56:33 blef Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
MING_BUILDLINK3_MK:=	${MING_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	ming
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nming}
BUILDLINK_PACKAGES+=	ming

.if !empty(MING_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.ming+=	ming>=0.2
BUILDLINK_PKGSRCDIR.ming?=	../../wip/ming
.endif	# MING_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
