# $NetBSD$

DISTNAME=	runas-0.1.1.10
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_GITHUB:=outpaddling/}
GITHUB_PROJECT=	runas
GITHUB_TAG=	98a230ff9a32d163bb056e290968a46a0a7b5c8d

MAINTAINER=	bacon@NetBSD.org
HOMEPAGE=	https://github.com/outpaddling/runas
COMMENT=	Wrapper around su for running a command as another user
LICENSE=	2-clause-bsd

.include "../../mk/bsd.pkg.mk"
