# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/08/26 05:16:26 phonohawk Exp $
#

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_IRC_BUILDLINK3_MK:=	${HS_IRC_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-irc
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-irc}
BUILDLINK_PACKAGES+=	hs-irc
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-irc

.if ${HS_IRC_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-irc?=	build
BUILDLINK_API_DEPENDS.hs-irc+=	hs-irc>=0.4.3
BUILDLINK_PKGSRCDIR.hs-irc?=	../../wip/hs-irc
.endif	# HS_IRC_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
