# $NetBSD: Makefile,v 1.4 2012/11/13 22:25:33 othyro Exp $

.include "../../wip/io-base/version.mk"

PKGNAME=		io-range-${IO_VERSION}
CATEGORIES=		devel
LICENSE=		modified-bsd

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		http://www.iolanguage.com/
COMMENT=		Range addon for Io

ADDON_NAME=		Range
ADDON_INSTALL_HEADERS=	yes

.include "../../wip/io-base/addon.mk"
.include "../../mk/bsd.pkg.mk"
