# $NetBSD: Makefile,v 1.5 2012/10/07 16:22:55 asau Exp $
#

DISTNAME=		sdd-1.52
CATEGORIES=		sysutils
MASTER_SITES=		ftp://ftp.berlios.de/pub/sdd/

MAINTAINER=		pancake@phreaker.net
HOMEPAGE=		http://directory.fsf.org/project/sdd/
COMMENT=		Replacement for 'dd'

USE_PKGLOCALEDIR=	yes
USE_TOOLS+=		gmake
MAKEFLAGS+=		INS_BASE=${PREFIX}/

.include "../../mk/bsd.pkg.mk"
