# $NetBSD: buildlink3.mk,v 1.2 2009/03/20 19:43:38 jsonn Exp $

BUILDLINK_TREE+=	ETL

.if !defined(ETL_BUILDLINK3_MK)
BUILDLINK_DEPMETHOD.ETL?=	build
BUILDLINK_API_DEPENDS.ETL+=	ETL>=0.04.11
BUILDLINK_PKGSRCDIR.ETL?=	../../wip/ETL

BUILDLINK_TREE+=	-ETL
