# $NetBSD: Makefile,v 1.5 2007/01/24 09:49:43 marttikuparinen Exp $

.include "../../wip/xfce4/Makefile.common"

XFCE4_VERSION=	0.4.6

DISTNAME=	xarchiver-${XFCE4_VERSION}
PKGNAME=	xfce4-xarchiver-${XFCE4_VERSION}
#PKGREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=xarchiver/}
COMMENT=	Xfce archiver handler

.include "../../wip/libxfce4gui/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
