# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/01/23 07:44:07 obache Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
CRFPP_BUILDLINK3_MK:=	${CRFPP_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	crfpp
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ncrfpp}
BUILDLINK_PACKAGES+=	crfpp
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}crfpp

.if ${CRFPP_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.crfpp+=	crfpp>=0.50
BUILDLINK_PKGSRCDIR.crfpp?=	../../wip/crfpp
.endif	# CRFPP_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
