# $NetBSD: hacks.mk,v 1.2 2010/08/18 10:28:25 pallegra Exp $

.  include "../../mk/bsd.fast.prefs.mk"

CFLAGS+=		-D__GLX_ALIGN64

CFLAGS.NetBSD+=		-D_NETBSD_SOURCE
CFLAGS.NetBSD+=		-DUSE_NATIVE_LIBM_FUNCS
CFLAGS.FreeBSD+=	-DUSE_NATIVE_LIBM_FUNCS
CFLAGS.DragonFly+=	-DUSE_NATIVE_LIBM_FUNCS
