# $NetBSD: buildlink3.mk,v 1.1.1.1 2006/04/21 04:23:05 jeremy-c-reed Exp $

BUILDLINK_DEPMETHOD.xf86dgaproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
XF86DGAPROTO_BUILDLINK3_MK:=	${XF86DGAPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	xf86dgaproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nxf86dgaproto}
BUILDLINK_PACKAGES+=	xf86dgaproto

.if !empty(XF86DGAPROTO_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.xf86dgaproto+=	xf86dgaproto>=2.0.2
BUILDLINK_PKGSRCDIR.xf86dgaproto?=	../../wip/xf86dgaproto
.endif	# XF86DGAPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
