# $NetBSD$

BUILDLINK_TREE+=	go-ps

.if !defined(GO_PS_BUILDLINK3_MK)
GO_PS_BUILDLINK3_MK:=

BUILDLINK_CONTENTS_FILTER.go-ps=	${EGREP} gopkg/
BUILDLINK_DEPMETHOD.go-ps?=		build

BUILDLINK_API_DEPENDS.go-ps+=	go-ps>=20201120
BUILDLINK_PKGSRCDIR.go-ps?=	../../wip/go-ps
.endif	# GO_PS_BUILDLINK3_MK

BUILDLINK_TREE+=	-go-ps
