# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/08/07 05:36:05 jeremy-c-reed Exp $

BUILDLINK_DEPMETHOD.bigreqsproto?=	build

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
BIGREQSPROTO_BUILDLINK3_MK:=	${BIGREQSPROTO_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	bigreqsproto
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nbigreqsproto}
BUILDLINK_PACKAGES+=	bigreqsproto

.if !empty(BIGREQSPROTO_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.bigreqsproto+=	bigreqsproto>=1.0
BUILDLINK_PKGSRCDIR.bigreqsproto?=	../../wip/bigreqsproto
.endif	# BIGREQSPROTO_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
