# $NetBSD: Makefile,v 1.5 2012/11/25 23:32:09 othyro Exp $
#

DISTNAME=		bwm-ng-0.5
CATEGORIES=		net
MASTER_SITES=		http://www.gropp.org/bwm-ng/

MAINTAINER=		pkgsrc-users@NetBSD.org
HOMEPAGE=		http://www.gropp.org/?id=projects&sub=bwm-ng
COMMENT=		Console-based bandwidth monitor
LICENSE=		gnu-gpl-v2

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes

.include "../../mk/bsd.pkg.mk"
