# $NetBSD: buildlink3.mk,v 1.1.1.1 2007/03/17 22:30:26 cosmedbr Exp $
BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
DMENU_BUILDLINK3_MK:=	${DMENU_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	dmenu
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndmenu}
BUILDLINK_PACKAGES+=	dmenu
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}dmenu

.if ${DMENU_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.dmenu+=	dmenu>=2.8
BUILDLINK_PKGSRCDIR.dmenu?=	../../wip/dmenu
.endif	# DMENU_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
