.\"	$Id: pkg_select.1,v 1.4 2005/03/18 10:50:04 imilh Exp $
.\"
.\" Copyright (c) 2005
.\"      iMil <imil@gcu.info>.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by iMil.
.\" 4. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY iMil AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL iMil OR THE VOICES IN HIS HEAD
.\" BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
.\" THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd February 07, 2005
.Dt PKG_SELECT 1
.Os
.Sh NAME
.Nm pkg_select
.Nd curses based pkgsrc system browser / manager
.Sh SYNOPSIS
.Nm
.Op Fl b Ar pkgsrcdir
.Op Fl K Ar pkg_dbdir
.Op Fl c Ar conf file
.Op Fl l
.Op Fl m
.Op Fl u Ar NetBSD ftp mirror
.Op Fl d Ar download url
.Op Fl s
.Sh DESCRIPTION
.Nm
will display a curses file browser for the pkg system. You can browse
.Ar pkgsrc
and gather
various informations about packages, like available version, installed version,
comment and homepage. A simple paging system lets you read information files.
You can browse both installed and uninstalled packages, as well as dependencies
list and perform various administrative tasks to them. A package finder system
helps you to easily locate a package by its name.
.Nm
can handle either source or binary installations when
.Ar pkgsrc
is installed on the local system, or binary only when using the
pkgsrc-over-ftp feature.
.Pp
If no
.Ar pkgsrc
is installed,
.Nm
offers ability fo fetch it by FTP, CVS or directory copy. It is also possible to
update an existing pkgsrc via the interface.
.Pp
.Nm
user interface is quite self explainatory, every available shortcut is
shown and annotated.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent-two
.It Fl b Ar pkgsrcdir
Set
.Ar pkgsrcdir
as the pkgsrc base directory. Default is set to
.Pa /usr/pkgsrc
.It Fl K Ar pkg_dbdir
Set
.Ar pkg_dbdir
as the package database directory. Default is set to
.Pa /var/db/pkg
.It Fl c Ar conf file
Set
.Ar conf file
as the configuration file. Default is set to
.Pa /usr/pkg/etc/pkg_select.conf
.It Fl l
Enable pkgsrc over FTP (don't need
.Ar pkgsrc
to be installed)
.It Fl m
Do not read Makefiles when browsing
.Ar pkgsrc
over FTP
.It Fl u Ar NetBSD ftp mirror
Defines a
.Ar NetBSD ftp mirror
for live pkgsrc-over-FTP
.It Fl d Ar url
Set
.Ar url
as the pkgsrc tree download url.
.Ar url
can be one of
.Pp
.Bl -item -compact
.It
.Pa ftp://ftp.mirror.NetBSD.org/pub/NetBSD
.It
.Pa cvs://[:pserver:]anoncvs@anoncvs.mirror.NetBSD.org:/cvsroot
.It
.Pa file:///some/path
.El
.It Fl s
Force shell output instead of curses progress bars
.El
.Sh ENVIRONMENT
.Bl -tag -width indent -compact
.It Ev PKGSRCDIR
If set, this variable changes
.Ar pkgsrc
base directory to
.Ar PKGSRCDIR .
Default is set to
.Pa /usr/pkgsrc
.It Ev PKG_DBDIR
If set, this variable changes the package database directory path.
Default is set to
.Pa /var/db/pkg
.El
.Sh FILES
.Bl -tag -width /var/db/pkg/pkgdb.byfile.db -compact
.It Pa /usr/pkg/etc/pkg_select.conf
.It Pa /usr/pkg/share/examples/pkg_select/pkg_select.conf.example
.It Pa /usr/pkg/share/pkg_select/mirrors.ftp
.It Pa /usr/pkg/share/pkg_select/mirrors.cvs
.El
.Pp
.Sh NOTES
When manipulating packages,
.Nm
obviously needs to be ran as root.
.Pp
.Sh SEE ALSO
.Xr pkg_add 1 ,
.Xr pkg_delete 1 ,
.Xr packages 7 ,
and
.Xr make 1
.Pp
.Sh AUTHOR
iMil <imil@gcu.info>
