# $NetBSD: Makefile,v 1.2 2014/05/05 00:03:06 szptvlfn Exp $

DISTNAME=	vector-algorithms-0.6.0.1
CATEGORIES=	devel

MAINTAINER=	szptvlfn@NetBSD.org
COMMENT=	Efficient algorithms for vector arrays
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../wip/hs-mwc-random/buildlink3.mk"
.include "../../wip/hs-primitive/buildlink3.mk"
.include "../../wip/hs-vector/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
