$NetBSD$

pkgsrc calls this pciutils

--- cmake/FindPCIUTILS.cmake.orig	2020-05-05 14:39:33.000000000 +0000
+++ cmake/FindPCIUTILS.cmake
@@ -9,9 +9,9 @@ if(PCIUTILS_INCLUDE_DIR AND PCIUTILS_LIB
    set(PCIUTILS_FIND_QUIETLY TRUE)
 endif(PCIUTILS_INCLUDE_DIR AND PCIUTILS_LIBRARIES)
 
-FIND_PATH(PCIUTILS_INCLUDE_DIR pci/pci.h)
+FIND_PATH(PCIUTILS_INCLUDE_DIR pciutils/pci.h)
 
-FIND_LIBRARY(PCIUTILS_LIBRARY NAMES pci)
+FIND_LIBRARY(PCIUTILS_LIBRARY NAMES pciutils)
 if(PCIUTILS_LIBRARY)
   FIND_LIBRARY(RESOLV_LIBRARY NAMES resolv)
   if(RESOLV_LIBRARY)
