
WITH REPORT; USE REPORT;
WITH C23003I_PKG;
PRAGMA ELABORATE (REPORT, C23003I_PKG);
PACKAGE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2
     IS NEW C23003I_PKG (IDENT_INT(2));
