# $NetBSD: Makefile,v 1.3 2009/05/21 04:52:46 phonohawk Exp $
#

DISTNAME=	regex-base-0.93.1
PKGREVISION=	1
PKGNAME=	hs-${DISTNAME}
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
HOMEPAGE=	http://sourceforge.net/projects/lazy-regex
COMMENT=	Replaces/Enhances Haskell Text.Regex

.include "../../wip/mk/haskell.mk"
.include "../../wip/hs-mtl/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
