# $NetBSD: buildlink3.mk,v 1.1 2008/09/05 12:07:15 asau Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
OPENMPI_BUILDLINK3_MK:=	${OPENMPI_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	openmpi
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nopenmpi}
BUILDLINK_PACKAGES+=	openmpi
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}openmpi

.if ${OPENMPI_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.openmpi+=	openmpi>=1.2.6
BUILDLINK_PKGSRCDIR.openmpi?=	../../wip/openmpi
.endif	# OPENMPI_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
