# $NetBSD: Makefile,v 1.1.1.1 2003/04/14 03:16:34 xtraeme Exp $
#

DISTNAME=	puf-0.93.2a
CATEGORIES=	net
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=puf/}

MAINTAINER=	jrp@hispabsd.org
HOMEPAGE=	http://puf.sourceforge.net/
COMMENT=	Parallel URL fetcher

GNU_CONFIGURE=		YES
USE_GMAKE=		YES

.include "../../mk/bsd.pkg.mk"
