# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/30 14:20:52 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_HTML_BUILDLINK3_MK:=	${HS_HTML_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-html
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-html}
BUILDLINK_PACKAGES+=	hs-html
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-html

.if ${HS_HTML_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-html?=	build
BUILDLINK_API_DEPENDS.hs-html+=	hs-html>=1.0.1.2
BUILDLINK_PKGSRCDIR.hs-html?=	../../wip/hs-html
.endif	# HS_HTML_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
