# $NetBSD$

DISTNAME=	lxmf-0.3.1
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	comms python
MASTER_SITES=	${MASTER_SITE_PYPI:=l/lxmf/}

MAINTAINER=	gdt@lexort.com
HOMEPAGE=	https://github.com/markqvist/lxmf
COMMENT=	Lightweight Extensible Message Format for Reticulum
LICENSE=	mit

DEPENDS+=	${PYPKGPREFIX}-rns>=0.4.7:../../wip/py-rns

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
