# $NetBSD$

DISTNAME=	tikz-timing
PKGNAME=	tex-${DISTNAME}-0.7f
TEXLIVE_REV=	64967

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/tikz-timing
COMMENT=	Easy generation of timing diagrams as TikZ pictures
LICENSE=	lppl-1.3c

DEPENDS+=	tex-svn-prov-[0-9]*:../../print/tex-svn-prov

# catalogue-contact-bugs https://github.com/MartinScharrer/tikz-timing/issues
# catalogue-contact-home https://github.com/MartinScharrer/tikz-timing
# catalogue-contact-repository https://github.com/MartinScharrer/tikz-timing.git

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
