# $NetBSD: Makefile,v 1.1 2013/10/11 11:48:24 thomasklausner Exp $

DISTNAME=	pkgsrc-status-dependencies-1.0
CATEGORIES=	misc
MASTER_SITES=	#

MAINTAINER=	sno@NetBSD.org
#HOMEPAGE=
COMMENT=	Meta Package for sno's pkgsrc status tool dependencies
LICENSE=	public-domain

DEPENDS+=	p5-CPAN-DistnameInfo-[0-9]*:../../devel/p5-CPAN-DistnameInfo
DEPENDS+=	p5-Carp-Assert-[0-9]*:../../devel/p5-Carp-Assert
DEPENDS+=	p5-File-ShareDir-[0-9]*:../../devel/p5-File-ShareDir
DEPENDS+=	p5-File-pushd-[0-9]*:../../devel/p5-File-pushd
DEPENDS+=	p5-File-Find-Rule-[0-9]*:../../devel/p5-File-Find-Rule
DEPENDS+=	p5-File-Find-Rule-Age-[0-9]*:../../devel/p5-File-Find-Rule-Age
DEPENDS+=	p5-IO-CaptureOutput-[0-9]*:../../devel/p5-IO-CaptureOutput
DEPENDS+=	p5-Hash-MoreUtils-[0-9]*:../../devel/p5-Hash-MoreUtils
DEPENDS+=	p5-SQL-Translator-[0-9]*:../../databases/p5-SQL-Translator
DEPENDS+=	p5-MooX-Cmd-[0-9]*:../../devel/p5-MooX-Cmd
DEPENDS+=	p5-MooX-Options-[0-9]*:../../devel/p5-MooX-Options
DEPENDS+=	p5-MooX-Roles-Pluggable-[0-9]*:../../devel/p5-MooX-Roles-Pluggable
DEPENDS+=	p5-DBD-SQLite-[0-9]*:../../databases/p5-DBD-SQLite
DEPENDS+=	p5-DBIx-Class-[0-9]*:../../databases/p5-DBIx-Class

META_PACKAGE=	yes

.include "../../mk/bsd.pkg.mk"
