$NetBSD$

Relax version requirements.

--- pyproject.toml.orig	2024-11-15 18:34:05.953710699 +0000
+++ pyproject.toml
@@ -22,7 +22,7 @@ classifiers=[
 custodian = 'c7n.cli:main'
 
 [tool.poetry.dependencies]
-cryptography = "<46"
+cryptography = "*"
 python = "^3.8"
 boto3 = "^1.12.31"
 jsonschema = ">=4.18"
@@ -30,22 +30,22 @@ argcomplete = ">=1.12.3"
 python-dateutil = "^2.8.2"
 pyyaml = ">=5.4.0"
 tabulate = "^0.9.0"
-docutils = ">=0.18, <0.19"
+docutils = ">=0.18"
 
 # some issue in c7n_gcp libraries, possibly a bug in poetry, even with this specification
 # importlib-metadata = ">=6,<9"
 # we're picking up a release behind on 8.4 vs 8.5 and to avoid incompatible package installs,
 # we're pinning for now. time to explore uv workspaces perhaps.
-importlib-metadata = "==8.4"
+importlib-metadata = ">=8.4"
 
 # temporary work around for 
 # https://github.com/cloud-custodian/poetry-plugin-freeze/issues/18
-urllib3 = "<2"
+urllib3 = "*"
 
 # temporary work around for
 # https://github.com/p1c2u/jsonschema-path/issues/98
 # which gets pulled in via moto
-referencing = "==0.35.1"
+referencing = ">=0.35.1"
 
 [tool.poetry.group.dev.dependencies]
 ruff = ">=0.3,<0.6"
