# $NetBSD: buildlink3.mk,v 1.1 2005/11/05 06:17:39 marttikuparinen Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
P5_CURSES_UI_BUILDLINK3_MK:=	${P5_CURSES_UI_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	p5-Curses-UI
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Np5-Curses-UI}
BUILDLINK_PACKAGES+=	p5-Curses-UI

.if !empty(P5_CURSES_UI_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.p5-Curses-UI+=	p5-Curses-UI>=0.95
BUILDLINK_PKGSRCDIR.p5-Curses-UI?=	../../wip/p5-Curses-UI
.endif	# P5_CURSES_UI_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
