# $NetBSD: Makefile,v 1.8 2004/09/23 05:59:41 jlamwww Exp $

DISTNAME=		gtk-mist-engine-0.10
PKGNAME=		gtk2-engines-mist-0.10
CATEGORIES=		x11
MASTER_SITES=		http://primates.ximian.com/~dave/mist/

MAINTAINER=		snj@pobox.com
HOMEPAGE=		http://primates.ximian.com/~dave/mist/
COMMENT=		Flat engine for GTK+ 2.x

GNU_CONFIGURE=		YES
USE_BUILDLINK3=		YES

USE_LIBTOOL=		YES
GNU_CONFIGURE=		YES

.include "../../x11/gtk2/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
