BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
JBIGKIT_BUILDLINK3_MK:=	${JBIGKIT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	jbigkit
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Njbigkit}
BUILDLINK_PACKAGES+=	jbigkit

.if ${JBIGKIT_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.jbigkit+=	jbigkit>=1.6.0
BUILDLINK_PKGSRCDIR.jbigkit?=	../../wip/jbigkit
BUILDLINK_DEPMETHOD.jbigkit=	build
.endif

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
