# $NetBSD$

BUILDLINK_TREE+=	CRCpp

.if !defined(CRCPP_BUILDLINK3_MK)
CRCPP_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.CRCpp+=	CRCpp>=1.2.1.0
BUILDLINK_PKGSRCDIR.CRCpp?=	../../wip/CRCpp

.endif # CRCPP_BUILDLINK3_MK

BUILDLINK_TREE+=	-CRCpp
