
SEPARATE (C83030C_DECL2)
PROCEDURE C83030C_PROC1 IS
     A : INTEGER := IDENT_INT(2);
BEGIN
     IF SWITCH THEN
          SWITCH := FALSE;
          C83030C_PROC1;
          IF GLOBAL /= IDENT_INT(3) THEN
               FAILED ("INCORRECT VALUE FOR PROCEDURE CALL - 1");
          END IF;
     END IF;
     C83030C_PROC1(A);
     IF GLOBAL /= IDENT_INT(2) THEN
          FAILED ("INCORRECT VALUE FOR PROCEDURE CALL - 2");
     END IF;
     GLOBAL := IDENT_INT(3);
END C83030C_PROC1;
