
SEPARATE (C83030C_DECL2)
FUNCTION C83030C_FUNC4 RETURN T IS
     A : T := T'LAST;
BEGIN
     IF SWITCH THEN
          SWITCH := FALSE;
          IF C83030C_FUNC4 /= T'LAST THEN
               FAILED ("INCORRECT VALUE FROM FUNCTION CALL - 40");
          END IF;
          RETURN T'FIRST;
     ELSE
          IF C83030C_FUNC4 THEN
               FAILED ("INCORRECT VALUE FROM FUNCTION CALL - 41");
          END IF;
          RETURN T'LAST;
     END IF;
END C83030C_FUNC4;
