
SEPARATE (C83030C_DECL2)
FUNCTION C83030C_FUNC3 RETURN INTEGER IS
     A : INTEGER := INTEGER'LAST;
BEGIN
     IF SWITCH THEN
          SWITCH := FALSE;
          IF C83030C_FUNC3 /= IDENT_INT(3) THEN
               FAILED ("INCORRECT VALUE FROM FUNCTION CALL - 30");
          END IF;
     END IF;
     IF C83030C_FUNC3(A) /= IDENT_INT(INTEGER'LAST) THEN
          FAILED ("INCORRECT VALUE FROM FUNCTION CALL - 31");
     END IF;
     IF C83030C_FUNC3 THEN
          FAILED ("INCORRECT VALUE FROM FUNCTION CALL - 32");
     END IF;
     RETURN IDENT_INT(3);
END C83030C_FUNC3;
