# $NetBSD: buildlink3.mk,v 1.3 2013/04/16 11:21:33 szptvlfn Exp $

BUILDLINK_TREE+=	hs-pureMD5

.if !defined(HS_PUREMD5_BUILDLINK3_MK)
HS_PUREMD5_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.hs-pureMD5+=	hs-pureMD5>=2.1.2
BUILDLINK_PKGSRCDIR.hs-pureMD5?=	../../wip/hs-pureMD5

.endif	# HS_PUREMD5_BUILDLINK3_MK

BUILDLINK_TREE+=	-hs-pureMD5
