
PROCEDURE C86004A2 IS
     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     A : INT := IDENT_INT(10);
     B : INT := IDENT_INT(0);
BEGIN
     DECLARE
          PROCEDURE SWITCH IS NEW STANDARD.C86004A_SWAP(INT);
     BEGIN
          SWITCH(A,B);
     END;
     IF A /= IDENT_INT(0) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - B-0");
     END IF;
     IF B /= IDENT_INT(10) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - B-10");
     END IF;
END C86004A2;
