
WITH C86004A_SWAP; WITH REPORT; USE REPORT;
PROCEDURE C86004A1 IS
     SUBTYPE INT IS INTEGER RANGE 0 .. 10;
     A : INT := IDENT_INT(10);
     B : INT := IDENT_INT(0);
     PROCEDURE SWITCH IS NEW STANDARD.C86004A_SWAP(INT);
BEGIN
     SWITCH(A,B);

     IF A /= IDENT_INT(0) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - 1");
     END IF;

     IF B /= IDENT_INT(10) THEN
          FAILED("STANDARD.GENERIC PROCEDURE - 2");
     END IF;
END C86004A1;
