
WITH C86004A1; WITH C86004A2;
WITH REPORT; USE REPORT;
PROCEDURE C86004A IS
BEGIN
     TEST("C86004A", "CHECK THAT IF A LIBRARY SUBPROGRAM DECLARATION " &
                     "IS PRECEDED BY A ""WITH"" CLAUSE FOR A GENERIC " &
                     "LIBRARY PROCEDURE M, THEN IN THE BODY OF THE " &
                     "SUBPROGRAM, ""STANDARD.M"" IS A " &
                     "LEGAL NAME FOR THE GENERIC PROCEDURE");
     C86004A1;
     C86004A2;

     RESULT;
END C86004A;
