# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/03/19 12:15:44 koifren Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
MONO_TOOLS_BUILDLINK3_MK:=	${MONO_TOOLS_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	mono-tools
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nmono-tools}
BUILDLINK_PACKAGES+=	mono-tools
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}mono-tools

.if ${MONO_TOOLS_BUILDLINK3_MK} == "+"
BUILDLINK_API_DEPENDS.mono-tools+=	mono-tools>=1.9
BUILDLINK_PKGSRCDIR.mono-tools?=	../../wip/mono-tools
.endif	# MONO_TOOLS_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
