
WITH SPPRT13;
WITH REPORT; USE REPORT;
PRAGMA ELABORATE (SPPRT13);
PRAGMA ELABORATE (REPORT);
PROCEDURE CD5003B IS
     TYPE ENUM IS (A0, A1, A2, A3, A4, A5);

     TEST_VAR : ENUM := A0;
     FOR TEST_VAR USE AT SPPRT13.VARIABLE_ADDRESS;
     USE SYSTEM;

     FUNCTION IDENT_ENUM (P : ENUM) RETURN ENUM IS
     BEGIN
          IF EQUAL (3, 3) THEN
               RETURN P;
          ELSE
               RETURN A0;
          END IF;
     END IDENT_ENUM;

BEGIN
     TEST ("CD5003B", "CHECK THAT A 'WITH' CLAUSE NAMING 'SYSTEM' " &
                      "NEED NOT BE GIVEN FOR A PROCEDURE BODY " &
                      "CONTAINING AN ADDRESS CLAUSE AS LONG AS A " &
                      "'WITH' CLAUSE IS GIVEN FOR THE PROCEDURE " &
                      "SPECIFICATION");

     TEST_VAR := IDENT_ENUM (A3);

     IF TEST_VAR /= A3 THEN
          FAILED ("INCORRECT VALUE FOR TEST_VAR");
     END IF;

     IF TEST_VAR'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR TEST_VAR");
     END IF;

    RESULT;
END CD5003B;
