# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/07/19 09:53:27 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HSOPENSSL_BUILDLINK3_MK:=	${HSOPENSSL_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	HsOpenSSL
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:NHsOpenSSL}
BUILDLINK_PACKAGES+=	HsOpenSSL
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}HsOpenSSL

.if ${HSOPENSSL_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.HsOpenSSL?=	build
BUILDLINK_API_DEPENDS.HsOpenSSL+=	HsOpenSSL>=0.4.2
BUILDLINK_PKGSRCDIR.HsOpenSSL?=	../../wip/HsOpenSSL
.endif	# HSOPENSSL_BUILDLINK3_MK

.include "../../security/openssl/buildlink3.mk"

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
