# $NetBSD: buildlink3.mk,v 1.1.1.1 2008/07/20 07:57:59 phonohawk Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
HSLOGGER_BUILDLINK3_MK:=	${HSLOGGER_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hslogger
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhslogger}
BUILDLINK_PACKAGES+=	hslogger
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hslogger

.if ${HSLOGGER_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hslogger?=	build
BUILDLINK_API_DEPENDS.hslogger+=	hslogger>=1.0.5
BUILDLINK_PKGSRCDIR.hslogger?=	../../wip/hslogger
.endif	# HSLOGGER_BUILDLINK3_MK

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH:S/+$//}
