# $NetBSD: buildlink3.mk,v 1.3 2008/02/16 01:29:09 lexort Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GRASS_BUILDLINK3_MK:=	${GRASS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	grass
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngrass}
BUILDLINK_PACKAGES+=	grass

.if !empty(GRASS_BUILDLINK3_MK:M+)
BUILDLINK_API_DEPENDS.grass+=	grass>=6.0.0
BUILDLINK_ABI_DEPENDS.grass?=	grass>=6.0.2nb2
BUILDLINK_PKGSRCDIR.grass?=	../../wip/grass
.endif	# GRASS_BUILDLINK3_MK

.include "../../geography/gdal-lib/buildlink3.mk"

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
