# $NetBSD$

DISTNAME=	tabto-ltx
PKGNAME=	tex-${DISTNAME}-1.4
TEXLIVE_REV=	78101

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://ctan.org/pkg/tabto-ltx
COMMENT=	"Tab" to a measured position in the line
LICENSE=	lppl-1.3c

# catalogue-alias tabto

.include "../../print/texlive/package.mk"
.include "../../mk/bsd.pkg.mk"
