
WITH SPPRT13;
WITH REPORT; USE REPORT;
PRAGMA ELABORATE (SPPRT13);
PRAGMA ELABORATE (REPORT);
PACKAGE BODY CD5003F_PACK2 IS
     TYPE ATYPE IS ARRAY (1 .. 10) OF INTEGER;

     TEST_VAR : ATYPE := (OTHERS => 0);
     FOR TEST_VAR USE AT SPPRT13.VARIABLE_ADDRESS;
     USE SYSTEM;

     FUNCTION IDENT (P : ATYPE) RETURN ATYPE IS
     BEGIN
          IF EQUAL (3, 3) THEN
               RETURN P;
          ELSE
               RETURN (OTHERS => 0);
          END IF;
     END IDENT;

     PROCEDURE REQUIRE_BODY IS
     BEGIN
       NULL;
     END;
BEGIN
     TEST ("CD5003F", "A 'WITH' CLAUSE NAMING 'SYSTEM' NEED NOT " &
                      "BE GIVEN FOR A GENERIC PACKAGE BODY " &
                      "CONTAINING AN ADDRESS CLAUSE AS LONG AS A " &
                      "'WITH' CLAUSE IS GIVEN FOR THE GENERIC " &
                      "PACKAGE SPECIFICATION");

     TEST_VAR := IDENT (ATYPE'(OTHERS => 3));

     IF TEST_VAR /= ATYPE'(OTHERS => 3) THEN
          FAILED ("INCORRECT VALUE FOR TEST_VAR");
     END IF;

     IF TEST_VAR'ADDRESS /= SPPRT13.VARIABLE_ADDRESS THEN
          FAILED ("INCORRECT ADDRESS FOR TEST_VAR");
     END IF;
END CD5003F_PACK2;
