# $NetBSD: buildlink3.mk,v 1.1 2014/11/24 03:09:44 makoto Exp $

BUILDLINK_TREE+=	SOPE

.if !defined(SOPE_BUILDLINK3_MK)
SOPE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.SOPE+=	SOPE>=2.1.1
BUILDLINK_ABI_DEPENDS.SOPE+=	SOPE>=2.1.1
BUILDLINK_PKGSRCDIR.SOPE?=	../../devel/SOPE
.endif # SOPE_BUILDLINK3_MK

BUILDLINK_TREE+=	-SOPE
