# $NetBSD: buildlink3.mk,v 1.2 2005/09/15 15:44:29 elvstone Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
LIBMEMCACHE_BUILDLINK3_MK:=	${LIBMEMCACHE_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	libmemcache
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nlibmemcache}
BUILDLINK_PACKAGES+=	libmemcache

.if !empty(LIBMEMCACHE_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.libmemcache+=	libmemcache>=1.4.0beta5
BUILDLINK_PKGSRCDIR.libmemcache?=	../../wip/libmemcache
.endif	# LIBMEMCACHE_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
