# $NetBSD:

UBOOT_TARGET=		sifive_unleashed
UBOOT_CONFIG=		sifive_unleashed_defconfig
UBOOT_BIN=		u-boot-nodtb.bin

UBOOT_INSTALLBOOT_PLIST=	installboot.plist

PKGREVISION=		4
KBUILD_VERBOSE= yes
VERBOSE = 1

.include "../../sysutils/u-boot/u-boot-riscv64.mk"
.include "../../mk/bsd.pkg.mk"
