# $NetBSD: Makefile,v 1.3 2012/11/13 23:05:30 othyro Exp $

.include "../../wip/io/version.mk"

PKGNAME=		io-user-${IO_VERSION}
CATEGORIES=		system

MAINTAINER=		milos.negovanovic@googlemail.com
HOMEPAGE=		www.iolanguage.com
COMMENT=		User addon for Io

ADDON_NAME=		User

.include "../../wip/io/addon.mk"
.include "../../mk/bsd.pkg.mk"
