

WITH SYSTEM; USE SYSTEM;
WITH REPORT; USE REPORT;
WITH C94005A_PKG;
PROCEDURE C94005A IS

     T : C94005A_PKG.TT;


BEGIN
     TEST ("C94005A", "CHECK THAT IF A TASK TYPE IS DECLARED IN A " &
                      "LIBRARY PACKAGE, A MAIN PROGRAM THAT " &
                      "DECLARES OBJECTS OF THAT TYPE DOES WAIT FOR " &
                      "TERMINATION OF SUCH OBJECTS");

     COMMENT ("THE INVOKING SYSTEM'S JOB CONTROL LOG MUST BE " &
              "EXAMINED TO SEE IF THIS TEST REALLY TERMINATES");

     T.E;

     IF T'TERMINATED THEN
          COMMENT ("TEST INCONCLUSIVE BECAUSE TASK T PREMATURELY " &
                   "TERMINATED");
     END IF;

     -- TASK T SHOULD WRITE THE RESULT MESSAGE.

END C94005A;
