# $NetBSD$

DISTNAME=	gh-dash-4.5.4
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=dlvhdr/}
GITHUB_TAG=	v${PKGVERSION_NOREV}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://dlvhdr.github.io/gh-dash/
COMMENT=	Beautiful CLI dashboard for GitHub
LICENSE=	mit

.include "go-modules.mk"
.include "../../lang/go/go-module.mk"
.include "../../mk/bsd.pkg.mk"
