# $NetBSD: Makefile,v 1.1.1.1 2003/11/05 05:20:53 mpasternak Exp $
#

DISTNAME=		Py2Play-0.1.5
PKGNAME=		${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=		devel
MASTER_SITES=		http://oomadness.tuxfamily.org/downloads/

MAINTAINER=		dotz@irc.pl
HOMEPAGE=		http://oomadness.tuxfamily.org/en/py2play/index.html
COMMENT=		Network game engine in Python, utilizing P2P model

USE_BUILDLINK2=		yes
PY_PATCHPLIST=		yes
PYDISTUTILSPKG=		yes

.include "../../lang/python/extension.mk"
.include "../../mk/bsd.pkg.mk"
