# $NetBSD: buildlink3.mk,v 1.1 2004/04/11 23:22:54 blef Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
GTKGLK_BUILDLINK3_MK:=	${GTKGLK_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	gtkglk
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ngtkglk}
BUILDLINK_PACKAGES+=	gtkglk

.if !empty(GTKGLK_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.gtkglk+=	gtkglk>=0.2
BUILDLINK_PKGSRCDIR.gtkglk?=	../../graphics/gtkglk
.endif	# GTKGLK_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
