# $NetBSD: Makefile,v 1.1 2013/01/15 12:56:00 phonohawk Exp $
#

DISTNAME=	Cabal-1.16.0.3
CATEGORIES=	devel

MAINTAINER=	pho@cielonegro.org
COMMENT=	Framework for packaging Haskell software
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../mk/bsd.pkg.mk"
