# $NetBSD: buildlink3.mk,v 1.1.1.1 2005/01/19 22:41:10 matthewluckie Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
NSS_BUILDLINK3_MK:=	${NSS_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	nss
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nnss}
BUILDLINK_PACKAGES+=	nss

.if !empty(NSS_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.nss+=		nss>=3.9.2
BUILDLINK_RECOMMENDED.nss+=	nss>=3.9.2
BUILDLINK_PKGSRCDIR.nss?=	../../security/nss
.endif  # NSS_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
