# $NetBSD: Makefile,v 1.1.1.1 2006/07/16 12:47:07 shattered Exp $
#

DISTNAME=		mp3chop-1.06
CATEGORIES=		audio
MASTER_SITES=		http://www.fysh.org/~mac/mp3chop/

MAINTAINER=		shattered@users.sourceforge.net
HOMEPAGE=		http://www.fysh.org/~mac/mp3chop/
COMMENT=		Program for chopping up mp3 files

USE_PKGLOCALEDIR=	yes
GNU_CONFIGURE=		yes
USE_LANGUAGES+=		c++

.include "../../mk/bsd.pkg.mk"
