# $NetBSD: Makefile,v 1.7 2014/05/26 22:08:04 szptvlfn Exp $

DISTNAME=	blaze-html-0.7.0.1
CATEGORIES=	textproc

MAINTAINER=	pho@cielonegro.org
COMMENT=	Blazingly fast HTML combinator library for Haskell
LICENSE=	modified-bsd

.include "../../wip/mk/haskell.mk"
.include "../../devel/hs-blaze-builder/buildlink3.mk"
.include "../../wip/hs-blaze-markup/buildlink3.mk"
.include "../../devel/hs-text/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
