# $NetBSD: buildlink3.mk,v 1.2 2004/06/09 02:58:38 minskim Exp $

BUILDLINK_DEPTH:=		${BUILDLINK_DEPTH}+
DAMAGEEXT_BUILDLINK3_MK:=	${DAMAGEEXT_BUILDLINK3_MK}+

.if !empty(BUILDLINK_DEPTH:M+)
BUILDLINK_DEPENDS+=	damageext
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Ndamageext}
BUILDLINK_PACKAGES+=	damageext

.if !empty(DAMAGEEXT_BUILDLINK3_MK:M+)
BUILDLINK_DEPENDS.damageext+=	damageext>=1.0
BUILDLINK_PKGSRCDIR.damageext?=	../../wip/damageext
BUILDLINK_DEPMETHOD.damageext?=	build
.endif	# DAMAGEEXT_BUILDLINK3_MK

BUILDLINK_DEPTH:=     ${BUILDLINK_DEPTH:S/+$//}
