# $NetBSD: buildlink3.mk,v 1.4 2009/03/20 19:43:51 jsonn Exp $

BUILDLINK_TREE+=	ode

.if !defined(ODE_BUILDLINK3_MK)
ODE_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.ode+=		ode>=0.7
BUILDLINK_ABI_DEPENDS.ode?=	ode>=0.7
BUILDLINK_PKGSRCDIR.ode?=	../../wip/ode
.endif # ODE_BUILDLINK3_MK

BUILDLINK_TREE+=	-ode
