# $NetBSD: Makefile,v 1.4 2015/05/30 01:49:34 krytarowski Exp $

.include "../../wip/liblxqt/Makefile.common"

DISTNAME=	lxqt-powermanagement-0.9.0
CATEGORIES=	x11

MAINTAINER=	pkgsrc-users@NetBSD.org
COMMENT=	Daemon use for power management and auto-suspend
LICENSE=	gnu-lgpl-v2.1

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../sysutils/desktop-file-utils/desktopdb.mk"
.include "../../x11/qt5-qtsvg/buildlink3.mk"
.include "../../wip/liblxqt/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
