# $NetBSD: buildlink3.mk,v 1.1.1.1 2009/01/12 06:54:50 phonohawk Exp $

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH}+
HS_TIME_BUILDLINK3_MK:=	${HS_TIME_BUILDLINK3_MK}+

.if ${BUILDLINK_DEPTH} == "+"
BUILDLINK_DEPENDS+=	hs-time
.endif

BUILDLINK_PACKAGES:=	${BUILDLINK_PACKAGES:Nhs-time}
BUILDLINK_PACKAGES+=	hs-time
BUILDLINK_ORDER:=	${BUILDLINK_ORDER} ${BUILDLINK_DEPTH}hs-time

.if ${HS_TIME_BUILDLINK3_MK} == "+"
BUILDLINK_DEPMETHOD.hs-time?=	build
BUILDLINK_API_DEPENDS.hs-time+=	hs-time>=1.1.2.2
BUILDLINK_PKGSRCDIR.hs-time?=	../../wip/hs-time
.endif	# HS_TIME_BUILDLINK3_MK

BUILDLINK_DEPTH:=	${BUILDLINK_DEPTH:S/+$//}
