
WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P1 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;

     PROCEDURE REQUIRE_BODY;

     GENERIC
          X : IN OUT INTEGER;
     PACKAGE C83024E_PACK1 IS
          C : INTEGER := A;
          A : INTEGER := IDENT_INT(3);
     END C83024E_PACK1;
END C83024E_P1;
