
WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P3 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;

     PROCEDURE REQUIRE_BODY;

     GENERIC
          X : IN OUT INTEGER;
     PACKAGE C83024E_PACK3 IS
     END C83024E_PACK3;
END C83024E_P3;
