
WITH REPORT; USE REPORT;
PRAGMA ELABORATE(REPORT);
PACKAGE C83024E_P2 IS
     A : INTEGER := IDENT_INT(2);
     B : INTEGER := A;
     OBJ : INTEGER := IDENT_INT(3);

     PROCEDURE REQUIRE_BODY;

     GENERIC
          X : IN INTEGER := A;
          A : IN OUT INTEGER;
     PACKAGE C83024E_PACK2 IS
          C : INTEGER := A;
     END C83024E_PACK2;
END C83024E_P2;
